### ISSUE TITLE
rc6 Windows 10: COM port resets after each upload

### ISSUE THREAD

**Issue by stegu** [arduino/arduino-ide#1007]
### Describe the problem

Each time I upload a sketch to an Arduino Micro, the virtual COM port disappears briefly (due to how the virtual COM ports work), and another one appears in its stead while the upload is in progress. The new 2.0 IDE (rc6) reacts to this and changes the COM port setting to my native COM1, which has no device connected, neither an Arduino or any other type. If I fail to manually change the COM port setting back to the correct value before the next upload, that upload stalls, locks me out from making any further uploads for a good while, and finally (after a minute or so) fails with an error message that the upload failed.

Please make the COM port setting resistant against these quick disappearing/reappearing acts by the selected virtual port, at least for the micro and some other devices which does this for every upload.

### To reproduce

Use 2.0 rc6 on Windows 10, on a computer with one or more other COM ports (virtual or real) to upload a sketch to an Arduino Micro. The COM port setting changes.

### Expected behavior

The COM port setting should not change.

### Arduino IDE version

Version: 2.0.0-rc6 Date: 2022-04-20T10:23:13.437Z CLI Version: 0.21.0 [10107d24]

### Operating system

Windows

### Operating system version

10

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @stegu. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/710.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
