### ISSUE TITLE
pressing Ctrl-T for autoformatting creates 80% processor-load through clang takes more than a minute

### ISSUE THREAD

**Issue by StefanL38** [arduino/arduino-ide#1008]
### Describe the problem

I tested Arduino IDE 0.2  - oh sorry  IDE 2.0 - today.

I loaded the blink example saved with a different filename and added a variable and an if-condition
I intentionally misplaced the added code to be clumsy indented for testing the auto-format function

I hit Ctrl-T - nothing happened
maybe after 20 seconds the status said "indexing"  for more than a minute
then the status said "building sketch"  for more than a minute
clang.exe took 80% processor-load

for me this is absolutely inacceptable 

### To reproduce

use my computer 

### Expected behavior

fast execution of autoformatting 

### Arduino IDE version

2.0 rc6

### Operating system

Windows

### Operating system version

Windows 10 update tonight by compulsion

### Additional context

sorry guys guys this is not imperfection. This behaviour is almost **perfect** imperfection

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @StefanL38. Thanks for taking the time to submit an issue.

> I hit Ctrl-T - nothing happened

I see we have a previous report about this at https://github.com/arduino/arduino-ide/issues/337.

>maybe after 20 seconds the status said "indexing" for more than a minute
then the status said "building sketch" for more than a minute
clang.exe took 80% processor-load

I see we have a previous report about this at https://github.com/arduino/arduino-ide/issues/714.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the others.

If you end up with additional information to share, feel free to comment in the other thread.
