### ISSUE TITLE
Inconsistent dialogs when exit would result in user data loss

### ISSUE THREAD

**Issue by per1234** [arduino/arduino-ide#1016]
### Describe the problem

Under either of the following conditions, closing the Arduino IDE window would result in loss of sketch content:

- New or example sketch staged in a temporary folder
- Unsaved changes (user has disabled "**Auto save**")

As is standard for any application, the Arduino IDE notifies the user of this situation when they initiate a window close operation.

🐛 The presented dialogs are significantly different depending on which combination of the above conditions are present:

| Saved | New | "will not be saved" dialog | "Save your sketch" dialog |
| ----- | --- | -------------------------- | ------------------------- |
| Y     | Y   | N                          | Y                         |
| N     | Y   | Y                          | Y                         |
| N     | N   | Y                          | N                         |

### To reproduce

1. Select **File > Preferences...** from the Arduino IDE menus.
1. Check the box next to "**☐ Auto save**".
1. Click the <kbd>**OK**</kbd> button.
1. Select **File > New** from the Arduino IDE menus.
1. Make any change to the sketch.
   ❗ Do not save the sketch.
1. Select **File > Close** from the Arduino IDE menus.
   🙂 Dialog offering save is presented:
   ![image](https://user-images.githubusercontent.com/8572152/171383686-1687f057-a4b8-4ef2-9366-9f6130e3e7a4.png)
1. Click the <kbd>**Cancel**</kbd> button.
1. Select **File > Preferences...** from the Arduino IDE menus.
1. Uncheck the box next to "**`☑` Auto save**".
1. Click the <kbd>**OK**</kbd> button.
1. Make any change to the sketch.
   ❗ Do not save the sketch.
1. Select **File > Close** from the Arduino IDE menus.
   🙁 Unintuitive and unhelpful "**Any unsaved changes will not be saved**" dialog appears:
   ![image](https://user-images.githubusercontent.com/8572152/171383747-ad25bb4c-f701-4e14-8af1-3b55ea99de52.png)
1. Click the <kbd>**Yes**</kbd> button.
   😕 Dialog offering save is presented.
1. Click the <kbd>**Cancel**</kbd> button.
1. Select **File > Save As...** from the Arduino IDE menus.
1. Save the sketch to any location and name you like.
1. Make any change to the sketch.
   ❗ Do not save the sketch.
1. Select **File > Close** from the Arduino IDE menus.
   🙁 Unintuitive and unhelpful "will not be saved" dialog appears.
1. Click the <kbd>**Yes**</kbd> button.
   🐛 Standard dialog offering save is **not** presented.

### Expected behavior

Always show only the "Save your sketch" dialog.

Eradicate the unintuitive (https://github.com/arduino/arduino-ide/issues/677) and unhelpful (https://github.com/arduino/arduino-ide/issues/170) "**Any unsaved changes will not be saved**" dialog from the IDE.

### Arduino IDE version

2.0.0-rc6-snapshot-5b486b1

### Operating system

Windows, Linux

### Operating system version

Windows 10, Ubuntu 20.04

### Issue checklist

- [x] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [x] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [x] My report contains all necessary details

**Comment by kittaakos** [comment]
> Eradicate the unintuitive (https://github.com/arduino/arduino-ide/issues/677) and unhelpful (https://github.com/arduino/arduino-ide/issues/170) "Any unsaved changes will not be saved" dialog from the IDE.

Related https://github.com/arduino/arduino-ide/pull/1018#issuecomment-1143606541.

**Comment by ubidefeo** [comment]
@per1234 
is this addressed in RC7?

**Comment by per1234** [comment]
@ubidefeo no.
