### ISSUE TITLE
Example files - ask to save even if no changes were made to them. 

### ISSUE THREAD

**Issue by KurtE** [arduino/arduino-ide#1026]
### Describe the problem

If I open up an example sketch like blink and simply use it to program the board, and then try to close it without making 
any changes, unlike Arduino 1.x it asks me if I wish to save the sketch or not.  

This is related to #893,
which I am glad was fixed, but I do think it should only ask if the user made changes to the sketch.

There are other related example sketch issues, but I am pretty sure they have been reported in the past including:

1) Show sketch folder shows the folder within the temp directory, which feels wrong. 
2) Still looks like the examples don't show up in recent sketch list

3) If the temporary folder is erased, like you have the blink window open, go away for awhile and Norton Desktop cleans up the temp directory and erases your sketch,  you end up with a strange looking windows:
![image](https://user-images.githubusercontent.com/1558080/172721205-f0b2365f-66f6-4299-80a4-2091a3a3bd7a.png)
Note: I also saw some message in the window saying something like it can no longer track file changes... As there are too many... or some such thing (sorry should have taken picture then)

### To reproduce

Go to examples: file->Examples->01 Basic -> Blink

then after the window opens, click on the close button and you will see the dialog asking if you wish to save. 

The strange window issue, happens of Norton does a cleanup... Or you can emulate by opening the folder and delete all of the files out of that folder. 

### Expected behavior

Expect to only be asked to save a file if the file has been changed.

### Arduino IDE version

Nightly build 20220608

### Operating system

Windows

### Operating system version

Windows 10

### Additional context

Sorry if I missed a duplicate. 

Also 2nd part not sure what to report... I know with Arduino 1.x when the temp is cleared, a compile will fail but the window still shows the file contents from before. 

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Thanks so much for this report @KurtE. I have also found these unnecessary confirmation dialogs inconvenient.

I see we now have another report about this at https://github.com/arduino/arduino-ide/issues/1274.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place. Even though this one came first, the other has a little bit more information (the comment by **kittaakos** [here](https://github.com/arduino/arduino-ide/issues/1274#issuecomment-1202293369)), so I'll go ahead and close this in favor of the other.

I made sure to add a note there about how the issue applies to examples in addition to new sketches (the Arduino IDE opens examples as a new sketch, as you reported at https://github.com/arduino/arduino-ide/issues/925), with a link to this issue to make sure it will be seen by the interested parties.

If you end up with additional information to share, feel free to comment in the other thread.
