### ISSUE TITLE
Upload button defaulting to "Upload Using Programmer" is not supported

### ISSUE THREAD

**Issue by sstaub** [arduino/arduino-ide#103]
### Describe the problem

There are two Upload-related operations:

- Upload
- Upload Using Programmer

In addition to the menu items (**Sketch > Upload** / **Sketch > Upload Using Programmer**) and keyboard shortcuts (<kbd>**Ctrl**</kbd>+<kbd>**U**</kbd> / <kbd>**Ctrl**</kbd>+<kbd>**Shift**</kbd>+<kbd>**U**</kbd>), an upload operation can be triggered by clicking the button on the Arduino IDE toolbar.

Some Arduino boards do not support standard "Upload", so the platform author configured their board definition to do an "**Upload Using Programmer**" operation when the "Upload" button is clicked. This makes the frequent task of uploading to these boards more convenient for the user than having to use the less accessible menu item.

🐛 Arduino IDE does an "**Upload**" operation when the button is clicked even when the board is configured for it to trigger an "**Upload Using Programmer**" operation.

### Expected behavior

Arduino IDE does an "**Upload Using Programmer**" operation on "Upload" button click when the board is configured for that behavior.

### Arduino IDE version

7c86f1f

### Operating system

All

### Operating system version

Any

### Additional context

Additional reports:

- https://github.com/arduino/arduino-ide/issues/1640
- https://github.com/arduino/arduino-ide/issues/1323
- https://github.com/arduino/arduino-ide/issues/2276
- https://github.com/arduino/arduino-ide/issues/2460
- https://github.com/arduino/arduino-pro-ide/issues/306
- https://github.com/MCUdude/MiniCore/issues/233
- https://forum.arduino.cc/t/strange-issue-uploading-code-using-updi-megatinycore/945896
- https://forum.arduino.cc/t/attiny85-wont-program/1043246
- https://forum.arduino.cc/t/cant-program-attiny85-with-attinycore-v1-5-2/701346
- https://forum.arduino.cc/t/uploading-to-attiny85-gives-error-a-programmer-is-required-to-upload/1065582
- https://forum.arduino.cc/t/usbasp-works-well-on-ide-1-8-19-but-it-does-not-work-on-ide-2-0-3/1085285
- https://forum.arduino.cc/t/arduino-ide2-0-3-cant-find-programmer/1081331
- https://forum.arduino.cc/t/cannot-upload-to-arduino/1117541/10
- https://forum.arduino.cc/t/where-to-locate-h-files-in-ide-2/1138746/18
- https://forum.arduino.cc/t/a-programmer-is-required-to-upload-for-attiny402/1147172
- https://forum.arduino.cc/t/i-was-trying-to-code-on-a-vega-aries-v3-and-got-this-error-messa-a-programmer-is-required-to-upload/1195228
- https://forum.arduino.cc/t/failure-programming-attiny85-using-uno-r3/1216658
- https://forum.arduino.cc/t/tiny-avr-programmer-not-found/1216550/16
- https://forum.arduino.cc/t/a-programmer-is-required-to-upload/1234159

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by AntonEstrela** [comment]
As I understand from this post on the forum [https://forum.arduino.cc/t/add-dedicated-upload-using-programmer-button/625370/2](https://forum.arduino.cc/t/add-dedicated-upload-using-programmer-button/625370/2),
The IDE2 should check the `boards.txt` file and if `upload.protocol` is not defined it should try to upload using programmer

**Comment by cmaglie** [comment]
@kittaakos 
you may check the error's details field coming back from the `Upload` gRPC call, if it is a `ProgrammerIsRequiredForUploadError` the IDE should silently try the upload again with the "Upload using programmer".
