### ISSUE TITLE
IDE2 used to focus the main sketch file when opening a sketch with multiple files

### ISSUE THREAD

**Issue by kittaakos** [arduino/arduino-ide#1037]
### Describe the problem

When I open a sketch in IDE2 the main sketch file is not focused anymore. It used to work.

Working with `Beta.12`:

https://user-images.githubusercontent.com/1405703/173084626-e22b2458-01f7-4b9d-94c5-5b24e3760105.mp4

Broken with `RC-7`:

https://user-images.githubusercontent.com/1405703/173084644-9f5aef64-ee52-45e7-b885-8d9a258fd3fe.mp4

### To reproduce

 - Have a sketch opened,
 - Open `File` > `Examples` > `02.Digital` > `toneKeyboard`,
 - When all sketch files are opened in the editor, not the main sketch file (`toneKeyboard.ino`) has the focus.

### Expected behavior

When a sketch consists of multiple files, the main sketch file has the focus when opening the sketch.

### Arduino IDE version

Version: 2.0.0-rc7 Date: 2022-06-09T08:19:19.877Z CLI Version: 0.23.0 [899dc91b]  Copyright © 2022 Arduino SA

### Operating system

macOS

### Operating system version

12.3.1

### Additional context

Breaking change https://github.com/arduino/arduino-ide/commit/9863dc2f909b15ed8048dd250e4c4295e4a62a68#diff-abca14a02be77160a86d9f4fb6eca8c18d47312d2d4be37c50de50430bbbcd07L511 (#612)

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Thanks for taking the time to submit an issue @kittaakos.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/643.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.

**Comment by KurtE** [comment]
Thanks, I was just checking to see if there was an open issue on this.
