### ISSUE TITLE
Live change of theme after selecting from preferences dropdown

### ISSUE THREAD

**Issue by per1234** [arduino/arduino-ide#1048]
### Describe the request

The Arduino IDE should change theme immediately upon the user selecting a different theme from the "**Theme**" menu in the "**Preferences**" dialog.

If the user then clicks the <kbd>**Cancel**</kbd> button, the IDE should return to using the previously configured theme preference.

🙂 This will provide the user with an immediate preview of the appearance of the various available themes.

### Describe the current behavior

The Arduino IDE theme only changes after clicking the <kbd>**OK**</kbd> button in the "**Preferences**" dialog.

🙁 It is less convenient to evaluate the appearance of the various available themes.

### Arduino IDE version

2.0.0-rc7

### Operating system

Windows, Linux

### Operating system version

Windows 10, Ubuntu 20.04

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My request contains all necessary details

**Comment by ubidefeo** [comment]
I remember discussing this one with either @fstasi or @AlbyIanna because if you select the theme via Theia's preference menu you do get the preview which can be confirmed with ENTER or discarded with ESC
