### ISSUE TITLE
Output panel colorized text

### ISSUE THREAD

**Issue by Farhankhosravi** [arduino/arduino-ide#1060]
### Describe the request

Hello all
please add colors in output panel like IDE v1...
if you check, old IDE had colored texts depending on it's situation; for example errors was in red and uploading states was in orange. but v2 it's always white, that makes it harder to figure out.
Thanks.

### Describe the current behavior

Output text is always white colored.

### Arduino IDE version

2.0.0 rc7

### Operating system

Windows

### Operating system version

11

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My request contains all necessary details

**Comment by per1234** [comment]
Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/229.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
