### ISSUE TITLE
'byte' not marked

### ISSUE THREAD

**Issue by Master811129** [arduino/arduino-ide#108]
**Describe the bug**
the app does not color 'byte'

**To Reproduce**
1. Go to 'Arduino Pro IDE'
2. type 'byte'
3. See the problem

**Screenshots**
![Annotation 2020-06-27 011416](https://user-images.githubusercontent.com/37829730/85899609-8dbbb580-b813-11ea-95f4-a203ac1d7433.png)

**Desktop (please complete the following information):**
 - OS:Win 10

like this one arduino/arduino-pro-ide#150

**Comment by ubidefeo** [comment]
I have merged this one into #380
