### ISSUE TITLE
Dark theme is not used on the change log window when an update is available

### ISSUE THREAD

**Issue by joshuag1000** [arduino/arduino-ide#1108]
### Describe the problem

Discovered this bug today when i installed rc7 of the ide when rc8 had just been released.
Basically as can be seen in the image attached the theme is inconsistent on the change log section of the new update window.
![image](https://user-images.githubusercontent.com/28513051/175327320-174798b6-9c15-4cc3-b8e1-b396259667df.png)

### To reproduce

Have an out of date ide.

### Expected behavior

Theme should be consistent.

### Arduino IDE version

2.0.0-rc7 (probably affects rc8 but i cannot test that!)

### Operating system

Linux

### Operating system version

Arch Linux (Flatpak)

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Thanks for your report @joshuag1000. I'm happy to tell you that this bug has already been fixed: https://github.com/arduino/arduino-ide/pull/1092

![image](https://user-images.githubusercontent.com/8572152/175332376-d1eaa42d-ebe2-4004-a280-7ba38c63af35.png)
