### ISSUE TITLE
Function println not matched when using ArduinoCore-samd core

### ISSUE THREAD

**Issue by enekochan** [arduino/arduino-ide#112]
**Describe the bug**
Using the [ArduinoCore-samd](https://github.com/arduino/ArduinoCore-samd) `println` function in `Serial` is highligthed as "No matching member function for call to '`println`'" even if it is shown in code completition and the sketch is built without problems:

```
No matching member function for call to 'println'

/Users/username/Library/Arduino15/packages/arduino/hardware/samd/1.8.6/cores/arduino/Print.h:78:12:
note: candidate function not viable: no known conversion from 'Uart' to 'Print' for object argument
```

**To Reproduce**
1. Install ArduinoCore-samd.
2. Create a simple sketch and write a `Serial.println("...");` statement
3. See error

**Expected behavior**
Call to `println` be correctly recognized as belonging to `Serial`.

**Screenshots**
![Screenshot 2020-06-20 at 23 13 13](https://user-images.githubusercontent.com/1836845/85211742-6c0e8a00-b34c-11ea-8b6a-16890e7f59d4.png)

**Desktop:**
 - OS: macOS 10.15.5
 - Version: Arduino Pro 0.0.6 (0.0.6.20200409.2)
 - ArduinoCore-samd 1.8.6

**Comment by per1234** [comment]
This issue only occurs with specific boards:

- Arduino M0
- Arduino M0 Pro (Native USB Port)
- Arduino M0 Pro (Programming Port)
- Arduino Tian
- Arduino Zero (Native USB Port)
- Arduino Zero (Programming Port)

It does not occur with these boards:

- Adafruit Circuit Playground Express
- Arduino MKR boards (all)
- Arduino Nano 33 IoT

**Comment by per1234** [comment]
Closing as resolved by https://github.com/arduino/arduino-language-server/pull/92
