### ISSUE TITLE
Intellisense : To be or not to be...sometimes work / sometimes not

### ISSUE THREAD

**Issue by virenchocha** [arduino/arduino-ide#1134]
### Describe the problem

Big problem !! Intellisense is worst as compared to VS Code PlatformIO.
Some times work and some time does not. And when works, it is a slug and erratic.
Without intellisense, I could not imagine using C++ in my code.
Need big help and will get big thanks....

### To reproduce

Could not suggest anything.
However try creating a C++ class / .h file i.e. library style. Put a few methods and variables in that class.
Derive an object from base class.
try to type name of object, press "."
This should lead to opening of intellisense box listing properties and method of baseclass.

### Expected behavior

in most probable case, intellisense will not work even if editor suggesion on is tick in preferences.

### Arduino IDE version

2.0

### Operating system

Windows

### Operating system version

10

### Additional context

Intellisense not working hence switching to PlatformIO. 
See you !

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @virenchocha. Thanks for taking the time to submit an issue.

We are already tracking various issues with the Arduino IDE's language server-based features:

https://github.com/arduino/arduino-ide/issues?q=is%3Aissue+is%3Aopen+label%3A%22topic%3A+language+server%22

Based on such a vague report, I will have to conclude that the issue you are experiencing is already reported in one of those, so I will close this as a duplicate.

Feel free to request assistance over on the Arduino Forum. We may be able to provide some advice or progress with the investigation over there:

https://forum.arduino.cc/c/software/arduino-ide-2-0-beta/93
