### ISSUE TITLE
Incorrect toolbar color with the Arduino Light theme

### ISSUE THREAD

**Issue by kittaakos** [arduino/arduino-ide#1143]
### Describe the problem

With the new button colors, we broke the toolbar.

![Screen Shot 2022-07-04 at 16 52 18](https://user-images.githubusercontent.com/1405703/177178789-43f0d103-1abb-4ec7-9dc8-71ed4957711b.png)

### To reproduce

Open the IDE2. I am on 9b7ab14.

### Expected behavior

The toolbar is as good as it was. The HC and darks themes look good.

### Arduino IDE version

9b7ab14

### Operating system

macOS

### Operating system version

12.3.1

### Additional context

Ref: https://github.com/arduino/arduino-ide/pull/1141

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

**Comment by AlbyIanna** [comment]
solved by #1145
