### ISSUE TITLE
Automatic versioning and GitHub integration

### ISSUE THREAD

**Issue by M1DLG** [arduino/arduino-ide#116]
I've looked and couldnt see any other references to this so apologies if this duplicates another request. 

Will there be automatic versioning? EG everytime you compile or upload code to a board, will it silently save the most recent version of your code allowing you to refer back to it later if you introduce a bug not found until later?

Will there be intergration with GitHub, perhaps upload to repositiory when compiling allowing the option to submit only compiled binary or source or both? This too would be great for versioning.

**Comment by mirrorleos** [comment]
I agree, the ability to manage code directly on GitHub would be really appreciated

**Comment by per1234** [comment]
Thanks for your suggestion @M1DLG. We have decided this is out of scope for our project. Please use a standalone Git client such as [GitHub Desktop](https://github.com/apps/desktop).
