### ISSUE TITLE
No Icon in GNOME for IDE2.0 appimage on Linux

### ISSUE THREAD

**Issue by khershberger** [arduino/arduino-ide#1170]
### Describe the problem

When running the AppImage version of ide-2.0 on Ubuntu 20.04 with GNOME there is no icon for the application.  It is just an empty (transparent) square.  

### To reproduce

1. Download arduino-ide_2.0.0-rc8_Linux_64bit.AppImage
2. Run it
3. Observe missing icon in task bar or Alt-Tab list

### Expected behavior

There should be a visible icon in the task bar and Alt-Tab list

### Arduino IDE version

arduino-ide_nightly-20220711_Linux_64bit.AppImage

### Operating system

Linux

### Operating system version

Ubuntu 20.04.4 LTS (Focal Fossa)

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @khershberger. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/131.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
