### ISSUE TITLE
`Ino` icon is missing from the editor tabs

### ISSUE THREAD

**Issue by kittaakos** [arduino/arduino-ide#1173]
### Describe the problem

I can see the `ino` icon in the editor tabs on Windows, it's missing on macOS. I did not even notice this earlier.

macOS:
![Screen Shot 2022-07-12 at 09 37 21](https://user-images.githubusercontent.com/1405703/178436112-7c936c6a-4339-4831-8876-feafdee40df6.png)

Windows:
![icon](https://user-images.githubusercontent.com/1405703/178436288-9d352a3b-d24e-48a2-b9d9-6eb41e422b2f.png)

### To reproduce

Open the IDE2.

### Expected behavior

`ino` icon is in the editor tab on macOS

### Arduino IDE version

Version: 2.0.0-rc8-nightly-20220711 Date: 2022-07-11T03:32:37.503Z CLI Version: 0.24.0 [c1b10f56]  Copyright © 2022 Arduino SA

### Operating system

macOS

### Operating system version

12.3.1

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

**Comment by kittaakos** [comment]
One has to enable the `"workbench.iconTheme"` preference key, then the icon is there, and the error decorator is also available.

<img width="335" alt="Screen Shot 2022-07-22 at 09 31 05" src="https://user-images.githubusercontent.com/1405703/180387512-58aa2562-d83f-4f39-973c-868afdf047af.png">

Are we good with the default, not showing icons in IDE2 behavior? What do you think, @per1234? Thank you!

**Comment by per1234** [comment]
I'm feeling very indecisive.

In the most common use case:

- Only `.ino` files are open in the IDE
- `arduino.language.realTimeDiagnostics` is disabled

the Arduino logo icons feel redundant ("yes, I already know I'm using the Arduino IDE") and like they are only taking up space on the editor tabs bar:

![image](https://user-images.githubusercontent.com/8572152/180448994-bb90f0af-89a7-45e3-9368-3c0313a8c209.png)

However, in the more advanced use case where several file types are open in the editor, and especially in the even more advanced use case where `arduino.language.realTimeDiagnostics` is enabled, I think it is valuable:

![image](https://user-images.githubusercontent.com/8572152/180449722-944e9495-4e6f-412e-a4f4-83221ac6adb5.png)

**Comment by kittaakos** [comment]
Thank you!

Let's leave it as is now without icons and no error decorations.

To enable the feature:
   - Open the _Command Palette_ with <kbd>F1</kbd>,
   - Search for `Preferences: File Icon Theme`, press <kbd>Enter</kbd>
   - Select `File Icons (Theia), press <kbd>Enter</kbd>

Or put `"workbench.iconTheme": "theia-file-icons"` to the `~/.arduinoIDE/settings.json` file.

https://user-images.githubusercontent.com/1405703/180458163-07aa25e8-329a-44f6-b56e-1445a5ba9e54.mp4
