### ISSUE TITLE
Output panel should open immediately at press of "verify" or "upload"

### ISSUE THREAD

**Issue by ubidefeo** [arduino/arduino-ide#1175]
### Describe the request

Modify the behaviour of the output panel upon "verify" or "upload" actions being triggered

As requested by @tigoe in https://github.com/arduino/arduino-ide/issues/279 we should better communicate to the user the following as bare minimum:
* something is happening
* what is happening
  * verify start
  * verify success
  * upload start
  * upload success
* interleave these messages to the tools' standard output we'd see when "verbose" is on

### Describe the current behavior

The behaviour of the output panel differs from IDE 1.x as it won't open immediately at begin of "verify" or "upload" actions.
When compile/upload verbose is disabled, especially since the buttons are disabled at click, this can create the impression that nothing is happening until successful compilation (or error) output needs to be displayed triggering the opening of the output panel.

### Arduino IDE version

2.0 (all)

### Operating system

N/A

### Operating system version

n/a

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My request contains all necessary details

**Comment by kittaakos** [comment]
> * something is happening
> * what is happening
>   
>   * verify start
>   * verify success
>   * upload start
>   * upload success

We agreed on the followings:
 - IDE2 does not add additional content to the _Output_ (such as _verify started_, _upload completed_, etc. messages) but uses the `out_stream` and `err_stream` from the CLI as they are (see: `CompileResponse`, `UploadResponse`, `UploadUsingProgrammerResponse`, and `BurnBootloaderResponse`)m
 - For the verify and compile commands, IDE2 will support progress indication as part of #575.
