### ISSUE TITLE
Having "Window" option on toolbar

### ISSUE THREAD

**Issue by pacav69** [arduino/arduino-ide#1183]
### Describe the request

on most software  there is a window option on the toolbar this allows changing the current window to another open window. For example sketch1 is open and in front while sketch2 is in background by using window option they could be quickly swapped. 

### Describe the current behavior

There is no option 

### Arduino IDE version

Version: 2.0.0-rc8 Date: 2022-06-23T09:37:18.120Z CLI Version: 0.24.0 [c1b10f56]

### Operating system

macOS

### Operating system version

11.6.5 (20G527)

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My request contains all necessary details

**Comment by per1234** [comment]
Hi . Thanks for your suggestion.

I see we have another report about this at .

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place. Even though this one came first, the other has a little bit more information so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
