### ISSUE TITLE
Add Update All Option to Board and Library Updates

### ISSUE THREAD

**Issue by RudraSen2** [arduino/arduino-ide#1188]
### Describe the request

I would like to have the Update All Option in Board and Library Updatable Section. It isn't easy to update one by one.

### Describe the current behavior

Go to Library Manager/Board Manager
See that there is no option for updating all.

### Arduino IDE version

1.8.19 (Windows Store 1.8.57.0)

### Operating system

Windows

### Operating system version

Windows 11 Dev Insider 25158.1000

### Additional context

N/A

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My request contains all necessary details

**Comment by per1234** [comment]
Thanks @RudraSen2. For the sake of making all the relevant information available to the interested parties, I'll add a link to the equivalent feature request for Arduino IDE 1.x: https://github.com/arduino/Arduino/issues/4438

## Related

- https://forum.arduino.cc/t/update-all-needed-in-library-manager/1006050

**Comment by RudraSen2** [comment]
Any update??
