### ISSUE TITLE
Error during Debug: Cannot get command line for tool: cannot get programmer tool: undefined 'debug.tool' property

### ISSUE THREAD

**Issue by Matszwe02** [arduino/arduino-ide#119]
HI. I just downloaded Arduino Pro, uploaded a program into my leonardo and hit "debug", and the error appears.

**Comment by ubidefeo** [comment]
@tuxedo0801 
the debug button now only becomes active when platform's debug support is defined.
Thank you for bringing this up, it's been useful :)

**Comment by el-samiyel** [comment]
Hi All,

Does anyone have a step by step for this, as I am interested in debugging the SAMD51 where possible. I believe its much the same as the SAMD21.

Any assistance will be most appreciated.

**Comment by per1234** [comment]
Hi @el-samiyel. Please request assistance over on the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/c/software/arduino-ide-2-0/93
