### ISSUE TITLE
Serial Monitor new line text hiding behind status bar

### ISSUE THREAD

**Issue by cije49** [arduino/arduino-ide#1198]
### Describe the problem

When you Serial.print(); something to serial monitor, new line text hides behind the status bar (the blue ribbon on the bottom of the program window) as the text is scrolling

Video example:

https://user-images.githubusercontent.com/65641589/179326344-403ba09f-ceea-47bc-a7af-2bc436d4d7e2.mp4

![arduinoIDE_200](https://user-images.githubusercontent.com/65641589/179326416-8917af11-0f21-468b-8650-a656b0febe2e.PNG)

With Nightly:

![with_nightly](https://user-images.githubusercontent.com/65641589/179326420-e6607afb-320b-4dcf-a5c4-0eb125cf8bff.PNG)

### To reproduce

Just copy the code below and upload to any Arduino board ( i tried with Arduino Nano and Generic ESP8266)

```c++
int i = 0;

void setup() {
  Serial.begin(115200);
}

void loop() {
  i++;
  Serial.println(i);
  delay(200);
}
```

### Expected behavior

You can expect to have every new line printed in the Serial monitor to be hidden behind the status bar (the blue ribbon on the bottom of the window)

### Arduino IDE version

Version: 2.0.0-rc8-nightly-20220713 Date: 2022-07-13T03:32:42.528Z CLI Version: 0.24.0 [c1b10f56]  Copyright © 2022 Arduino SA

### Operating system

Windows, Linux

### Operating system version

Windows 10; Kali Linux release 2022.2

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @cije49 . Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/972.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
