### ISSUE TITLE
Alpha 0.1.1 Debugging: breakpoints on local libraries are not considered

### ISSUE THREAD

**Issue by rei-vilo** [arduino/arduino-ide#120]
**Describe the bug**

Breakpoints defined on local libraries are not considered.

**To Reproduce**

Very basic example with 3 files: `Blink.ino`, `LocalLibrary.h`, `LocalLibrary.cpp`
Two breakpoints defined: one in `Blink.ino`, another in `LocalLibrary.cpp`

**Expected behavior**

Breakpoints defined on local library `LocalLibrary.cpp` should be considered.

Actually, all the files are duplicated under a temporary folder, `/private/var/folders/wn/n7qqb8ss0k3bvpqwfcdwp_7r0000gn/T/arduino-sketch-7CD787D3756B222A4A3572C34ED19F79/sketch/`

The breakpoint on `Blink.ino` is kept, but not the breakpoint on `LocalLibrary.cpp`.

**Workaround**

Launch the debugging session.
Define the breakpoint on the local library again.

**Screenshots**

+ Initial project folder during editing

<img width="1440" alt="Capture 2020-02-28 à 15 02 53" src="https://user-images.githubusercontent.com/951776/75554982-acfc2f00-5a3b-11ea-8328-e89b8fedf53f.png">

+ Initial project folder during debugging

<img width="1440" alt="Capture 2020-02-28 à 14 51 28" src="https://user-images.githubusercontent.com/951776/75554559-d9637b80-5a3a-11ea-9cfb-69a62e0ee157.png">

+ Copy to temporary folder during debugging

<img width="1440" alt="Capture 2020-02-28 à 14 50 21" src="https://user-images.githubusercontent.com/951776/75554551-d5cff480-5a3a-11ea-8ecf-bbb65c14eee7.png">

**Desktop (please complete the following information):**
 - macOS 10.15
 - Arduino Pro IDE 0.0.5
 - SAMD core 1.8.5 

**Code**

+ Blink.ino

```
#include "LocalLibrary.h"
uint8_t myLED;

void setup()
{
    Serial.begin(9600);
    delay(500);
    Serial.println(__FILE__);

    myLED = LED_BUILTIN;

    pinMode(myLED, OUTPUT);
}

void loop()
{
    Serial.println(millis());

    blinkLED(myLED, 3, 333);
    delay(1000);
}
```

+ LocalLibrary.h

```
#include "Arduino.h"

#ifndef blink_LocalLibrary_h
#define blink_LocalLibrary_h

///
/// @brief      Blink a LED
/// @details	LED attached to pin is turned on then off
/// @note       Total cycle duration = ms
/// @param      pin pin to which the LED is attached
/// @param      times number of times
/// @param      ms cycle duration in ms
/// @param		level level for HIGH, default=true=positive logic, false=negative logic
///
void blinkLED(uint8_t pin, uint8_t times, uint16_t ms, bool level = true);
// !!! Help: https://bit.ly/2Bwmyk6

#endif // blink_LocalLibrary_h
```

+ LocalLibrary.cpp

```
#include "LocalLibrary.h"

// Code
void blinkLED(uint8_t pin, uint8_t times, uint16_t ms, bool level)
{
    for (uint8_t i = 0; i < times; i++)
    {
        digitalWrite(pin, level ? HIGH : LOW);
        delay(ms >> 1);
        digitalWrite(pin, level ? LOW : HIGH);
        delay(ms >> 1);
    }
}
```

**Comment by rei-vilo** [comment]
@ubidefeo Nice to know it is a "good bug" :-)

**Comment by rsora** [comment]
@rei-vilo Please check the [beta.4 version](https://github.com/arduino/arduino-ide/releases/tag/2.0.0-beta.4), your issue should be solved (the fix was done here https://github.com/arduino/arduino-cli/pull/1224)

Feel free to close the issue if you don't experience the issue anymore.

Happy coding!

**Comment by rei-vilo** [comment]
@rsora Thank you for the update. I’ll give a try when I return home. 

I am a bit lost between this alpha 0.1.1 and the beta 2.0. 

Are they the same project? How do they compare?

**Comment by ubidefeo** [comment]
@rei-vilo 
Over the past few months we have brought the most important parts of Pro IDE into this new IDE 2.0,
which is now the base of development for advanced features we'll be adding from this point on.

Please try IDE 2.0 Beta 4 like suggested by @rsora and let us know.
If your issue is resolved, please close this issue 👍🏼

**Comment by rei-vilo** [comment]
Sorry for the late answer. Simple breakpoint works now on libraries.

However, conditional breakpoint doesn't seem to work yet. I am opening a new ticket at #268.
