### ISSUE TITLE
Themes: High Contrast is broken 

### ISSUE THREAD

**Issue by AlbyIanna** [arduino/arduino-ide#1202]
### Describe the problem

With the last changes in the color themes, we've accidentally broken the High Contrast theme, which now lacks some UI elements that are present in other themes and it results in a degraded experience.

Here is an example:

https://user-images.githubusercontent.com/6939054/179462951-122ffa10-4757-44ea-9a0a-28678db7bd4a.mov

### To reproduce

- open the Preferences
- enable the **High Contrast (Theia)** theme
- 🐛  UI is broken (missing hover status in dropdowns and in the sketchbook, primary buttons background is transparent, board selector has no border, etc...)

### Expected behavior

- open the Preferences
- enable the **High Contrast (Theia)** theme
- 🦋 UI is not broken

### Arduino IDE version

2.0.0-rc8-snapshot-4f27725

### Operating system

macOS

### Operating system version

MacOS Monterey 12.3.1

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

**Comment by kittaakos** [comment]
Also, we should restore the border (or have any other working solution) for the board selector dropdown.

<img width="289" alt="Screen Shot 2022-07-19 at 16 10 33" src="https://user-images.githubusercontent.com/1405703/179771501-e0941dc0-733d-4196-8dae-6196ab900f54.png">

It used to be like this with RC-8:
<img width="249" alt="Screen Shot 2022-07-19 at 16 12 34" src="https://user-images.githubusercontent.com/1405703/179771762-7ebc4af6-f011-4805-9ed5-9067c213b1db.png">
