### ISSUE TITLE
Problem with WiFiNINA.h

### ISSUE THREAD

**Issue by GitHubRea** [arduino/arduino-ide#121]
**Describe the bug**
problem with WiFi-Status constant.
see screenshot: arduino-pro-ide 0.0.5
<img width="640" alt="image" src="https://user-images.githubusercontent.com/60554523/75382097-254adf00-58da-11ea-8c25-33929171e268.png">

But in Arduion 1.8.12 it is working fine
<img width="495" alt="image" src="https://user-images.githubusercontent.com/60554523/75382710-495af000-58db-11ea-9c61-d6d11116905f.png">

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Version [10.15.3]

**Comment by per1234** [comment]
I am able to reproduce the issue of the incorrect language server results with older versions of the IDE (e.g. 2.0.0-beta.3), but not with 2.0.0-beta.12.

So I'll close this as fixed. If anyone is able to still reproduce the issue with the latest version of the IDE, please comment here with full details and I'll investigate.

Note: While attempting to bisect, I had annoying experiences of the bad state persisting into later IDE versions until I cleared the data folders, after which I could no longer reproduce the issue with those later IDE versions.
