### ISSUE TITLE
The output is treated as the source code for correction prompts

### ISSUE THREAD

**Issue by Silver-Fang** [arduino/arduino-ide#1210]
### Describe the problem

In non-English IDE installations, non-ASCII punctuation characters, such as Chinese brackets （）, often appear in the output box. When these symbols appear in the output box, they will be highlighted by the code analysis tool as source code and judged to be obfuscated symbols. This is ridiculous.

### To reproduce

Upload the code on the Chinese version of the IDE, you will see:
![屏幕截图 2022-07-19 093725](https://user-images.githubusercontent.com/33191697/179645963-2eaf9711-b3d2-451a-a1cc-f74792e9dfc3.png)

### Expected behavior

The output should not be prompted for correction as code.

### Arduino IDE version

2.0.0-rc8

### Operating system

Windows

### Operating system version

10.0.19044.1826

### Issue checklist

- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [x] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] My report contains all necessary details

**Comment by kittaakos** [comment]
Could you please try and modify the advanced settings and let us know if it solved the problem:
 - Open IDE2,
 - Press <kbd>F1</kbd>,
 - Type `Preferences: Open Settings (JSON)`, press <kbd>Enter</kbd>,
 - Add the following entries to the JSON:
 ```json
{
  "editor.unicodeHighlight.ambiguousCharacters": false,
  "editor.unicodeHighlight.invisibleCharacters": false
}
````
 - Close the `settings.json` by clicking on the `X`,
 - Tell us if it fixed the issue in the _Output_.

Here is the ref on how it should work: https://code.visualstudio.com/updates/v1_63#_unicode-highlighting

**Comment by kittaakos** [comment]
> No, not fixed.
> Highlights disappeared in the real source code, but not in the output box.

Thank you so much for trying it and reporting back. I will try to come up with a fix soon.

**Comment by Silver-Fang** [comment]
> @Silver-Fang, could you please share a bare-minimum sketch that I can use to reproduce the problem? Thank you!

You can simply create a new sketch and Verify/Upload. The problem has nothing to do with the sketch. What you really need is a Chinese locale. Maybe you should try to set your OS to Chinese and then launch the IDE?

**Comment by Silver-Fang** [comment]
> @Silver-Fang, could you please share a bare-minimum sketch that I can use to reproduce the problem? Thank you!

I guess the problem is from the incorrect application of some code checks to the output box. The output text should not be the prey of any code checkers.

**Comment by kittaakos** [comment]
I have opened an upstream PR: https://github.com/eclipse-theia/theia/pull/11615.

I will look for a temp solution for the time being.

**Comment by kittaakos** [comment]
@Silver-Fang, I have a PR with some changes. Can you please help verify whether the proposed changes fix the issue on your side?

Here is the PR: https://github.com/arduino/arduino-ide/pull/1375

Please let me know if you do not know how _GitHub Actions_ works or cannot download the build artifacts. You have to be logged in with your GH account to see the artifacts.

**Comment by Silver-Fang** [comment]
> @Silver-Fang, I have a PR with some changes. Can you please help verify whether the proposed changes fix the issue on your side?
> 
> Here is the PR: #1375
> 
> Please let me know if you do not know how _GitHub Actions_ works or cannot download the build artifacts. You have to be logged in with your GH account to see the artifacts.

Yes, please tell my how to get the binary with your fix.

**Comment by kittaakos** [comment]
Sure, thank you for your support on this.

 - You need a GitHub account (you have one)
 - You need to be logged in (you are),
 - Go to the [PR](https://github.com/arduino/arduino-ide/pull/1375),
 - Click on `Checks`,
    ![Screen Shot 2022-08-31 at 14 16 05](https://user-images.githubusercontent.com/1405703/187676509-26a038a6-efbb-444a-83d3-b06af6e5130b.png)
 - Click on `Arduino IDE` on the left:
    ![Screen Shot 2022-08-31 at 14 16 12](https://user-images.githubusercontent.com/1405703/187676664-187b95ad-ce51-4bd4-8321-d263186d1299.png)
 - Scroll down to the bottom of the page and pick the artifact for your OS:
    ![Screen Shot 2022-08-31 at 14 16 22](https://user-images.githubusercontent.com/1405703/187676796-37e72f74-8311-4d04-93a1-f356649ed9a6.png)

Notes:
 - You cannot scroll in this area 🤦
    ![Screen Shot 2022-08-31 at 14 20 29](https://user-images.githubusercontent.com/1405703/187677046-f446a0af-83c4-4964-9fe6-b8c4239534b8.png)
 - If for whatever reason, you cannot access and download the artifacts, let me know.
