### ISSUE TITLE
"Optimize for Debugging" state indicator doesn't change from disabled

### ISSUE THREAD

**Issue by per1234** [arduino/arduino-ide#1212]
### Describe the problem

The "**Optimize for Debugging**" item in the Arduino IDE's "**Sketch**" menu toggles the state of the `arduino.compile.optimizeForDebug` setting. The current state of the setting is indicated by the presence or absence of a **✓** at the left side of the menu item:

![image](https://user-images.githubusercontent.com/8572152/179661290-c6899c94-0b61-481e-af44-588e86c3fb12.png)

🐛 If the setting was disabled (the default state) when the Arduino IDE window was opened, the **✓** indicator will not appear when the setting is enabled.

#### Set up

1. Open the Arduino IDE's "**Sketch**" menu.
1. If there is a **✓** at the left side of the "**Optimize for Debugging**" menu item, select the menu item to disable it and open a new window.

#### Steps

1. Select **Sketch > Optimize for Debugging** from the Arduino IDE menus.
1. Open the Arduino IDE's "**Sketch**" menu.

🐛 There is no **✓** indicator next to the "**Optimize for Debugging**" menu item, even though the setting is enabled:

![image](https://user-images.githubusercontent.com/8572152/179661319-c136029d-bae6-46b7-9ae3-bc30761a7172.png)

### Expected behavior

State of the `arduino.compile.optimizeForDebug` setting is always indicated in the "**Sketch**" menu.

### Arduino IDE version

2.0.0-rc8-snapshot-5ff9ce0

### Operating system

Windows

### Operating system version

10

### Additional context

I bisected the introduction of the issue to 8ad10b5 (it does not occur when using the build for fe31d15)

---

I verified that the **Sketch > Optimize for Debugging** menu item is changing the `arduino.compile.optimizeForDebug` setting even when the indicator is not working.

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

**Comment by kittaakos** [comment]
Possible this one: https://github.com/eclipse-theia/theia/issues/11221
