### ISSUE TITLE
the serial Plotter can't be opened

### ISSUE THREAD

**Issue by xwzkj** [arduino/arduino-ide#1231]
### Describe the problem

in the menu "tools",the serial Plotter can't be opened

### To reproduce

-

### Expected behavior

-

### Arduino IDE version

2.0.0-rc8

### Operating system

Windows

### Operating system version

windows10 21h2

### Issue checklist

- [ ] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [ ] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [ ] My report contains all necessary details

**Comment by per1234** [comment]
Closing due to lack of response.

@xwzkj if you will provide the requested information by commenting here, I'll be happy to re-open this issue.
