### ISSUE TITLE
High RAM & CPU Usage

### ISSUE THREAD

**Issue by aliphys** [arduino/arduino-ide#1240]
### Describe the problem

The Arduino IDE uses over 25% of the CPU resources and 1GB of RAM. In the bottom left of the screen, it says `indexing` which does not go away even after 15 minutes
![image](https://user-images.githubusercontent.com/75624145/180437336-e353cd52-3b80-45c1-8b56-81f20af88984.png)

![image](https://user-images.githubusercontent.com/75624145/180438426-007f328a-8dfa-4d82-8ef2-b94217040fc6.png)

### To reproduce

1. Open the IDE
2. Run a sketch
3. Sometimes the message pops up in the bottom left corner which says `indexing`.
4. Check Task Manager

Laptop is a core i7 with 24GB of RAM.

### Expected behavior

CPU usage would fall down to under 5% and 500 MB after compiling.

### Arduino IDE version

IDE 2.0.0-rc9

### Operating system

Windows

### Operating system version

Windows 10

### Additional context

Not tested with latest nightly build

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @aliphys. Thanks so much for your report.

We are tracking this problem at https://github.com/arduino/arduino-ide/issues/714

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread. We also have an active discussion about it over on the forum: https://forum.arduino.cc/t/cpu-utilization-very-high/941187

We are currently analyzing data provided recently by some of the other affected users, but we will definitely get in contact with you if we need additional information or testing.
