### ISSUE TITLE
If the IDE window is not requested to be displayed on the screen, the bootloader will get stuck.

### ISSUE THREAD

**Issue by Silver-Fang** [arduino/arduino-ide#1254]
### Describe the problem

There seems to be a step in the IDE window loading process that has to be requested to be displayed before passing. If the IDE window is always completely covered by other windows, bootloading cannot be completed.

### To reproduce

1. Open IDE or .ino file.
2. The moment the splash screen appears, immediately switch to another maximized, full-screen window, the sooner the better, ensuring that every corner of the IDE window is completely covered, eliminating any chance of the IDE window being displayed, including previewing it by hovering over the IDE window icon on the taskbar.
3. Wait for an hour or longer. The IDE window loading never completes and the splash screen never disappears.
4. Switch to the IDE window to make it visible, or hover over the IDE window icon on the taskbar to preview it. Loading is done in seconds.

### Expected behavior

The IDE window should be able to complete all loading steps below any other window without requiring any actual display. The sign of finished loading is the disappearance of the splash screen.

### Arduino IDE version

2.0.0-rc9

### Operating system

Windows

### Operating system version

11.0.25163.1010

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @Silver-Fang. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/327 (there is also a different but closely related https://github.com/arduino/arduino-ide/issues/193).

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
