### ISSUE TITLE
Serial monitor window cannot see bottom row

### ISSUE THREAD

**Issue by xuancong84** [arduino/arduino-ide#1267]
As shown below, in Linux/Ubuntu, the serial monitor window always cannot see the bottom row, even if I scroll to very bottom, upon new input, it stupidly scrolls to the position that hides off most of the bottom row, very annoying.

![image](https://user-images.githubusercontent.com/10172392/181587055-e9d2eef4-deea-46b7-95cf-eb1714f35951.png)

**Comment by per1234** [comment]
Hi @xuancong84. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/972.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
