### ISSUE TITLE
Drag Serial monitor window to the left or right side

### ISSUE THREAD

**Issue by ednieuw** [arduino/arduino-ide#1268]
### Describe the request

As a user I want to dock the Serial monitor window on the left or right side of the IDE. The docking position must be remembered after starting the IDE again. Docking separately from the IDE would be a fine addition

In the first releases of this IDE it was possible to drag the serial monitor screen to the side. 
Especially on wide screens this was very handy. 
It was not possible to dock it permanently

### Describe the current behavior

It is permanent at the bottom

### Arduino IDE version

rc9

### Operating system

Windows

### Operating system version

w11

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My request contains all necessary details

**Comment by per1234** [comment]
Hi @ednieuw. Thanks for your suggestions.

> In the first releases of this IDE it was possible to drag the serial monitor screen to the side.

This ["Flexible Window Layout"](https://www.typefox.io/blog/flexible-window-layout-in-theia-ide) feature was intentionally disabled in https://github.com/arduino/arduino-ide/pull/940

>Docking separately from the IDE would be a fine addition

I see we have another request for this at https://github.com/arduino/arduino-ide/issues/289.

Note this comment from the development head:

https://github.com/arduino/arduino-ide/issues/289#issuecomment-1070964887

>it's definitely in our roadmap and at the top of the list.
>
>We are giving maximum priorities to bugs that compromise the standard usage, next will come performance and UX improvements, like this issue with the monitor. We already designed the new one that is gonna be a separate window like the serial plotter.

So your alternative request will be accommodated in the near future.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
