### ISSUE TITLE
Workspaces, Folders, Sketches...

### ISSUE THREAD

**Issue by cirobruno** [arduino/arduino-ide#127]
Taking some time during vacations for getting used to Arduino Pro IDE V0.0.2 (0.0.2.20191025.13).

Third time trying, but I guess I haven't understood the roles of Workspaces and Folders in relation to Sketches.

Starting Arduino Pro IDE, I haven't already found out how to begin a sketch and give it the name I'd like to. I always have to save it named like the date I've started it. Indeed I've just managed to name the Workspade ("Save Workspace as ..."). Nevertheless, the sketch inside it is also named like the current date. The only solution I found to have a Sketch named as I desire is to prior creating it in Arduino IDE (that one for mortal people) and saving it, so that I can further open it in Arduino Pro IDE.

Moreover, why "New Folder" and "Add Folder to Workspace..."? What are these resources designed for?

So, what's the relationship between Workspaces, Folders and Sketches? Is there any tutorial about it?

#_requires_developers'_further_instructions

**Comment by per1234** [comment]
Thanks for the report @cirobruno!

You raised some very good points here and the UI of the IDE has been significantly upgraded to deal with these very issues.
The workspace concept has been removed from the UI. I think the new interface, which is based on the classic Arduino IDE, is very intuitive and will not result in this sort of confusion.

So I'll close this as resolved.
