### ISSUE TITLE
Serial send trigger

### ISSUE THREAD

**Issue by ArcRobotics** [arduino/arduino-ide#1270]
### Describe the request

I would like to be able to change the sending commands in the serial monitor the way it was before using just Enter button so if u could that option available for change that would be nice thx.

### Describe the current behavior

currently i have to press CTRL+ENTER

### Arduino IDE version

IDE2

### Operating system

Windows

### Operating system version

windows 10

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My request contains all necessary details

**Comment by per1234** [comment]
Hi @ArcRobotics. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/572.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
