### ISSUE TITLE
Upload fails when Serial Monitor is open

### ISSUE THREAD

**Issue by per1234** [arduino/arduino-ide#1278]
### Describe the problem

The Arduino IDE uses the serial ports of Arduino boards in two different ways:

- Uploading sketches
- Communication via **Serial Monitor**

The port can not be used for both of these things simultaneously. Rather than imposing the inconvenience of juggling the port usage on the user the Arduino IDE is intended to handle the condition of **Serial Monitor** being open when an upload is started automatically like so:

1. Close port in **Serial Monitor**
2. Complete upload process
3. Reopen port in **Serial Monitor**

🐛 Uploading fails when the **Serial Monitor** is open, indicating the port handling is not working correctly.

### To reproduce

1. Connect an Arduino board to your computer.
1. Select the appropriate board and port in the Arduino IDE.
1. Open **Serial Monitor** in the Arduino IDE.
1. Select **Sketch > Upload** from the Arduino IDE menus.

🐛 The upload fails with an error like:

```text
Failed uploading: uploading error: exit status 1avrdude: ser_open(): can't open device "\\.\COM61": Access is denied.
```

### Expected behavior

Having Serial Monitor open does not interfere with uploading.

### Arduino IDE version

2.0.0-rc9.1

### Operating system

Windows

### Operating system version

10

### Additional context

I bisected the introduction of the issue to https://github.com/arduino/arduino-ide/commit/e156dcc213221489241669f076937a1642a2ab16 / https://github.com/arduino/arduino-ide/pull/1260

---

Originally reported tangentially at https://github.com/arduino/arduino-ide/issues/581#issuecomment-1203193020

---

It may be the same issue as reported at https://github.com/arduino/arduino-ide/issues/1277, but there is currently insufficient information there to be able to say.

UPDATE: per https://github.com/arduino/arduino-ide/issues/1277#issuecomment-1203738489, https://github.com/arduino/arduino-ide/issues/1277 does not have Serial Monitor as a required condition, which indicates these are two separate issues.

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

**Comment by InstantMuffin** [comment]
Thanks you for referencing #1277. It seems odd this is the same bug as we get differing error messages. At the same time you can narrow down the problem precisely to a commit, and I can narrow it down in to the changes since rc-9.0.
I'll see to it if I can also boil it down to that specific changeset on my end.
