### ISSUE TITLE
Missing "Close Folder" option

### ISSUE THREAD

**Issue by OslafEman** [arduino/arduino-ide#128]
**Is your feature request related to a problem? Please describe.**
Can not find the way to quick change from one project to another one.

**Describe the solution you'd like**
Adding a "Close Folder" option should be great.

Windows 10
Alpha 0.0.3

**Comment by per1234** [comment]
Thanks for taking the time to make this request @OslafEman. The IDE's UI has since been reworked with inspiration from the beloved classic Arduino IDE. It is now easy to open multiple projects, one in each window.

So I'll close this as resolved.
