### ISSUE TITLE
The layout of the main toolbar items (toggle pro-mode, serial monitor) is broken

### ISSUE THREAD

**Issue by kittaakos** [arduino/arduino-ide#129]
**Describe the bug**
Refer to the bug title and see the attached screencast:
![screencast 2019-11-12 10-51-41](https://user-images.githubusercontent.com/1405703/68661057-9f797280-053a-11ea-9a41-c1b0e164b6ef.gif)

**Desktop:**
 - OS: all
 - Version: from source, `HEAD`

**Comment by per1234** [comment]
>if a "proper" fix is found for that and the minimum window size is made more reasonable.

This has happened: https://github.com/arduino/arduino-ide/pull/243

**Comment by per1234** [comment]
Closing as resolved by https://github.com/arduino/arduino-ide/pull/1151
