### ISSUE TITLE
Add "Arduino" launcher symbol for Arduino Pro IDE Linux

### ISSUE THREAD

**Issue by aentinger** [arduino/arduino-ide#131]
**Is your feature request related to a problem? Please describe.**
Using [Arduino Pro IDE Linux v0.0.2-alpha.preview](https://downloads.arduino.cc/arduino-pro-ide/arduino-pro-ide-0.0.2-alpha.preview-linux64.tar.xz) on Ubuntu 18.04.3 LTS I've noticed that no Arduino logo or something similiar is displayed on the launcher when running the Pro IDE. Instead the default "no-logo" launcher symbol is shown. Looking through the Arduino Pro IDE directories I also did not find a suitable illustration (maybe I missed it?).

![2019-10-30-Arduino-Pro-IDE-Logo](https://user-images.githubusercontent.com/3931733/67836043-d20f7e00-faeb-11e9-9c8f-92007d24b14e.png)

**Describe the solution you'd like**
When I run the Arduino Pro IDE I'd like to see the Arduino logo or a dedicated Arduino Pro IDE logo  (if such a Arduino Pro IDE logo exists) in the launcher.

**Comment by AndKe** [comment]
This issue is still a thing on Linux (at least Ubuntu)  - nor is a .png icon provided..   why is this issue closed?

**Comment by per1234** [comment]
>why is this issue closed?

@AndKe It's not closed. It's open. I guess you were mislead by the "Closed" label shown next to the reference from the duplicate issue https://github.com/arduino/arduino-ide/issues/329. That's just how GitHub works.

**Comment by matteocordray** [comment]
Any updates on this? Current Arduino IDE on Ubuntu 20.04 still displays no symbol...

**Comment by Sid110307** [comment]
Any update?

**Comment by ParadoxNinja** [comment]
If there was a `arduinoIcon.png` file provided while downloading, the users can manually set the icon in Ubuntu in the properties of the `.appimage` file

**Comment by AndKe** [comment]
come on... we need to have higher ambitions than "set icon manually"
Devs need to look at https://github.com/thomasnordquist/MQTT-Explorer  - that project has a perfectly working icon.

**Comment by cassiorodrigo** [comment]
3, 4 years? No response? Come on, guys... Icon... It's not a big thing, but it's odd to see an empty spot in there.

**Comment by AndKe** [comment]
Another example of how to do it right would be to look at the PrusaSlicer appimage.

**Comment by cassiorodrigo** [comment]
I managed to get the image 512x512 in the repo and make it the default icon but it feels wrong. This should be placed by the appimage itself.

**Comment by AndKe** [comment]
@cassiorodrigo please consider looking at PrusaSlicer or MQTT-Explorer (both open source projects) for clues on how to do it right.
thank you for looking into this.

**Comment by cassiorodrigo** [comment]
> @cassiorodrigo please consider looking at PrusaSlicer or MQTT-Explorer (both open source projects) for clues on how to do it right. thank you for looking into this.

Will do, thanks.

**Comment by AndKe** [comment]
@kittaakos Thank you!
