### ISSUE TITLE
Broken buttons when installing libs

### ISSUE THREAD

**Issue by kittaakos** [arduino/arduino-ide#1314]
### Describe the problem

Sometimes, the buttons look ugly in the lib install dialog.

<img width="652" alt="Screen Shot 2022-08-10 at 13 32 41" src="https://user-images.githubusercontent.com/1405703/183891009-36380a41-0413-4cf2-8b34-0e2a8d246f45.png">

### To reproduce

Try to install `Adafruit MAX31855 library:1.3.0`, it does not look good. The UI scale is 100%.

https://user-images.githubusercontent.com/1405703/183890732-a8295381-fa07-4bf6-8ca6-73ebfd96de08.mp4

### Expected behavior

The buttons look OK.

### Arduino IDE version

9cabd404

### Operating system

macOS

### Operating system version

12.3.1

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

**Comment by ubidefeo** [comment]
This seems to be related to the window size.
At its minimum the layout of the buttons shifts around
