### ISSUE TITLE
File are not renamed when renaming tab

### ISSUE THREAD

**Issue by matsekberg** [arduino/arduino-ide#1316]
### Describe the problem

If I rename the filename of a tab; eg util.c to util.cpp
When compiling the compiler will still use the util.c file and ignore the newly renamed util.cpp

### To reproduce

Create a new file in a new tab, rename the tab.
Check in the directory, both files will be there.

### Expected behavior

The file should be renamed,

### Arduino IDE version

2.0.0-rc9.2

### Operating system

macOS

### Operating system version

Monterey 12.5

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

**Comment by matsekberg** [comment]
I think it may have to do with caching. If I change board, compile and change back to the correct board and build it works.

**Comment by per1234** [comment]
Hi @matsekberg. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-cli/issues/1240.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
