### ISSUE TITLE
Error: 13 INTERNAL: Cannot install tool...

### ISSUE THREAD

**Issue by juddidier** [arduino/arduino-ide#1352]
### Describe the problem

With certain antivirus installation of tools fails with the error e.g.:
> Failed to install platform: esp32:esp32.
> Error: 13 INTERNAL: Cannot install tool ... moving extracted archive to destination dir: rename xxxx\xtensa-esp32-elf yyyy\xtensa-esp32-elf-gcc\gcc8_4_0-esp-2021r2-patch3: Access is denied.

renaming a directory (in my case `xtensa-esp32-elf`) to a nested directory (`xtensa-esp32-elf-gcc\gcc8_4_0-esp-2021r2-patch3`) is blocked. 

### To reproduce

in my case I use mcAfee

### Expected behavior

in the tool installation process manually create the parent directory (in my case `xtensa-esp32-elf-gcc`) and then move.

### Arduino IDE version

2.0.0rc9.2

### Operating system

Windows

### Operating system version

10

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @juddidier. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/1307. See the discussion there for the explanation of the most common causes of this error.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
