### ISSUE TITLE
Annoying auto text formatting issues.   Magical text cursor 

### ISSUE THREAD

**Issue by KurtE** [arduino/arduino-ide#1364]
### Describe the problem

Sorry I know there must be several reports on things like this.  

But I got annoyed this morning, after more times where something that appears like should just work correctly
like hit CR to create a new line and have the cursor go to the right place and does not.  And then when you try to correct it does something else strange.  

### To reproduce

Suppose I wanting to add new line
![image](https://user-images.githubusercontent.com/1558080/187075880-b8a2b35c-b0c0-41ba-b6c1-6e0d625417eb.png)
I hit CR and at first the cursor moves to the right place and then jumps to start of line?
![image](https://user-images.githubusercontent.com/1558080/187075941-bd2efd60-10df-424b-ae6e-459022c84a3e.png)
So I hit tab to get to the right spot and start typing the next line:   I type; if
and again, text cursor jumps to strange place
![image](https://user-images.githubusercontent.com/1558080/187076023-4ed099fe-973e-4c4e-8a4f-d93b6e69e6cf.png)
Sorry images not picking up text cursor but it is now on the next line with the other Text line

So I hit up arrow and then hit the end key and now the cursor is at about:
![image](https://user-images.githubusercontent.com/1558080/187076137-f2ee52f5-74ac-420d-b4b5-ac6cd6d8b071.png)
Red mark is about where it is.  I back space 5 or 6 times to get back to after if:
I type in: if ((buttons & 1) != buttons_prev & 1)) {
it fills in the trailing }, I hit the CR
![image](https://user-images.githubusercontent.com/1558080/187076284-72c2888e-a4a6-4f56-bcdf-cc869008243e.png)
And back to another repeat where the Text cursor goes to the right place and then jumps back to start to repeat this whole process over again.

Edit: I then was then trying to finish the code change in this section, and after the buttons >>=1;
I am adding: buttons_prev <<= 1;
But after I typed: butt, the text changed and the cursor went again to start of next line:
![image](https://user-images.githubusercontent.com/1558080/187076606-27c1c2ef-fdae-4537-941a-87fe0fd30f54.png)

### Expected behavior

The text cursor would go where it should.

### Arduino IDE version

Nightly 20220827

### Operating system

Windows

### Operating system version

Windows 11

### Additional context

Sorry, I know there are probably several like reports of this, but sometimes hard to search.

Wish there was a simple place to post a questions/observation, and then hopefully someone can triage it...
I have been trying to use the IDE to do a lot of my editing of test sketches, instead of doing the work within sublime Text, which also allows me to edit/view the library code as well as do the builds which when there are errors, I can again see the library code...  And then I use TyCommander to do Serial monitor stuff.

The main things that keep me from wanting to use the IDE 2 more are:
a) The problems with the Serial Monitor - clips the bottom, can't easily navigate with keyboard (or mouse), issues with copy content from it.
b)  I cannot identify exactly it, but the new daily builds versus RC9.2 feels like it forgets what port it is working with more, especially when I am switching back and forth from building and using TyCommander
c) The annoying magical text cursor and similar strange auto formatting.  

Again, my guess is this has been reported before! If so feel free to close...

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @KurtE . Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/437.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.

---

I'll provide instructions for the simple workaround that was discovered by a community member:

1. Open the "**Command Palette**" via the <kbd>**Ctrl**</kbd>+<kbd>**Shift**</kbd>+<kbd>**P**</kbd> (<kbd>**Command**</kbd>+<kbd>**Shift**</kbd>+<kbd>**P**</kbd> for macOS users) keyboard shortcut.
1. Select the "**Preferences: Open Settings (UI)**" command.
1. In the "**Search Settings**" field, type `files.trimAutoWhitespace`
1. Uncheck the checkbox next to "**`☑` Remove trailing auto inserted whitespace.**"

---

>Wish there was a simple place to post a questions/observation, and then hopefully someone can triage it...

All are welcome to participate in the dedicated category on the Arduino Forum for Arduino IDE 2.x:

https://forum.arduino.cc/c/software/arduino-ide-2-0-beta/93

I try to be pretty active in addressing the posts there, whether that is providing support, linking to relevant GitHub issues/PRs, or escalating verified original bug reports/feature requests to the appropriate GitHub issue tracker.
