### ISSUE TITLE
Project file handling

### ISSUE THREAD

**Issue by Drakelive** [arduino/arduino-ide#137]
Hello everyone

I think the View Explorer creates confusion when we have more projects. The IDE on startup always opens the first one.
If I select a project in the list proposed by the "Open" button it opens all the files contained, horizontally as in the Cassic Mode.  In very large projects there is confusion.

Can we think of adding a new Project File? It could contain all project files and all folders, libraries, Arduino type and preferences. etc. The IDE should open one project at a time.

Drk

**Comment by per1234** [comment]
Thanks for taking the time to submit this issue @Drakelive! The IDE's UI has been significantly reworked over the last year specifically to address the sort of confusing experience you have reported here.

The Explorer is no longer an integral part of the UI and the IDE now does only open one sketch per window.

So I'll close this as resolved.
