### ISSUE TITLE
Bug with "Peek Declaration" and "Peek Definition" also with "Go To ..."

### ISSUE THREAD

**Issue by sstaub** [arduino/arduino-ide#138]
**Describe the bug**
There is a bug with "Peek Declaration" and "Peek Definition"
"Peek Declaration" does nothing!
"Peek Definition" shoes the declaration of  functions instead of their definition
The same happens with "Go To...

**To Reproduce**
1. Open Blink example
2. right click on **digitalWrite** and select "Peek Declaration" -> noting happens
3. right click on **digitalWrite** and select "Peek declaration" -> it shows the declaration  in common.h

**Expected behavior**
It should work like in VSC, in this example
- "Peek Declaration" should show the declaration of the function in common.h
- "Peek Definition" should show the definition of the function in wiring_digital.c

**Screenshots**
- Peek Definition in Arduino IDE
<img width="1072" alt="peek definition Arduino IDE" src="https://user-images.githubusercontent.com/6450325/67200759-f2ad4900-f404-11e9-9fe4-1a4d82a06041.png">

- Peek Definition in VSC
<img width="1277" alt="peek definition in VSC" src="https://user-images.githubusercontent.com/6450325/67200794-08227300-f405-11e9-9070-002b195356b9.png">

**Desktop (please complete the following information):**
 - macOS Catalina
 - Version 0.0.1

**Comment by mink99** [comment]
I would not consider the language server bugs as low. Hover help, and project navigation are the one  main differentiator between 2.0 and 1.x. And if these features are not working as expected , i would consider a partially working project navigation and hover help as working at all, and therefore upgrading to 2.0 makes currently no sense, 
... as those colleagues who are using a debugging facility, the other usp, have already switched to alternative ide

**Comment by per1234** [comment]
>"Peek Declaration" does nothing!

This non-functional feature has been removed.

>right click on **digitalWrite** and select "Peek declaration" -> it shows the declaration in common.h

This issue is board-specific. For example, I am able to reproduce it with the "Arduino MKRZERO" board, but not with "Arduino Uno".

Note that the megaavr architecture is not supported at all now (https://github.com/arduino/arduino-ide/issues/31), so you will no longer get the described results with the "Arduino Nano Every" board selected.

**Comment by per1234** [comment]
As I mentioned above, the non-functional "Peek Declaration" feature was removed (https://github.com/arduino/arduino-ide/issues/1394). We are tracking the need to implement this feature at https://github.com/arduino/arduino-language-server/issues/156.

This leaves one other bug report that was mashed into this issue:

> "Peek Definition" shoes the declaration of functions instead of their definition
The same happens with "Go To...

We are not tracking that in the higher quality issue https://github.com/arduino/arduino-language-server/issues/167 so I will close this one as a duplicate.
