### ISSUE TITLE
Help Forum...

### ISSUE THREAD

**Issue by MrRSquared** [arduino/arduino-ide#141]
I enjoy the new implementation of the Arduino Pro IDE, and it meets of the desires I had subconsciously, and did not know I was missing.
**Is your feature request related to a problem? Please describe.**
After opening the app and getting over the initial excitement of the vscode implementation, I quickly got really confused as to where to go to ensure my libraries (especially custom ones) were installed.  This has always been a powerful feature of the IDE (and why I currently do not use vscode for my arduino projects).

**Describe the solution you'd like**
Because I think it is way too early for any documentation, it would be great if there were an online portal where people can discuss difficulties they are having with migration.  I realize may be too much of a NOOB to be expecting much out of Alpha software, but the entire interface has been revamped and as such, many Arduino IDE conventions are missing, or have been moved.  Without knowing the expectation, it is difficult to know which (missing or moved) is true.  This is true even with the classic view of the IDE.

**Describe alternatives you've considered**
I have (and will continue) to poke around in the IDE to look for solutions.  The immediate need for me is to understand where the workspace and libraries folders are.

**Additional context**
On Windows (I am on WIn10), the installer is a portable .exe and folder.  Upon opening it, it opens my last used .ino, but there are errors (including the error, sketch (linting? I forget the actual language used) may not be accurate, because the Arduino Uno library is not installed).  Yet, when I look to install it, it looks like it is installed.  I do not know if this is a bug, or operator error because the interface looks so different (in a good way), I cannot tell how I was supposed to set up the environment (which I probably did not do correctly).  I am fully aware that with new software the docs are frequently the last things written, but some help would be nice.

Thank you for creating the hardware and software.  This is an amazing device, and the upgraded IDE is incredible already. As a side note, the inclusion of the source control module is superb.

**Comment by per1234** [comment]
Now that this is the Arduino IDE, the standard forum board should be used for support and discussion:
https://forum.arduino.cc/index.php?board=2.0
Thanks!
