### ISSUE TITLE
Let tools menu items show current option like 1.x

### ISSUE THREAD

**Issue by pwnept** [arduino/arduino-ide#1434]
### Describe the request

Like in 1.x, items in the tools menu i.e. ESP32 "CPU Frequency", "Core debug level", and STM32 Optimization level can easily be viewed at a glance without having to explicitly hover over each option which can be hard when wanting to view multiple options at once. (See picture below)

### Describe the current behavior

Tools menu items does not show current option selected.

### Arduino IDE version

2.0.0

### Operating system

Windows

### Operating system version

Windows 10 21H2(10.0.19044)

### Additional context

![image_2022-09-15_092433973](https://user-images.githubusercontent.com/34002935/190299053-1b7dd6e0-b624-4d65-a3cf-90081b3d3ddf.png)
![image_2022-09-15_092919302](https://user-images.githubusercontent.com/34002935/190299438-f4a03299-dab1-40b6-9b8e-d9acce220a5f.png)

If the tools menu can be shown with the options on it without clipping it should be appended and the tools menu horizontally extended(or wrap the tooltip).
I do not know too which extent the implementation in 2.x can imitate 1.x without being clunky, but it would be very welcome quality of life improvement especially for platforms with multiple choices that need to be reviewed in order for the code to work i.e. partition scheme.

There is most likely a duplicate of this when I tested it in beta but I cannot find it when I searched for issues.

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My request contains all necessary details

**Comment by per1234** [comment]
Hi @pwnept. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/343.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
