### ISSUE TITLE
OTA - on wrong password fails with error instead of prompting for password again

### ISSUE THREAD

**Issue by benapetr** [arduino/arduino-ide#1443]
### Describe the problem

In old IDE when OTA password was wrong IDE reported this and asked for password again. New IDE instead prints error code and stops the process. On next upload it again shows error code and stop. Restart of whole IDE is necessary to re-open the password prompt.

### To reproduce

Try OTA upload with wrong pasword

### Expected behavior

Prompt user for password instead of dropping into unrecoverable broken state

### Arduino IDE version

2.0.0

### Operating system

Windows

### Operating system version

Windows 10

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @benapetr . Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/1386.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

I'm happy to say that a fix for this is already in progress: https://github.com/arduino/arduino-ide/pull/1415

If you end up with additional information to share, feel free to comment in the other issue thread.
