### ISSUE TITLE
Progress status for Installing boards and libraries

### ISSUE THREAD

**Issue by shanmugam10** [arduino/arduino-ide#145]
Will be more viable if progress status  while installing additionals boards and libraries

**Comment by kittaakos** [comment]
Great idea. It's supported in 2.0.3 and was fixed via https://github.com/arduino/arduino-ide/commit/9aff90b0aff46503c6f87c133a0a9d1f4de5a895. Closing.


https://user-images.githubusercontent.com/1405703/210963163-80e019e1-4db8-4626-b03e-da3cd563da27.mp4
