### ISSUE TITLE
Lack of translation on the "Save" and "Save As..." options on português (Brasil)

### ISSUE THREAD

**Issue by Tuczz** [arduino/arduino-ide#1451]
### Describe the problem

The options "Save" and "Save As..." on the Files tab should be translated as "Salvar" and "Salvar Como" in the Portuguese pack.

![image](https://user-images.githubusercontent.com/83172596/190710132-d5e4f52f-38f2-4dd8-a1ca-2fef9f6b456d.png)

### To reproduce

Update the translation pack.

### Expected behavior

The options should appear as "Salvar" and "Salvar como"

![image](https://user-images.githubusercontent.com/83172596/190709917-91a6c13d-3d0b-435d-92f6-7236927ab2e5.png)

### Arduino IDE version

Versão: 2.0.0
Data: 2022-09-14T07:06:37.759Z
Versão do CLI : 0.27.1 [a900cfb2]

Copyright © 2022 Arduino SA

### Operating system

Windows

### Operating system version

Windows 11

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @Tuczz. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/pull/1449. (the Chinese language was used as an example, but the bug affects all languages equally)

I'm happy to tell you that a fix is already in progress: https://github.com/arduino/arduino-ide/issues/1431

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
