### ISSUE TITLE
Add support to global platform.txt as in Arduino IDE 1

### ISSUE THREAD

**Issue by fabianoriccardi** [arduino/arduino-ide#1452]
### Describe the request

Re-introduce the support to the global `platform.txt` file.

I have [read](https://arduino.github.io/arduino-cli/0.26/platform-specification/#global-platformtxt) that currently is not supported, but I had used it to run automatic script such as <https://github.com/fabianoriccardi/git-describe-arduino> which relies on it.

### Describe the current behavior

not supported

### Arduino IDE version

2.0.0

### Operating system

Windows

### Operating system version

10

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My request contains all necessary details

**Comment by per1234** [comment]
Hi @fabianoriccardi. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-cli/issues/999.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
