### ISSUE TITLE
some functions and constants doesn't colored like Arduino IDE 1.x

### ISSUE THREAD

**Issue by Nch-MOSFET** [arduino/arduino-ide#1485]
### Describe the problem

some functions and constants doesn't colored like Arduino IDE 1.x

![image](https://user-images.githubusercontent.com/91242561/191758274-248d9da1-c706-4f41-adbe-fd3cfd7847ac.png)

`sizeof` and `OUTPUT` must be coloed as light blue

the below image shows a same code in Arduino IDE 1.8.13

![image](https://user-images.githubusercontent.com/91242561/191765619-89df4c76-5bdc-48c8-bdbb-f6090f83e891.png)

### To reproduce

I used this code

```
uint8_t pins[] = {1, 2, 3, 4, 5};

void setup() {
  for(uint8_t i = 0; i < sizeof(pins); i++) {
    pinMode(pins[i], OUTPUT);
  }
}

void loop() {}
```

### Expected behavior

The display of functions and constants should be the same as in the previous IDE

### Arduino IDE version

2.0.0

### Operating system

Windows

### Operating system version

Windows 10 Pro 21H1

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @Nch-MOSFET . Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/380.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.

**Comment by Nch-MOSFET** [comment]
Sorry, I couldn't find it
