### ISSUE TITLE
Autoformat removes new-line before EOF

### ISSUE THREAD

**Issue by kaysievers** [arduino/arduino-ide#1487]
### Describe the problem

The autoformat feature removes the last line's new-line, disturbs all sorts of diff / git tools.

Quoting the C++ standard: ```A source file that is not empty and that does not end in a new-line character, or that ends in a splice, shall be processed as if an additional new-line character were appended to the file.```

Could this be changed to leave the new-line in place, or maybe even add one if it is missing?

Thanks!

Example:
<img width="375" alt="Screen Shot 2022-09-23 at 11 51 35" src="https://user-images.githubusercontent.com/1064936/191935801-4d33c423-42e0-4a5b-acf6-47278f99fa21.png">

### To reproduce

Press CMD-T and save. Look at the last character in the sketch file.

### Expected behavior

Leave the new-line before EOF in place.

### Arduino IDE version

2.0-nightly-202209

### Operating system

macOS

### Operating system version

12.6

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Thanks for reporting this @kaysievers. [The **ClangFormat** formatting tool](https://releases.llvm.org/14.0.0/tools/clang/docs/ClangFormat.html) used by Arduino IDE 2.x does not remove the newline, so it is a bug in the Arduino IDE code itself.

>maybe even add one if it is missing?

Surprisingly for such a [comprehensive](https://releases.llvm.org/14.0.0/tools/clang/docs/ClangFormatStyleOptions.html) tool, **ClangFormat** doesn't provide this capability:

https://github.com/llvm/llvm-project/issues/38042

Also surprising is that [the Eclipse Theia IDE framework](https://theia-ide.org/) Arduino IDE 2.x is built on doesn't provide an setting for this, as VS Code does with its `files.insertFinalNewline`.

---

I think there is a way for the user to set up Arduino IDE 2.x do this, which would even counteract the formatter's current removal of the newline. However, discussion of that is not really appropriate for the issue tracker. I'm certain that if you post over on the Arduino forum someone will provide you with instructions:

https://forum.arduino.cc/c/software/arduino-ide-2-0/93
