### ISSUE TITLE
Move settings access to File > Preferences

### ISSUE THREAD

**Issue by per1234** [arduino/arduino-ide#15]
**Is your feature request related to a problem? Please describe.**
A pretty gear icon is shown prominently in the side bar:
![Clipboard02](https://user-images.githubusercontent.com/8572152/109356811-17ee6a80-7836-11eb-8e58-579c665d286e.png)
When this is clicked, the very complex "Preferences" tab opens. This exposes options that will be of no use to the target user. The settings available via **File > Preferences** are the only thing the target user needs. It is good to give more advanced users access to advanced configuration options (as is done in the Java IDE's  **File > Preferences > More preferences can be edited directly in the file...** but the current UI funnels all users equally to those advanced preferences.

**Describe the solution you'd like**
Make the gear icon in the side bar open the **File > Preferences** dialog. Provide some form of access (even if it's only mentioning editing the settings.json file directly) to the advanced configuration from **File > Preferences**.

**Describe alternatives you've considered**
Remove the gear icon from the side bar. Preferences are accessed only via **File > Preferences**.

**Environment**

OS: Windows 10
Version: 2.0.0-beta.2-snapshot.298cc11
Date: 2021-02-15T14:16:52.603Z
CLI Version: 0.16.0 alpha [c977a238]

**Comment by ubidefeo** [comment]
@kittaakos can we move it to a button/link inside the compact preferences GUI?
For now I kinda like having some advanced/unsupported way of customising the IDE for that one user over 500 who wants to achieve that particular goal.

Also the "preferences" pop-over loses alignment with the gear icon when UI is zoomed.
Must be some local-to-global mapping gone awry :)

<img width="255" alt="Screenshot 2021-03-04 at 11 52 58" src="https://user-images.githubusercontent.com/1894487/109953970-0c40ef00-7ce1-11eb-8152-9ff35467a895.png">
<img width="270" alt="Screenshot 2021-03-04 at 11 53 04" src="https://user-images.githubusercontent.com/1894487/109954032-1cf16500-7ce1-11eb-87de-2daa59f169f3.png">
<img width="445" alt="Screenshot 2021-03-04 at 11 53 22" src="https://user-images.githubusercontent.com/1894487/109954099-2ed30800-7ce1-11eb-99e2-2046ba074086.png">

**Comment by kittaakos** [comment]
> can we move it to a button/link inside the compact preferences GUI?

Sure.

Or we can just remove it. I would expect, advanced users can use the _Command Palette_ and open it if you they want to.

![Screen Shot 2021-03-04 at 12 08 48](https://user-images.githubusercontent.com/1405703/109955148-75753200-7ce2-11eb-803d-40db465b59ef.jpg)

https://user-images.githubusercontent.com/1405703/109955461-cedd6100-7ce2-11eb-828f-53539a11a29e.mp4


> Also the "preferences" pop-over loses alignment with the gear icon when UI is zoomed.

It's a known issue and has been fixed upstream: https://github.com/eclipse-theia/theia/pull/9082
