### ISSUE TITLE
using a install.sh for installation

### ISSUE THREAD

**Issue by benlumia007** [arduino/arduino-ide#1505]
### Describe the request

As for IDE 1.8.9, it has a install.sh but 2.0 doesn't 

### Describe the current behavior

This is more of a question than an issue, but... is there a reason why for arduino-ide does not contain a install.sh file. The reason why i asked because when you download the zip file, you would need to open a terminal and run ./arduino-ide and the terminal needs to be open just to keep the IDE open.

### Arduino IDE version

2.0.0

### Operating system

Linux

### Operating system version

Ubuntu

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My request contains all necessary details

**Comment by per1234** [comment]
Hi @benlumia007. Thanks for taking the time to submit an issue.

>when you download the zip file, you would need to open a terminal and run ./arduino-ide and the terminal needs to be open just to keep the IDE open.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/690.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
