### ISSUE TITLE
Can't add additional board URL in settings

### ISSUE THREAD

**Issue by thewh1teagle** [arduino/arduino-ide#1511]
### Describe the problem

When using arduion IDE 2.0 on Windows, when trying to add additional board URL through the settings, I can't apply it with OK button, it says `Invalid sketchbook location: c:\Users\User\Documents\Arduino`.
It happened because the folder does not exists. If I create the folder it solves it, but the application itself should create the folder automatically in case it's not exists. 

It happens here: 
`arduino/arduino-ide/arduino-ide-extension/src/browser/dialogs/settings/settings.ts`
I would add additional check before of that: 
pseudo code:
```
IF {default sketch folder does not exists}
THEN create it
...
```

Let me know if it's something you would interested in I can make new PR.
 

### To reproduce

Delete `C:\Users\User\Documents\Arduino` folder, then try to add additional board URL in settings.

### Expected behavior

Add board URL without ERROR.

### Arduino IDE version

2.0.0

### Operating system

Windows

### Operating system version

11

### Additional context

.

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @thewh1teagle. This bug has already been fixed: https://github.com/arduino/arduino-ide/pull/1448

Please use the nightly build of the Arduino IDE. The download links are listed here:

https://github.com/arduino/arduino-ide#nightly-builds
