### ISSUE TITLE
Other tab in editor

### ISSUE THREAD

**Issue by KerteszDomokos** [arduino/arduino-ide#152]
**My request or idees is:**
If we open a file, not new window opening, but also just a new tab.
And in left can we open folders as in VS code.

And add close button to all tabs, and a + icon to new or openin right.

I hope they are useful idees.

My english isn't perfect, sorry

**Comment by szerwi** [comment]
It is possible to have file explorer and open files like .cpp or .h. Enabling file explorer is described in issue #150. Unfortunately, it is not possible to close tab with .ino file

**Comment by KerteszDomokos** [comment]
I understand. Thanks.
