### ISSUE TITLE
What happened to the "Open Recent" menu option

### ISSUE THREAD

**Issue by Gerriko** [arduino/arduino-ide#1539]
### Describe the request

I have grown very used to relying on the "Open Recent" menu option in Arduino 1.8.x over many years.
I searched preferences in case it was an option but I could not see any option there. 
Please can you add it to Arduino 2.x. It is sorely missed. 

### Describe the current behavior

There is only the "Open..." file menu option in Arduino 2.0. This does not provide you with a list of previous sketches opened.

### Arduino IDE version

Version 2.0.0

### Operating system

Linux

### Operating system version

20.04

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My request contains all necessary details

**Comment by per1234** [comment]
Hi @Gerriko. Arduino IDE 2.x does have a **File > Open Recent** menu:

![image](https://user-images.githubusercontent.com/8572152/194283616-fe2d37bd-0496-4912-a971-5ca39469c088.png)

The design of the Arduino IDE 2.x menus is a bit different than Arduino IDE 1.x in that submenu items are omitted if they are empty. So if you don't have any recent sketches, then it is expected that the menu item will be missing. But it is expected to be present and populated if you have opened a non-temporary sketch.

In regards to the "temporary sketch" caveat, you should be aware that, unlike Arduino IDE 1.x, Arduino IDE 2.x opens example sketches as temporary sketches, meaning that example sketches are not currently listed in the **Open Recent** menu. So if you have only opened examples and other temporary sketches, then it is expected that the menu item will not be present. There is work in progress now to change that for examples: https://github.com/arduino/arduino-ide/pull/1376

Please try this:

1. Select **File > New** from the Arduino IDE menus.
1. Select **File > Save As...** from the Arduino IDE menus.
1. Save the sketch to any convenient location.
1. Open the **File** menu.

Do you now see an **Open Recent** item in the menu?

**Comment by Gerriko** [comment]
Aha, ok. I see it now. Thanks for this. 
So there is still a subtle difference. 
With Arduino 1.8.x, it would also list Example files that had been previously opened even if not saved into a different folder. This I like to have too but maybe this is an option for a user to select under preferences.

**Comment by per1234** [comment]
You are welcome. Thanks for taking the time to share your findings.

>This I like to have too but maybe this is an option for a user to select under preferences.

There isn't one at the moment. I don't think there is any plan to control it via a preference. It will simply work the same as it does in Arduino IDE 1.x, where the examples are always added to the menu.

Since we were able to determine that the "Open Recent" menu is working for non-temporary sketches, and since we already have an issue tracking the need to also add example sketches to the menu (https://github.com/arduino/arduino-ide/issues/935), I will go ahead and close this.

Regards,
Per
