### ISSUE TITLE
Upload to fast for old Nano and clones (Old Bootloader)

### ISSUE THREAD

**Issue by toogooda** [arduino/arduino-ide#154]
**Describe the bug**
Old IDE allowed you to select ATMega328p (Old Bootloader) which slowed down the upload speed to 57600. No such option so half my boards cannot be programed new system tries 115200 and times out.

**To Reproduce**
1. Use old aduino or clone 
2. upload blink

**Expected behavior**
Have to Old Bootloader option in boards select or change upload speed.

**Screenshots**
Have screenshots but don't see an option to insert or upload them.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**
Used Aduino as ISP to burn bootloader using old IDE but it did not fix the issue

**Comment by ubidefeo** [comment]
@toogooda 

I have personally tested the slow clones and they work.
You will only have to select the **old bootloader** option from the **Tools >> Processor** sub-menu

<img width="479" alt="Screenshot 2021-03-02 at 08 24 47" src="https://user-images.githubusercontent.com/1894487/109612980-d2c98180-7b30-11eb-96a8-8fc51190cb9d.png">

**Comment by ubidefeo** [comment]
@toogooda  If that works for you, please close this issue 
thanks
u.

**Comment by toogooda** [comment]
Yes that works thanks I used the board and port screen as I thought it had replaced the other menus.  @ubidefeo Should processor also be on the board and port screen screen?

**Comment by ubidefeo** [comment]
@toogooda 
I was looking into that possibility, we have it on the Create Web Editor for targets with further options, but we haven't gotten to that level of granularity yet.
This version might require some workarounds at times, but we're confident we'll manage to fit more features and refine the ones it has over the next few months ✌🏼
