### ISSUE TITLE
Uploading to Pico fails, even with the board connected to PC

### ISSUE THREAD

**Issue by integrated-circuit** [arduino/arduino-ide#1557]
### Describe the problem

When i'm trying to flash the uf2 file to the pico, i get this error:
Le croquis utilise 89824 octets (4%) de l'espace de stockage de programmes. Le maximum est de 2097152 octets.
Les variables globales utilisent 42824 octets (15%) de mémoire dynamique, ce qui laisse 227512 octets pour les variables locales. Le maximum est de 270336 octets.
.....................
Failed uploading: uploading error: exit status 1.
and here is a screenshot of my screen:
![image](https://user-images.githubusercontent.com/68387582/195394946-f82cddf2-8448-4662-b2da-1420698d500d.png)

Im using the right board plugin for th pico as you can see:
![image](https://user-images.githubusercontent.com/68387582/195395257-9e23ba77-a68d-448a-b3dd-58843005fc60.png)

### To reproduce

1)Connect the pico to the PC
2) Open this example file:
[Blink.zip](https://github.com/arduino/arduino-ide/files/9766848/Blink.zip)
3)Verify the sketch
4)Upload the sketch to the pico

### Expected behavior

The pico LED should blink after upload

### Arduino IDE version

Version: 2.0.1-nightly-20221012Date: 2022-10-12T03:46:53.546Z Version CLI: git-snapshot [c8ff0425]Copyright © 2022 Arduino SA

### Operating system

Linux

### Operating system version

ubuntu 22.04

### Additional context

Exported UF2 Binaries from IDE 2.0 stable and nightly just work OOTB

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @integrated-circuit. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
