### ISSUE TITLE
Cannot use uint-declarations

### ISSUE THREAD

**Issue by vipoty** [arduino/arduino-ide#1567]
### Describe the problem

When I try to use the declarations like uint8_t, uint16_t and so on on the second and further files in a project I have the errors:
error: unknown type name 'uint8_t'
error: unknown type name 'uint16_t'

### To reproduce

Just add the second file to the project and write something like:
/* Can I use uint16_t and uint8_t here& */
uint16_t a_function(uint8_t a_variable) {
  return a_variable * 2;
}

![image](https://user-images.githubusercontent.com/116120880/196545663-29c6183f-6cd3-46f6-a1a9-44766459a4cf.png)
![image](https://user-images.githubusercontent.com/116120880/196545745-7cc5fb9e-c3b0-4daf-87f2-6256db9f847b.png)

### Expected behavior

uint16_t and uint8_t should be valid type declarations like in the first file in the project.

### Arduino IDE version

2.0.0

### Operating system

Windows

### Operating system version

10

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @vipoty. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
