### ISSUE TITLE
"Open Recent" menu missing after recent sketch is deleted

### ISSUE THREAD

**Issue by per1234** [arduino/arduino-ide#1596]
### Describe the problem

Arduino IDE has a **File > Open Recent** menu that lists the most recently opened sketches for quick access by the user.

🐛 If a recently opened sketch is deleted, **Open Recent** is no longer shown under the **File** menu.

### To reproduce

1. Select **File > Save As...** from the Arduino IDE menus.
1. Save the sketch with the name "FooSketch" to any convenient location.
1. Select **File > Open Recent** from the Arduino IDE menus.
   🙂 "FooSketch" and any other recently opened sketches are listed (unless you are already affected by the bug).
1. Select **File > Quit** from the Arduino IDE menus.
1. Delete the "FooSketch" sketch you created.
1. Start the Arduino IDE.
1. Select **File > Save As...** from the Arduino IDE menus.
1. Save the sketch with the name "BarSketch" to any convenient location.
1. Open the **File** menu. 

🐛 There is no **Open Recent** menu item. The only way to recover the IDE from this state is to manually delete or remove the deleted sketch entry from the `~/.arduinoIDE/recent-sketches.json` file.

### Expected behavior

**Open Recent** menu is still functional after deletion of recently opened sketch.

### Arduino IDE version

2.0.1

### Operating system

Windows

### Operating system version

10

### Additional context

I bisected the regression to 2b2463b / https://github.com/arduino/arduino-ide/pull/1563 (does not occur when using the tester build for the previous commit 0773c3915ccf8938259a6d82198aa14410c9cb38)
I see this in the logs on IDE startup:

```text
root ERROR Uncaught Exception:
root ERROR Error: ENOENT: no such file or directory, scandir 'c:\Users\per\Documents\Arduino\FooSketch'
```

---

Originally reported by @UKHeliBob at https://forum.arduino.cc/t/2-0-1-no-open-recent-menu-item/1046905

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

**Comment by nmzaheer** [comment]
I think the relevant code section which raises the error is at Line 196 wherein `lstat` function raises an error.https://github.com/arduino/arduino-ide/blob/0d0550974abd26adffd53a9d3036172705dd5177/arduino-ide-extension/src/node/sketches-service-impl.ts#L189-L198

The `loadSketch` function is called in a `try` block in the `recentlyOpenedSketches` function where the `catch` block is empty which doesn't seem right.
https://github.com/arduino/arduino-ide/blob/0d0550974abd26adffd53a9d3036172705dd5177/arduino-ide-extension/src/node/sketches-service-impl.ts#L392-L399

However, I am unable to understand the next code block which updates the list of recently opened sketches. If somebody can guide me, I would be able to help submit a PR.
