### ISSUE TITLE
Board Manager dont show Sketchbook Hardware

### ISSUE THREAD

**Issue by ericlangel** [arduino/arduino-ide#161]
**Describe the bug**
in Arduino 1.8.x i can select Boards stored in C:\Users\User\Documents\Arduino\hardware
this folder seems to be ignored by IDE 2.0

**Expected behavior**
Boards in C:\Users\User\Documents\Arduino\hardware should be shown in Boardmanager
and they should be marked with (in Sketchbook) like Arduino 1.8.13

**Screenshots**
![Arduino](https://user-images.githubusercontent.com/40859702/109793355-d33b4880-7c14-11eb-8745-f085bedff9a1.jpg)
![Arduino_IDE](https://user-images.githubusercontent.com/40859702/109793458-f665f800-7c14-11eb-9307-91801c4aee8f.jpg)

**Desktop (please complete the following information):**
 - OS: WIN 10
 - Version: 2.0.0-beta.3

**Comment by kittaakos** [comment]
Thank you for letting us know, @ericlangel. This is a known issue and tracked under https://github.com/arduino/arduino-ide/issues/126.

Closing as a duplicate.
