### ISSUE TITLE
Serial port in use message in 2.0.1 is uninformative

### ISSUE THREAD

**Issue by tigoe** [arduino/arduino-ide#1615]
### Describe the problem

When another program has control of a serial port and you try to upload, the IDE 2.0.1 reports  either "No device found on XXXX" or "Signal killed". This is unhelpful. 

### To reproduce

1. upload a serial sketch to an Arduino
2. Open the serial port in another application
3. Return to IDE, and try to upload a sketch

### Expected behavior

A better response would be "Arduino not responding on port XXX. Is the port in use by another application?" or 
perhaps a checklist:

* Is there an Arduino of the chosen model on port XXX?
* Is the port in use by another application?

Does port XXX still exist to the operating system? did the user "eliminate"  it by unplugging, or putting a USB-native board in reset? This is a common cause of the error for beginners in my experience. Harder to write an error message for, but perhaps an error with a link to a checklist of possible causes, 

### Arduino IDE version

2.0.1

### Operating system

macOS

### Operating system version

12.6

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Thanks for your suggestion @tigoe!

These messages are coming from the arbitrary 3rd party upload tools, not from Arduino IDE. For example, [the "No device found on \_\_\_" error comes from bossac](https://github.com/shumatech/BOSSA/blob/1.9.1/src/bossac.cpp#L385). So the request to rewrite the messages is out of scope for this repository, but you are welcome to suggest this in the relevant upload tool repositories.

>a checklist of possible causes,

This is something Arduino can definitely do. In fact, "No device found on \_\_\_" is already listed in this Arduino Help Center article:

https://support.arduino.cc/hc/en-us/articles/4403365313810-Errors-when-uploading-a-sketch#no-device-found-on-port

If you would like to request additional error messages be added to the Help Center articles, or any other enhancements, please submit those requests to the repository where the Arduino Help Center source content is hosted:

https://github.com/arduino/help-center-content
