### ISSUE TITLE
python in arduino ide

### ISSUE THREAD

**Issue by DaakyeHeneEmma** [arduino/arduino-ide#1619]
### Describe the request

I simply want to suggest if there could be support for python in the Arduino IDE since there are libraries for it like pyfirmata, this would help exclude the usage of other applications to run python for Arduino codes.

### Describe the current behavior

It has no support for it.

### Arduino IDE version

2.0

### Operating system

Windows, Linux

### Operating system version

Manjaro kde and window 11

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My request contains all necessary details

**Comment by per1234** [comment]
Hi @DaakyeHeneEmma. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/140.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
