### ISSUE TITLE
Beginner-unfriendly behavior of long int initialization

### ISSUE THREAD

**Issue by wagenadl** [arduino/arduino-ide#1629]
### Describe the request

Request: Implement IDE warnings for integer assignments that do not behave as a beginner would expect.

Rationale: Experienced C programmers will know that

`long int x = 100 * 1000;`

is a dangerous thing to write, because the two numbers will be interpreted as plain ints. As a consequence, when compiled on an Arduino Uno, the multiplication is interpreted as a 16-bit operation, and the end result will be x = 34,464. A beginner might reasonably expect that x = 100,000 at the end of this. While I fully realize that silent integer overflow is a problem with the C/C++ language rather than with the Arduino IDE per se, the fact is that may Arduino users may not be C/C++ experts. In fact, one of the key reasons that Arduino is so popular, is that for the most part you _don't_ have to be a C/C++ expert to use it.

Another great example is

`delay(66*1000)`

which most people would expect to result in a 66 second delay. In fact, 66*1000 overflows to 464, so the actual delay is less than half a second.

If it is not possible to make the compiler understand the obvious intention in these cases, it would be really helpful if the IDE could flag this sort of thing with a visible warning. 

### Describe the current behavior

The Arduino IDE does not notice calculations where C quirks result in different results than a casual user would expect. No compiler warnings are generated either.

### Arduino IDE version

2.0.1

### Operating system

Linux

### Operating system version

Ubuntu 22.04

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My request contains all necessary details

**Comment by per1234** [comment]
Hi @wagenadl. Thanks for your suggestion.

>No compiler warnings are generated either.

I'm happy to tell you that they are. You only need to enable warnings in your preferences and you'll get a nice warning like this:
```text
C:\Users\per\AppData\Local\Temp\.arduinoIDE-unsaved2022103-716-a7vrx4.zaink\sketch_nov3a\sketch_nov3a.ino: In function 'void setup()':
C:\Users\per\AppData\Local\Temp\.arduinoIDE-unsaved2022103-716-a7vrx4.zaink\sketch_nov3a\sketch_nov3a.ino:3:18: warning: integer overflow in expression [-Woverflow]
 long int x = 100 * 1000;
              ~~~~^~~~~~
```

I'll provide instructions:

1. Select **File > Preferences...** from the Arduino IDE menus.
1. Select any value "**Default**" or higher from the "**Compiler warnings**" menu.
1. Click the <kbd>**OK**</kbd> button.

As for the idea of enabling compiler warnings by default in the IDE preferences, that is tracked here: https://github.com/arduino/arduino-ide/issues/1630
