### ISSUE TITLE
Feature request: Hability to set custom baudrates manually for monitor

### ISSUE THREAD

**Issue by Anyeos** [arduino/arduino-ide#1639]
### Describe the request

There are some uncommon situations where you will need a non listed baudrate (ie. 28800).

And for example the cp2102 supports 250000 and there are other chips lying around that supports uncommon/weird baudrates that can be used because the error rate is low for that particular chip in that particular baudrate. Or simply because we can test the behaviour on different manually tweaked baudrates.

Either way, it is always handy to have the option to edit manually a value on an editor or software utility (for example on CuteCom it can be done).

### Describe the current behavior

Actually there are only a listbox to choose the baudrates.

### Arduino IDE version

Version: 2.0.2 Date: dev build CLI Version: 0.28.0 [06fb1909]  Copyright © 2022 Arduino SA

### Operating system

Linux

### Operating system version

Ubuntu 20.04.5

### Additional context

The cp2103 for example supports all this:
`300, 600, 1200, 1800, 2400, 4000, 4800, 7200, 9600, 14400, 16000, 19200, 28800, 38400, 51200, 56000, 57600, 64000, 76800, 115200, 128000, 153600, 230400, 250000, 256000, 460800, 500000, 576000, 921600`
As you can see on the PDF here: [https://www.silabs.com/documents/public/data-sheets/CP2103.pdf](https://www.silabs.com/documents/public/data-sheets/CP2103.pdf)

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My request contains all necessary details

**Comment by per1234** [comment]
Hi @Anyeos. Thanks for taking the time to submit an issue.

I see this was proposed previously at https://github.com/arduino/serial-monitor/issues/20#issuecomment-1162900747

My understanding is that this is not really about the desire to set strange arbitrary baud rates, but only that it be possible to set Serial Monitor to any of the full set of standardized baud rates, which is already tracked at https://github.com/arduino/serial-monitor/issues/20

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
