### ISSUE TITLE
OTA upload freezes

### ISSUE THREAD

**Issue by wavoigt** [arduino/arduino-ide#1641]
### Describe the problem

The Output view freezes at "Uploading........................" and the status window shows "uploading" forever.
The "Upload" button remains lightblue.
"ESC" only closes the Status window.
I have to restart IDE to reset the state.
All works fine with Arduino 1.8

### To reproduce

Arduino IDE 2.01, latest Version
Windows 10
ESP8266 Adafruit Huzzah Breakout
#include <ArduinoOTA.h>

### Expected behavior

Output Message "Sketch uploaded successfully"
Close the upload status window
Reset the "Upload" button

### Arduino IDE version

2.01

### Operating system

Windows

### Operating system version

10 22H2

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @wavoigt . Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/1356.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
