### ISSUE TITLE
Other remote sketch files not pulled from the Arduino Cloud

### ISSUE THREAD

**Issue by kittaakos** [arduino/arduino-ide#1645]
### Describe the problem

When I manually sync and pull a remote sketch, other files (such as `.h`, `.cpp`, or `.ono`) are not pulled.

### To reproduce

 - Open IDE2,
 - Activate the remote sketchbook and log in,
 - Create a sketch online: https://create.arduino.cc/editor,
 - Sync the sketch in IDE2 (the new remote sketch is visible, it's not pulled yet),
 - Pull the remote sketch (it creates the cached sketch locally under `directories/data/RemoteSketchbook/ArduinoCloud/$USER_UUID`),
 - Add a new tab online, for example `foo.ino`,
 - Pull the sketch in IDE2. The new `foo.ino` file is not copied to the cache folder

### Expected behavior

After pulling the remote sketch, all sketch files are pulled.

### Arduino IDE version

2.0.1

### Operating system

macOS

### Operating system version

12.5.1

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @kittaakos . Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/444.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
