### ISSUE TITLE
Export to File/Select All function for Serial Monitor

### ISSUE THREAD

**Issue by Lorandil** [arduino/arduino-ide#1654]
### Describe the request

Sometimes I require the full output of the Serial Monitor window.
It would be a great feature to select the complete content of the window by a shortcut (CTRL-A) or by a context menu which could also offer to export the content to a file.

### Describe the current behavior

Because it is not possible to select the full window content with CTRL-A (on Windows) I'm forced to scroll the whole way down while pressing the left button. 

### Arduino IDE version

2.0.1

### Operating system

Windows

### Operating system version

10 21H2

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My request contains all necessary details

**Comment by per1234** [comment]
Hi @Lorandil . Thanks for taking the time to submit an issue.

I see we have other reports about this at:

- https://github.com/arduino/arduino-ide/issues/812
- https://github.com/arduino/arduino-ide/issues/549

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
