### ISSUE TITLE
Investigate bumping Theia dependency to 1.30.x

### ISSUE THREAD

**Issue by per1234** [arduino/arduino-ide#1655]
### Describe the request

Investigate the updating the version of the [`@theia` package](https://github.com/eclipse-theia/theia) dependencies used by Arduino IDE to 1.30.x

Bumping the Theia version is likely to cause regressions, subsequent code changes may be required. Therefore this initial investigation task is needed as the first "phase" of the work to actually update the dependency.

#### Expected outcome

A clear breakdown of the major regressions when bumping the Theia version in IDE 2.x to 1.30.x, and a general estimate of overhead to resolve them.

🙂 It will be more clear how much work will be required to accomplish the dependency update and what previously unrecognized complications might be encountered.

### Describe the current behavior

Arduino IDE 2.x is built on the [**Eclipse Theia** IDE framework](https://theia-ide.org/).

The Theia version currently in use in the Arduino IDE project is [1.25.0](https://github.com/eclipse-theia/theia/releases/tag/v1.25.0). Eight releases of Theia have been made since that time, which include significant advancements and relevant bug fixes.

🙁 At present we have outstanding issues that don't make sense to investigate until we've updated Theia as related behavior may differ between versions.

### Arduino IDE version

3a7054777089243174cf3cf8df89716e15e14de1

### Operating system

All

### Operating system version

Any

### Additional context

Issues that may be resolved by a 1.30.x bump:

- https://github.com/arduino/arduino-ide/issues/1498
- https://github.com/arduino/arduino-ide/issues/999

Issues that will only be resolved by a bump to >=1.31.0

- https://github.com/arduino/arduino-ide/issues/571
- https://github.com/arduino/arduino-ide/issues/1077 (partially resolved)
- https://github.com/arduino/arduino-ide/issues/1613

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My request contains all necessary details

**Comment by kittaakos** [comment]
@91volt, Theia `1.31.0` comes with changes to have better accessibility support. Here and there the Theia styles contradict IDE2 styles. In this comment, I will attach screenshots depicting which UI parts are affected. (I will periodically update the comment with new findings if any.)

<img width="347" alt="Screen Shot 2022-11-09 at 10 43 59" src="https://user-images.githubusercontent.com/1405703/200802401-17dcaa42-4270-41e1-a5b3-64c9f39b6e25.png">
<img width="252" alt="Screen Shot 2022-11-09 at 10 44 34" src="https://user-images.githubusercontent.com/1405703/200802529-413d1233-1194-4c13-9d5d-4e15254ca2f8.png">
