### ISSUE TITLE
Arduino IDE 2.0.1 is making me crazy!

### ISSUE THREAD

**Issue by DellroyGM** [arduino/arduino-ide#1669]
I don't mind the automatic completion, E.G., always adding closing parenthesis or closing braces, but often, after I enter a line of code, and press Enter, my typing begins with the same indentation as the previous line (which is good), but while I am typing on that line, it sometimes moves left, like a tab got erased.  Sometimes, the next line gets joined to the current line, as if I hit delete at the start of the next line (which I did not).
Please, can we have these features switchable, so if one does not like them, he/she can turn them off?  Thanks!

**Comment by per1234** [comment]
Hi @DellroyGM. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/437.

---

I'll provide instructions for the simple workaround that was discovered by a community member:

1. Open the "**Command Palette**" via the <kbd>**Ctrl**</kbd>+<kbd>**Shift**</kbd>+<kbd>**P**</kbd> (<kbd>**Command**</kbd>+<kbd>**Shift**</kbd>+<kbd>**P**</kbd> for macOS users) keyboard shortcut.
1. Select the "**Preferences: Open Settings (UI)**" command.
1. In the "**Search Settings**" field, type `files.trimAutoWhitespace`
1. Uncheck the checkbox next to "**`☑` Remove trailing auto inserted whitespace.**"

---

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.

**Comment by DellroyGM** [comment]
Thanks!
