### ISSUE TITLE
Unable to select content from serial monitor

### ISSUE THREAD

**Issue by eclipse1985** [arduino/arduino-ide#167]
**Describe the bug**
I want to perform a copy/paste operation from serial monitor output, but the selection disappear on the mouse up

**To Reproduce**
1. Print something on the serial monitor
2. Try to select some text

**Expected behavior**
Selection does not disappear

**Screenshots**
https://user-images.githubusercontent.com/6736700/109802275-e1db2d00-7c1f-11eb-8e38-022a2275b8ed.mov

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: Mojave 10.14.6 (18G8012)

**Additional context**
Even with auto-scroll on and off

**Comment by kittaakos** [comment]
Thank you for reporting it, @eclipse1985. The copy/paste is tracked [here](https://github.com/arduino/arduino-ide/issues/105#issue-818838115):

> * We get copy/paste/find/select-all for the _Serial Monitor_ for free.

I am closing your issue as a duplicate.

**Comment by per1234** [comment]
This bug is now being tracked at https://github.com/arduino/arduino-ide/issues/247
