### ISSUE TITLE
Open fileing file fails if IDE is already open

### ISSUE THREAD

**Issue by Chose99** [arduino/arduino-ide#1681]
### Describe the problem

If i have the IDE open and want to open a other file ( aka double cklick it) the file doen't open. If i use the open from the menu it works fine.

### To reproduce

```text
Foo1/
└── Foo1.ino

Foo2/
└── Foo2.ino
```

open `Foo1.ino` by doubble clicking it.
try to open `Foo2.ino` by doubble clicking it.
my corser get the spinning blue wheel thing but nothing happens.

### Expected behavior

The `Foo2.ino` opens normaly in a seperat IDE window.

### Arduino IDE version

2.0.1

### Operating system

Windows 10

### Operating system version

Version	10.0.19045 Build 19045

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @Chose99. Thanks for your report. This bug has already been fixed: https://github.com/arduino/arduino-ide/issues/1590

The fix is available in the nightly build of Arduino IDE. The download links for the nightly build are listed here:

https://www.arduino.cc/en/software#nightly-builds

**Comment by Chose99** [comment]
I thaught i tested if the nightly build woud fix, but i think i had a mix up with the normal and nightly exe sorry for that.

**Comment by Chose99** [comment]
I thaught i tested if the nightly build woud fix, but i think i had a mix up with the normal and nightly exe sorry for that.

Thanks and keep up the grate work :)
