### ISSUE TITLE
stm32 with arduino

### ISSUE THREAD

**Issue by robot78p** [arduino/arduino-ide#1682]
### Describe the request

i cannot compile stm32F4 board compiling error

### Describe the current behavior

i cannot compile stm32F4 board compiling error

### Arduino IDE version

2.0.1

### Operating system

Windows

### Operating system version

10

### Additional context

many solution i found but for my arduino none of them working help

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My request contains all necessary details

**Comment by per1234** [comment]
Hi @robot78p. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
