### ISSUE TITLE
Offer save option in unsaved file dialogue on exit from IDE

### ISSUE THREAD

**Issue by UKHeliBob** [arduino/arduino-ide#170]
When closing the IDE with an unsaved file open the dialogue only offers Yes and No options to the "Are you sure that you want to close the sketch" question.  There is no option to save the sketch at that point.. To do so requires answering No to close the dialogue, saving the sketch from the IDE and closing it again.

**Comment by per1234** [comment]
This was resolved some time ago by https://github.com/arduino/arduino-ide/pull/1351 but we didn't close the issue at the time that was merged.

The dialog on exit with unsaved sketch changes now looks like this:

![image](https://user-images.githubusercontent.com/8572152/207850045-fb344314-409c-4ffe-af0d-626aeeeeef53.png)
