### ISSUE TITLE
Where can I keywords, and automatic addition commit in github, or in local files?

### ISSUE THREAD

**Issue by KerteszDomokos** [arduino/arduino-ide#171]
Hi,

I think so the autocomplate, and keyword coloring is priority feature, so I want to help this feature. I'm beginner in Java, but well in arduino, and C++.
Can I help this for you?  
Thanks!
<br>  

*My English isn't perfect, sorry.*

**Comment by ubidefeo** [comment]
@KerteszDomokos 
Syntax highlighting and code intelligence is now handled through a Language Server and ClangD.
The legacy Arduino `keyword.txt` path is not currently needed/supported
