### ISSUE TITLE
Copy-pasting from the serial monitor only copies what's on the screen.

### ISSUE THREAD

**Issue by justinmcgrath** [arduino/arduino-ide#1710]
### Describe the problem

When selecting more data than fits in the serial monitor, and using Ctrl+C to copy, only what is visible in the area is copied.

### To reproduce

Select more text than shows on the screen and press Ctrl+C. Paste elsewhere.

### Expected behavior

The text that was selected should be copied.

### Arduino IDE version

Version: 2.0.2 Date: 2022-11-17T11:54:56.612Z CLI Version: 0.29.0 [76251df9]  Copyright © 2022 Arduino SA

### Operating system

Windows

### Operating system version

Windows 7. 6.1.6701 Service pack 1 build 7601

### Additional context

Using Ctrl+A to select the text in the serial monitor area instead selects the text in the code area.

The serial monitor no longer its own window and there does not appear to be a way to separate it from the code window.

The biggest issue with the version 1 was that it was slow. Version 2 does not appear to address this.

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @justinmcgrath . Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/1081.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.

---

>Using Ctrl+A to select the text in the serial monitor area instead selects the text in the code area.

Tracked at https://github.com/arduino/arduino-ide/issues/812

>The serial monitor no longer its own window and there does not appear to be a way to separate it from the code window.

Tracked at https://github.com/arduino/arduino-ide/issues/289

>The biggest issue with the version 1 was that it was slow. Version 2 does not appear to address this.

It is not clear to me what this means. Please create a separate issue for each distinct defect or feature request you wish to report. If you do a search through the issues and find this one has not yet been reported, then you are welcome to submit a dedicated detailed issue report for it.
