### ISSUE TITLE
Boards Manager Column: Can not reach 'Install' button due wrong sized item with filter active.

### ISSUE THREAD

**Issue by adrianhoehne** [arduino/arduino-ide#1713]
### Describe the problem

I am switching regulary my work place, therefore I work on different environments, one of them is a 13 inch laptop with a resolution of 1280x800 px on Windows 10 and 100% scaling.
I wanted to install a customized board over boardsmanager. So, I inserted the url in preferences and tried to install it. I used the filter with the word 'pico' and it was visible in the column but not correctly sized. Even not as only match.

If filter is not used, the alignment works. 

![bottomOfItem](https://user-images.githubusercontent.com/19731088/204138570-d393354c-a077-41b3-bf1e-b7dc1834f5ad.PNG)
![topOfItem](https://user-images.githubusercontent.com/19731088/204138571-ee3899fa-68fd-41ff-915d-0d8ab87378fb.PNG)

### To reproduce

1. set Monitor resolution to 1280x800 at 100 % scaling
2. search for a board with a long description. (earlephilhower/arduino-pico is the one I tried)
3. Try to find the install button. 

### Expected behavior

Items in the boards manager column should be sized so that they are fully accessible and not overlap any other items.

### Arduino IDE version

2.0.2

### Operating system

Windows

### Operating system version

21H2 Pro

### Additional context

with click on tab you can navigate but will not solve the issue

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @adrianhoehne. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/1591.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
