### ISSUE TITLE
Verify and Upload buttons do not change colour when activated.

### ISSUE THREAD

**Issue by ghost** [arduino/arduino-ide#173]
Verify Button does not change colour when activated, yet.

**Comment by ubidefeo** [comment]
@BCGuy none of the buttons have rollover or press yet.
Thank you for the suggestion

**Comment by ubidefeo** [comment]
Closed by #190 
@BCGuy , please check the behaviour in Beta 4 and close if solved

**Comment by BCGuy** [comment]
sorry i am so new to this, i did not know i was responsible to close it

great stuff you guys do!

**Comment by ubidefeo** [comment]
no worries
just confirm it works :)

**Comment by BCGuy** [comment]
When I install the beta 4 version onto my windows machine, after it opens
it also presents the message "an unexpected error occurred when locating
the Git executable and it will not compile and gives the compile window
message "Compilation error: Error: 2 UNKNOWN: no FQBN provided"

but the colour changes on the verify button

**Comment by BCGuy** [comment]
And I learned what I say in emails appears here.  Cheers.

**Comment by ubidefeo** [comment]
Thanks @BCGuy 
The `git` error you reported is already being tracked by us in #163 
We're trying to figure out why it only happens to some users.
Would you be so kind to comment on #163 and add your Windows version for reference?

Thanks
u

**Comment by kittaakos** [comment]
It still does not work for me. I can see the yellow background for verifying, but not for uploading.
![screencast 2021-04-01 09-03-39](https://user-images.githubusercontent.com/1405703/113256455-7db49300-92c9-11eb-9d6f-735e5e76b389.gif)

I am using
```
Version: 2.0.0-beta.4-nightly.20210401
Date: 2021-04-01T03:09:59.931Z
CLI Version: nightly-20210329 alpha [ac39429e]
```

CC: @fstasi

**Comment by ubidefeo** [comment]
same here, @kittaakos

**Comment by per1234** [comment]
Related: https://github.com/arduino/arduino-ide/issues/279

**Comment by per1234** [comment]
Closing as fixed by https://github.com/arduino/arduino-ide/commit/5ff9ce0028726a01d07511897150d07541a7b476 / https://github.com/arduino/arduino-ide/pull/1194
