### ISSUE TITLE
"File > Preferences" disabled if dialog used soon after IDE startup

### ISSUE THREAD

**Issue by per1234** [arduino/arduino-ide#1735]
### Describe the problem

If the "**Preferences**" dialog is opened soon after Arduino IDE is started, after closing the menu the **File > Preferences** menu item is disabled.

### To reproduce

1. Start Arduino IDE.
1. Watch the Arduino IDE window. As soon as the menu bar appears, select **File > Preferences**.
1. The "**Preferences**" dialog may be empty. Wait for it to populate.
1. Click the "**CANCEL**" button.
1. Open the **File** menu.

🐛 The **File > Preferences** menu item is disabled:

![image](https://user-images.githubusercontent.com/8572152/205478941-57a5a93b-8173-4b02-a805-4e4b567862ac.png)

### Expected behavior

**File > Preferences** menu item is only disabled if there is a specific reason the preferences dialog should not be accessible to the user (The only reason I can think of is if the dialog is already open, but that should be handled by making the dialog modal).

### Arduino IDE version

5695fd8

### Operating system

Windows

### Operating system version

10

### Additional context

I bisected the introduction of the bug to https://github.com/arduino/arduino-ide/commit/7d6a2d5e3340aabc1e635d508509dc92a4000fdc / https://github.com/arduino/arduino-ide/pull/1581 (does not occur when using the build for https://github.com/arduino/arduino-ide/commit/6984c52b927260e13e23ae6eeb6f0b7488f7e12d).

---

Similar to https://github.com/arduino/arduino-ide/issues/1722 (note they were bisected to the same commit).

---

The fault does not occur if the IDE startup process is allowed to finish completely (as indicated by the disappearance of the busy spinner next to the mouse pointer).

---

The menu item is enabled in new Arduino IDE windows that are opened when the menu item is in the disabled state in the parent window.

---

Even when the menu item is in the disabled state, I can still open the "**Preferences**" dialog using the keyboard shortcut (<kbd>**Ctrl**</kbd>+<kbd>**,**</kbd>), or "**Arduino: Open Preferences**" command palette command.

---

I have experienced a similar fault with **Tools > WiFi101 / WiFiNINA Firmware Updater**, but have not found a way to reproduce it.

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by sunzhongmeng** [comment]
I have the same problem.there is nothing in the Preferences dialog.
the OS is windows 10 Home (21H2)
![image](https://user-images.githubusercontent.com/4470014/209589023-88c67ef1-58df-4fb4-882b-71c6ddaa4bb7.png)

**Comment by per1234** [comment]
Hi @sunzhongmeng. That is a completely different fault. This issue is about the **File > Preferences** menu item being disabled. Your problem is the "**Preferences**" dialog being empty.

I saw your report about this on the Arduino Forum and am intending to investigate it:

https://forum.arduino.cc/t/arduino-ide-2-0-3-is-now-available/1061763/12

We can start over there and then create a dedicated bug report here if appropriate once we know more.
