### ISSUE TITLE
Allow for canceling verify or upload

### ISSUE THREAD

**Issue by EliasA97** [arduino/arduino-ide#1749]
### Describe the request

When we have a huge sketch, it takes some time to compile and upload. I think a "cancel verify/cancel upload" option would be a good time and flash saver. It can be as simple as clicking again the same verify or upload buttons.

### Describe the current behavior

Imagine you just have pressed the upload button and then you remembered that something needs to change on your code. At this moment the only thing I know, is you wait for the compilation to complete, then unplug arduino in order not to upload the code and then start again. I think an arduino has something like 10K times limit for uploading because flash memory degrades over time. 

### Arduino IDE version

2.0.3

### Operating system

Windows

### Operating system version

11

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My request contains all necessary details

**Comment by kittaakos** [comment]
Thanks for reporting it, @EliasA97. This is a great idea. However, it's already tracked under https://github.com/arduino/arduino-ide/issues/1199. We prefer tracking one issue, so I am closing this as a duplicate.
