### ISSUE TITLE
Right click context menu missing items found in IDE 1.x

### ISSUE THREAD

**Issue by illigtr** [arduino/arduino-ide#1752]
### Describe the request

The right click context menu in the IDE editor is missing items found originally in IDE 1.x. Can we have these back? They are faster to use than selecting the corresponding items from the File menu.

### Describe the current behavior

One cannot simply comment/uncomment a block with context menu. One is forced to use a keyboard shortcut or File/Edit/Comment

### Arduino IDE version

2.0.4-nightly-20221208

### Operating system

Windows

### Operating system version

11

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My request contains all necessary details

**Comment by per1234** [comment]
Hi @illigtr . Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/223.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
