### ISSUE TITLE
Error in Translation to Portuguese -Brazil (Português - Brasil)

### ISSUE THREAD

**Issue by MicSG-dev** [arduino/arduino-ide#1753]
### Describe the problem

When selecting the arduino 2.0 IDE language for Português (Brasil), the options Upload (Ctrl+ U) and Upload Using Programmer (Ctrl+ Shift + U) have the same translation: Enviar usando Programador.

### To reproduce

1. Navigate to File > Preferences...
2. Select Language português (Brasil)
3. Confirm the change by clicking OK

### Expected behavior

The Upload (Ctrl+ U) and Upload Using Programmer (Ctrl+ Shift + U) options have the correct translations:

- Upload (Ctrl+U) -> Carregar (Ctrl+U)
- Upload Using Programmer (Ctrl+ Shift + U) -> Carregar usando programador (Ctrl+ Shift + U)

### Arduino IDE version

2.0.3

### Operating system

Windows

### Operating system version

Windows 11 Home

### Additional context

Arduino IDE Additional Data:
Date: 2022-12-05T09:30:25.331Z
CLI Version: 0.29.0 [76251df9]

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @MicSG-dev. Thanks so much for your report. The translations are maintained by the Arduino community on Transifex. Please submit the fix over there:

https://explore.transifex.com/arduino-1/ide2/
