### ISSUE TITLE
Print code option no longer in version2.0

### ISSUE THREAD

**Issue by KJohanson62** [arduino/arduino-ide#1759]
### Describe the problem

The print code option does not exist in version 2.0.  

### To reproduce

go to file 
there is no print option

### Expected behavior

when you go to file there should be a print option

### Arduino IDE version

2.0.0

### Operating system

Windows

### Operating system version

10

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @KJohanson62. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/214.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
