### ISSUE TITLE
Debugging is not supported by "Nucleo-64' while selected Nucleo F446RE

### ISSUE THREAD

**Issue by N0rbert** [arduino/arduino-ide#1760]
### Describe the problem

Unable to debug simple *Blink.ino* program on Nucleo F446RE board.

![blink-debug](https://user-images.githubusercontent.com/309456/206846156-61c76de6-1d03-496e-ae6c-dfff4319319e.png)

Pressing *Debug → Start Debugging* open empty template for *launch.json* instead of normally preconfigured and reproducible file.

![debug-start_debugging](https://user-images.githubusercontent.com/309456/206849566-0f349a7a-e2e4-4b3b-97d1-12dbcc0bd528.png)

It is unclear what user should write in the fields on *launch.json* file 

```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  "version": "0.2.0",
  "configurations": [
  {
    "cwd": "${workspaceRoot}",
    "executable": "./bin/executable.elf",
    "name": "Debug with OpenOCD",
    "request": "launch",
    "type": "cortex-debug",
    "servertype": "openocd",
    "configFiles": [],
    "searchDir": [],
    "runToEntryPoint": "main",
    "showDevDebugOutput": "none"
  }
  ]
}
```

to get OpenOCD working with STM32.

### To reproduce

1. Download latest Arduino IDE 2.0.3, extract and launch it.
2. In Arduino IDE go to *File* → *Preferences* and set `https://github.com/stm32duino/BoardManagerFiles/raw/main/package_stmicroelectronics_index.json` as additional board URL for stm32duino.
1. In *Boards Manager* add *STM32 MCU based boards by STMicroelectronics*.
1. Select *Nucleo-64* board and set *Tools* → *Board part number* to *Nucleo F446RE*.
1. Set *Tools* → *Debug symbols and core logs* to *Symbols Enabled (-g)*.
1. Set *Tools* → *Optimize* to *Debug (-Og)*.
1. Try to debug the program.

### Expected behavior

Arduino IDE has preconfigured *launch.json*  for well known and mature stm32duino framework. 
Debugging is possible using OpenOCD software and embedded ST-Link hardware.

### Arduino IDE version

Version: 2.0.3 
Date: 2022-12-05T09:27:52.215Z 
CLI Version: 0.29.0 [76251df9] 

### Operating system

Linux

### Operating system version

Debian 11 bullseye (stable)

### Additional context

The debugging of STM32F446RE on Nucleo-64 F446RE is actually possible using VSCode with [*vscode-arduino*](https://marketplace.visualstudio.com/items?itemName=vsciot-vscode.vscode-arduino), [*cortex-debug*](https://marketplace.visualstudio.com/items?itemName=marus25.cortex-debug) and [*marus25.cortex-debug-dp-stm32f4*](https://marketplace.visualstudio.com/items?itemName=marus25.cortex-debug-dp-stm32f4) extensions by `openocd`  from Debian repository and `STM32F446x.svd` file from *marus25.cortex-debug-dp-stm32f4* extension.

I hope someone will post fully-reproducible instruction to setup Arduino IDE 2.x for STM32 debugging.

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @N0rbert. The reason debugging is not supported is because the STM32duino boards platform is not configured for debugging support. If the necessary configuration is done in the boards platform, then you will see that Arduino IDE allows you to debug.

>It is unclear what user should write in the fields on launch.json file

Nothing. Arduino IDE automatically generates a `launch.json` file based on the configuration from the boards platform if the platform contains such a configuration.

Since your report is actually about the STM32duino boards platform codebase and nothing can be done here in the Arduino IDE 2.x codebase repository, I'll close this as off topic.
