### ISSUE TITLE
Saving sketches in a read-only filesystem.

### ISSUE THREAD

**Issue by tistructor** [arduino/arduino-ide#1768]
### Describe the problem

If you save a sketch in a read-only filesystem you get no error message.
This way you think you have saved the project but at the restart the saved sketch opens before the file system was read-only.
As a result, losing subsequent changes.

### To reproduce

Try saving a sketch in a read-only filesystem.

### Expected behavior

A dialog box should be shown stating that the operation cannot be performed.

### Arduino IDE version

2.0.3

### Operating system

Linux

### Operating system version

Linux Mint 21

### Additional context

This particular problem happens because using linux and then moving to windows and then again to linux sometimes the disk where I save the projects, formatted NTFS is mounted by linux in read only.

The project is not located in the sketchbook folder but in my personal folder.
I don't know if this changes things, I haven't run tests on this.

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @tistructor >. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/1501.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
