### ISSUE TITLE
The key number one don't work. Portuguese Keyboard

### ISSUE THREAD

**Issue by kittaakos** [arduino/arduino-ide#1772]
### Describe the problem

Originally reported by @samtd [here](https://github.com/arduino/arduino-ide/issues/989#issuecomment-1327904430):

> I check with version 2.0.2 and the problem persist. The key number one don't work.
> Portuguese Keyboard

> I'm using Portuguese pt pc keyboard.
> 
> Also i already test on version v2.0.3 and the problem maintains. With Arduino 1x i don't have any problem.

> i tested with Theia IDE and works. Theiablueprint cloud: Work Theiablueprint installed v1.32.0: Work arduino-ide_2.0.3_Windows_64bit.zip : Dont Work arduino-ide_2.0.3_Windows_64bit.exe : Dont Work Arduino Web App Version - 6.4.6: Work
> 
> Edição Windows 11 Pro Versão 22H2 Instalado em ‎08/‎10/‎2022 Compilação do SO 22621.900
> 
> If i use key number 1 with shift it works the correct character "!", but number 1 i can't have all other keys also works

### To reproduce

See description

### Expected behavior

<kbd>1</kbd> works.

### Arduino IDE version

2.0.2

### Operating system

Windows

### Operating system version

Edição Windows 11 Pro Versão 22H2 Instalado em ‎08/‎10/‎2022 Compilação do SO 22621.900

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
I see we have another report about this at https://github.com/arduino/arduino-ide/issues/1047.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If anyone has additional information to share about this subject, feel free to comment in the other thread.
