### ISSUE TITLE
[Feature Request] Request the ArduinoIDE2  can show LITERAL1  keyword's color.

### ISSUE THREAD

**Issue by BlynkGO** [arduino/arduino-ide#1785]
### Describe the request

In a library, can define  any keyword as "LITERAL1" keyword.

Arduino IDE1.8.x  can change "LITERAL1" keyword's color as the following.

![image](https://user-images.githubusercontent.com/65327357/209475514-02ba7dee-bf2a-4e7b-b694-f24e2eed5673.png)

However, Arduino IDE2.0.x  can't display  "LITERAL1" keyword's color.

![image](https://user-images.githubusercontent.com/65327357/209475565-40688c79-6acb-4e82-b6ee-02062230dcb0.png)

Request,  the ArduinoIDE2  can show LITERAL1  keyword's color too.

Thank you.

### Describe the current behavior

 the ArduinoIDE2  , the current behavior can't  show LITERAL1  keyword's color.
 
 
![image](https://user-images.githubusercontent.com/65327357/209475604-66edf677-a3b7-4709-8f54-43b165f6203f.png)

### Arduino IDE version

2.0.3

### Operating system

Windows, Linux, macOS

### Operating system version

Windows10

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My request contains all necessary details

**Comment by per1234** [comment]
Hi @BlynkGO. Thanks for taking the time to submit an issue.

I see we have another report that covers the same subject at https://github.com/arduino/arduino-ide/issues/380.

You should note that [the crude system of library maintainers manually definining keywords](https://arduino.github.io/arduino-cli/latest/library-specification/#keywords) from Arduino IDE 1.x will not be implemented in Arduino IDE 2.x, so there will never be support for `LITERAL1` specifically. But perhaps the intelligent automatic syntax highlighting system used by Arduino IDE 2.x can be refined to better handle these objects.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
