### ISSUE TITLE
Make CTRL-SHIFT-TAB shortcut able to switch from the first tab to the last one

### ISSUE THREAD

**Issue by muchachagrande** [arduino/arduino-ide#1786]
### Describe the request

I'd like to be able to use the CTRL-SHIFT-TAB shortcut to switch from the first tab to the last one.
In 1.x series when you are editing a multi-file project with many opened tabs, you could press the CTRL-SHIFT-TAB key combination and switch from the actual tab to the previous one (the first to the left) and when you are standing at the first tab (the leftmost one) you could jump straight to the last one (the rightmost tab).

### Describe the current behavior

In 2.x series you can't do this anymore forcing you to switch one tab at a time to the right with CTRL-TAB until reaching the last one or using the mouse to chose the last tab from the tab list drop-down menu.

### Arduino IDE version

2.0.3

### Operating system

Linux, N/A

### Operating system version

Ubuntu 20.04

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My request contains all necessary details

**Comment by per1234** [comment]
Resolved by https://github.com/arduino/arduino-ide/pull/2027 / https://github.com/eclipse-theia/theia/pull/11794
