### ISSUE TITLE
Board manager install button cut off at bottom

### ISSUE THREAD

**Issue by jpmeijers** [arduino/arduino-ide#1794]
### Describe the problem

The install button is not visible for the last entry in the boards manager list.

### To reproduce

Open the boards manager and scroll down to the last entry.

### Expected behavior

The button should be visible to install the boards of course.

### Arduino IDE version

Version: 2.0.4-nightly-20221231 Date: 2022-12-31T03:03:21.261Z CLI Version: 0.29.0 [76251df9]

### Operating system

Linux

### Operating system version

Ubuntu 22.04

### Additional context

Current situation for the ESP board definitions that need to update.

![Screenshot from 2022-12-31 14-23-20](https://user-images.githubusercontent.com/948278/210136705-c99869e9-1667-4ee3-85e9-a483e0b836e4.png)

When I resize the sidebar the install button becomes visible:

![Screenshot from 2022-12-31 14-23-33](https://user-images.githubusercontent.com/948278/210136755-63c48344-4310-4857-9bae-4c0f86199a9a.png)

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @jpmeijers. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/1591.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
