### ISSUE TITLE
Allow Output and Serial Monitor to be docked beside each other.

### ISSUE THREAD

**Issue by TheConceptBoy** [arduino/arduino-ide#1799]
### Describe the request

Allow the "**Output**" and "**Serial Monitor**" views to be docked beside each other.

### Describe the current behavior

Only one view at a time can be displayed in the Bottom Panel.

### Arduino IDE version

76f9f635d8558f399423f64c0c709e3a53bdcd03

### Operating system

All

### Operating system version

Any

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My request contains all necessary details

**Comment by per1234** [comment]
Hi @TheConceptBoy. Thanks for your suggestion. Arduino IDE previously had this capability and the project managers decided that it did not align with the intended design architecture for Arduino IDE, so it was intentionally removed: https://github.com/arduino/arduino-ide/pull/940

Regardless of whether you agree with that, the proposal specific to the "**Serial Monitor**" will be obviated anyway by the planned reworking of the "**Serial Monitor**" feature as a dedicated window similar to the "**Serial Plotter**" feature: https://github.com/arduino/arduino-ide/issues/289#issuecomment-1070964887

**Comment by TheConceptBoy** [comment]
Can they at least prevent the Output window from going into focus on every upload? It's pretty annoying when debugging via Serial monitor while doing rapid sketch uploads to have to keep switching to Serial Monitor as the Output keeps taking focus.

Compared to this, docking side by side seems like a much more reasonable solution.
