### ISSUE TITLE
Copy from Serial monitor on mac

### ISSUE THREAD

**Issue by jeromekasparian** [arduino/arduino-ide#1817]
### Describe the problem

Copying from serial monitor on mac (tested on Ventura 13.1 and Arduino IDE 2.0.3) only copies the part of the selected text that is visible within the Serial Monitor window.

Related issue: even if the cursor is in the Serial Monitor, "select all" selects all the .ino code displayed above, not the text of the serial monitor 

### To reproduce

wait till the text in the serial monitor exceeds the size of the display
(optional - for easier test) : stop the flow to the serial monitor eg by unplugging the arduino from the mac
Select the whole text in the serial monitor
Paste into a text editor
Only the text visible in the serial monitor is pasted

### Expected behavior

The whole selected text should be pasted

### Arduino IDE version

2.0.3

### Operating system

macOS

### Operating system version

Ventura 13.1

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi . Thanks for taking the time to submit an issue.

> only copies the part of the selected text that is visible within the Serial Monitor window.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/1081.

> even if the cursor is in the Serial Monitor, "select all" selects all the .ino code displayed above, not the text of the serial monitor

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/812.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the others.

If you end up with additional information to share, feel free to comment in the other thread.
