### ISSUE TITLE
No ports reported on macos ventura 13.1 apple silicon arduino 2.0.3 unless rosetta is installed

### ISSUE THREAD

**Issue by nickdesaulniers** [arduino/arduino-ide#1818]
### Describe the problem

Apple Silicon-based machines ([M1, M2 CPUs](https://en.wikipedia.org/wiki/Apple_silicon#M_series)) are able to run applications built for x86 host thanks to the [**Rosetta 2** binary translator](https://en.wikipedia.org/wiki/Rosetta_(software)#Rosetta_2).

**Rosetta 2** is not installed by default, but when an x86 application is started on an Apple Silicon-based machine, macOS displays a dialog offering the installation to the user:

https://support.apple.com/en-us/HT211861

Since native Apple Silicon builds have better performance, Arduino produced the first Arduino IDE 2.x build for this target and published it in December. Unlike the x86 build of Arduino IDE 2.x, starting the Apple Silicon build does not result in the **Rosetta 2** installation dialog. Even though **Rosetta 2** is not needed by the Arduino IDE application itself, the IDE uses a wide array of additional tools. Many of these are not available in an Apple Silicon build:

- [**serial-discovery**](https://github.com/arduino/serial-discovery)
- [**serial-monitor**](https://github.com/arduino/serial-monitor)
- **GCC**
- [**AVRDUDE**](https://github.com/arduino/avrdude-packing)
- ...

🐛 These tools produce an error when Arduino IDE attempts to execute them:

```text
bad CPU type in executable
```

This produces an array of symptoms. For example, no serial ports are discovered (due to not having a functional **serial-discovery** tool).

### To reproduce

1. Download the Apple Silicon build of Arduino IDE:
   https://www.arduino.cc/en/software
1. Start Arduino IDE on an Apple Silicon machine that does not have **Rosetta 2** installed.

🐛 No **Rosetta 2** installation prompt is shown.
🐛 All x86 targeted tools fail to execute.
🐛 The IDE displays a variety of symptoms, including no ports listed, failed compilation ...

### Expected behavior

The dependency on **Rosetta 2** is communicated to the user.

### Arduino IDE version

2.0.3

### Operating system

macOS

### Operating system version

Ventura

#### Fix

1. Open your **Applications** folder in **Finder**.
1. Open the **Utilities** folder.
1. Double-click on "**Terminal**".
1. Type the following command in the **Terminal** window:
   ```text
   softwareupdate --install-rosetta
   ```
1. Accept the license agreement.
1. Wait for the installation to finish.

#### Additional reports

- https://forum.arduino.cc/t/bad-cpu-type-in-executable-compile-error/1064440
- https://forum.arduino.cc/t/24-mac-m1-bad-cpu-type-in-executable/1071674
- https://forum.arduino.cc/t/one-mac-sees-my-arduinos-the-other-doesnt/1076201/9
- https://github.com/arduino/arduino-ide/issues/1796 (unconfirmed)

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by nickdesaulniers** [comment]
Ok, so we were able to resolve the forum thread (at least my issue).  So it looks like if you run a binary compiled for x86_64-apple-darwin on apple silicon which expects aarch64-apple-darwin (err, maybe aarch64e, which is their own ABI for BTI/PAC IIRC), then you will not get a prompt to install rosetta.  You need to manually install rosetta, which can be done from the command line via `softwareupdate --install-rosetta`.

So I guess it's a matter of contacting expressif or whomever to provide cross compilers for aarch64e-apple-darwin hosts in their board manager files.  Not sure how pervasive this is, but perhaps the arduino ide could trigger the rosetta install for the time being?  That would have been nice.

**Comment by nickdesaulniers** [comment]
Sorry, it's `arduino-fwuploader` that's first failing (see [the forum post](https://forum.arduino.cc/t/one-mac-sees-my-arduinos-the-other-doesnt/1076201/13?u=ndesaulniers) for the stack trace) which is a node.js app, IIUC.

**Comment by nickdesaulniers** [comment]
Not sure where the source for `arduino-ide-extension` are to report the issue to.
https://github.com/arduino/arduino-ide/blob/197cea2a60a9e6eed85be3069ea7a5bd88f963f8/electron-app/package.json#L24
https://www.npmjs.com/search?q=arduino-ide-extension

**Comment by army11b1980** [comment]
Very much looking forward to a resolution for this issue.
Apple M1
OS Ventura
IDE 2.0.3 for Mac
Rosetta 2 installed
!!Bad CPU Type!!

**Comment by army11b1980** [comment]
@per1234 I have Rosetta 2 installed. I still have this error.

**Comment by per1234** [comment]
@army11b1980 please post the full and exact output that contains the "Bad CPU Type" error.

**Comment by army11b1980** [comment]
@per1234 
Failed uploading: cannot execute upload tool: fork/exec /Users/michaelsmacstudio/Library/Arduino15/packages/arduino/tools/avrdude/6.3.0-arduino9/bin/avrdude: bad CPU type in executable

**Comment by per1234** [comment]
> ```text
> /Users/michaelsmacstudio/Library/Arduino15/packages/arduino/tools/avrdude/6.3.0-arduino9/bin/avrdude: bad CPU type in executable
> ```

OK, this is a completely different problem that happens to produce the same error message. The problem here is you are using a very old version of AVRDUDE from when Arduino only distributed 32-bit macOS builds of that tool. Support for 32-bit applications was dropped in macOS 10.15 Catalina:

https://support.apple.com/en-us/HT208436

So when you attempt to run a 32-bit application you get this "`bad CPU type in executable`" error.

Since your problem is unrelated to the subject of this bug report, and is also not related to the codebase hosted in this repository, it will not be appropriate to continue the discussion here. But if you make a post on the Arduino Forum, I'll be happy to provide you with assistance in solving the problem:

https://forum.arduino.cc/c/using-arduino/installation-troubleshooting/18

**Comment by per1234** [comment]
Closing as resolved to the extent that is feasible through the addition of a dedicated article in the Arduino Help Center:

https://support.arduino.cc/hc/en-us/articles/7765785712156-Error-bad-CPU-type-in-executable-on-macOS

I have been closely monitoring GitHub and Arduino Forum for reports and fortunately it seems to not affect many users. So hopefully that will be sufficient. I also hope that Apple might eventually enhance the user experience under these conditions with something similar to the Rosetta installation offer dialog that shows when starting an x86 application.
