### ISSUE TITLE
Arm 64-bit version of IDE 2.x

### ISSUE THREAD

**Issue by hybotics** [arduino/arduino-ide#1824]
### Describe the request

When will there be a 64-bit Arm version of IDE 2.x?? I am working on an Arm 64-bit SBC and need IDE 2.0.

### Describe the current behavior

There is currently no Arm 64-bit version of IDE 2.x.

### Arduino IDE version

2.x

### Operating system

Linux

### Operating system version

Debian Bullseye.

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My request contains all necessary details

**Comment by per1234** [comment]
Hi @hybotics. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/107.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
