### ISSUE TITLE
Nested folders in Sketchbook

### ISSUE THREAD

**Issue by Legion2** [arduino/arduino-ide#183]
**Is your feature request related to a problem? Please describe.**
With Arduino IDE 1.8 it was possible to organize sketches in the sketchbook directory using nested directories.
The nested sketches were available in the IDE to select them.
With Arduino IDE 2.0.0-beta3 I can not access nested sketches from the Sketchbook menu.

**Describe the solution you'd like**
Add support for organizing sketches into directories like in Arduino IDE 1.8.

**Describe alternatives you've considered**
Placing all sketches into the sketches folder, but then they can not be organized into groups.

**Additional context**
I use the subdirectories to manage groups of sketches using git repositories.

**Comment by per1234** [comment]
Hi @Legion2. Thanks for taking the time to submit an issue.

We already have a prior issue report about this at https://github.com/arduino/arduino-ide/issues/35.

It's best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.
If you end up with additional information to share, feel free to comment in the other thread.
