### ISSUE TITLE
Save serial monitor output as log

### ISSUE THREAD

**Issue by maifeeulasad** [arduino/arduino-ide#1839]
There should be a save button, where we can click and save the log into a certain file.

*Or some auto logger function so that no data gets lost.*

**Comment by per1234** [comment]
Hi @maifeeulasad. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/549.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
