### ISSUE TITLE
Cannot delete sketch

### ISSUE THREAD

**Issue by kittaakos** [arduino/arduino-ide#1843]
### Describe the problem

When deleting the main sketch file, the sketch folder and its content will be deleted. It does not work. Originally from here: https://github.com/arduino/arduino-ide/issues/1825#issuecomment-1398582540

### To reproduce

 - Open a sketch,
-  delete it,
- nothing happens.

> Another unhandled use-case for sketch deletion:
> 
> * Open IDE2,
> * Create a new sketch,
> * Click on the `...` on the tab toolbar, select Delete, click OK in the dialog, and see the notification for a subsecond
> 
> <img alt="Screen Shot 2023-01-20 at 16 45 31" width="846" src="https://user-images.githubusercontent.com/1405703/213742382-109d4809-b529-4330-b17b-ff54e3852e52.png">
> 
> - Nothing happens, no errors. - Deletion of temp sketches should be disabled, or the deletion should work.

### Expected behavior

IDE2 deletes the sketch folder and closes the window

### Arduino IDE version

2.0.3

### Operating system

macOS

### Operating system version

12.5.1

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @kittaakos. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/649.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
