### ISSUE TITLE
German translation incomplete and faulty

### ISSUE THREAD

**Issue by temran** [arduino/arduino-ide#1845]
### Describe the problem

Version: 2.0.4-nightly-20230131
Datum: 2023-01-31T03:07:58.343Z
CLI Version: 0.29.0Copyright © 2023 Arduino SA [undefined]

New Sketch -> Neu or Neuer Sketch
New Remote Sketch -> Neuer Fernbedienungs-Sketch

Werkzeuge->automatisch Formatieren -> Werkzeuge->automatisch formatieren 
Berabeiten->automatisch Formatieren -> Bearbeiten->automatisch formatieren

### To reproduce

Open IDE

### Expected behavior

New Sketch -> Neu or Neuer Sketch
New Remote Sketch -> Neuer Fernbedienungs-Sketch

Werkzeuge->automatisch Formatieren -> Werkzeuge->automatisch formatieren 
Berabeiten->automatisch Formatieren -> Bearbeiten->automatisch formatieren

### Arduino IDE version

Version: 2.0.4-nightly-20230131

### Operating system

Windows

### Operating system version

Home

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @temran. Thanks so much for your report. The translations are maintained by the Arduino community on Transifex. Please submit the fix over there:

https://explore.transifex.com/arduino-1/ide2/

More information on contributing to the Arduino IDE translations is available here:

https://github.com/arduino/arduino-ide/blob/main/docs/contributor-guide/translation.md#translator-guide
