### ISSUE TITLE
Sketchesd in alphabetical order but capitalised are grouped first

### ISSUE THREAD

**Issue by ubidefeo** [arduino/arduino-ide#185]
**Describe the bug**
When the sketchbook menu is expanded all the ones which have capitalised names come as a group in alphabetical order, followed by a group of examples with lowercase names as another group (see screenshot)

**To Reproduce**
1. **File > Sketchbook**
2. Scroll examples
3. Notice that uppercase named sketches are grouped first

**Expected behavior**
Sketches should be in true alphabetical order, despite their initial

**Screenshots**
<img width="295" alt="Screenshot 2021-03-08 at 16 13 25" src="https://user-images.githubusercontent.com/1894487/110340731-db86ef80-8029-11eb-9262-44948d527370.png">

**Desktop (please complete the following information):**
 - OS: Mac OS 10.15.7
 - Version: 2.0.0-beta.3 Date: 2021-02-26T10:47:47.411Z

**Comment by silvanocerza** [comment]
I think that list is generated directly by the IDE, it's not a concern of the CLI as of now.

**Comment by ubidefeo** [comment]
thanks @silvanocerza 
@kittaakos can you look into this?

**Comment by Sebastian-Brzuzek** [comment]
I'm new here, so I'm not sure if proposed solution is reasonable, but if looks like assing "order" property with lower case "label" value in sketches/examples solves the issue without impacting other elements. (I have tested solution on Windows only)

**Comment by ubidefeo** [comment]
Closed by #222
