### ISSUE TITLE
How to update board libs?

### ISSUE THREAD

**Issue by hyansuper** [arduino/arduino-ide#1862]
### Describe the request

[Arduino-ESP32 releases](https://github.com/espressif/arduino-esp32/releases) is ahead of what "ArduinoIDE -> board manager" shows

### Describe the current behavior

there's no update button, only install/uninstall button

### Arduino IDE version

2.0.3

### Operating system

Windows

### Operating system version

win11

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My request contains all necessary details

**Comment by per1234** [comment]
Hi @hyansuper. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
