### ISSUE TITLE
uploading progress bar persists

### ISSUE THREAD

**Issue by graham2550** [arduino/arduino-ide#1864]
### Describe the problem

Using ESP32 development board, uploading by WiFi.
After uploading a sketch OTA the uploading progress bar fails to disappear.
A further upload is not possible.
To upload again OTA the IDE must be restarted.
This is a very time-consuming and frustrating bug considering you have to first save any changes made, close the IDE and restart (which takes forever).
Please FIX.

### To reproduce

Upload OTA.

### Expected behavior

the upload progress bar does not close after upload is comlete.

### Arduino IDE version

2.0.3

### Operating system

Windows

### Operating system version

10

### Additional context

I see other complaints of the same bug, but no fix. 
So I ask again.
I am using the latest nightly build, which is quite old.

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @graham2550. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/1356.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
