### ISSUE TITLE
Can't find 'esp8266 by esp8266 community' [solved]

### ISSUE THREAD

**Issue by bobblkabb** [arduino/arduino-ide#187]
**Describe the bug**
I have added the esp8266 url in the settings but the board manager does not find the library I need 

**To Reproduce**
1. Go to _File_ -> _Preferences_
2. Add _https://arduino.esp8266.com/stable/package_esp8266com_index.json_ to Additional Boards Manager URL
3. Go to _Tools_ -> _Library Manager_
4. Search for 'community' or 'esp8266' for instance

**Expected behavior**
Show lib 'esp8266 by esp8266 community'

**Desktop (please complete the following information):**
 - OS: openSUSE Tumbleweed
 - Version: 1.8.13

**Additional context**
Was no problem to add esp32 _https://dl.espressif.com/dl/package_esp32_index.json_
Board is NodeMcu v3  LoLin (CH340G driver)

**Comment by ubidefeo** [comment]
@bobblkabb 
are you using IDE 1.8.13?

This is the repository for IDE 2.0

**Comment by bobblkabb** [comment]
Yes, I do use 1.8.13. Shall I use the new beta version?

**Comment by ubidefeo** [comment]
@bobblkabb 
it really depends.
you can give it a try for sure, just remember that being Beta you might bump into some bugs

**Comment by bobblkabb** [comment]
Still, can't also find it with latest beta (v2.0). Board ist plugged in, /dev/ttyUSB0 is selected.

**Comment by ubidefeo** [comment]
@bobblkabb

I think you're doing it wrong, I only realised it now that I read your report a few times.
You are searching for the board support in the library manager

go to **Tools > Board > Board manager** and search for esp8266

**Comment by bobblkabb** [comment]
That's it! I'm fool!
Thanks a lot.

**Comment by ubidefeo** [comment]
no worries, @bobblkabb 
happy you got it to work 👍🏼
