### ISSUE TITLE
OTA doesn't close properly after upload to ESP32

### ISSUE THREAD

**Issue by thorathome** [arduino/arduino-ide#1871]
### Describe the problem

IDE 2.0.3 uploads OTA to ESP32 targets via Networked Ports perfectly and the devices start running as expected. 

**However, the Upload... progress bar in the lower right corner of the IDE continues to show movement and does not disappear. See screenshot. The IDE window is now frozen, and has to be closed to continue working.**  

ESP8266 OTA uploads appear to work fine. 
Serial uploads to all targets work fine. 

### To reproduce

I am working on a streamlined sketch to reproduce this and am happy to continue the investigation. 

Targets are ESP32 Feather and ESP32 S3 Feather from Unexpected Maker (both via Adafruit), 
Serial upload works fine with ESP32 targets. 
Hangup is OTA only. 

The sketches I am using are well-used, currently running sketches. I do use Blynk. 

OTA appears to work fine with ESP8266 (Node MCU 1.0) and SONOFF targets. 

### Expected behavior

Once OTA upload is complete, and ...Done shows on the Output tab, I expect the Uploading progress bar to close. Instead, it stays open andhangs the window. 

The OTA upload actually works. Devices get the upload. 
However I must then close the IDE window and re-open to continue working. ,

### Arduino IDE version

Version: 2.0.3 Date: 2022-12-05T09:30:25.331Z CLI Version: 0.29.0 [76251df9]

### Operating system

Windows

### Operating system version

11 Pro 10.0.22621 Build 22621

### Additional context

![image](https://user-images.githubusercontent.com/2821513/217901661-b3a46d61-9e9b-4708-90f6-2fcc8375713a.png)

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @thorathome. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/1356.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
