### ISSUE TITLE
Sketches on UNC paths cannot be opened from Windows File Explorer

### ISSUE THREAD

**Issue by Silver-Fang** [arduino/arduino-ide#1872]
### Describe the problem

My sketch is shared by another computer on a LAN and can be viewed in Windows File Explorer using a UNC path. However, if I double-click the sketch .ino file and try to open it using the Arduino IDE, it will get stuck during the window loading phase. After waiting for a while, a significant memory leak can be observed using Task Manager. Wait a little longer, and the entire Windows system will freeze and crash.

### To reproduce

1. Create a sketch and share it on the LAN.
2. Find the sketch from another computer using Windows File Explorer.
3. Double-click the sketch .ino file to open it with Arduino IDE.
4. IDE gets stuck forever and finally crash the OS.

### Expected behavior

The sketch is normally opened in the IDE and no OS crashes happen.

### Arduino IDE version

2.0.3

### Operating system

Windows

### Operating system version

10 & 11

### Additional context

Win11 is more vulnerable to crashes than 10. Memory leak is observable on both versions. For the nightly build Arduino IDE, you can also drag the .ino file on the Arduino executable to reproduce this issue.

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @Silver-Fang. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/1797.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
