### ISSUE TITLE
Emoji not displaying properly when pulling sketch from cloud arduino editor

### ISSUE THREAD

**Issue by lewixlabs** [arduino/arduino-ide#1874]
### Describe the problem

Hi,
my Issue is: emoji not displaying properly on Arduino IDE 2 native, but on cloud editor they are ok.
Seems a sketch download from cloud problem because after that, if I try to retype emoji on Arduino IDE directly, this one is correctly displayed.

I attach screenshots
![image](https://user-images.githubusercontent.com/7371215/218082371-7d5cc78b-957c-4954-b285-0099384137e2.png)
![image](https://user-images.githubusercontent.com/7371215/218082460-44b44540-ba47-4f7b-b124-26e7c75defe0.png)

### To reproduce

1. Insert any emojy on your code in cloud editor
2. from you arduino ide 2.0 native make a pull of that sketch (from cloud -> to native)
3. you can notice emoji not displaying properly 

### Expected behavior

Emoji must be correctly displayed on arduino ide

### Arduino IDE version

2.0.4-nightly-20230210

### Operating system

macOS

### Operating system version

Ventura 13.2

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @lewixlabs. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/449.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.

**Comment by lewixlabs** [comment]
Hi @per1234 ok thank you, I didn't find this report you mentioned when I searched on opens issues.
