### ISSUE TITLE
Allow copying of a local sketch to Arduino Cloud in IDE2

### ISSUE THREAD

**Issue by davegarthsimpson** [arduino/arduino-ide#1876]
### Describe the request

At present cloud sketches can be viewed and modified from IDE2, but there is no way of copying a local sketch to Arduino Cloud from the IDE2 interface.

This "one-way-only" workflow makes our offering of cloud sketch features feel incomplete.

We should implement a "Push Sketch to Cloud" action/option in the ui of IDE2, as per design spec. 

#### Outcome

Push "action icons" added to local sketches in the Sketchbook list, and push "action items" added to "sketch item popover menus" in the Sketchbook list.

When a user is logged in to Arduino cloud from IDE2, these ui elements should **copy** the related sketch to their Arduino Cloud account.

The newly create cloud sketch should then be visible as a separate entity in the cloud sketchbook list.

### Additional context
Figma links here

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My request contains all necessary details

**Comment by kittaakos** [comment]
> We should implement a "Push Sketch to Cloud" action/option in the ui of IDE2, as per design spec.
> 

> Push "action icons" added to local sketches in the Sketchbook list, and push "action items" added to


I copy paste my remark from an internal thread:

> “Pushing” a local sketch to the cloud is vital, but it could be confusing for users to understand what happens. After a push, I expect one local sketch, but two identical sketches will exist locally in this case. Pushing is not the correct term for me. “clone” or “create a cloud copy” sounds better. Also, we need more use cases for the development phase. Having these slides for the presentation is great, but IDE2 needs more details. For example, what happens when a cloud sketch already exists with the same name? What’s the error message?
