### ISSUE TITLE
Arduino 2.0 uploading & no baud rate  issue

### ISSUE THREAD

**Issue by KvarTechnologies** [arduino/arduino-ide#1890]
### Describe the problem

I am currently using arduino 2.0 idle on windows 10, And using to program esp32. But when i program its compiles and upload the program to full 100% but the GUI still shows "Uploading prompt" . this problem has occurred now.
![Capture](https://user-images.githubusercontent.com/104092776/219323304-443f09d0-0053-4742-adc8-119c17f57c84.PNG)

I cant see option to change the baudrate.
![Capture2](https://user-images.githubusercontent.com/104092776/219323345-0154684e-8ced-4ccc-8caa-6e1edcce9c62.PNG)

### To reproduce

i have been changing the board manager lib to 1.0 of esp32

### Expected behavior

it shows uploading even after the uploading is occurred. And there isn't place to change the baud rate

### Arduino IDE version

2.0.3

### Operating system

Windows

### Operating system version

10

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @KvarTechnologies. Thanks for taking the time to submit an issue.

>upload the program to full 100% but the GUI still shows "Uploading prompt" .

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/1801.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.

>I cant see option to change the baudrate.

I will provide support over on your forum post about this problem:

https://forum.arduino.cc/t/arduino-2-0-upload-issue/1090859
