### ISSUE TITLE
Unable to select files in explorer tab in Arduino ide2.0.3

### ISSUE THREAD

**Issue by piyushsuteri** [arduino/arduino-ide#1891]
### Describe the problem

When I have many files, so I have to scroll down or up to open other files in explorer tab. But the problem is that I can't scroll anywhere, scrollbar comes to the current opend file always, if i just select other files (down or up to currently opened files) so then only i am able to scroll a bit down or up. That's is first problem, second is related to Serial monitor.
While I have to print many lines continously in every delay of time, i am unable to see last line and it just gets hidden downward. If i scroll down it can be seen then only. I think printing area to be shifted some upwards. When the another line(or new line) is sent from Arduino, the previous line gets vissible but the line sent just now is not hidden. This process continues when other line is sent form arduino uno, same as above previous line now vissible but last line hidden. In my case I had made the Arduino UNO and numeric keypad circuit. Project is like that whenever I press any key in numeric keypad so its printed alphabet is printed on Serial monitor. But whenever i press new key it is not shown in Serial monitor instantly but previous key press becomes vissible (earlier which was invissible). I think its issue with new Arduino IDE 2.0.3 as this was not with older IDE 1. Thank you, I hope that my problem will be resolved in next update of Arduino ide 2.0.3

### To reproduce

Improve this problem for next versions and make newer versions faster.

### Expected behavior

I hope this problem must be solved

### Arduino IDE version

2.0.3

### Operating system

Windows

### Operating system version

11

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @piyushsuteri. Thanks for taking the time to submit an issue.

> When I have many files, so I have to scroll down or up to open other files in explorer tab. But the problem is that I can't scroll anywhere, scrollbar comes to the current opend file always

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/1766.

>That's is first problem, second is

In the future, please submit a separate issue for each distinct subject matter. Mashing multiple unrelated items into a single issue makes maintenance very difficult and makes it more likely we will overlook one of the items.

>While I have to print many lines continously in every delay of time, i am unable to see last line and it just gets hidden downward

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/1736

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the others.

If you end up with additional information to share, feel free to comment in the other threads.
