### ISSUE TITLE
Error 13  INTERNAL: Library failed

### ISSUE THREAD

**Issue by Cabinfourus** [arduino/arduino-ide#1894]
### Describe the problem

I cannot add a .zip library to IDE. 
When I try to add a zip library to Ardruino IDE, I get an "Error 13 INTERNAL: Library install failed: library not valid"

### To reproduce

Open Arduino IDE version  2.0.3  (Windows 11 OS)
Click on 'sketch'
click on 'include library'
click on  'add.zip library'
click on  'grbl 1.1h20190825' (zip folder)

I have also tried to unzip the folder and add it but I get the same error. 

### Expected behavior

add Zip library to Arduino IDE files

### Arduino IDE version

2.0.3

### Operating system

Windows

### Operating system version

11

### Additional context

I have tried every tutorial online and I keep getting this error. 

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @Cabinfourus. The error message is correct and expected. The ZIP file does not have the required format for installation via the Arduino IDE's **Sketch > Include Library > Add .ZIP Library...** feature.

You can install it by following the instructions from the Grbl wiki:

https://github.com/gnea/grbl/wiki/Compiling-Grbl#if-you-are-using-arduino-ide-2x

If you have any questions or problems while following those instructions, please post about it on the Arduino Forum:

https://forum.arduino.cc/

I'm certain we will be able to help you out over there.
