### ISSUE TITLE
Make Boards/Library Manager uninstall functionality easier to find

### ISSUE THREAD

**Issue by per1234** [arduino/arduino-ide#19]
### Describe the problem

I needed to uninstall a boards platform via Boards Manager and couldn't find the <kbd>**Remove**</kbd> button I'm used to from using Arduino IDE 1.x.

It took me quite some time to realize that the "**INSTALLED**" label on the entry in the list of platforms turns into an "**UNINSTALL**" button when you hover on it.

### To reproduce

1. Open the "**Boards Manager**" view.
1. Scroll down until you see the "**Arduino AVR Boards**" platform entry.
1. Look for an obvious mechanism to uninstall the platform. 

### Expected behavior

Make the uninstall functionality easy for the user to discover.

#### Original report

2.0.0-beta.2-snapshot.298cc11

#### Last verified with

76f9f635d8558f399423f64c0c709e3a53bdcd03

### Operating system

All

### Operating system version

Any

### Additional context

A minimal change that would improve the current situation would be to change the installed "**INSTALLED**" label to have the same border and drop shadow as the <kbd>INSTALL</kbd> button.

Alternatively, a <kbd>**Remove**</kbd> button could be added to mirror the Arduino IDE 1.x Boards Manager UI.

---

The Arduino IDE 1.x Library Manager does not have an uninstall capability, but the Arduino IDE 1.x Boards Manager does have an uninstall capability, so the latter should be used if looking for a reference design.

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My request contains all necessary details

**Comment by mklemarczyk** [comment]
It works well for me as it is. I do not find adding another button a good improvement. It just need to be well documented in my opinion so you do not need to find it out on your own.

**Comment by littlegreenrock** [comment]
There is nothing wrong with the functionality of the button, it simply requires explanation either through documentation or experimentation.  Dynamic button labels should always have grammatical consistency.

- **INSTALL** is the action user would like to perform. Install 'this' module which I don't have.
- **INSTALLED** is not an action, it's the status of this module.  The action button has changed to a status button. 


This may lead to the need for documentation.  Documentation can (and should) be avoided when simply altering the user interface is the alternative.  
**Proposed change:** 
1. the button label always represents an action the user may perform by clicking the button.  
2. The position remains consistent.
3. version and changing versions share the space
4. colour helps highlight installed packages.

All functions remain the same.  Changes are UI.


![button label](https://user-images.githubusercontent.com/23202921/210731080-67088641-0234-4272-b3dc-7c8731cee557.jpg)
