### ISSUE TITLE
Jumpin drop down menue in v2.0.3

### ISSUE THREAD

**Issue by hasenradball** [arduino/arduino-ide#1900]
### Describe the problem

Lets assume you have a big list of sketches....in your sketchbook.
And you want to scroll down....to select one sketch from the bottom.
... it is not possible... if you scroll down then it jumps immediately up again if the start folder goes out of scope!!!

Terrrible!!!! 

![grafik](https://user-images.githubusercontent.com/26808969/220397343-999ea41a-e966-4e48-a917-4a702f82d064.png)

### To reproduce

Big list of sketches in your sketchbook.

### Expected behavior

Jumping drop down Menue.

### Arduino IDE version

2.0.3

### Operating system

Linux

### Operating system version

Ubuntu 20.04.5 LTS

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @hasenradball. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/1766.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
