### ISSUE TITLE
`debug.server.openocd.script` should support multiple files

### ISSUE THREAD

**Issue by fpistm** [arduino/arduino-ide#1906]
### Describe the request

Currently `{debug.server.openocd.script}` is used to provide the openocd file configuration to load by expanding {build.openocdscript}
example:
`debug.server.openocd.script={build.openocdscript}`
`Nucleo_64.build.openocdscript=board/st_nucleo_f4.cfg`
produces:
`-f "board/st_nucleo_f4.cfg"`

This board config will load the interface and target.
Anyway it should be useful to be able to provide the interface and the target if no board config available:
`-f "interface/stlink.cfg" -f "target/stm32f4x.cfg"`
which is supported by openocd.

### Describe the current behavior

It is not possible to provide more than one configuration file.

Example if we defined 2 configurations files:
`Nucleo_64.build.openocdscript=target/stm32f4x.cfg interface/stlink.cfg`
it produces this arguments:
`-f "target/stm32f4x.cfg interface/stlink.cfg"`
while we expect:
-f "target/stm32f4x.cfg" -f "interface/stlink.cfg"
### Arduino IDE version

2.0.3

### Operating system

Windows, Linux, macOS

### Operating system version

10, ubuntu 20.04, ventura

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My request contains all necessary details

**Comment by kittaakos** [comment]
It should be possible with https://github.com/arduino/arduino-cli/commit/748fcf6228327a18dd896cd4edf38f96a2443510 and Arduino IDE 2.3.0.

Please use the `debug.server.openocd.scripts.N` directive. Reference the `OpenOCD server specific configurations` section from the platform specification: https://arduino.github.io/arduino-cli/latest/platform-specification/#debugger-configuration-directives for more details.

I am closing as resolved. If you disagree or notice any bugs, please update this issue, and maintainers will reopen if needed. Thanks
