### ISSUE TITLE
mdns-discovery pop-up on start-up

### ISSUE THREAD

**Issue by ishouldmomo** [arduino/arduino-ide#1914]
### Describe the problem

When I open the IDE (2.0.3, but it was happening with earlier 2.0 versions too) I get a pop-up asking me whether I want the mdns-discovery to accept incoming network connections.
![Screenshot 2023-02-23 at 09 58 22](https://user-images.githubusercontent.com/91489321/220875477-7b0946f1-dc6a-4c0d-83f5-6303766751e1.png)
Regardless of whether I choose _Deny_ or _Accept_, I get the same pop-up every time I start the IDE. Looks like multiple entries are being added to the firewall list:
<img width="471" alt="Screenshot 2023-02-23 at 10 10 08" src="https://user-images.githubusercontent.com/91489321/220878040-98f9e927-9187-490f-ab8d-193e74b69603.png">
On macOS Ventura 13.2.1

### To reproduce

Open the IDE on macOS more than once.

### Expected behavior

Once I have selected an option, to never see the pop-up again.

### Arduino IDE version

2.0.3

### Operating system

macOS

### Operating system version

Ventura 13.2.1

#### Additional reports

- https://github.com/arduino/mdns-discovery/issues/45

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by maddisondesigns** [comment]
I'm getting the same annoying message as well. It happens every time you start the Arduino IDE, and it also happens every time you try to compile when using VS Code (with the Visual Studio Code extension for Arduino).

I have the same Arduino IDE version and the same macOS version as @ishouldmomo above.
