### ISSUE TITLE
IDE 2.0.3 unable to copy content of serial monitor with ctrl-a / ctrl-c

### ISSUE THREAD

**Issue by StefanL38** [arduino/arduino-ide#1918]
### Describe the problem

The title says it all:
IDE 2.0.3 unable to copy content of serial monitor with ctrl-a / ctrl-c

don't you think that it is crucial for debugging to have this function?

### To reproduce

take any code of your choice that prints to the serial monitor 20 to 50 lines
stop the printing (f.e. by unplugging the µC.

click into area of serial monitor
Try to use ctrl-a, ctrl-c
nothing happends

### Expected behavior

take any code of your choice that prints to the serial monitor 20 to 50 lines
stop the printing (f.e. by unplugging the µC.

click into area of serial monitor
Try to use ctrl-a, ctrl-c
all content of the serial monitor is copied to the clipboard

### Arduino IDE version

Ide 2.0.3 if you need more info add a description RIGHT HERE how to obtain the additional info

### Operating system

Windows

### Operating system version

if you need more info add a links RIGHT HERE that lead to how to obtain the additional info

### Additional context

simply baffeled by **not** implementing this function of beeing able to use
ctrl-a / ctrl-c to copy content of serial monitor

I checked all the checkboxes. It is my full intention to create another ISSUE as a bug-report on this 
despite there are multiple similar issues. 

I feel it is a bottomless cheek to advertise the IDE 2.0.3 as the "current version" of the IDE and still not have this function installed!

What are the reasons to **NOT** add this functionality?

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
>It is my full intention to create another ISSUE as a bug-report on this
despite there are multiple similar issues.

@StefanL38 that is counterproductive. Instead of putting the time to working on fixing problems and making enhancements to Arduino IDE 2.x, we must clean up after your inappropriate usage of this issue tracker. I have warned you about this before. If you persist in this behavior I will be forced to report your account to GitHub for abuse.

>if you need more info add a links RIGHT HERE that lead to how to obtain the additional info

Give me a break. I'm certain you already know which version of Windows you are using.
