### ISSUE TITLE
When installing library through the library manager, it does not show to include in the code and does not show examples

### ISSUE THREAD

**Issue by MicSG-dev** [arduino/arduino-ide#192]
When installing a library through the library manager, it does not appear in the Sketch -> Include Library menu to include the library in the code. There are also no examples from the library in the File -> Examples menu.

I installed the arduino IDE 2.0 by zip. I don't know if it interfered with anything.

IDE Version

> Version: 2.0.0-beta.3
Date: 2021-02-26T10:48:13.025Z
CLI Version: 0.16.1 alpha [76f55490]

**Comment by kittaakos** [comment]
> it does not appear in the Sketch -> Include Library menu to include the library in the code

Did you select a board, @MicSG-dev? You have to select a board to populate the `Include Library` menu. Under the hood, the IDE uses the CLI's `lib list` command filtered by the FQBN of the currently selected board. If you do not select a board, the IDE shows nothing.

https://user-images.githubusercontent.com/1405703/110769359-62211400-8258-11eb-8dee-24cbd660e29a.mp4

**Comment by MicSG-dev** [comment]
Got it. Thanks for the clarification.
