### ISSUE TITLE
Serial Montier is sum time not Geeting data

### ISSUE THREAD

**Issue by gopalreddylakki** [arduino/arduino-ide#1930]
### Describe the problem

Serial monitor is sum time not Geeting data and auto scrolling also not going we need scrolling down 

### To reproduce

Serial monitor 

### Expected behavior

no

### Arduino IDE version

2.0.3

### Operating system

Windows

### Operating system version

11

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @gopalreddylakki. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/1736 or https://github.com/arduino/arduino-ide/issues/1724.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
