### ISSUE TITLE
no tools

### ISSUE THREAD

**Issue by luqizhi666** [arduino/arduino-ide#1931]
### Describe the problem

Tools in the arduino1 like "ESP32FS" doesn't exsit in the menu.

### To reproduce

/tools/ESP32FS

### Expected behavior

add them back

### Arduino IDE version

2.0

### Operating system

Windows

### Operating system version

win11

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @luqizhi666. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/58.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
