### ISSUE TITLE
Library manager not formatting windows correctly

### ISSUE THREAD

**Issue by thearduinoguy** [arduino/arduino-ide#1933]
### Describe the problem

Library manager not formatting windows correctly. Each library window is being overlapped by the enxt. Some so badly that the INSTALL button is covered.

### To reproduce

Open Library Manager

### Expected behavior

Each windows should be within its own boundary only

### Arduino IDE version

2.0.4

### Operating system

Windows

### Operating system version

11

### Additional context

Incorrect window example below.... 

[https://imgur.com/gallery/11SSahY](url)

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @thearduinoguy. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/1591.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
