### ISSUE TITLE
CLI version reported by IDE does not match Command Prompt

### ISSUE THREAD

**Issue by aliphys** [arduino/arduino-ide#1958]
### Describe the problem

The Arduino-CLI CLI version reported by the IDE does not match Command Prompt
![image](https://user-images.githubusercontent.com/75624145/225024721-85c53632-150a-4a00-a41c-152e4105116e.png)

### To reproduce

1. Upgrade Arduino IDE from previous version to 2.0.4
2. In Command Prompt, enter the command `arduino-cli board listall`
3. At the end of the board list, this message is given

    > A new release of Arduino CLI is available: 0.27.0 → 0.31.0
https://arduino.github.io/arduino-cli/latest/installation/#latest-packages

5. Click on Help -> About Arduino IDE
6. The following message is given
    > Version: 2.0.4
        Date: 2023-02-27T16:14:28.576Z
       CLI Version: 0.31.0
       Copyright © 2023 Arduino SA

### Expected behavior

Both the Command Prompt and IDE show the same arduino CLI version

### Arduino IDE version

Arduino 2.0.4

### Operating system

Windows

### Operating system version

Windows 10

### Additional context

I have NOT verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds), since the nightly build is provided as portable application.

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [ ] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by kittaakos** [comment]
Thanks for keeping an eye on this and reporting it to use.

It's not a bug.

> 2\. In Command Prompt, enter the command `arduino-cli board listall`

When you run `arduino-cli.exe board install`, the CLI from your `$PATH` is picked up. The correct way to determine the CLI's version inside IDE2 is this:

```
Microsoft Windows [Version 10.0.19044.2728]
(c) Microsoft Corporation. All rights reserved.

c:\Users\kittaakos\Desktop\ide2 2.0.4>cd resources\\app\\node_modules\\arduino-ide-extension\\build

c:\Users\kittaakos\Desktop\ide2 2.0.4\resources\app\node_modules\arduino-ide-extension\build>arduino-cli.exe version
arduino-cli.exe  Version: 0.31.0 Commit: 940c9457 Date: 2023-02-22T16:15:54Z
```
