### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by Lucas-Niesen** [arduino/arduino-ide#1959]
### Describe the request

 I want i functie i use tabs like in vscode.

### Describe the current behavior

Not working.

### Arduino IDE version

2.0.4

### Operating system

N/A

### Operating system version

22h2

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My request contains all necessary details

**Comment by per1234** [comment]
Hi @Lucas-Niesen. If you want "tabs like in vscode" then please use VS Code. The Arduino IDE tabs work exactly as designed and their functionality will not be changed.
