### ISSUE TITLE
Millis() as delay() - Monitor serial 

### ISSUE THREAD

**Issue by Adanoter** [arduino/arduino-ide#196]
I try see in serial monitor the time with timestamp and is really wrong
For example

     Smartdelay = millis ();
     while (millis () <Smartdelay + 5000) {}

Takes 32 seconds to change.

**Comment by ubidefeo** [comment]
@Adanoter 
please be more informative with your issue report.
Post your entire sketch code and we'll test it.

I have no idea where you print to `Serial` and what else happens in the meantime

thank you
