### ISSUE TITLE
Entry highlight in Library Manager alternates when scrolling list

### ISSUE THREAD

**Issue by pastacolsugo** [arduino/arduino-ide#1973]
### Describe the problem

List entries alternate colors when scrolling the Library Manager library list, making the experience quite confusing.

### To reproduce

1- Open the Library Manager
2- Scroll the library listing
3- Notice that when scrolling down all entries in view switch color between light gray and white

### Expected behavior

When the list is scrolled each entry should keep its background color. They should *not* change.

### Arduino IDE version

Version: 2.0.4 Date: 2023-02-27T16:11:45.995Z CLI Version: 0.31.0  Copyright © 2023 Arduino SA

### Operating system

macOS

### Operating system version

12.6.3 (21G419)

### Additional context

Intel cpu

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by kittaakos** [comment]
Hi, thanks for taking the time and reporting the bug. We have improved the library/boards manager widget at https://github.com/arduino/arduino-ide/pull/1927. Please try it with the nightly build: https://github.com/arduino/arduino-ide#download. If you still experience the same problem, ping me, and I will reopen this task.

Closing as invalid for now.
