### ISSUE TITLE
IDE opens stretched out on widescreen monitor.

### ISSUE THREAD

**Issue by steelgoose** [arduino/arduino-ide#1981]
### Describe the problem

Windows with 49" Samsung curved widescreen. When opening a sketch from the 2.04 IDE, the sketch is stretch out to about 2/3rds across the monitor. This is kind of annoying as I half to drag it back to normal size on every sketch I open.

### To reproduce

Open the IDE on the widescreen monitor then open a sketch from the IDE.

### Expected behavior

The sketch would open up 780mm long.

### Arduino IDE version

2.04

### Operating system

Windows

### Operating system version

Windows 10

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @steelgoose. Thanks for taking the time to submit an issue.

It looks like we have a previous report about this at https://github.com/arduino/arduino-ide/issues/1329.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
