### ISSUE TITLE
Support selected terminal escape sequences in serial monitor

### ISSUE THREAD

**Issue by wodzuu** [arduino/arduino-ide#1991]
### Describe the request

It would be nice to support following two escape sequences:

- \x1B[H (move cursor to upper left corner)
- \x1B[2J (clear screen)

When such sequence is received from serial connection the serial monitor should act accordingly.

### Describe the current behavior

Escape sequences are not interpreted as special sequences.

### Arduino IDE version

2.0.4

### Operating system

N/A

### Operating system version

N/A

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My request contains all necessary details

**Comment by kittaakos** [comment]
Hi @wodzuu . Thanks for taking the time to submit an issue.

I see we already had prior requests for this or similar features, which were declined:

- https://github.com/arduino/Arduino/issues/9102
- https://github.com/arduino/Arduino/issues/346
- https://github.com/arduino/Arduino/issues/3654
- https://github.com/arduino/arduino-ide/issues/1897

There is a different take on adding such support here: https://github.com/arduino/arduino-ide/issues/406

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
