### ISSUE TITLE
problem while uploading sketch on arduino ide

### ISSUE THREAD

**Issue by Nikunjj20** [arduino/arduino-ide#1995]
### Describe the problem

```
Arduino: 1.8.19 (Windows Store 1.8.57.0) (Windows 10), Board: "Arduino Nano, ATmega328P"

Sketch uses 13518 bytes (44%) of program storage space. Maximum is 30720 bytes.

Global variables use 1148 bytes (56%) of dynamic memory, leaving 900 bytes for local variables. Maximum is 2048 bytes.

C:\Users\Lenovo\Documents\ArduinoData\packages\arduino\tools\avrdude\6.3.0-arduino17/bin/avrdude -CC:\Users\Lenovo\Documents\ArduinoData\packages\arduino\tools\avrdude\6.3.0-arduino17/etc/avrdude.conf -v -patmega328p -carduino -PCOM4 -b115200 -D -Uflash:w:C:\Users\Lenovo\AppData\Local\Temp\arduino_build_475147/project.ino.hex:i 



avrdude: Version 6.3-20190619

         Copyright (c) 2000-2005 Brian Dean, http://www.bdmicro.com/

         Copyright (c) 2007-2014 Joerg Wunsch



         System wide configuration file is "C:\Users\Lenovo\Documents\ArduinoData\packages\arduino\tools\avrdude\6.3.0-arduino17/etc/avrdude.conf"

avrdude: can't open config file "C:\Users\Lenovo\Documents\ArduinoData\packages\arduino\tools\avrdude\6.3.0-arduino17/etc/avrdude.conf": No such file or directory

avrdude: error reading system wide configuration file "C:\Users\Lenovo\Documents\ArduinoData\packages\arduino\tools\avrdude\6.3.0-arduino17/etc/avrdude.conf"

avrdude: error reading system wide configuration file "C:\Users\Lenovo\Documents\ArduinoData\packages\arduino\tools\avrdude\6.3.0-arduino17/etc/avrdude.conf"





This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
```

### To reproduce

i tried to uninstall avr 1.8.6 and download 1.8.3 but nothing happens

### Expected behavior

i have tried a lot to upload the program on arduino but nothing happens

### Arduino IDE version

Arduino IDE 1.8.19

### Operating system

Windows

### Operating system version

Windows 11

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by kittaakos** [comment]
Hi! Thanks for taking the time to report the problem. This GitHub repository tracks imperfections and enhancements for the [new version (2.x)](https://www.arduino.cc/en/software) Arduino IDE. Your error output shows that you used an [older version (1.x)](https://github.com/arduino/arduino) of the Arduino IDE.

I am sure somebody will be happy to help you to figure out a solution for your problem on the [Arduino forum](https://forum.arduino.cc/).
