### ISSUE TITLE
[AE-63] Increase contrast of "Select board" text in the GUI in Linux

### ISSUE THREAD

**Issue by aliphys** [arduino/arduino-ide#2009]
### Describe the request

Make the "Select board" text more clear by using the same colour scheme in Windows (dark grey text on light grey background)

### Describe the current behavior

The "Select Board" element is white on a light grey background and very difficult to see.
https://github.com/arduino/arduino-ide/blob/eb1f247296a1993c38a65b1b5707a238a8d8a77d/arduino-ide-extension/src/browser/boards/boards-toolbar-item.tsx#L211
![image](https://user-images.githubusercontent.com/75624145/231129170-8821cc47-b272-4a35-a8df-b3395c9e5c89.png)
This is also the case when a board is selected as well.
![image](https://user-images.githubusercontent.com/75624145/231129843-2dd64aa1-934e-4653-90cd-ac4c8ffdb4d6.png)

### Arduino IDE version

2.0.4

### Operating system

Linux

### Operating system version

Ubuntu 22.04

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My request contains all necessary details

**Comment by aliphys** [comment]
The lack of contrast is only problematic on the default `Light (Arduino)` theme. For example, this is the `Light (Theia)` theme in which the text is clear. 
![image](https://user-images.githubusercontent.com/75624145/231131498-5a5badc1-afeb-4dc5-9310-b30ac9092e13.png)

**Comment by kittaakos** [comment]
> Make the "Select board" text more clear by using the same colour scheme in Windows (dark grey text on light grey background)

Thank you for taking the time to report the issue, @aliphys 👍 

This issue is related to the https://github.com/eclipse-theia/theia/issues/11151 upstream defect. We have a pending fix for the problem, but it will be available after the next IDE2 release: https://github.com/arduino/arduino-ide/pull/1994.

Please check if you can fix the problem locally. I am going to provide the steps:

 - Start IDE2,
 - When the window has loaded, please press <kbd>Ctrl/⌘</kbd>+<kbd>Alt</kbd>+<kbd>I</kbd>,
 - The right-hand side of the window the developer tools opens,
 - If you do not see the _Console_, press <kbd>Esc</kbd>,
 - Type the following into the console `indexedDB.deleteDatabase('theia-monaco')` and press <kbd>Enter</kbd>.
 - Restart IDE2.


https://user-images.githubusercontent.com/1405703/231210029-43aa791e-71b6-40e4-8813-c36bd4625496.mp4

Thank you!

**Comment by aliphys** [comment]
Following the same steps on the nightly build, also does not fix the contrast.
![image](https://user-images.githubusercontent.com/75624145/231290763-462b7b16-d2e7-4bf6-9be2-dcfa4b92b9a6.png)
Hope you have fun working on  https://github.com/arduino/arduino-ide/pull/1994 :smiley: Do let me know if I can provide additional information from my side @kittaakos

**Comment by aliphys** [comment]
Here you go!
[arduino-IDE folder.zip](https://github.com/arduino/arduino-ide/files/11208604/arduino-IDE.folder.zip)

Both the `arduino-ide` and `Arduino IDE` folders are included in the zip file.
![image](https://user-images.githubusercontent.com/75624145/231389637-8f739615-d6bf-450a-b4f7-467fe523c444.png)

**Comment by kittaakos** [comment]
> I followed your steps, did not see any changes locally

Strange. It worked for me.


https://user-images.githubusercontent.com/1405703/231461245-8a298300-ac37-4206-8dad-9e8bf7ccc15e.mp4

@aliphys, could you please double-check you have executed the command in the _Console_ without any typos?

**Comment by aliphys** [comment]
I entered exactly this command into the console:
> indexedDB.deleteDatabase('theia-monaco')
![image](https://user-images.githubusercontent.com/75624145/231463437-2ddc54d3-cef3-4dce-b50f-aa7a810efc03.png)

**Comment by aliphys** [comment]
The themes included in IDE 2.1.0, do not have the problem stated in this issues anymore.
- Light
    - ![image](https://user-images.githubusercontent.com/75624145/234924611-4972639d-7562-411a-b5d3-aa4dd4b4f622.png)
- Dark
    -  ![image](https://user-images.githubusercontent.com/75624145/234924461-b02a85cb-2392-4721-9129-d2005cb15015.png)
- High Contrast
    - ![image](https://user-images.githubusercontent.com/75624145/234924228-6359574c-83a3-47d3-aab4-2317fbea227a.png)


Marking issue as completed! Thanks @kittaakos :tada:
