### ISSUE TITLE
Highlight board family group in Tools > Board menu

### ISSUE THREAD

**Issue by ubidefeo** [arduino/arduino-ide#2035]
### Describe the request

When multiple platforms are installed, it is nearly impossible to identify, at a glance, which family the currently selected board belongs to.
The menu item in which to find the board we're using should be selected or highlighted.
I would expect it to be easily identifiable in some way

<img width="391" alt="CleanShot 2023-04-28 at 08 01 24@2x" src="https://user-images.githubusercontent.com/1894487/235067712-bc1f9c28-e328-4b67-84f5-65f694601d5c.png">

### Describe the current behavior

<img width="434" alt="CleanShot 2023-04-28 at 08 01 24@2x" src="https://user-images.githubusercontent.com/1894487/235067238-0a05c357-b987-4145-8d43-af1f3e83b000.png">
<img width="520" alt="CleanShot 2023-04-28 at 08 01 34@2x" src="https://user-images.githubusercontent.com/1894487/235067249-d8bc922d-25c2-47f1-abde-0c573298e6f4.png">

### Arduino IDE version

2.x

### Operating system

N/A

### Operating system version

n/a

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My request contains all necessary details

**Comment by per1234** [comment]
Closing as fixed by https://github.com/arduino/arduino-ide/pull/2165
 
![image](https://github.com/arduino/arduino-ide/assets/8572152/bd97015a-0692-46eb-ab84-1e443816396a)
