### ISSUE TITLE
Add the OPEN DIRECTORY menu item to the FILE menu

### ISSUE THREAD

**Issue by korenevskiy** [arduino/arduino-ide#2041]
### Describe the problem

I regard this introduction as the presence of an error. Since such a function should be the default for script code editors.

### To reproduce

I regard this introduction as the presence of an error. Since such a function should be the default for script code editors.

### Expected behavior

![image](https://user-images.githubusercontent.com/6898474/235867287-2b438321-3dfd-470b-9983-9f9a73d46260.png)

### Arduino IDE version

2.1

### Operating system

Windows

### Operating system version

Windows 11

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @korenevskiy. Thanks for your suggestion. Arduino IDE is a tool for development of Arduino sketches. The sketch is the unit the IDE works with.

Although the ability to open a directory can be useful for a general purpose code editor, it is not a capability that is needed for this application specific tool.

**Comment by korenevskiy** [comment]
> Hi @korenevskiy. Thanks for your suggestion. Arduino IDE is a tool for development of Arduino sketches. The sketch is the unit the IDE works with.
> 
> Although the ability to open a directory can be useful for a general purpose code editor, it is not a capability that is needed for this application specific tool.

Any sketch code is a project folder. The code editor automatically creates a parent folder with the same name when saving the file. The user also needs to add libraries to the project, which they download on forums and instructions. Please describe how people can add libraries to a project?

**Comment by per1234** [comment]
>Any sketch code is a project folder

Correct, and the existing **File > Open Sketch** menu item already opens the sketch folder in the IDE. So a **File > Open Directory** menu item would be redundant.

>The user also needs to add libraries to the project

You can learn how to install libraries from these tutorials:

- https://docs.arduino.cc/software/ide-v2/tutorials/ide-v2-installing-a-library
- https://docs.arduino.cc/software/ide-v1/tutorials/installing-libraries#importing-a-zip-library

If you have any questions about installing libraries, feel free to ask over on Arduino Forum:

https://forum.arduino.cc/
