### ISSUE TITLE
Save fails silently when sketch out of sync with file system

### ISSUE THREAD

**Issue by per1234** [arduino/arduino-ide#2051]
### Describe the problem

When the "**Auto save**" preference is disabled, any changes to a sketch made in the Arduino IDE editor are "staged" in memory until the user manually saves the sketch. The sketch file can be modified externally during that time. These conditions pose a danger of user data being lost when the sketch is saved.

When the user attempts to save the sketch under these conditions Arduino IDE detects the out of sync state and displays a dialog notifying the user of the situation and asking how to proceed:

![image](https://user-images.githubusercontent.com/8572152/236776198-0cf5974b-851a-46d5-b61a-bb8a152d0a15.png)

🐛 If the user clicks the "**YES**" button in the dialog to indicate they wish to write the version of the sketch from the editor to disk, the write does not occur contrary to the user's directive.

### To reproduce

1. Select **File > New Sketch** from the Arduino IDE menus.
1. Select **File > Save As...** from the Arduino IDE menus.
1. Save the sketch with the name "**UnsyncedSketch**".
1. Select **File > Preferences** from the Arduino IDE menus.
1. Uncheck the box next to "**`☑` Auto save**"
1. Click the <kbd>**OK**</kbd> button.
1. Make an identifiable change to the sketch:
   ```cpp
   // change made in IDE
   ```
   ❗ Do not save the sketch.
1. Open `UnsyncedSketch/UnsyncedSketch.ino` in a text editor.
1. Make an identifiable change to the sketch:
   ```cpp
   // change made externally
   ```
1. Save the file in the text editor.
1. Select **File > Save** from the Arduino IDE menus.
   The "**The file 'UnsyncedSketch.ino' has been changed on the file system.**" dialog opens.
1. Click the <kbd>**YES**</kbd> button in the dialog.

🐛 The change made in the IDE editor is not saved to disk.
🐛 There is no indication to the user that their data was not saved other than the **⬤** ("dirty" state indicator) remaining on the sketch tab.

### Expected behavior

When the user directs Arduino IDE to write the sketch to disk, it does so.

### Arduino IDE version

964ea3bc0cb51c87592757ca7b8b73002c475033

### Operating system

Windows

### Operating system version

11

### Additional context

I bisected the regression to e4beb03 (does not occur with the build of the previous commit dafb245).

---

Nothing is printed to the logs when the save fails.

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by kittaakos** [comment]
> I bisected the regression to [e4beb03](https://github.com/arduino/arduino-ide/commit/e4beb03a404b6f6f7ecfad3a7d3b9ea24476632c) (does not occur with the build of the previous commit [dafb245](https://github.com/arduino/arduino-ide/commit/dafb2454fd3133e229d0081a2b6788f88ac39e95)).

I think this is the breaking change https://github.com/arduino/arduino-ide/commit/39ab836880ce7a958ce1d61e43e7e3e75120d3fc, and not https://github.com/arduino/arduino-ide/commit/dafb2454fd3133e229d0081a2b6788f88ac39e95.

<img width="1234" alt="Screen Shot 2023-05-09 at 11 00 21" src="https://user-images.githubusercontent.com/1405703/237047670-2f5bb618-d9cd-4c1e-b81d-9e32e8658400.png">
