### ISSUE TITLE
Remove useless notification window

### ISSUE THREAD

**Issue by Franck78** [arduino/arduino-ide#2057]
### Describe the request

![ide21](https://github.com/arduino/arduino-ide/assets/1778884/b4899990-960d-4220-b2d0-92e94f97f7fb)

Particularly when when 'show verbose output options are activated

Please add an option to fully disable this notification window.
Or use it for serious stuff (update available, board manager problem, etc etc)
But not repetitive useless notifications !

### Describe the current behavior

By itself this windows is annoying. Not moveable, not nothing.

### Arduino IDE version

2.1

### Operating system

Linux

### Operating system version

x

### Additional context

related

long lines need to to wrap, useless message

https://github.com/arduino/arduino-ide/issues/1486
https://github.com/arduino/arduino-ide/issues/1464

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My request contains all necessary details

**Comment by per1234** [comment]
Hi @Franck78. Thanks for taking the time to submit an issue.

>Please add an option to fully disable this notification window.

You'll be glad to know an option is already in place to control this. It is in the [advanced settings](https://github.com/arduino/arduino-ide/blob/main/docs/advanced-usage.md#advanced-settings). I'll provide instructions for disabling it:

1. Press the <kbd>**Ctrl**</kbd>+<kbd>**Shift**</kbd>+<kbd>**P**</kbd> keyboard shortcut (<kbd>**Command**</kbd>+<kbd>**Shift**</kbd>+<kbd>**P**</kbd> for macOS users) to open the "Command Palette".
   A menu will appear on the editor toolbar:
   ![image|440x112](upload://uEkJ7cHNKHKo2lWMcYt1xeqjgoW.png)
1. Select the "**Preferences: Open Settings (UI)**" command from the menu.
   **ⓘ** You can scroll down through the list of commands to find it or type the name in the field.
   A "**Preferences**" tab will open in the Arduino IDE main panel.
1. Type `workbench.silentNotifications` in the "**Search Settings**" field of the "**Preferences**" tab.
1. Check the box under the "**Workbench: Silent Notifications**" setting.
1. Close the **Preferences** tab by clicking its **X** icon.
