### ISSUE TITLE
add git & github 

### ISSUE THREAD

**Issue by ibrahelsheikh** [arduino/arduino-ide#2058]
### Describe the request

Adding Git and GitHub to an Arduino project can be extremely beneficial. Git is a version control system that allows for easy tracking of code changes over time, making it easier to revert to previous versions of the code if necessary. GitHub, a web-based platform, allows for code hosting and collaboration tools such as pull requests and code reviews. 

By using Git and GitHub, team members can easily collaborate and share their code with others, making the development process more efficient. It also adds a level of professionalism to the project, making it more attractive to potential contributors. 

Overall, using Git and GitHub in an Arduino project can help streamline development, improve collaboration, and demonstrate a commitment to maintaining the project over time.

### Describe the current behavior

Before Git and GitHub, managing changes in an Arduino project could be a challenging and time-consuming process. Without version control, team members may have had to rely on manual backups or separate copies of the code to keep track of changes. This process can be prone to errors and make it difficult to collaborate on the project.

Additionally, sharing and collaborating on code can be a hassle without a web-based platform like GitHub. Code may need to be shared via email or file-sharing services, making it challenging to manage multiple changes and keep track of who has made what changes. Overall, without Git and GitHub, managing changes and collaborating on an Arduino project can be a disjointed and inefficient process.

### Arduino IDE version

latest version

### Operating system

Windows

### Operating system version

Any

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My request contains all necessary details

**Comment by per1234** [comment]
Hi @ibrahelsheikh. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/1880.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
