### ISSUE TITLE
IDE 2.0: Selecting/changing a board is a pain

### ISSUE THREAD

**Issue by rs0xFFFF** [arduino/arduino-ide#2070]
### Describe the problem

Selecting/changing a board via the Tools->Board:... menu is 5x faster than via the combo box on the toolbar. The board and port settings are always lost. You have to spend a lot of time looking for the board every time.

### To reproduce

n/a

### Expected behavior

Provide a combobox with drop down list (history list) of last used boards inclusive ports.

### Arduino IDE version

2.0.4

### Operating system

Windows

### Operating system version

Win10

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @rs0xFFFF. Thanks for your suggestion. I see we have previous feature requests about this here:

- https://github.com/arduino/arduino-ide/issues/86
- https://github.com/arduino/arduino-ide/issues/330
- https://github.com/arduino/arduino-ide/issues/1953

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the others.

If you end up with additional information to share, feel free to comment in the relevant previous thread.
