### ISSUE TITLE
serial monitor stuck in bottom of code window

### ISSUE THREAD

**Issue by gitcnd** [arduino/arduino-ide#2075]
### Describe the problem

the other bug report for this same issue got force-closed due to "heatedness".

I'm reporting it again now, because that "heat" is a critical indicator of just how many people are angry that the serial monitor got moved from a window to a fixed panel.  Crazy new features like this should not be introduced in a way the prevents the original superior implementation from still working!

### To reproduce

open monitor

### Expected behavior

new window

### Arduino IDE version

2.1.0

### Operating system

Windows

### Operating system version

11 pro

### Additional context

Fixing this should be a top priority

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by kittaakos** [comment]
Thanks for letting us know.

> the serial monitor got moved from a window to a fixed panel


> ### To reproduce
> open monitor
> 
> ### Expected behavior
> new window

It looks like we have an existing bug report for this problem. https://github.com/arduino/arduino-ide/issues/289.

We prefer tracking one issue per topic. I will close your issue as a duplicate. If you have any helpful remarks, please add them to the existing thread. Thank you!
