### ISSUE TITLE
macOS Apple Silicon (arm64) release is missing from GitHub

### ISSUE THREAD

**Issue by HelgeSeidel** [arduino/arduino-ide#2124]
### Describe the problem

The latest release V2.1.1 doesn't contain a build for Apple Silicion (arm64). Same as #2044.

### To reproduce

https://github.com/arduino/arduino-ide/releases/tag/2.1.1 < missing arm64
https://github.com/arduino/arduino-ide/releases/tag/2.1.0 < has arm64

### Expected behavior

When a new release is made also include the arm64 version.

### Arduino IDE version

2.1.1

### Operating system

macOS

### Operating system version

13.4.1

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by HelgeSeidel** [comment]
@kittaakos , @per1234 2.1.1 for Apple Silicon (arm64) is available on GitHub, but the IDE can't find any update.

Error message: There are no recent updates available for the Arduino IDE

**Comment by kittaakos** [comment]
> but the IDE can't find any update.

Thanks for getting back to us. This is expected for now. Unfortunately, building the artifacts for the release has become more complicated as we need to build Linux on 18.04 Ubuntu which GH Actions do not support, plus we have to build an M1 for macOS, which is also not supported by GH Actions.

Please bear with us.

**Comment by kittaakos** [comment]
> is available on GitHub, but the IDE can't find any update.

This should be fixed now. If there is a problem, please ping me. Thank you!
