### ISSUE TITLE
Version 2.1.1 breaking lib compatibility

### ISSUE THREAD

**Issue by willie68** [arduino/arduino-ide#2141]
### Describe the problem

After installing Arduino IDE 2.1.1 (I was previously using the last 2.0) after startup, the ide tells me that there are lib to update.
But the IDE can't update the libs because the Library Manager doesn't know his old lib format on updating. All the things with folder renaming on update now confuses the lib manager.  

![ard_01](https://github.com/arduino/arduino-ide/assets/5518382/f3a4f0f2-7db1-464d-9be9-eb40e5a1b351)

### To reproduce

Just work something with an old IDE, adding some libs (in may case there are 208 folders in the libraries folder, but just round about 100 libs. 106 folders are updates from the libs. 

### Expected behavior

Simply read the libs and do the update rightly.

### Arduino IDE version

2.1.1

### Operating system

Windows

### Operating system version

win 11

### Additional context

I'm working with 1.8.x and 2.1.x in parallel... because the 2.1.x is incredible slow. Startup is about 4:30 min, without an life sign.

---

If you like I can provide my lib folder.

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
As the error message explains, there is no way for Arduino IDE to know how to correctly perform an update when you have multiple copies of the same library installed. So the update being canceled with this error message is the intended and correct behavior under these conditions. There is a detailed explanation of why this is the only correct behavior here:

https://github.com/arduino/arduino-cli/issues/1871

Please follow the instructions from the error message and delete the superfluous library installations.
