### ISSUE TITLE
compiling sketch without selecting a board yields non helpful error report.

### ISSUE THREAD

**Issue by butchalline** [arduino/arduino-ide#215]
This will trip up noobs.  

![image](https://user-images.githubusercontent.com/2797036/111053446-d367ef00-8431-11eb-87e4-c938a2b05283.png)

More helpful would be:  Please select a board before compiling.

**Comment by ubidefeo** [comment]
@butchalline 
we're reworking the whole error messages thing, this is now up for resolution soon :)
