### ISSUE TITLE
int8_t, int16t and int32_t are 32bit

### ISSUE THREAD

**Issue by cnyrr** [arduino/arduino-ide#2150]
### Describe the problem

sizeof() reports correct sizes (1, 2, 4). When you try to use them they are all 32 bit values.

### To reproduce

```
int8_t x = -1;
int16_t y = -1;
int32_t z = 100000000000;


Serial.println("int8_t x = -1");
Serial.println(sizeof(int8_t));
Serial.println(x, HEX);
Serial.println(x - 1, HEX);

Serial.println("int16_t y = -1");
Serial.println(sizeof(int16_t));
Serial.println(y, HEX);
Serial.println(y - 9999, HEX);

Serial.println("int32_t z = -1");
Serial.println(sizeof(int32_t));
Serial.println(z, HEX);
Serial.println(z - 10000000000, HEX);
```
Console Output:

```
02:35:56.491 -> For int8_t x = -1
02:35:56.534 -> 1
02:35:56.534 -> FFFFFFFF
02:35:56.534 -> FFFFFFFE
02:35:56.566 -> For int16_t y = -1
02:35:56.566 -> 2
02:35:56.566 -> FFFFFFFF
02:35:56.598 -> FFFFD8F0
02:35:56.598 -> For int32_t z = -1
02:35:56.646 -> 4
02:35:56.646 -> FFFFFFFF
02:35:56.646 -> 4876E800
```

### Expected behavior

Providing exactly 8/16/32 bit integers.

### Arduino IDE version

2.1.1

### Operating system

Windows

### Operating system version

Windows 10 22H2

### Additional context

Using original Arduino Nano.

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by kittaakos** [comment]
Thanks for taking the time and filing the bug report. I need to investigate if this issue is the same as https://github.com/arduino/arduino-ide/issues/80.

**Comment by per1234** [comment]
Hi @cnyrr. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
