### ISSUE TITLE
Arduino IDE, when "installed" from a portable zip file, asks to update and installs... somewhere random

### ISSUE THREAD

**Issue by trollcop** [arduino/arduino-ide#2154]
### Describe the problem

Basically the title.

Windows, arduino 2.0.4 installed from zip to f:\arduino (for example), will popup a "update" dialog on startup, download and install 2.1.1 somewhere unknown.

### To reproduce

1. install 2.0.4
2. run
3. allow to update to 2.1.1
4. ???

### Expected behavior

Update 2.0.4 installation to 2.1.1

### Arduino IDE version

2.0.4

### Operating system

Windows

### Operating system version

10

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by kittaakos** [comment]
Thanks for taking the time and filing the bug report.

> Windows, arduino 2.0.4 installed from zip

> will popup a "update" dialog on startup

> install 2.1.1 somewhere unknown.

No matter how you installed IDE2 (zip or NSIS) on Windows, the auto-updater will always be NSIS: https://www.electron.build/auto-update.html#auto-updatable-targets. It's not a bug.

We are aware of inconsistencies between the installation paths on Windows: https://github.com/arduino/arduino-ide/issues/879.

As described at https://github.com/arduino/arduino-ide/issues/879#issue-1158328623, the installation path is, unlike you state, not random:

> **Windows MSI installer**	Windows Installer	`%LOCALAPPDATA%\Programs\arduino-ide`
> (e.g., `C:\Users\per\AppData\Local\Programs\arduino-ide`)
> **Windows MSI installer**	Windows Installer
> (`ALLUSERS=1`)	`%PROGRAMFILES%\arduino-ide`
> (e.g., `C:\Program Files\arduino-ide`)


We prefer keeping one open GitHub issue for the same topic. If you have more details, please comment on the open issue. I appreciate your understanding.
