### ISSUE TITLE
breaks old items.

### ISSUE THREAD

**Issue by Tom-Neverwinter** [arduino/arduino-ide#2159]
### Describe the problem

breaks code. https://github.com/rbalboa8/ProtonPack

nuisance upgrade.

### To reproduce

compile.

### Expected behavior

compile.

### Arduino IDE version

latest.

### Operating system

Windows

### Operating system version

10

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @Tom-Neverwinter. Thanks for your interest in this open source project. This issue tracker is only to be used to submit high quality structured formal bug reports. You have not made even close to the effort we expect from those who submit issues here.

Please submit a report over on Arduino Forum. We'll attempt to squeeze the necessary information out of you over there:

https://forum.arduino.cc/
