### ISSUE TITLE
ESP32 S2 I2C Bus speed changes unexpectedly from 400KHz to 5KHz

### ISSUE THREAD

**Issue by tchilton** [arduino/arduino-ide#2161]
### Describe the problem

On an ESP32 S2 device, when attempting to write to an I2C device via the Wire library to a device which is not currently present on the bus, after 10 such transactions, the bus speed changes unexpectedly from the configured 400KHz to 5KHz. It does not matter if the 10 transactions are sequential to each other, or interspersed with other valid I2C traffic.

Additionally, 5KHz is not a standard I2C bus speed and its also far too slow for any effective communications

### To reproduce

1. Configure IDE for ESP32 S2 device
2. Write sample code to perform Wire transactions against a non-existent device address. Repeat this for several test cycles. See attached sample sketch
[i2cBus_bug.txt](https://github.com/arduino/arduino-ide/files/12241010/i2cBus_bug.txt)

3. Observe bus speed change unexpectedly from 400KHz to 5KHz using a logic analyser or digital scope after 10 successful I2C transfers at the expected speed
[I2C Bus Defect Saelae Capture.txt](https://github.com/arduino/arduino-ide/files/12241164/I2C.Bus.Defect.Saelae.Capture.txt)
Rename this file to a .sal file and open in Saelae logic 2 software (https://www.saleae.com/downloads/) . Problem is visible from 12ms into the capture

4. Optionally change target board and prove expected bus protocol on other chips
5. Optionally, to see the work-around, un-comment the two lines 76 and 77 to change the bus speed 

Problem likely to be in Arduino wire library for ESP32 S2 or in Espressif ESP32 S2 code.

### Expected behavior

The I2C bus should remain at the configure bus speed set via Wire.setClock() for all I2C transactions. 

### Arduino IDE version

2.1.1

### Operating system

Windows

### Operating system version

10 22H2

### Additional context

Once the bus speed has changed, requests to change the bus speed to 400KHz have no impact, thus bus continues to operate at 5KHz. However, changing the bus speed to another value such as 1MHz and then back to 400KHz results in the bus operating correctly again.

This is specific to ESP32 S2 and the same code has been run on both ESP32 DevKit v1 and AtMega 2560, both of which operate as expected.

The reason for wanting to talk to non-present devices are that they are are on optional add-on boards within my design and may or may not be present at bootup, or during operation. I2C device presence can be determined during I2C transactions, since a present device will ACK a successful transfer, whereas a missing device has no impact on the bus, hence the I2C master will not see any ACK signal, resulting in a NACK on the bus transfer.

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @tchilton . Thanks for your interest in this open source project. Arduino IDE doesn't have anything to do with setting the I2C bus speed so this report is off-topic for this repository.

>Problem likely to be in Arduino wire library for ESP32 S2 or in Espressif ESP32 S2 code

Then you need to report the problem to the repository where that codebase is hosted. The ESP32 code is not maintained by Arduino.

If you would like to discuss the problem with the Arduino community, you are welcome to post on the Arduino Forum:

https://forum.arduino.cc/
