### ISSUE TITLE
Add ANSI code support in serial monitor

### ISSUE THREAD

**Issue by tchilton** [arduino/arduino-ide#2169]
### Describe the request

The IDE, like many other development environments and applications, uses colour, reverse video text, flashing text and screen control (position, clear screen, etc) all of which, when used appropriately aids readability.

However, this capability is not extended to the serial monitor, meaning that sketches can't use these commonly available features. 

The request is to add support for ANSI codes, thus allowing the screen to be manipulated more effectively with colour, cursor manipulation, screen clear, flashing text, etc.  This allows for error conditions to be more readable in output text for example.

ANSI codes are defined here : [https://en.wikipedia.org/wiki/ANSI_escape_code](ANSI Codes)

### Describe the current behavior

The terminal does not respond to ANSI codes and simply prints them out. Competing serial monitoring tools such as PuTTY and minicom correctly respond to such codes.

### Arduino IDE version

2.1.1

### Operating system

Windows

### Operating system version

10 22H2

### Additional context

Addition of this feature would provide consistency on the use of colour in the main code and debug output windows and allow greater control from sketches for improved formatting and visualisation of sketch output.

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My request contains all necessary details

**Comment by kittaakos** [comment]
Thank you for the feature request.

This has already been requested: https://github.com/arduino/arduino-ide/issues/1726. Also here: https://github.com/arduino/arduino-ide/issues/1991. There is an on-hold PR supporting a subset of the ANSI codes. See why it's on hold: https://github.com/arduino/arduino-ide/pull/1992#issuecomment-1621354466.

We prefer keeping one open GitHub issue for the same bug/feature request. I close this one as a duplicate. If you have any more details, please comment on the open issues.

I appreciate your understanding!
