### ISSUE TITLE
Stuck in debug after upload to ESP32

### ISSUE THREAD

**Issue by wyzarddoc** [arduino/arduino-ide#2171]
### Describe the problem

copied full code at
 mqtt https://www.emqx.com/en/blog/esp32-connects-to-the-free-public-mqtt-broker#getting-started-with-mqtt-on-esp32
into new arduino 2.1.1 new file.
checked and loaded file to esp32
seemed to upload
tried to change print statement message and upload
UI went into debug mode and I can't get it out to load new program into esp32

### To reproduce

see above

### Expected behavior

on and off button for debug

### Arduino IDE version

2.1.1

### Operating system

Linux

### Operating system version

ubuntu 20.04

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @wyzarddoc. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/c/software/ide-2-x/93
