### ISSUE TITLE
Assembly language file extension has the wrong case

### ISSUE THREAD

**Issue by per1234** [arduino/arduino-ide#218]
**Describe the bug**
The Arduino build system requires assembly language files to use the `.S` file extension but the "New Tab" dialog only allows `.s`. Files using the `.s` extension are not compiled.

**To Reproduce**

1. Click the downward pointing triangle button on the right side of the tab bar.
2. Click "New Tab"
2. In the "Name for new file" dialog, type "Foo.S". - ".S is not a valid file extension." is shown and the "OK" button is disabled.

**Expected behavior**
The `.S` file extension to be allowed and the `.s` extension prohibited by the "New Tab" and  "Rename" dialogs of the tab control menu.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 2.0.0-beta.3-nightly.20210313
Date: 2021-03-13T03:11:23.309Z
CLI Version: 0.16.1 alpha [76f55490]

**Additional context**
Reference from the Arduino Sketch Specification: https://arduino.github.io/arduino-cli/latest/sketch-specification/#additional-code-files

I believe the relevant code is here:
https://github.com/arduino/arduino-ide/blob/eadc9938547fdc42308d279b109f89c50474e6aa/arduino-ide-extension/src/common/protocol/sketches-service.ts#L89-L90

**Comment by kittaakos** [comment]
Monkey see monkey do 😊 Thanks for bringing this up.

Let's check if we have to adjust anything in the CLI:
 - https://github.com/arduino/arduino-cli/blob/414ab001a235c213f96e00f185f082783118e109/arduino/globals/globals.go#L38
 - https://github.com/arduino/arduino-cli/blob/414ab001a235c213f96e00f185f082783118e109/arduino/globals/globals.go#L45
 - https://github.com/arduino/arduino-cli/blob/414ab001a235c213f96e00f185f082783118e109/legacy/builder/builder.go#L34-L35
 - https://github.com/arduino/arduino-cli/blob/414ab001a235c213f96e00f185f082783118e109/legacy/builder/create_cmake_rule.go#L35
