### ISSUE TITLE
Non English Characters in OpenOCD Filenames

### ISSUE THREAD

**Issue by marcusobrien** [arduino/arduino-ide#2180]
### Describe the problem

I have an error when uploading to some devices that always complains about openocd. I decided to check for some other files today, and I noticed that 2 of the files in this arduino openocd folder can't even be correctly detected by Windows 10...

C:\Users\marcu>findstr /i /p /s sonic *
FINDSTR: Cannot open .arduino-create\arduino\openocd\0.11.0-arduino2\share\openocd\scripts\target\1986??1?.cfg
FINDSTR: Cannot open .arduino-create\arduino\openocd\0.11.0-arduino2\share\openocd\scripts\target\?1879x?1?.cfg

It says it can't find these but the files are there, just witrh non english characters in the filenames

![image](https://github.com/arduino/arduino-ide/assets/3989070/437824c5-cf42-49f5-8ee9-984394a398e0)

The filenames have what looks like Russian characters.

Anyway Windows 10 does not handle this well, so I presume its a bug. 

And BTW I have never set my language, keyboard, location, timezone etc to Russian.

### To reproduce

Clean install, I did install the Arduino Nicla Voice board into Arduino 2.1.

Version: 2.1.1
Date: 2023-06-30T16:04:40.277Z (1 month ago)
CLI Version: 0.32.3

Copyright © 2023 Arduino SA

### Expected behavior

Should not corrupt my file system.

### Arduino IDE version

2.1.1

### Operating system

Windows

### Operating system version

10

### Additional context

I tried this on Nightly build with a clean install and its still there, as maybe the fiels come from the baord management plugin ? Where ever they come from, the main Application should verify the files before copying them on to the system, so I believe the fault lies with the main IDE.

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @marcusobrien. The presence of these files is normal, expected, and intended:

```text
C:\Users\marcu\.arduino-create\arduino\openocd\0.11.0-arduino2\share\openocd\scripts\target\1986ве1т.cfg
```

```text
C:\Users\marcu\.arduino-create\arduino\openocd\0.11.0-arduino2\share\openocd\scripts\target\к1879xб1я.cfg
```

The file system used by Windows (including Windows 10) [has full support for these characters](https://learn.microsoft.com/en-ca/windows/win32/fileio/naming-a-file#naming-conventions:~:text=Use%20any%20character%20in%20the%20current%20code%20page) and the OpenOCD developers intentionally added these files to the tool distribution:

- https://sourceforge.net/p/openocd/code/ci/v0.11.0/tree/tcl/target/1986%D0%B2%D0%B51%D1%82.cfg
- https://sourceforge.net/p/openocd/code/ci/v0.11.0/tree/tcl/target/%D0%BA1879x%D0%B11%D1%8F.cfg

This is the classic case of a "red herring", where you are experiencing some unspecified problem:

> I have an error when uploading to some devices that always complains about openocd

Then got focused on these file names, which are surely completely unrelated to your problem.

This issue tracker is only to be used to report bugs or feature requests specific to the Arduino IDE project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/

Please make sure to provide a detailed description of the actual problem you are having when you make your request on Arduino Forum. This should include:

- Complete Instructions the helpers can follow to reproduce the problem
- The full and exact text of any error or warning messages you are encountering
