### ISSUE TITLE
Missing translations in Turkish language

### ISSUE THREAD

**Issue by metehoca** [arduino/arduino-ide#2201]
### Describe the problem

After updating to 2.2.0 from 2.1.1, some menu translations are turned English.

I'm the Turkish translator of IDE 2.0, and can confirm all translations done.

### To reproduce

Change language to Turkish, check English words on all over the IDE.

### Expected behavior

All menus and windows must be in Turkish.

### Arduino IDE version

2.2.0

### Operating system

Windows

### Operating system version

Windows 10

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by antalpeter** [comment]
ok
