### ISSUE TITLE
Previous selection remains in Firmware Updater and Certificate Uploader menu after no longer available

### ISSUE THREAD

**Issue by per1234** [arduino/arduino-ide#2222]
### Describe the problem

Arduino IDE's ["**Firmware Updater**"](https://docs.arduino.cc/software/ide-v2/tutorials/ide-v2-fw-cert-uploader#firmware-updater) and ["**Upload SSL Root Certificates**"](https://docs.arduino.cc/software/ide-v2/tutorials/ide-v2-fw-cert-uploader#certificates-uploader) features allow the user to update the supplemental modules found on some Arduino boards.

The "**Select Board**" menu in these dialogs lists all the discovered board+ports of boards supported by the feature, from which the user can select the intended target.

🐛 Once the user has selected an item from the menu, it will remain selected even after that board+port is no longer available. This might cause confusion for the users.

#### Equipment

- Any board that is supported by the Arduino Firmware Uploader:
  - [**Nano 33 IoT**](https://docs.arduino.cc/hardware/nano-33-iot)
  - [**MKR WiFi 1010**](https://docs.arduino.cc/hardware/mkr-wifi-1010)
  - [**UNO R4 WiFi**](https://docs.arduino.cc/hardware/uno-r4-wifi)

#### Steps

1. Select **Tools > Firmware Updater** from the Arduino IDE menus.
1. If it is not already connected, connect the board to your computer with a USB cable.
1. Expand the "**Select Board**" menu.
   🙂 All connected supported board+ports are listed in the menu.
1. Unplug the USB cable of the board from your computer.
   🙂 The board+port that was disconnected from the computer is no longer listed in the menu.
1. Connect the board to your computer with a USB cable.
1. Select the board+port from the "**Select Board**" menu.
1. Unplug the USB cable of the board from your computer.
   🐛 The board+port is still shown as selected in the menu.
1. Click the **X** icon at the top right corner of the **Firmware Updater** dialog.
1. Select **Tools > Firmware Updater** from the Arduino IDE menus.
   🐛 The previously selected board+port is still shown as selected in the menu even though it is no longer connected to the computer.

### Expected behavior

The menu goes back to the "**Select a board...**" state if the previously selected board+port is no longer discovered.

### Arduino IDE version

2.2.1

### Operating system

Windows

### Operating system version

11

### Additional context

I bisected the regression to 69ae38e (does not occur with the build from the previous commit 9a6a457bc44fb16f646b9e61a9e8b336b3666412).

---

I used the "**Firmware Updater**" feature in the demonstration above, but the behavior is the same in "**Upload SSL Root Certificates**" as well.

---

An example of when this might cause confusion is when updating the firmware or uploading certificates to the **UNO R4 WiFi** board. After the process is completed, the board is left in a state where it is no longer discovered as a supported board and can not be used with these features until it has been power cycled (a requirement which is currently not communicated to the user: https://github.com/arduino/arduino-ide/issues/2220). The user might be misled by the presence of the board in the menu into thinking the board was still available for subsequent firmware updates or certificate uploads.

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by CreativeRobotics** [comment]
This sounds like an issue I had with board definitions as well. I have a branch of the Mattairtech SAMD boards installed in sketchbook->hardware.
After I had added a new variant and loaded it into the IDE I made some alterations to that variant, one being a change to the names in a menu list for that new variant. When I reloaded the IDE the old menu names were still there and the board was unuseable because the IDE threw up an error about not being able to find that item.
It looks like the IDE is chaching some parts of the board variant items and saving them to the file system, then ignoring the variants if they have already been cached.
The only work around was to cut all the text for that variant from the variants.h file, restart Arduino, close it again and paste back the text.
