### ISSUE TITLE
No indication for an unsaved sketch

### ISSUE THREAD

**Issue by shobeira** [arduino/arduino-ide#2223]
### Describe the problem

In the IDE 2.2.1, there is no indication whether the sketch file is saved already or there is/are unsaved changes that is needed to be saved. The indication was there in IDE v2.1.1

### To reproduce

No need.

### Expected behavior

An indicator next to the sketch file name to show if there is/are unsaved change(s).

### Arduino IDE version

2.2.1

### Operating system

Linux

### Operating system version

22.04

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @shobeira. Thanks for your report.

> An indicator next to the sketch file name

Are you referring to this indicator?:

![image](https://github.com/arduino/arduino-ide/assets/8572152/e48f7953-a6a4-40cf-8ef0-028a8494f869)

Do you have "**Auto save**" enabled in your Arduino IDE preferences?

Which theme do you have selected from the "**Theme**" menu in your Arduino IDE preferences?

**Comment by shobeira** [comment]
Hi @per1234,

I realised it after I submitted the issue. Yea, the auto save is enabled and that explained everything. Maybe a grayed out "autosave" next to the filename would be a good idea though.
