### ISSUE TITLE
themeable menu bar

### ISSUE THREAD

**Issue by BPplays** [arduino/arduino-ide#2229]
### Describe the request

the menu bar looks somewhat out of place if your theme's backgound differs from pure grey
![](https://cdn.discordapp.com/attachments/783368902255575040/1152760645628993606/Screenshot_2023-09-16_171851.png)

### Describe the current behavior

the menu bar is not effected by your theme

### Arduino IDE version

2.2.1

### Operating system

Windows

### Operating system version

10

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My request contains all necessary details

**Comment by kittaakos** [comment]
Thanks for taking the time to report this to us. The OS renders the menu bar, and we cannot change it. (Previously: https://github.com/arduino/arduino-ide/issues/321)

There is a related issue ([arduino/arduino-ide#1733](https://github.com/arduino/arduino-ide/issues/1733)) and a PR ([arduino/arduino-ide#1870](https://github.com/arduino/arduino-ide/pull/1870)) to restore the default `window.titleBarStyle` [Theia IDE](https://theia-ide.org/) behavior in IDE2. Note this is currently supported on Windows and Linux in Theia. See https://github.com/eclipse-theia/theia/pull/10044#issuecomment-1423841453.

I close this issue and move your request to #1733.
