### ISSUE TITLE
IDE 2.0 does not upload for stm32f1   -    IDE 2.0 não faz upload para o stm32f1

### ISSUE THREAD

**Issue by nivatec** [arduino/arduino-ide#224]
instalei a ide 2.0 mas não consigo fazer upload  para o stm32f1 sempre apresenta erro. por favor algem pode me ajudar
I installed ide 2.0 but I can't upload for stm32f1 it always shows an error. please someone can help me

**Comment by nivatec** [comment]
I installed ide 2.0 but I can't upload it always shows an error. please someone can help me

**Comment by BelKed** [comment]
What error?

First you need to select board and pin. Then you can upload...

**Comment by nivatec** [comment]
> What error?
> 
> First you need to select board and pin. Then you can upload...

the error you present is this:
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x000000007110b5db, pid=6692, tid=0x0000000000000598
#
# JRE version: Java(TM) SE Runtime Environment (8.0_281-b09) (build 1.8.0_281-b09)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.281-b09 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [jSSC-2.8_x86_64.dll+0xb5db]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows

**Comment by ubidefeo** [comment]
@nivatec 
the error you report is about Java, the IDE 2.0 does not require Java.
Also please provide detailed information as specified in the issue template.

Operating system
ways to reproduce
versions and so on

thanks
