### ISSUE TITLE
Tooltips when hovering the cursor over procedures and functions are missing, the link jump when pressing the Ctrl key on functions and procedures is missing.

### ISSUE THREAD

**Issue by Dmitry-Chernikov** [arduino/arduino-ide#2244]
### Describe the problem

Tool-tips when hovering the cursor over procedures and functions are missing, the link jump when pressing the Ctrl key on functions and procedures is missing.

### To reproduce

Appeared when installing the new version 2.2.1

### Expected behavior

Should work.

### Arduino IDE version

2.2.1

### Operating system

Linux

### Operating system version

System:   Kernel: 6.2.0-33-generic x86_64 bits: 64 compiler: N/A Desktop: Cinnamon 5.8.4 tk: GTK 3.24.33     wm: muffin dm: LightDM Distro: Linux Mint 21.2 Victoria base: Ubuntu 22.04 jammy

### Additional context

https://dropmefiles.com/zDPRR

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by kittaakos** [comment]
> ### Additional context
> https://dropmefiles.com/zDPRR

Thanks for the detailed report. It's not a bug. You must select a board to enable the [Arduino language features](https://github.com/arduino/arduino-language-server) in IDE2. See the tutorial here: https://docs.arduino.cc/software/ide-v2/tutorials/ide-v2-autocomplete-feature.

After you have opened 2.2.1, no board was selected in your sketch. That's the reason you did not get tooltips and navigation.
