### ISSUE TITLE
Error loading code onto Arduino UNO board

### ISSUE THREAD

**Issue by AntonioBerna** [arduino/arduino-ide#2250]
### Describe the problem

I'm on Linux Manjaro and when I press the button on the IDE to upload the code to the Arduino UNO board I get this error:

```
avrdude: ser_open(): can't open device "/dev/ttyACM0": Permission denied
```

### To reproduce

I'm on Linux Manjaro and when I press the button on the IDE to upload the code to the Arduino UNO board I get this error:

```
avrdude: ser_open(): can't open device "/dev/ttyACM0": Permission denied
```

### Expected behavior

Normally I would expect the code to load onto the card after a few seconds

### Arduino IDE version

2.2.1

### Operating system

Linux

### Operating system version

Manjaro

### Additional context

I tried to fix the problem using the following command:

```
sudo chmod a+rw /dev/ttyACM0
```

except that after a few hours the initial problem returns and I don't feel like running this command every time...

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @AntonioBerna. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
