### ISSUE TITLE
Serial data reception drops characters causing unreliable data communication

### ISSUE THREAD

**Issue by rondlh** [arduino/arduino-ide#2255]
### Describe the problem

I'm not sure if this is the correct place for this issue. The issue is not a direct IDE related issue, it's about the Arduino platform.

Marlin uses the Arduino framework to received serial data with the support of interrupts.
After enabling CRC codes for the Gcodes I send to Marlin, and stressing Marlin (sending more commands) I found that some serial characters are lost once in a while. Adding some debug code did not resolve the issue, the provided uart error code was 0, also no error flags were set (NE, FE, PE).

### To reproduce

Send serial data to the Arduino serial port at a high rate, speed 250K baud or above. (Faster rates cause more problems)
Command length: >35 characters
Command rate > 120 commands per second (faster rates cause more problems)
Check if the commands are received correctly.
I never saw any data corruption, the problem is always that a character is not received.
At 115200 baud the problem is less frequent, but still occurs.

I found that reading the serial data with DMA solves the problem completely!

### Expected behavior

Receive the data correctly, no missing characters.

### Arduino IDE version

2.2.1

### Operating system

Windows

### Operating system version

Windows 10 Enterprise

### Additional context

Hardware used for receiving the data: STM32F407 (MKS Monster 8 V1.0) running Marlin.
Hardware used for sending the data: BTT TFT35 V3.0 (STM32F207)

I monitored the data received by the STM32F407 with an additional serial port I put in parallel to the STM32F407 board. There I can see that there is no data corruption and no data loss. The data is send correctly, but not processed correctly by the STM32F407.

**Additionally I programmed an experimental DMA reading algorithm to check if this is more reliable. This proved to be a great solution, and allows for serial rates of 1M baud without having this issue. This makes me think the problem is located in the Arduino platform.**

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @rondlh. Thanks for your interest in this free open source software project.

>reading the serial data with DMA solves the problem completely!

This issue tracker is only used for tracking bug reports and feature requests directly related to the Arduino IDE application code hosted in this repository. As you explained, your excellent investigation shows that the fault is not in the Arduino IDE codebase. You should report the problem to the developers of the software where the bug/deficiency is located.
