### ISSUE TITLE
Custom board menu selection reverts to default on new window open

### ISSUE THREAD

**Issue by per1234** [arduino/arduino-ide#2271]
### Describe the problem

For the convenience of the user, Arduino IDE automatically configures the board and port selection of a new IDE window according to the configuration of the previous window.

In addition to the primary board selection, some board definitions have ["custom board options"](https://arduino.github.io/arduino-cli/dev/platform-specification/#custom-board-options) that allow additional configuration via arbitrary submenus added under the **Tools** menu.

🐛 The configuration of the custom board options revert to the default values when a new window is opened.

### To reproduce

1. Select **Tools > Board > Arduino AVR Boards > Arduino Nano** from the Arduino IDE menus.
1. Select **Tools > Processor > ATmega168** from the Arduino IDE menus.
1. Select **File > New Sketch** from the Arduino IDE menus.
   A new window will open.
1. Open the **Tools** menu in the new window.
   🐛 The default **ATmega328P** option is selected in the **Tools > Processor** custom board option menu.
1. Select **Tools > Processor > ATmega168** from the Arduino IDE menus.
   Select **File > Save As...** from the Arduino IDE menus.
1. Save the sketch to any name and location.
1. Open the **Tools** menu in the new window.
   🐛 The default **ATmega328P** option is selected in the **Tools > Processor** custom board option menu.

### Expected behavior

The custom board options configuration from the parent window are used in new windows.

### Arduino IDE version

69b7365

### Operating system

Windows

### Operating system version

11

### Additional context

The behavior described here was introduced at ce02e263ec336c84739aed5fc43f7a1ac16cfd79 / https://github.com/arduino/arduino-ide/pull/2241.

The described behavior does not occur when using the IDE build from ed2d8ad or earlier (but note those versions had a related fault https://github.com/arduino/arduino-ide/issues/2240).

---

Originally reported by @mjs513 at https://forum.arduino.cc/t/is-there-a-m4-and-m7-usage-for-dummies-document-d/1180371/10

#### Additional reports

- https://github.com/arduino/arduino-ide/issues/2271#issuecomment-1789878803
- https://forum.arduino.cc/t/arduino-ide-2-2-1-with-arduino-giga-dual-core-issues/1181384/4

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by frankcohen** [comment]
+1 on changing the behavior. The options revert to default values when opening new sketches, in addition to non-standard boards.
