### ISSUE TITLE
Sketch uses 2960 bytes (0%) of program storage space. Maximum is 2097152 bytes. A programmer is required to upload

### ISSUE THREAD

**Issue by sohail-inamdar** [arduino/arduino-ide#2276]
Sketch uses 2960 bytes (0%) of program storage space. Maximum is 2097152 bytes.
A programmer is required to upload.
A program is required to upload.

I am trying to get started with Aries v2 on ARDUINO IDE, Code is compiling successfully but failed to upload code. and its showing this error. 
![arduino ide](https://github.com/arduino/Arduino/assets/135228434/46203a8f-a8ea-4b06-b097-50f03c017309)

**Comment by per1234** [comment]
Hi @sohail-inamdar. The ["ARIES IoT" board definition](https://gitlab.com/riscv-vega/vega-bsp/-/blob/1.0.7/boards.txt?ref_type=heads#L195-231) does not contain [an `upload.protocol` property](https://arduino.github.io/arduino-cli/latest/platform-specification/#sketch-upload-configuration). This means the only method supported for uploading to this board is "**Upload Using Programmer**".

If you select the appropriate programmer from the **Tools > Programmer** menu and then select **Sketch > Upload Using Programmer** from the Arduino IDE menus, the sketch will upload without this "`A programmer is required to upload`" error.

Arduino IDE 1.x automatically uses "**Upload Using Programmer**" even when the user triggers an upload normally under these conditions, but that feature was never implemented in Arduino IDE 2.x. We already have an issue tracking the IDE's violation of the Arduino Platform Specification at https://github.com/arduino/arduino-ide/issues/103.

So I'll close this as a duplicate.
