### ISSUE TITLE
Add the 'Search all Sketch Tabs" checkbox to the Find dialog

### ISSUE THREAD

**Issue by esp32croft** [arduino/arduino-ide#228]
The old IDE allowed you to search across all tabs of a sketch (and replace). This useful checkbox option has been lost in v2 of the IDE so you have to search each tab in turn.

**Comment by kittaakos** [comment]
Thanks for reporting it, @esp32croft.

We added the _Search_ view to the IDE: https://github.com/arduino/arduino-ide/pull/202. The new view supports find, replace, exclude/include globs, and compare editor if you want to double-check your changes before replacing the content. It works on all tabs.

You can try it out from the nightly builds if you want to: https://github.com/arduino/arduino-ide#nightly-builds.
We would love to hear your feedback. Thanks!

**Comment by esp32croft** [comment]
Hi @kittaakos,
I've just tried the nightly build but didn't find a way of searching all the tabs for the selected text. The search still only finds matches in the selected tab. I've included a screenshot which shows what I'm getting;
<img width="961" alt="Screenshot 2021-03-16 at 21 54 47" src="https://user-images.githubusercontent.com/80626357/111385989-7a06f680-86a3-11eb-83ba-49e430ce7a89.png">
 I was expecting an option to search across all tabs from this dialog. I'm wondering if there is a setting somewhere that I've not enabled.

**Comment by ubidefeo** [comment]
@esp32croft 
you are still using the "find" command, not the search feature.
"Find" searches in the current tab, the "search" feature is on the left, in the sidebar

**Comment by kittaakos** [comment]
> The search still only finds matches in the selected tab. I've included a screenshot which shows what I'm getting;

You're very close, @esp32croft. If you want to search in all tabs, you have to use the new _Search_ view.

![Screen Shot 2021-03-17 at 08 21 53](https://user-images.githubusercontent.com/1405703/111429900-e876a380-86f9-11eb-8f7e-904672a1a66c.jpg)

See the screenshot:

![screencast 2021-03-17 08-19-19](https://user-images.githubusercontent.com/1405703/111429796-c2510380-86f9-11eb-9ab4-81f6258009f3.gif)

**Comment by esp32croft** [comment]
Thanks @kittaakos , @ubidefeo ,
I didn't spot it was a NEW search feature rather than an extension to Find as previous. I blame muscle memory and should RTFM.
Would be nice if the Search could pick up the highlighted text in the current tab to pre-fill the Search, as it does for Find.

**Comment by ubidefeo** [comment]
hi @esp32croft 
no worries, new features are often not immediately noticeable :)

> Would be nice if the Search could pick up the highlighted text in the current tab to pre-fill the Search, as it does for Find.

the editor find is its own component part of the Monaco editor.
I guess for this kind of stuff you can build up some muscle memory for copy paste 😀 

We won't implement this, since the search facility is a "search within workspace" and its functionalities go beyond searching for text. Pre-filling it would require moving text from one context to another.
We'd like to save development time for more pressing issues

thank you for your contribution 🙏🏼
