### ISSUE TITLE
strange compilation issue version 2.2.1 

### ISSUE THREAD

**Issue by huber6709** [arduino/arduino-ide#2285]
It compile a code I get somme errors like miss { or null characters ... I check my code everything is there { } and so. But compilation still stuck. Il a copy paste my code in note.exe, empty arduino ide and copy paste back the selection (code) from note.exe to arduino ide and then compile ... the code is ok.

**Comment by per1234** [comment]
Hi . Thanks for your interest in this open source project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
