### ISSUE TITLE
How F__k developer force user to loading screen because of internet problem.!

### ISSUE THREAD

**Issue by lessload** [arduino/arduino-ide#2290]
### Describe the request

- Please stop force user at loading screen, firewall may cause many problem with it.
- Loading not show anything, f__king useless.
- 2.0 mean bad for offline compiler ?
- portable not work as portable.

### Describe the current behavior

- stuck at loading screen, i need to fix many anti virus rule to fix it.

### Arduino IDE version

2.2.1

### Operating system

Windows

### Operating system version

Windows 11

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My request contains all necessary details

**Comment by per1234** [comment]
Hi @lessload. Thanks for your interest in this free open source project.

We expect the issues submitted to Arduino's repositories to be high quality formal reports that contain all the information required for the developers to perform an investigation. You didn't make even the slightest effort to provide useful information about the problem you are experiencing so I will close this as not actionable. If you aren't capable of producing a high quality formal report, you are welcome to request assistance on Arduino Forum, where we are more willing to coax the necessary information out of the recalcitrant users.

We also hold the communications made in Arduino's repositories on GitHub and Arduino Forum both to high standards of behavior. Your rude behavior here is absolutely unacceptable and counterproductive. If you continue to behave this way on GitHub or the forum you will receive a ban.
