### ISSUE TITLE
Whole window goes blank and stops responding, can't even close

### ISSUE THREAD

**Issue by php4fan** [arduino/arduino-ide#2297]
### Describe the problem

This has happened to me twice already.

I have no idea how to reproduce at will.

I use the IDE, I edit a sketch, I upload it.
Then I forget about it and leave the IDE open. At some point I disconnect the board (no clue whether this is what triggers the issue). At some point I leave the computer idle which locks the screen (I'm not sure whether it goes to sleep or only turns off the screen after a while).

Hours later I give focus back to the IDE to look at the sketch again, and what I find is a completely empty window (light grey almost white) that does not respond. Actually the menus do respond in that they show up and unfold when clicked, but then actions such as "new sketch" do nothing.
And the window can't even be closed.

### To reproduce

No idea what triggers this.
As I said what I did was:
- launch the Arduino IDE: this opened a sketch that I had opened last time I used the IDE
- edited the sketch, saved, changed settings such as "debug port"
- compiled and uploaded the sketch, possibly more than once
- watched the serial monitor as the sketch was running on the board and sending data to the monitor through the serial port
- forgot about it and left the IDE open while not using it, for hours
- at some point disconnected the board from the USB port
- locked and unlocked screen and possibly suspended and resumed
- came back to the IDE i.e. gave focus to it

### Expected behavior

the window shouldn't go blank and shouldn't stop responding.

### Arduino IDE version

2.2.1

### Operating system

Linux

### Operating system version

Manjaro Linux

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by kittaakos** [comment]
Thanks for reporting the bug.

> Then I forget about it and leave the IDE open.

> Hours later I give focus back to the IDE to look at the sketch again, and what I find is a completely empty window (light grey almost white) that does not respond.

It's a known issue: https://github.com/arduino/arduino-ide/issues/2148.
