### ISSUE TITLE
Using breakpoints to debug STM32

### ISSUE THREAD

**Issue by Bambofy** [arduino/arduino-ide#230]
**Is your feature request related to a problem? Please describe.**
I would like to debug an STM32 using the new IDE using breakpoints.

**Describe the solution you'd like**
At the moment, the debug button is greyed and disabled, i'd like to use it to debug my program.

**Describe alternatives you've considered**
Alternatives i've considered are usin Visual Micro VS2019 which has OpenOCD built in to allow debugging.

**Additional context**
<img width="306" alt="Arduino_IDE_64D2uqOjRz" src="https://user-images.githubusercontent.com/1304898/111288337-fa920c80-863b-11eb-98bd-44549c40f9d2.png">

**Comment by ubidefeo** [comment]
@Bambofy 
right now 3rd party cores don't have experimental support for the debugger in IDE 2.
We have added it to our own cores but it's not documented yet.

On the other hand, you could just create your own new debug configuration once opened the debug panel and run that one from within the debug panel itself.

You can find examples of configurations on the wiki for Cortex Debug https://github.com/Marus/cortex-debug/wiki

Please be patient as we extend support of the debugger and most importantly document the feature

ciao.ubi
