### ISSUE TITLE
Support ESP Secure Boot and Encryption

### ISSUE THREAD

**Issue by DanielLester83** [arduino/arduino-ide#2303]
### Describe the request

I realize this would be an advanced feature, but it would be nice to have an automated process of setting up encryption and secure boot of esp32 devices, burning the efuses and storing the key in the project file and then pre encrypting all future uploads.

### Describe the current behavior

No encryption support as far as I know.

### Arduino IDE version

2

### Operating system

Windows

### Operating system version

10

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My request contains all necessary details

**Comment by per1234** [comment]
Hi @DanielLester83. It sounds like a cool project!

The implementation of this type of feature is out of scope for the Arduino IDE project and can be accomplished without any changes to the Arduino IDE codebase. So I'll close this as off topic for this repository.

---

I'll add some notes that might help you to get started on your project:

A secure boot capability was implemented for the Arduino Portenta H7 board:

https://docs.arduino.cc/tutorials/portenta-h7/secure-boot

This was done without the need for any changes to Arduino IDE. The "Arduino Mbed OS Portenta Boards" platform was configured to produce a **Tools > Board > Security setting** menu in Arduino IDE when a Portenta H7 board is selected by using the existing "custom board options" capability of the Arduino boards platform framework:

https://arduino.github.io/arduino-cli/latest/platform-specification/#custom-board-options

In case you need more customization of the Arduino IDE user interface and underlying behaviors than the Arduino boards platform framework provides, you can use the IDE's support for VS Code extensions. An enhancement was made recently that gives such extensions access to the Arduino-specific data in the IDE (https://github.com/arduino/arduino-ide/pull/2110), which might be useful for this specific project. You can see an example of an extension using that feature here:

https://github.com/dankeboy36/esp-exception-decoder

I recommend you to discuss your project with the ESP32 community. I'll be very interested to see what you create!
