### ISSUE TITLE
sdram.h gets duplicate class SDRAMClass if included twice

### ISSUE THREAD

**Issue by dav322** [arduino/arduino-ide#2309]
### Describe the problem

Since this is not part of the nightly build I can't check to see if it is already fixed
I edited the local copy of this file for now.

file path on my machine is:
C:\Users\david\AppData\Local\Arduino15\packages\arduino\hardware\mbed_giga\4.0.10\libraries\Portenta_SDRAM\src\SDRAM.h
need to add
#ifndef __sdramh__
#define __sdramh__
at beginning of file 
and 
#endif
at end of file

### To reproduce

include "sdram.h" twice

### Expected behavior

not generate linker error

### Arduino IDE version

nightly build 12/14/2023

### Operating system

Windows

### Operating system version

windows 11

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @dav322. Thanks for your report. This is the repository for the Arduino IDE 2.x codebase, so the report of the missing include guard in the header file of the "Portenta_SDRAM" library is off topic here.

Please submit an issue to the repository where the library's code is hosted:

https://github.com/arduino/ArduinoCore-mbed/issues

Or better yet, submit a pull request to that repository for the important fix for the missing include guard.
