### ISSUE TITLE
Getting started on macOS 12.5.1 with apple silicon, getting compilation failure

### ISSUE THREAD

**Issue by mmacneille** [arduino/arduino-ide#2310]
### Describe the problem

Hello,

I am new to using Arduino, and am working on setting up my first project. I have an Elegoo Uno R3 and a Miuzei Starter Kit.
My developer environment is a Mac with an Apple M1 Pro chip, running on macOS 12.5.1. I have downloaded the respective IDE version that says it is compatible with my hardware and OS. 

While attempting to compile the Blink example program. I get the following error:

fork/exec /Users/mmacneille/Library/Arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++: bad CPU type in executable

Compilation error: fork/exec /Users/mmacneille/Library/Arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++: bad CPU type in executable

This indicates that there is some incompatibility between my CPU and the compiler that is packaged with the IDE.

I do not know much about what compiler is packaged, so I am not sure how to fix this issue.

Thank you in advance for your help.

### To reproduce

Attempt to compile the example Blink program on a Mac with Apple M1 Pro Chip and macOS 12.5.1

### Expected behavior

It should compile.

### Arduino IDE version

2.2.1

### Operating system

macOS

### Operating system version

12.5.1

### Additional context

Using Apple M1 Pro CPU

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @mmacneille. You can learn how to configure your system to be compatible with the toolchain of the "Arduino AVR Boards" platform from this Arduino Help Center article:

https://support.arduino.cc/hc/en-us/articles/7765785712156-Error-bad-CPU-type-in-executable-on-macOS

If you have any questions or problems while following the instructions, please post over on Arduino Forum and we'll help you out over there:

https://forum.arduino.cc/
