### ISSUE TITLE
Arduino 2.X portable

### ISSUE THREAD

**Issue by MatheusCaltran** [arduino/arduino-ide#2311]
I followed a co-worker who is using IDE 2.X and I really liked several improvements compared to IDE 1.X

I would really like to change my projects to version 2.X but I use several portable IDEs on an SD card. I would like to know about the unfolding of putting the portable IDE together with the board and component libraries

**Comment by per1234** [comment]
Hi @MatheusCaltran. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/122.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you would like assistance with using Arduino IDE 2.x, or to discuss the project, you are welcome to post over on Arduino forum:

https://forum.arduino.cc/c/software/ide-2-x/93
