### ISSUE TITLE
Library Manager wants to install dependencies that are already installed

### ISSUE THREAD

**Issue by php4fan** [arduino/arduino-ide#2317]
### Describe the problem

![image](https://github.com/arduino/arduino-ide/assets/13969584/fac90801-892c-48d4-9d1a-686dbfd9a3ed)

![image](https://github.com/arduino/arduino-ide/assets/13969584/3bd750c2-e22d-4471-b8ca-f8f897f4f147)

### To reproduce

From the Library manager:
1. Install the libraries: Adafruit GFX Library and Adafruit BusyIO
2. Install the library: GxEPD

### Expected behavior

At step 2, should simply install the GxEPD library, because the dependencies are already installed

### Observed behavior

Prompts me whether to install the abovementioned libraries which are dependencies, or to install without dependencies.
This prompt is completely unnecessary as both dependencies are already installed

### Arduino IDE version

2.2.1

### Operating system

Linux

### Operating system version

Manjaro Linux

### Additional context

Last time I tried the nightly build it  wouldn't even start, so no, I did not verify the problem still occurs when using the latest nightly build 

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by php4fan** [comment]
The library that I actually meant to install was GxEPD2, not GxEPD, but I've just tried with GxEPD2 and it also reproduces the issue.

**Comment by per1234** [comment]
Hi . Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/721.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.
