### ISSUE TITLE
Debug issue on IDE

### ISSUE THREAD

**Issue by Shikamru** [arduino/arduino-ide#2329]
### Describe the problem

Hi team,
            I am using Arduino IDE for for my work, and I am using picoW board. I am able to build and upload the Blinky code from IDE, however am not able to debug this. is there any way to achieve this. Anything needs to be added. Kindly guide me here.

Regards,
Shikamaru

### To reproduce

Select the board as Pico W and COM Port accordingly. Select the Blinky sketch and build and upload.

### Expected behavior

The Debug session has to start.

### Arduino IDE version

IDE 2.2.1

### Operating system

Windows

### Operating system version

19044.3803

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @Shikamru>. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
