### ISSUE TITLE
Application cannot be close after windows 10 sleep cycle

### ISSUE THREAD

**Issue by CreativeRobotics** [arduino/arduino-ide#2331]
### Describe the problem

After an indeterminate number of sleep cycles the application stops responding to certain actions:
It cannot be closed using the UI button and can only be closed using Windows task manager.
It will not save sketches and displays an error message telling you to copy your entire sketch into a different application.

### To reproduce

Use windows 10.
Open one or more sketches and have a device connected on a serial port.
Put windows through several sleep cycles.

### Expected behavior

An application should close when you click the close button.
It should never EVER be the case that a release version of an application cannot save your work and demands that you use another application to rescue it. Requesting that you copy and paste your work out of the application to save it is NOT a fix, it is a serious bug.

### Arduino IDE version

2.2.1

### Operating system

Windows

### Operating system version

10

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @CreativeRobotics. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/2148.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.
