### ISSUE TITLE
Allow serial number and other info from "Get Board Info" to be copy-pastable

### ISSUE THREAD

**Issue by JonNelson** [arduino/arduino-ide#2349]
### Describe the request

It would sometimes be nice to be able to copy from the "Get Board Info" window. 

### Describe the current behavior

The contents are not copyable.

### Arduino IDE version

2.2.1

### Operating system

Linux

### Operating system version

n/a

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My request contains all necessary details

**Comment by per1234** [comment]
Hi @JonNelson. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/1898.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

---

Note the workaround that was shared in the other issue's thread:

https://github.com/arduino/arduino-ide/issues/1898#issuecomment-1778397500

> Ctrl+C when the dialog box is in focus will copy the details.
