### ISSUE TITLE
please add a function to display the function list to the ide

### ISSUE THREAD

**Issue by vbzc** [arduino/arduino-ide#237]
please add a function to display the function list to the ide? I can jump to the beginning of the function in the code by double-clicking the function list item.

**Comment by kittaakos** [comment]
There is one, @vbzc. It's called the _Outline_ view.

You can access the _Outline_ view from the _Command Palette_.
 - Press <kbd>F1</kbd> or <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>,
 - Use the _Toggle Outline View_ command: just type `Toggle Outline View` and hit <kbd>Enter</kbd>.

If you select a symbol (method) in the _Outline_ view, the signature will be highlighted in the editor.
If you select the method signature or the content, the _Outline_ view updates.

This is how it works in-action:

https://user-images.githubusercontent.com/1405703/111625074-c0b43800-87ec-11eb-9bfc-f66c6316ab48.mp4
 
I hope this helps.

Related: https://github.com/arduino/arduino-ide/issues/150#issuecomment-790527865
