### ISSUE TITLE
It would be interesting to generate an array variable insufficient length warning - sprintf() random failures - LiquidCrystal

### ISSUE THREAD

**Issue by rtek1000** [arduino/arduino-ide#2372]
### Describe the request

It would be interesting to generate an array variable insufficient length warning,

### Describe the current behavior

I spent a long time looking for "hairs in eggs" and the problem was the char array variable of size 16 (char buffer[16]), which needed to be of size 17. This way, other variables were being written randomly with the sprintf() function, causing random failures.

### Arduino IDE version

2.3.0

### Operating system

Linux

### Operating system version

Xubuntu 22.04.3 LTS

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My request contains all necessary details

**Comment by per1234** [comment]
Hi @rtek1000. This sort of thing could never be implemented in the Arduino IDE codebase. Arduino IDE does not compile the sketch. It only invokes a the command that compiles the sketch using a standard C++ compiler (GCC). Arduino IDE doesn't even decide which command to invoke. It generates the command according to [a pattern](https://arduino.github.io/arduino-cli/latest/platform-specification/#recipes-to-compile-source-code) (template) defined by each boards platform author.

Besides that, there already is such a warning:

https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wformat-overflow

```cpp
void setup() {
  char buffer[16];
  sprintf(buffer, "%s %s %s %s %s %s %s", "foo", "bar", "baz", "qux", "pippo", "pluto", "paperino");
}
void loop() {}
```

```text
C:\Users\per\AppData\Local\Temp\.arduinoIDE-unsaved2024116-15900-532u5a.fywq\sketch_feb16a\sketch_feb16a.ino: In function 'void setup()':
C:\Users\per\AppData\Local\Temp\.arduinoIDE-unsaved2024116-15900-532u5a.fywq\sketch_feb16a\sketch_feb16a.ino:1:6: warning: '%s' directive writing 5 bytes into a region of size 0 [-Wformat-overflow=]
 void setup() {
      ^~~~~
C:\Users\per\AppData\Local\Temp\.arduinoIDE-unsaved2024116-15900-532u5a.fywq\sketch_feb16a\sketch_feb16a.ino:3:10: note: 'sprintf' output 37 bytes into a destination of size 16
   sprintf(buffer, "%s %s %s %s %s %s %s", "foo", "bar", "baz", "qux", "pippo", "pluto", "paperino");
   ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Note that you must have the "**Compiler warnings**" preference enabled to see the compiler warnings.

The output I shared above was from compiling for a MKR Zero board. I found that the compiler does not produce such a warning when compiling for a board of the "Arduino AVR Boards" platform, but that it does appear if I remove the `-flto` flag from the compilation pattern:

https://github.com/arduino/ArduinoCore-avr/blob/1.8.6/platform.txt#L28

So it appears this "link time optimization" feature makes it so the compiler is no longer able to detect the problem. That is unfortunate, but out of scope for this repository. If you are interested in discussing the subject further, you are welcome to do so over on Arduino Forum:

https://forum.arduino.cc/
