### ISSUE TITLE
Arduino 2.3.2 Compilation error: exit status 1 (Ambiguous Error)

### ISSUE THREAD

**Issue by EpicConOwO** [arduino/arduino-ide#2391]
### Describe the problem

I was trying to make a project using Waveshare 4.0.1 7 color E paper display. i tried the epd4in01f-demo code provided by waveshare, the code compiles fine at 1.8.19 but when compiling it on latest Arduino IDE 2.3.2 (And nightly) i am getting errors and code fails to compile, the error is very ambiguous and does not explain whats wrong, i will be attaching the error log for 2.3.2 along with output from 1.8.19 (if needed).
[arduino1.8.19output.txt](https://github.com/arduino/arduino-ide/files/14395838/arduino1.8.19output.txt)
[arduino2.3.2Errors.txt](https://github.com/arduino/arduino-ide/files/14395839/arduino2.3.2Errors.txt)

(I'm new to GitHub, and this is my first issue report. I tried my best to be as detailed and specific as possible in describing the bug. Please let me know if you require any further information.)

### To reproduce

To reproduce 
please first extract the library provided by waveshare which i will attach below 
[[esp32-waveshare-epd.zip](https://github.com/arduino/arduino-ide/files/14395845/esp32-waveshare-epd.zip)]
to Documents\Arduino\libraries
set the board to ESP32S3 (i am using https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json)
try compiling the provided code in epd4in01f-demo.ino file inside the attached zip below.
[[epd4in01f-demo.zip](https://github.com/arduino/arduino-ide/files/14395843/epd4in01f-demo.zip)]

### Expected behavior

The code should compile just like in Arduino 1.8.19 and provide appropriate error if something is wrong so that it can be easily understood by the user.

### Arduino IDE version

Version: 2.3.2 Date: 2024-02-20T10:04:35.814Z CLI Version: 0.35.3

### Operating system

Windows

### Operating system version

22H2 (Build 19045.4046)

### Additional context

- [ x ] I tried Restarting Arduino IDE 2.3.2 that did not fixed the issue.
- [ x ] I tried Restarting Windows that did not fixed the issue either.
- [ x ] i tried compiling other codes at Arduino 2.3.2 and they compile just fine.
- [  ] i did not tried uninstalling Arduino IDE since the issue was present at nightly build as well.
- [  ] i did not tried compiling the code on a different computer because i only own one PC currently.
- [  ] i did not tried the code on previous release version of Arduino 2.x.

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @EpicConOwO. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
