### ISSUE TITLE
"byte" type not syntax highlighted

### ISSUE THREAD

**Issue by MihaiZecheru** [arduino/arduino-ide#2406]
### Describe the request

Add syntax highlighting for the "byte" type

### Describe the current behavior

There is no syntax highlighting for the "byte" type

### Arduino IDE version

2.3.2

### Operating system

Windows

### Operating system version

11

### Issue checklist

- [x] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My request contains all necessary details

**Comment by per1234** [comment]
Hi @MihaiZecheru. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/380.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.
