### ISSUE TITLE
Function list view

### ISSUE THREAD

**Issue by Shumatic** [arduino/arduino-ide#2414]
### Describe the request

I would like a view where i can see alle the function that is definde in the sketch
It could like the view in Notepad++ v.8.6.4   menu - view - Function list
This provide a rapid way to goto a function.
Preferrebly it should work across Tabs
![Skærmbillede 2024-04-11 102955](https://github.com/arduino/arduino-ide/assets/27434906/7eb458a0-1174-4456-8192-3977149ae6a6)

### Describe the current behavior

N/A

### Arduino IDE version

2.3.2

### Operating system

Windows

### Operating system version

10

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My request contains all necessary details

**Comment by per1234** [comment]
Hi @Shumatic. Arduino IDE already has this feature. It is called the "Outline View".

You will find instructions for enabling the Outline View in the previous requests for the feature: https://github.com/arduino/arduino-ide/issues/237 and https://github.com/arduino/arduino-ide/issues/1157

**Comment by Shumatic** [comment]
I am so sorry for not investigating properly ..... :-)
