### ISSUE TITLE
Issue #2878 is still an issue (Can't remove library using IDE library manger GUI)

### ISSUE THREAD

**Issue by bperrybap** [arduino/arduino-ide#2428]
According to the final comment in issue arduino/Arduino#2878 before the issue was locked from comments, 
the ability to remove a library using the library manager is only partially implemented as it will not allow removing some of the libraries in a user's sketchbook/libraries directory.
This is problematic and as such issue arduino/Arduino#2878 is not truly resolved.

A good user interface should be easy to use but not get in the way of user completing tasks.
This seems to be a case where extra work was put into the current implementation to prevent some libraries from being removed but in the end it means the functionality fails to allow the user to remove a library that they may want to remove.

There should be no need for the added nanny behavior.
It also means that the current implementation is only a partial solution to issue arduino/Arduino#2878 
A user should be able to use the IDE library manger GUI to remove ANY library in his sketchbook/libraries directory.

**Comment by per1234** [comment]
Thanks for your suggestion @bperrybap but we are satisfied with the current behavior of Arduino Library Manager and an uninstall capability for libraries not distributed via Library Manager will not be provided.
