### ISSUE TITLE
The output of the Port Monitor is not copied

### ISSUE THREAD

**Issue by whitevast** [arduino/arduino-ide#2431]
### Describe the problem

It is not possible to select the entire output using Ctrl+A. If you select with the mouse, only the text on the screen is copied.

### To reproduce

Try copying the entire output of the Port Monitor to the clipboard. Select the text of the Port Monitor using Ctrl+A

### Expected behavior

Selecting the entire output of the port Monitor when pressing Ctrl+A, copying the entire selected fragment to the clipboard (Ctrl+C)

### Arduino IDE version

2.3.2

### Operating system

Windows

### Operating system version

10

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @whitevast. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/812 and https://github.com/arduino/arduino-ide/issues/1081.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the others.
