### ISSUE TITLE
Faster compiles

### ISSUE THREAD

**Issue by frankcohen** [arduino/arduino-ide#2435]
### Describe the request

I'm using Arduino IDE 2.3 on a MacBook Pro laptop 2.3 Ghz Quad Core Intel I7 on Sonoma 14.4.1. My Reflections project has 1 .ino file and 25 .cpp files. It's about 15,000 lines of code in total. Code is here: [GitHub - frankcohen/ReflectionsOS: Reflections is a hardware and software platform for building entertaining mobile experiences.](https://github.com/frankcohen/ReflectionsOS). It takes about 8 minutes to compile the code. During the compile the aggregate CPU is 11% used. It seems the compiler is using 1 of the cores only. What ways are there to compile the code in less than minute? -Frank

### Describe the current behavior

Compiles appear to be using 1 core, when 4 are available.

### Arduino IDE version

Version: 2.3.2 Date: 2024-02-20T09:57:46.613Z CLI Version: 0.35.3  Copyright © 2024 Arduino SA

### Operating system

macOS

### Operating system version

14.4.1 (23E224)

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My request contains all necessary details

**Comment by per1234** [comment]
Hi @frankcohen. Thanks for your interest in this open source project. Your "Reflections" project looks very cool!

This issue tracker is only to be used to report bugs or feature requests specific to the project. This topic is more appropriate for the Arduino Forum. I see you have already created a forum topic on this subject:

https://forum.arduino.cc/t/how-to-compile-very-fast-in-arduino-ide/1260047

I'll be sure to monitor that thread and participate if I can add anything of value. If anyone else is interested in the subject or can provide input then please feel free to join in over there.
