### ISSUE TITLE
redefinition error when using Library WiFiNINA in Version 1.8.14 and Library WiFiNINA_Generic in Version 1.8.15-1 

### ISSUE THREAD

**Issue by rbaumann** [arduino/arduino-ide#2439]
### Describe the problem

After the installation of Arduino IDE 2.3.2 I followed the package upgrade proposals for WiFiNINA, WiFININA_Generic and pfodParser. I was using the below packages in older release w/o problem to compile an application for Arduino Nano 33 IoT.
Please see below the used libraries of the application as reported by the Arduino IDE compile error message:

```text
Library SPI in Version 1.0 im Ordner: /home/rene/.arduino15/packages/arduino/hardware/samd/1.8.14/libraries/SPI  used
Library WiFiNINA_Generic in Version 1.8.15-1 im Ordner: /home/rene/Arduino/libraries/WiFiNINA_Generic  used
Library SafeString in Version 4.1.31 im Ordner: /home/rene/Arduino/libraries/SafeString  used
Library pfodWifiGenericBufferedClient in Version 2.5 im Ordner: /home/rene/Arduino/libraries/pfodWifiGenericBufferedClient  used
Library pfodDwgControls in Version 1.2 im Ordner: /home/rene/Arduino/libraries/pfodDwgControls  used
Library pfodParser in Version 3.63.1 im Ordner: /home/rene/Arduino/libraries/pfodParser  used
Library WATCHDOG_SAMD21CPU im Ordner: /home/rene/Arduino/libraries/WATCHDOG_SAMD21CPU (veraltet) used
Library SYS_MSG im Ordner: /home/rene/Arduino/libraries/SYS_MSG (veraltet) used
Library Arduino_LSM6DS3 in Version 1.0.3 im Ordner: /home/rene/Arduino/libraries/Arduino_LSM6DS3  used
Library Wire in Version 1.0 im Ordner: /home/rene/.arduino15/packages/arduino/hardware/samd/1.8.14/libraries/Wire  used
Library Fan_Ctrl im Ordner: /home/rene/Arduino/libraries/Fan_Ctrl (veraltet) used
Library WiFiNINA in Version 1.8.14 im Ordner: /home/rene/Arduino/libraries/WiFiNINA  used
```

The newest release of the "WiFiNINA_Generic" seems to be a bit over-complex and worst, it contains exact copies of declaration files
of `/Arduino/libraries/WiFiNINA/src/utility` like `wl_definitions.h`, `wl_types.h` and others in `/Arduino/libraries/WiFiNINA_Generic/src/utility` but without using the standard multiple `#include` guards:

```cpp
    #ifndef WL_DEFINITIONS_H_
    #define WL_DEFINITIONS_H_

    #endif
```

instead using a `pragma` statement

```
    #pragma once

    /*****************************
      wl_definitions.h

      Created on: Mar 6, 2011
      Author: dlafauci
     *****************************/
```

Which to my humble opinion does not do the trick! Please read as well the below text on that subject.
https://arduino.stackexchange.com/questions/66104/include-guards-vs-pragma-once
The compiler therefore reports redefinition errors!

### To reproduce

With the following includes the problem appears - in my context.

```cpp
#include <SPI.h>
#include <WiFiNINA_Generic.h>

#define DEBUG
#define DEBUG_I2C
#define DEBUG_L1
#define DEBUG_CMD
//#undef DEBUG
//#undef DEBUG_I2C
//#undef DEBUG_L1
//#undef DEBUG_CMD
//
// Install SafeString library from the Arduino IDE Library Manager
// SafeString tutorial at https://www.forward.com.au/pfod/ArduinoProgramming/SafeString/index.html
#include "SafeString.h"

// Download pfodWiFiGenericBufferedClient library from http://www.forward.com.au/pfod/pfodParserLibraries/index.html
// pfodWiFiGenericBufferedClient.zip contains pfodWiFiGenericBufferedClient and pfodWiFiGenericUtils
#include <pfodWiFiGenericUtils.h>
#include <pfodWiFiGenericBufferedClient.h>

// download the libraries from http://www.forward.com.au/pfod/pfodParserLibraries/index.html
#include <pfodDwgControls.h>
#include <pfodSecurity.h>
int swap01(int); // method prototype for slider end swaps

// --------  D E F I N E   P F O D - A P P   V E R S I O N -------------------
pfodSecurity parser("V3"); // create a parser with menu version string to handle the pfod messages
// ---------------------------------------------------------------------------
pfodDwgs dwgs(&parser);  // drawing support
// Commands for drawing controls only need to unique per drawing, you can re-use cmds 'a' in another drawing.
pfodWiFiGenericBufferedClient bufferedClient;
```

### Expected behavior

Behavior as it was earlier release in `WiFiNINA_Generic` w/o `#pragma` statement

### Arduino IDE version

2.3.2

### Operating system

Linux

### Operating system version

Ubuntu 24.04

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @rbaumann. Thanks for your interest in this open source project.

This issue tracker is used for bug reports and feature requests specific to the Arduino IDE application codebase that is hosted in this repository. This is not an appropriate place to submit issues related to the code of a library.
