### ISSUE TITLE
Arduino IDE UI

### ISSUE THREAD

**Issue by AGaafar7** [arduino/arduino-ide#2441]
### Describe the request

Arduino IDE needs Themes to look better as it does not catch the eye. So I hope that you add themes either already made and bundled with the IDE or make the user edit the theme of his IDE.

### Describe the current behavior

I use the dark theme that is already made.

### Arduino IDE version

2.3.3-nightly-20240502

### Operating system

Windows

### Operating system version

23H2

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My request contains all necessary details

**Comment by per1234** [comment]
Hi @AGaafar7. Thanks for your interest in this open source project.

> Themes to look better as it does not catch the eye

We are satisfied with the current level at which our themes "catch the eye" so your request for increasing this level is declined.

If you aren't satisfied with the themes Arduino includes with Arduino IDE, you'll be happy to learn that thousands more 3rd party themes are available, some of which have a far higher level of eye-catchingness.

Instructions for installing these 3rd party themes are provided here:

https://github.com/arduino/arduino-ide/blob/main/docs/advanced-usage.md#3rd-party-themes

Please note that Arduino does maintain or provide support for individual 3rd party themes. If you have problems while using a theme, you can request assistance over on [**Arduino Forum**](https://forum.arduino.cc/), or report the problem to the creator of the theme.

> make the user edit the theme of his IDE

You can create your own custom themes. A community member shared some general information on how to do that here:

https://forum.arduino.cc/t/personal-themes/1024606/2

You will also find a lot more information on the subject if you do some searching. Keep in mind that Arduino IDE uses [**VS Code**](https://code.visualstudio.com/) themes, so use the "VS code" keyword in your searches, _not_ "Arduino IDE".

As for being able to modify the existing themes, this capability is not currently provided by the [**Eclipse Theia** IDE framework](https://theia-ide.org/) upon which Arduino IDE is built. A request for the addition of that capability has already been submitted to the **Theia** developers: https://github.com/eclipse-theia/theia/issues/8060
