### ISSUE TITLE
avrdude: ser_open(): can't open device "/dev/ttyUSB0": Permission denied Failed uploading: uploading error: exit status 1

### ISSUE THREAD

**Issue by roda37** [arduino/arduino-ide#2444]
### Describe the problem

avrdude: ser_open(): can't open device "/dev/ttyUSB0": Permission denied
Failed uploading: uploading error: exit status 1

also doesn't allow me to run it as root, broken software

### To reproduce

run it

### Expected behavior

to work properly

### Arduino IDE version

latest

### Operating system

Linux

### Operating system version

GNU/ Linux

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @roda37. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
