### ISSUE TITLE
Add the ability to ignore specific serial ports

### ISSUE THREAD

**Issue by RobertoD91** [arduino/arduino-ide#2448]
### Describe the request

It would be useful to have the option to specify a list of serial ports to ignore.

For example, in the case of macOS:
- cu.BLTH
- cu.Bluetooth-Incoming-Port

Users can add to this list serial ports for UPS devices and other devices.

### Describe the current behavior

All serial port are showed

### Arduino IDE version

2.3.3-nightly-20240423

### Operating system

macOS

### Operating system version

14.5

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My request contains all necessary details

**Comment by per1234** [comment]
Hi @RobertoD91. Thanks for your suggestion. I understand the motivation behind this request, but we are satisfied with the current design of Arduino IDE in this area so I will close this as declined.
