### ISSUE TITLE
Line numbering in output when compiling

### ISSUE THREAD

**Issue by ednieuw** [arduino/arduino-ide#2451]
### Describe the request

Line numbering or an alternating character like / and \ when compiling at the start of a line in the output TAB 

### Describe the current behavior

When a long sketch is compiled there are many long lines with an identical beginning. 
It is difficult to check if something is happening because printing is so fast unlike the IDE 1

### Arduino IDE version

2.3.3 nightly 20240422

### Operating system

Windows

### Operating system version

W11

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My request contains all necessary details

**Comment by per1234** [comment]
Hi @ednieuw. Thanks for taking the time to submit a feature request.

Although I do understand the reasoning behind you suggestion, we are satisfied with the current approach to printing output so I will close this as declined.
