### ISSUE TITLE
The default hotkey for upload and toggle output window is the same.

### ISSUE THREAD

**Issue by pauljurczak** [arduino/arduino-ide#2453]
### Describe the problem

Ctrl+Shift+U is listed as a hot key for both "Toggle Output View" and "upload sketch using programmer":

![Screenshot from 2024-06-12 22-23-38](https://github.com/arduino/arduino-ide/assets/4933032/d72655c2-ec9e-466a-84be-1f87821fc34e)

![Screenshot from 2024-06-12 22-24-01](https://github.com/arduino/arduino-ide/assets/4933032/3b50c211-0734-4ace-9493-d9d3792d5338)

### To reproduce

Go to keyboard shortcuts and see the default settings.

### Expected behavior

See images.

### Arduino IDE version

2.3.1

### Operating system

Linux

### Operating system version

22.04.4

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @pauljurczak. Thanks for taking the time to submit an issue.

I see we have another report about this at 
If you end up with additional information to share, feel free to comment in the other thread..

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.
