### ISSUE TITLE
Serial Monitor: IDE becomes nearly unusable with really long lines.

### ISSUE THREAD

**Issue by Spaceballs3000** [arduino/arduino-ide#2459]
### Describe the problem

IDE becomes sluggish over a few seconds.

### To reproduce

Open Serial Monitor, run this code
```
void setup()
{      
  Serial.begin(115200); 
}
void loop()
{
 // Serial.println("------------------------------------------------------------------------------------------------------------------------------------------------------------");  // No issues with IDE slowness
 Serial.print("------------------------------------------------------------------------------------------------------------------------------------------------------------");  // With Serial Monitor windows open, IDE slowness will happen after a min or so. 
}
```

### Expected behavior

IDE to not become sluggish.

### Arduino IDE version

2.3.2

### Operating system

Windows

### Operating system version

Win 10

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @Spaceballs3000. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/934.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.
