### ISSUE TITLE
Some IDE instances become unresponsive

### ISSUE THREAD

**Issue by CreativeRobotics** [arduino/arduino-ide#2467]
### Describe the problem

When running multiple instances of Arduino, some of those instances will become unresponsive and report that they have lost connection with the backend. The instance IDE will still allow editing and menus can still be opened but some menu items will not work:
Saving is disabled
compiling is disabled (The popup message "compiling sketch" appears but does nothing.
Global search is disabled but local search still works.
Selecting different boards through the tools menu works and boards can be selected through the other menu widget but searching for boards doesn't work.
Open, new and close sketch menus don't work.
-> Selecting 'Quit'  will result in any OTHER instances of Arduino that have not frozen to quit, leaving only those instances that have become unresponsive.
The only way to quit the unresponsive IDE is to use the task manager.

### To reproduce

Open multiple instances of Arduino. perform a number of sleep cycles.

### Expected behavior

One or more instance of the IDE will stop working.

### Arduino IDE version

2.3.2

### Operating system

Windows

### Operating system version

10

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @CreativeRobotics. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/2148.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.
