### ISSUE TITLE
Please make "Upload" button have option to "Upload Using Programmer"

### ISSUE THREAD

**Issue by Napoleon-BlownApart** [arduino/arduino-ide#2472]
### Describe the request

Thus the option would be in an intuitive location as it is rare to use the "Sketch" menu item because the IDE itself has the "Upload" function.  The "Tools" menu item has all the other board related functionality. 

### Describe the current behavior

"Upload Using Programmer" is on the "Sketch" menu item which may not be the most intuitive location.

### Arduino IDE version

aa9b10d

### Operating system

N/A

### Operating system version

N/A

#### Related

- https://github.com/arduino/arduino-ide/issues/199
- https://github.com/arduino/arduino-ide/issues/103

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My request contains all necessary details

**Comment by per1234** [comment]
Hi @Napoleon-BlownApart. Thanks for taking the time to submit this suggestion.

"Upload Using Programmer" is an advanced feature that is not used by the average Arduino IDE user. We only want to expose the most commonly used operations in the Arduino IDE primary UI. So we are happy with the current availability of the feature via the **Sketch > Upload Using Programmer** menu item as well as its configurable shortcut and thus I'll close this suggestion as declined.

We are already tracking the lack of the features from Arduino IDE 1.x that made "Upload Using Programmer" more accessible to users without a modification of the primary UI:

- https://github.com/arduino/arduino-ide/issues/103
- https://github.com/arduino/arduino-ide/issues/199
