### ISSUE TITLE
ESP32-S2/S3 Upload Failure: Needs --after no_reset Option

### ISSUE THREAD

**Issue by DocKenny** [arduino/arduino-ide#2478]
### Describe the problem

When uploading code to the ESP32-S2 or ESP32-S3 boards using the Arduino IDE, the process fails with a warning that the board cannot exit download mode over USB. This issue persists due to the lack of the `--after no_reset` option in the esptool command used by the IDE.

### To reproduce

1. Connect an ESP32-S2 or ESP32-S3 board to your computer via USB.
2. Open the Arduino IDE and select the appropriate board under Tools > Board.
3. Load any sample sketch and attempt to upload it to the board.
4. Observe the error in the console output indicating that the board cannot exit download mode.

### Expected behavior

The sketch should upload successfully without errors.

### Arduino IDE version

2.3.3

### Operating system

Windows

### Operating system version

Windows 10

### Additional context

This issue seems to be specific to boards like the ESP32-S2/S3 that use GPIO0 for download mode. A manual workaround is to add `--after no_reset` to the esptool command, but this requires user intervention and is not conducive to a smooth workflow. For more context and related discussions, please refer to this pull request on the esptool repository: [esptool PR #997](https://github.com/espressif/esptool/pull/997).

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @DocKenny. This issue is specific to the ESP32 and other boards platforms that use esptool. The `esptool` command is configured in the platform.

So there is nothing that can or should be changed in the Arduino IDE codebase hosted in this repository. Instead, it should be done in the boards platform.

You should report it to the "esp32" boards platform developers here:

https://github.com/espressif/arduino-esp32/issues/
