### ISSUE TITLE
URL protocol for opening a sketch from a website

### ISSUE THREAD

**Issue by Mammad900** [arduino/arduino-ide#248]
**Is your feature request related to a problem? Please describe.**
I have written [a (web) app](https://github.com/Mammad900/Gui900-visual-editor) where the user designs a program and gets Arduino code. It is a pain to copy-paste the generated code to Arduino IDE every time I generate code.

**Describe the solution you'd like**
Implement URL protocol for opening a sketch, so I can implement a button which opens a URL like `arduinoide://opensketch?code=void%20setup%20%28%29%20%7B%7D%20void%20loop%20%28%29%20%7B%7D` and the IDE opens the sketch automatically.

**Additional context**
An upload option would also be nice, using `arduinoide://uploadsketch?code=blablabla`, and the Arduino IDE opens with a dialog asking the port, board, etc. and then the upload process starts.

**Comment by ubidefeo** [comment]
@Mammad900 
this is very much out of the scope of our work.

>It is a pain to copy-paste the generated code to Arduino IDE every time I generate code.

possibly working weeks to implement this to avoid someone the burden of doing a copy/paste is not something I'd like our team to do

regards,
ubi
