### ISSUE TITLE
Shortcuts don't work

### ISSUE THREAD

**Issue by linuxni** [arduino/arduino-ide#2490]
### Describe the request

Depending on the keyboard language used when Arduino IDE is running, shortcut keys may not work.

### Describe the current behavior

Arduino IDE Shortcut Key Problem:

Core issue:
The functionality of shortcut keys within the Arduino IDE is determined by the keyboard layout state when the IDE is launched.
Specific scenarios:
a) Normal operation case:

When Arduino IDE is launched while Mac OS keyboard layout is set to English
Result: Shortcut keys (e.g., CMD + C, CMD + V, etc.) work normally

b) Problem case:

When Arduino IDE is launched while Mac OS keyboard layout is set to a non-English language (e.g., Korean)
Result: Shortcut keys do not function

Notable points:

Changing the keyboard layout after launching the IDE does not resolve the issue
The problem occurs regardless of the IDE's language setting (English/Korean)

Presumed cause:
It appears that the Arduino IDE sets its shortcut keys based on the keyboard layout at the time of launch and fails to recognize subsequent changes.
![스크린샷 2024-08-13 21 39 30](https://github.com/user-attachments/assets/ec7d30bd-f9a1-4378-b1b3-728d2b4ab1ae)
![스크린샷 2024-08-13 21 39 48](https://github.com/user-attachments/assets/b17314a2-4a2b-4adf-a813-d43fec8213cf)

### Arduino IDE version

2.3.2

### Operating system

macOS

### Operating system version

15.0

### Additional context

---

<details>
  <summary><b>Keywords</b></summary>
  <p>

- "keybinding"
- "key binding"
- "hotkey"
- "hot key"
- "accelerator"
- "key combination"
- "key sequence"
- "key chord"
- "shortcut key"

  </p>
</details>

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My request contains all necessary details

**Comment by per1234** [comment]
Hi @linuxni. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/2263.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
