### ISSUE TITLE
There should be a way to cancel a compile.

### ISSUE THREAD

**Issue by gilesp1729** [arduino/arduino-ide#2495]
### Describe the request

At present a compile/upload cannot be cancelled.

### Describe the current behavior

No way is provided to cancel a compile, which may involve a long wait.

### Arduino IDE version

Any

### Operating system

Windows

### Operating system version

11

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My request contains all necessary details

**Comment by per1234** [comment]
Hi @gilesp1729. Thanks for taking the time to submit an issue.

I see we already had a request for this at https://github.com/arduino/arduino-ide/issues/1199, which has already been resolved by https://github.com/arduino/arduino-ide/commit/2a325a5b74a7ea80645cd2da74588f706292f4ff (https://github.com/arduino/arduino-ide/pull/2334).

The feature was added after the time of the Arduino IDE 2.3.2 release, so it is currently only available when using the nightly build of Arduino IDE:

https://www.arduino.cc/en/software#nightly-builds
