### ISSUE TITLE
Arduino Uno R4 Minima Programmer Bugs

### ISSUE THREAD

**Issue by mithrandirmatt** [arduino/arduino-ide#2496]
### Describe the problem

When trying the burn bootloader option I get the following error:

`Property 'bootloader.tool.dfu' is undefined`

When trying to burn a sketch with a programmer I get the following error:

`Failed programming: recipe not found 'program.pattern'`

Using IDE 2.3.2, tried Windows and Ubuntu, tried nightly build, all the same errors.

After chatting in the forums it would seem that this may not be supported for the R4, which is a pretty big step back from the support the Atmel chips had.

I originally got the board due to the debugging capability, so big thanks for that. However, I have bricked one of my boards trying to upload a build from the arduino-cli, which could have totally been a fault in my build, or with the process of loading it, I was working out issues in both at the time.

Either way, if this is not supposed to be supported, or is not currently planned on being supported, then I plan to solve for this issue myself and would like to contribute so that others don't have to go through this pain either.

If this is expected, please give me some details on how I can implement this feature here to be shared among the community, at least for the two programmers I have on hand. If you have an example(s) or a wiki for how to do this I will give it a whirl.

Thanks in advance!

### To reproduce

Select Uno Minima as board. Select jlink or stm programmer options (all options appear to do the same, but I have these two programmers). 

1. Click "Burn Bootloader" option.
2. Click "Upload Using Programmer" option.

### Expected behavior

I would have expected a command to be run to a corresponding selected device.

### Arduino IDE version

2.3.2

### Operating system

Windows, Linux

### Operating system version

Ubuntu 22.04, Windows 10

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @mithrandirmatt

> please give me some details on how I can implement this feature here to be shared among the community, at least for the two programmers I have on hand. If you have an example(s) or a wiki for how to do this I will give it a whirl.

Here it is:

https://arduino.github.io/arduino-cli/latest/platform-specification/
