### ISSUE TITLE
Why are my PC paths included in every compiled firmware elf?

### ISSUE THREAD

**Issue by JustTryingToGetSomeWorkDone** [arduino/arduino-ide#2497]
### Describe the problem

Arduino IDE saves multiple paths to libraries from the PC that I used to compile anything inside the compiled and uploaded firmware. Those paths leaked out through the OLED I'm using on a project. I checked the compiled .elf files of variously compiled sketches, and they all contain this private information. This is important, because on Windows this means the files contain the name of the administrator account for my computer. These paths are all in plain text. Why is this necessary and why is it in plain text? Finally how on earth is this something that can leak through the connected OLED? (Yes, it was a memory leak of some sort, but why is this in there to begin with?)

### To reproduce

Compile anything for anything with any settings. Open the file in a text editor like Notepad++ and search for "C:\Users" and you'll find your Windows computer's user account name along with the paths to your libraries.

### Expected behavior

I expect Arduino IDE not to leak my private information in plain text. No, I expect that information never to have been included in the first place. Can anyone explain the reasoning behind this?

### Arduino IDE version

2.3.2

### Operating system

Windows

### Operating system version

Windows 10 22H2

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Closing as off topic for this repository. Arduino IDE doesn't have anything directly to do with producing the compiled sketch binary. It only sends a general purpose compile command to a helper tool, which in turn runs the standard GCC compiler commands that are defined by the command patterns of the Arduino boards platform of the board you have selected.

>Can anyone explain the reasoning behind this?

As with the issue itself, such explanation is off topic for this issue tracker. We will use the Arduino Forum topic you created on the subject for such discussion:

https://forum.arduino.cc/t/arduino-ide-leaks-windows-pc-administrator-account-name-and-paths-in-every-compiled-firmware/1294511
