### ISSUE TITLE
Waiting a few minutes for the ESP32 downloading index

### ISSUE THREAD

**Issue by VladimirVecera** [arduino/arduino-ide#2506]
### Describe the request

I'm using ESP32 and let's say after daily powering on Arduino 2.3.2 I wait a few minutes for ESP32 downloading index. Why is the ESP32 index downloaded and not cached?

It delays work unnecessarily. What's more, if I open a new scatch in a new window during downloading, insert the code and want to upload the code to the ESP32, the compilation is completely blocked, because the downloading index of the ESP32 is in the first window.

![image](https://github.com/user-attachments/assets/f07f7561-3c50-4a96-be47-1a1b4bc82166)

### Describe the current behavior

Do not use the ESP32 downloading index every time you turn on the Arduino. It really hinders the use of the program.

### Arduino IDE version

2.3.2

### Operating system

Windows

### Operating system version

11

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My request contains all necessary details

**Comment by per1234** [comment]
Hi @VladimirVecera . Thanks for taking the time to submit an issue.

>  I wait a few minutes for ESP32 downloading index

I see we have another report about this at https://github.com/arduino/arduino-cli/issues/2347.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.

> Why is the ESP32 index downloaded and not cached?

It is cached, but only for four hours:

https://github.com/arduino/arduino-ide/blob/1ec0a8cc77c2741ef380f682fa95273615dda06f/arduino-ide-extension/src/browser/contributions/update-indexes.ts#L163

The reason for this is that the platform developer makes new releases of the platform by updating the package index. So we must periodically download a fresh copy of the index to check whether there is a new version of the platforms from the index.
