### ISSUE TITLE
When I start debugging, it says: OpenOCD: GDB Server Quit Unexpectedly

### ISSUE THREAD

**Issue by Roland1121** [arduino/arduino-ide#2509]
I'm a beginner in programming, but I have such a problem that when I go to start debugging, it says: OpenOCD: GDB Server Quit Unexpectedly. See gdb-server output for more details. I've already tried many options, but nothing works! (maybe I sent the post to the wrong place., sorry.)

**Comment by per1234** [comment]
Hi @Roland1121. Thanks for your interest in this open source project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
