### ISSUE TITLE
Wa language support arduino-wasm3

### ISSUE THREAD

**Issue by chai2010** [arduino/arduino-ide#2512]
### Describe the request

Wa is a general-purpose programming language designed for developing robustness and maintainability WebAssembly software. The wa languge support buildin arduino-wasm target.

![](https://raw.githubusercontent.com/wa-lang/wa/master/docs/images/logo/logo-animate1.svg)

https://github.com/wa-lang/wa

Tere is a example:

https://github.com/wa-lang/wa/tree/master/waroot/examples/arduino

```wa
import "syscall/arduino"

global LED = arduino.GetPinLED()

func init {
	arduino.PinMode(LED, 1)
	arduino.Print("凹语言(Wa)/Arduino is running ...\n")
	arduino.Print("https://wa-lang.org\n")

	for {
		arduino.DigitalWrite(LED, arduino.HIGH)
		arduino.Delay(100)
		arduino.DigitalWrite(LED, arduino.LOW)
		arduino.Delay(900)
	}
}
```

![](https://github.com/wa-lang/wa/raw/master/docs/images/arduino-nano33-01.png)

see https://wa-lang.org/smalltalk/st0052.html (chinese)

### Describe the current behavior

Wa is new language, will it be supported?

### Arduino IDE version

2

### Operating system

N/A

### Operating system version

all

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My request contains all necessary details

**Comment by per1234** [comment]
Hi @chai2010. Thanks for taking the time to suggest a feature.

Arduino IDE is a tool for developing Arduino sketches, so we only support the Arduino programming language, as well as the related C++, C, and assembly languages that are provided by the GCC compiler. So we can not add support to Arduino IDE for the the unrelated Wa language.
