### ISSUE TITLE
The IDE "forgets" avrdude processes, lets them hang and consume resources

### ISSUE THREAD

**Issue by AndKe** [arduino/arduino-ide#2527]
### Describe the problem

This is the task manager after programming 30x Leonardo.  
![Screenshot from 2024-10-08 16-40-11](https://github.com/user-attachments/assets/ee8d0b2e-18bb-409f-b110-6a33a2718fed)

And 5% CPU load on this computer is not insignificant. (basically one core per dead avrdude process)
The load is reduced by exiting ArduinoIDE:

![Screenshot from 2024-10-08 16-40-27](https://github.com/user-attachments/assets/96d46874-a5b4-428a-be8c-48d774834679)

This is an example of the failure that leaves one zombie thread:
(bootloader not trigged, I clicked "cancel")

![Screenshot from 2024-10-08 18-58-06](https://github.com/user-attachments/assets/49b2717b-cc81-439d-8ffd-d5e0610542ec)

### To reproduce

Flash a bunch of Leonardo's - quite possibly one , *maybe* reconnect every time to simulate many.

### Expected behavior

I'd expect that after flashing, successful or not the process started is terminated.

### Arduino IDE version

2.3.3 

### Operating system

Linux

### Operating system version

Ubuntu 24.04

### Additional context

Additional info, having the flashing fail and never commence can also happen when reflashing the same chip.
The Serial (USB) interface is in use for terminal, but not transmitting data.
I've observed that the bootloader is not always trigged correctly, and pressing Cancel, and retrying can help.
All the hung processes makes next /dev/ttyACMx to enumerate with higher and higher number.

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @AndKe. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/2517.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
