### ISSUE TITLE
Can't open sketches with drag and drop on macOS

### ISSUE THREAD

**Issue by alranel** [arduino/arduino-ide#253]
`.ino` files can't be opened by dragging and dropping them onto the application icon. This works correctly with the Java IDE.

(In theory we should also accept folders, since technically speaking the "sketch" is a folder and not the .ino file, but this requires we handle the non-sketch folder somehow)

**Comment by ubidefeo** [comment]
@alranel  this is covered by #186 
We don't have file association yet, but it's in the backlog

**Comment by alranel** [comment]
Closing as it's a duplicate then :)
