### ISSUE TITLE
Cannot copy more than the screen content from Serial-Monitor

### ISSUE THREAD

**Issue by rin67630** [arduino/arduino-ide#2533]
### Describe the problem

Arduino IDE V2.3.3 has an unusual behaviour on its serial monitor.
When marking a block of text including scrolling (concretely an exception report) **it copies only the part of text shown on the screen**.

That is quite annoying to get an exception report right.

### To reproduce

Mark a large block of text incuding scrolling.
Copy it into the clipboard
Paste it elsewhere.

Only the block dispalyed on the screen is copied.

### Expected behavior

I expect a standard behaviour, bein able to copy also scrolled parts of the text.

### Arduino IDE version

2.3.3

### Operating system

Windows

### Operating system version

Windows 11 Pro 22H2

### Additional context

Similar to old bug 812
Beside that, there is a known bug that Serial monitor causes freeze in compiling.

Will test on nightly build too, but need to get an exception report to copy first... 

Will test on macOSX, but needs to sent that issue first,

### Issue checklist

- [x] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [x] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [x] My report contains all necessary details

**Comment by per1234** [comment]
Hi @rin67630. Thanks for taking the time to submit an issue.

> When marking a block of text including scrolling (concretely an exception report) it copies only the part of text shown on the screen.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/1081.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

> Beside that, there is a known bug that Serial monitor causes freeze in compiling.

Yes, it has already been reported so please don't submit another one: https://github.com/arduino/arduino-cli/issues/2719
