### ISSUE TITLE
Take over microsoft/vscode-arduino

### ISSUE THREAD

**Issue by iamart** [arduino/arduino-ide#2534]
### Describe the request

Can arduino take over microsoft's vscode-arduino repo?
In addition to support in vscode, I think arduino-ide repo can utilize the vscode extension.

### Describe the current behavior

n/a

### Arduino IDE version

2

### Operating system

N/A

### Operating system version

n/a

### Issue checklist

- [x] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [x] I verified the feature was still missing when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [x] My request contains all necessary details

**Comment by per1234** [comment]
Hi @iamart. No, but the community has already taken it over here:

https://github.com/vscode-arduino/vscode-arduino
