### ISSUE TITLE
Autocomplete not working for esp32 project

### ISSUE THREAD

**Issue by alexarnoldi** [arduino/arduino-ide#254]
The code completation doesn't work if i select a platform other than Arduino like ESP32.

 - OS: Windows 10
 - Version: 2.0 beta

**Comment by ubidefeo** [comment]
@alexarnoldi please provide more information
An example of your sketch might help us find the issue

I cannot reproduce the issue with Beta 4

**Comment by alexarnoldi** [comment]
OK,with beta 4 works all,thank you...
