### ISSUE TITLE
how will I check and change my ESP32 SPIFFS partition.

### ISSUE THREAD

**Issue by viveky1794** [arduino/arduino-ide#255]
I am working on a esp32 project Where I need only 1 MB SPIFFS and remaining memory for Other purpose.
All this I can check and change board related information in Arduino IDE 1.xx but I am not able to do this in new IDE.

Can you tell me how to fix this problem ?

I want same feature which you have in previous IDE. under Tool section or somewhere I can simply find board related information.

https://user-images.githubusercontent.com/29608699/111947500-a091bb00-8b03-11eb-93e8-00738133e855.mp4

**Comment by ubidefeo** [comment]
hi @viveky1794 

This issue is already being tracked in #245 
It is a bug introduced in Beta 4 and we'll fix it as soon as possible.

You can try Beta 3 in the meantime
https://github.com/arduino/arduino-ide/releases/tag/2.0.0-beta.3
