### ISSUE TITLE
[docs] 2.3.4 release notes contain a bad link

### ISSUE THREAD

**Issue by ssilverman** [arduino/arduino-ide#2589]
### Describe the problem

The "related change" link in the release notes is this: https://github.com/arduino/arduino-ide/blob/2.3.4/%5Bc09b5f71%5D
It should be: https://github.com/arduino/arduino-ide/commit/c09b5f718a5a14c420c1649ac5bf117d8fd68d9e

Ref: https://github.com/arduino/arduino-ide/releases/tag/2.3.4

### To reproduce

Click on the "related change" link in the release notes.

### Expected behavior

The link should go to the intended change.

### Arduino IDE version

N/A

### Operating system

N/A

### Operating system version

N/A

### Issue checklist

- [x] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [x] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [x] My report contains all necessary details

**Comment by per1234** [comment]
Thanks so much for pointing this out @ssilverman. I have corrected the link in the release notes.
