### ISSUE TITLE
IDE hangs on startup due to problem with chrome-sandbox

### ISSUE THREAD

**Issue by gatherinegod** [arduino/arduino-ide#2593]
### Describe the problem

I found an error in chrome-sandbox.

I'm in Lubuntu and I'm using the .zip IDE. IDE executes but don't charge, only appears the load window but I can't use it.

I replaced the chrome-sandbox file with the one from Arduino IDE 2.3.3 and it works now. 

### To reproduce

Start Arduino IDE.

### Expected behavior

Arduino IDE starts.

### Arduino IDE version

2.3.4

### Operating system

Linux

### Operating system version

Lubuntu (version not specified)

**Comment by per1234** [comment]
Thanks for your report @gatherinegod. I'm going to ask you to provide some additional information that might help us to identify the problem.

---

❗ This procedure is not intended to solve the problem. The purpose is to gather more information.

---

Please do this:

1. Close all Arduino IDE windows if the IDE is already running.
1. Replace the `chrome-sandbox` file with the original file (or make a fresh installation of Arduino IDE 2.3.4).
1. Open [a command line terminal](https://ubuntu.com/tutorials/command-line-for-beginners) in the folder that contains the Arduino IDE installation.
1. Type the following command:
   ```text
   ./arduino-ide
   ```
1. Press the <kbd>**Enter**</kbd> key.
   Debug output should now be printed to the PowerShell window as Arduino IDE starts (or fails to start).
1. Wait for Arduino IDE to finish starting, or failing to start.
1. Switch back to the terminal window if the Arduino IDE window took the focus.
1. Use the mouse to select all the text in the terminal window. Make sure to scroll all the way up to the top.
1. Press the <kbd>**Ctrl**</kbd>+<kbd>**Shift**</kbd>+<kbd>**C**</kbd> keyboard shortcut to copy the selected text to the clipboard.
1. Paste (<kbd>**Ctrl**</kbd>+<kbd>**V**</kbd>) the copied output in a reply to this GitHub issue thread.

---

Please let me know if you have any questions or problems while following those instructions.

**Comment by gatherinegod** [comment]
Ok, first of all I have this problem, I need to configurate chrome-sandbox:

[23396:1205/191936.218932:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /home/drakter/Descargas/arduino-ide_2.3.4_Linux_64bit/chrome-sandbox is owned by root and has mode 4755.

That I solve doing this:
sudo chown root:root /path/to/chrome-sandbox
sudo chmod 4755 /path/to/chrome-sandbox

Now I don't know what's happening but works, maybe is because I used it before in the new version and all packages are updated?
