### ISSUE TITLE
arduino-ide/docs/development.md has old link to Arduino CLI's prerequisites section.

### ISSUE THREAD

**Issue by brewmanz** [arduino/arduino-ide#2595]
### Describe the problem

arduino-ide/docs/development.md has sentence
"For more details, refer to the Arduino CLI’s [prerequisites section](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#prerequisites)."
but link to
https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#prerequisites
which seems to go to the OLD Arduino CLI site.

Sorry if I've mis-read things.

### To reproduce

click link

### Expected behavior

Go to CLI 2 prerequisites

### Arduino IDE version

2.x

### Operating system

N/A

### Operating system version

Ubuntu 20.04

### Issue checklist

- [x] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [x] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [x] My report contains all necessary details

**Comment by per1234** [comment]
Hi @brewmanz.

>which seems to go to the OLD Arduino CLI site.

There is no "OLD Arduino CLI site". There is only one **Arduino CLI** documentation website, and that is the site the link points to:

https://arduino.github.io/arduino-cli/latest

Rest assured that the documentation you find on that site is applicable to the **Arduino CLI** helper tool used by **Arduino IDE**

> Go to CLI 2 prerequisites

There is no such thing as "CLI 2". There is only **Arduino CLI**. It might be that in the future we will release an Arduino CLI 2.0.0 version, in compliance with [The **SemVer** specification](https://semver.org/), but that will simply be a new release of the **Arduino CLI** project, not a new generation of the project, and so the https://arduino.github.io/arduino-cli/ website will continue to be used for all versions of **Arduino CLI**.
