### ISSUE TITLE
Ribbon Menu

### ISSUE THREAD

**Issue by SkylarAstarot** [arduino/arduino-ide#2598]
### Describe the request

Add new Ribbon Menu.

### Describe the current behavior

I would like you to add the ribbon menu, for better management and automated development.
[https://i.imgur.com/v0tElZj.png](https://i.imgur.com/v0tElZj.png)

### Arduino IDE version

2.3.4

### Operating system

Windows

### Operating system version

11

### Issue checklist

- [x] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [x] I verified the feature was still missing when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [x] My request contains all necessary details

**Comment by per1234** [comment]
Hi @SkylarAstarot. Thanks for taking the time to submit this suggestion.

The Arduino IDE user interface is the result of careful intentional design, based on user studies. We are satisfied with the current design and so are declining to add a ribbon menu.
