### ISSUE TITLE
Conditional breakpoint only stops the first time

### ISSUE THREAD

**Issue by rei-vilo** [arduino/arduino-ide#268]
**Describe the bug**

Conditional breakpoint only stops the first time.

Adding `i%2` to line 8 only stops the first time when i=1, but not after when i=3 or 5.

**To Reproduce**

Same example as for arduino/arduino-ide#120 but with modified shown below.

**Expected behavior**

Debugger stops at 1, 3 and 5.

**Screenshots**

![Capture 2021-03-25 08-25-06](https://user-images.githubusercontent.com/951776/112435052-885cae80-8d44-11eb-9a82-342ab9a41f19.png)

![Capture 2021-03-25 08-28-37](https://user-images.githubusercontent.com/951776/112435068-8c88cc00-8d44-11eb-89f6-bac86142d599.png)

**Desktop (please complete the following information):**

 - OS: Windows 10
 - Version: 2.0.0 beta 4
 - SAMD core 1.8.11

**Additional context**

+ Modified **LocalLibrary.cpp**

```
#include "LocalLibrary.h"

// Code
void blinkLED(uint8_t pin, uint8_t times, uint16_t ms, bool level)
{
    for (uint8_t i = 0; i < times * 2; i++)
    {
        digitalWrite(pin, (level ^(i%2)) ? HIGH : LOW);
        delay(ms >> 1);
    }
}
```

**Comment by ubidefeo** [comment]
@rei-vilo 
I have just tested this and it is working for me
I use an `uint8_t` and only break on `counter % 2 == 0`

**Comment by per1234** [comment]
Closing as fixed by https://github.com/arduino/arduino-ide/pull/1706

After quite some deciphering of this unnecessarily complex report, I finally determined that it is the same as https://github.com/arduino/arduino-ide/issues/412
