### ISSUE TITLE
strcopy and strcat show error

### ISSUE THREAD

**Issue by DeJHDante** [arduino/arduino-ide#278]
Compiling for esp8266 NodeMCU 1.0, this statement

strcat(message, ";");

shows this error
No matching function for call to 'strcat'
:26:15:
note: candidate function not viable: requires 0 arguments, but 2 were provided clang(ovl_no_viable_function_in_call)

strcpy(message, deviceID); does the same thing.

However, the compilation seems to work and give the same result as IDE 1.0 in terms of executable segment sizes that I haver not yet tested the code by uploading to the esp8266.

**Comment by mink99** [comment]
![Image4](https://user-images.githubusercontent.com/11485843/115142180-a4502900-a040-11eb-8f74-91d0d33ee5d9.png)
```
#include <stdio.h>
#include <string.h>

void setup() {
  // put your setup code here, to run once:
char str[80];
  strcpy (str,"these ");
  strcat (str,"strings ");
  strcat (str,"are ");
  strcat (str,"concatenated.");
  puts (str);
}

void loop() {
  // put your main code here, to run repeatedly:

}

```
see the temporary fix for https://github.com/arduino/arduino-ide/issues/55
