### ISSUE TITLE
Support internationalization

### ISSUE THREAD

**Issue by per1234** [arduino/arduino-ide#28]
**Is your feature request related to a problem? Please describe.**
Arduino has a global community who speak many languages. Arduino IDE 2.0.0 currently only provides English language support.

**Describe the solution you'd like**
In order to make Arduino as accessible as possible, it would be beneficial to provide internationalization (i18n) support.

The classic Arduino IDE and Arduino CLI are currently using [the Transifex translation platform](https://www.transifex.com/), and this has enabled amazing community volunteers to provide high quality translations to [83 languages](https://www.transifex.com/mbanzi/arduino-ide-15/)! This system seems to be working well, so it should be considered for Arduino IDE 2.0.0 as well.

If possible, existing translations for strings shared between the classic Arduino IDE and Arduino IDE 2.0.0 should be reused.

**Additional context**
Arduino CLI already has internationalization support (https://github.com/arduino/arduino-cli/pull/676) and the strings originating from Arduino CLI should be translated there so that they can benefit every tool using Arduino CLI.

**Related**
- https://github.com/arduino/arduino-pro-ide/issues/303
- https://github.com/arduino/arduino-ide/issues/627
- https://github.com/arduino/arduino-ide/issues/712
- https://github.com/arduino/arduino-ide/issues/741
- https://github.com/arduino/arduino-ide/issues/762
- https://github.com/arduino/arduino-ide/issues/771

**Comment by rsora** [comment]
Closing, as we implemented the internationalization support though the following PRs:  
#542 
#545 
#616
#610

**Comment by per1234** [comment]
Not completed until we are able to actually deliver localization to the users, which has not happened yet.

**Comment by kotobuki** [comment]
Hi. I am a little bit confused. I am a translater of Japanese (ja) and translated all resources on Transifex. What all we translators have to do is translate strings on Transifex? Do we need anything else to be included in the nightly build and the release version?

**Comment by per1234** [comment]
>I am a translater of Japanese (ja) and translated all resources on Transifex.

Thanks so much @kotobuki!

>What all we translators have to do is translate strings on Transifex?

That is correct.

>Do we need anything else to be included in the nightly build and the release version?

No additional action is required from you beyond the translation work on Transifex.

Arduino has been working to set up the internationalization system that:

- Pushes the English language source strings that need to be localized from this repository to Transifex
- Pulls the localization data from Transifex back to this repository
- Integrates the localization data into the IDE builds
- Provides a user interface for language selection

It is that internationalization infrastructure which has not yet been completed (though it is very close). That work will be done by Arduino's developers (though contributions from the community are welcome as always). I believe the final task is tracked here:
https://github.com/arduino/arduino-ide/issues/712

**Comment by fstasi** [comment]
As @per1234 suggested, this is superseeded by #712 and more specific issues. Closing.
