### ISSUE TITLE
Incorrect bool syntax coloring

### ISSUE THREAD

**Issue by kittaakos** [arduino/arduino-ide#291]
**Describe the bug**

`true` and `false` have incorrect syntax coloring:

Java IDE:
![Screen Shot 2021-03-31 at 13 24 01](https://user-images.githubusercontent.com/1405703/113137349-bb131500-9224-11eb-8ef1-99a0d73df235.jpg)

New IDE:
![Screen Shot 2021-03-31 at 13 23 53](https://user-images.githubusercontent.com/1405703/113137356-bc444200-9224-11eb-8325-33f38e328286.jpg)

**Comment by Macka323** [comment]
I don't know if this isn't the problem or I have different version or something else but the syntax coloring is correct.
![image](https://user-images.githubusercontent.com/75259519/113282433-33daa580-92e7-11eb-8125-719242f49cfd.png)

**Comment by kittaakos** [comment]
> the syntax coloring is correct.

No, it isn't. I am comparing the Java IDE and the new IDE bahevior.

![Screen Shot 2021-04-01 at 12 49 40](https://user-images.githubusercontent.com/1405703/113283676-e19a8400-92e8-11eb-9aa4-a9636b7894ae.jpg)
![Screen Shot 2021-04-01 at 12 49 45](https://user-images.githubusercontent.com/1405703/113283672-e101ed80-92e8-11eb-8201-0a50eca384bb.jpg)

**Comment by Macka323** [comment]
![image](https://user-images.githubusercontent.com/75259519/113284214-9a60c300-92e9-11eb-8740-14e66f9e4739.png)

**Comment by ubidefeo** [comment]
@kittaakos I have tried and it only lacks colouring on the **Light Arduino** theme
the dark theme shows it correctly.
@Macka323 can you try the **Light Arduino** theme?

Light Arduino
<img width="721" alt="Screenshot 2021-04-01 at 22 46 55" src="https://user-images.githubusercontent.com/1894487/113352456-927e3e80-933c-11eb-8a24-c878ec30b71b.png">

Light Theia
<img width="795" alt="Screenshot 2021-04-01 at 22 49 21" src="https://user-images.githubusercontent.com/1894487/113352490-9f9b2d80-933c-11eb-9afb-d173f6a6f544.png">

Dark Theia
<img width="771" alt="Screenshot 2021-04-01 at 22 48 59" src="https://user-images.githubusercontent.com/1894487/113352512-a75ad200-933c-11eb-8f6b-19cae2b2e555.png">

**Comment by Macka323** [comment]
@ubidefeo The syntax coloring in the Light Arduino is wrong.

**Comment by ubidefeo** [comment]
thank you for confirming this.
definitely a bug :)
