### ISSUE TITLE
"Show Sketch folder" points to temp directory when opened via File > Sketchbook > Sketch_name

### ISSUE THREAD

**Issue by ubidefeo** [arduino/arduino-ide#297]
**Describe the bug**
If I need to add files to my Sketch I need quickly find the folder and see my files, 
but the **Sketch > Show Sketch Folder** opens the temporary directory, hence every change is lost.
i.e.: the **Recent** submenu does not update with the open Sketch

This only seems to happen when Sketch is open via **File > Sketchbook**.
The same file reports the correct absolute path if open via **File > Open**

**To Reproduce**
1. Open a pre-existing Sketch (or save a new one)
2. Click on **Sketch > Show Sketch Folder**
3. Look at the containing tree
4. You will see that you got directed to the temporary folder, not to the one inside the Sketchbook
5. This seems to also prevent the **File > Open Recent ** not to have updated content even after a restart

**Expected behavior**
Pointing to the content of my Sketch inside the Sketchbook folder and having the **File > Open Recent** correctly show the file I last opened.

**Screenshots**
<img width="544" alt="Screenshot 2021-04-02 at 10 07 37" src="https://user-images.githubusercontent.com/1894487/113396254-85446c80-939b-11eb-9558-26e8c56639cc.png">
<img width="612" alt="Screenshot 2021-04-02 at 10 07 50" src="https://user-images.githubusercontent.com/1894487/113396262-883f5d00-939b-11eb-8678-7e8816449c53.png">
<img width="737" alt="Screenshot 2021-04-02 at 10 08 04" src="https://user-images.githubusercontent.com/1894487/113396267-8aa1b700-939b-11eb-9413-940a455f3b57.png">
<img width="720" alt="Screenshot 2021-04-02 at 10 08 15" src="https://user-images.githubusercontent.com/1894487/113396272-8d041100-939b-11eb-9aa4-4e01fbd5cdac.png">
<img width="673" alt="Screenshot 2021-04-02 at 10 08 28" src="https://user-images.githubusercontent.com/1894487/113396284-8f666b00-939b-11eb-8e73-6922e15a4e8a.png">
<img width="559" alt="Screenshot 2021-04-02 at 10 08 48" src="https://user-images.githubusercontent.com/1894487/113396290-92615b80-939b-11eb-99bf-b3dd1342f818.png">

**Desktop (please complete the following information):**
 - OS: Mac OS 11.2.3 Big Sur
 - Version: 2.0.0-beta.4-nightly.20210402

**Comment by silvanocerza** [comment]
I investigated a bit and turns out that this bug has been introduced by c64ac48 and PR #198.
