### ISSUE TITLE
In order to open a whole folder, you must click one of the files in it

### ISSUE THREAD

**Issue by Shashank-Prasanna** [arduino/arduino-ide#299]
**Describe the bug**
I have a folder full of all of the sketches in my project. The first time I tried this, I tried to open a folder. I couldn't do it, as it only lets me open a file. However, when I pressed on a file and opened it, it opened **the whole folder**, which is confusing. 

**To Reproduce**
1. Go to the open file menu
2. Click on any folder with `.ino` files in it (For me, it won't let me open the folder itself)
3. Open one of the files in the folder
4. It open the whole folder!

**Expected behavior**
I would expect a better and clearer way to open the files. If you click on a folder, it opens all the files in the folder. If you click on a file, it opens only that file. 

**Desktop (please complete the following information):**
 - OS: macOS
 - Catalina (10.15)

**Additional context**

**Comment by ubidefeo** [comment]
@Shashank-Prasanna 
Do you intend to keep multiple `.ino` files in the same folder as separate Sketches or as part of the same Sketch?
A Sketch is a folder which contains a `.ino` file with the same name of the folder and a series of other source files which can be `.ino`, `.h`, `.cpp`, `.S`

The behaviour has always been the same, you need to click the `.ino` file to open the Sketch, which is assumed to be the containing folder and all the valid source files contained
