### ISSUE TITLE
"WiFi101 / WiFiNINA Firmware Updater" tool is missing

### ISSUE THREAD

**Issue by per1234** [arduino/arduino-ide#30]
**Describe the bug**
The classic Arduino IDE has a **Tools > WiFi101 / WiFiNINA Firmware Updater** menu option that is used to update the firmware and certificates on the WiFi module on the MKR WiFi 1010, Nano 33 IoT, Uno WiFi Rev2, MKR 4000 Vidor, and MKR1000 boards:
- https://www.arduino.cc/en/Reference/WiFiNINA#wikitext:~:text=Firmware%20Update
- https://www.arduino.cc/en/Tutorial/FirmwareUpdater

**To Reproduce**

1. Open the **Tools** menu - no "WiFi101 / WiFiNINA Firmware Updater" option is shown

**Expected behavior**
Arduino IDE 2.0.0 to provide a mechanism for easy updates of the WiFi module firmware.

**Screenshots**
![FW_UPD_1](https://user-images.githubusercontent.com/8572152/109068386-a3d08d00-76a4-11eb-803b-a22615dc27f3.jpg)

**Desktop (please complete the following information):**
 - OS: All
 - Version: 2.0.0-beta.2-snapshot.f9730ab
Date: 2021-02-18T13:01:31.751Z
CLI Version: 0.16.0 alpha [c977a238]

**Additional context**
There is a command line tool: https://arduino.github.io/arduino-fwuploader/

**Related**
- https://github.com/arduino/arduino-ide/issues/58

**Comment by alranel** [comment]
Meanwhile, in addition to the mentioned command line tool, the NINA firmware can be easily upgraded with the [Arduino Cloud](https://create.arduino.cc) web interface
