### ISSUE TITLE
Unable to start IDE, stuck on splash screen

### ISSUE THREAD

**Issue by PaszaVonPomiot** [arduino/arduino-ide#300]
**Describe the bug**
I'm posting this as bug because it could be considered as such by users. 
When starting IDE while having firewall enabled Arduino gets stuck indefinitely without any error message and splash screen blocks central part of the screen.

**To Reproduce**

1. Have your firewall enabled (TinyWall in my case) 
1. Start Arduino IDE
1. See the splash screen indefinitely
2. Close Arduino IDE
1. Open firewall traffic for Arduino IDE and CLI
2. Start Arduino IDE
3. See that it works

**Expected behavior**
Splash screen disappears and user can work in IDE
OR
Error message is displayed indicating no connection

**Screenshots**
![arduinosplash](https://user-images.githubusercontent.com/5560454/113566523-1ec68500-960d-11eb-9a5a-45c9c5e87923.png)

**Desktop (please complete the following information):**
 - OS: W10HOME
 - Version: 2.0.0.beta4

**Comment by per1234** [comment]
>Error message is displayed indicating no connection

This should already be the case when using the nightly build of Arduino IDE 2.x:
https://www.arduino.cc/en/software#nightly-builds

Thanks to https://github.com/arduino/arduino-ide/pull/266, you should now get an informative error message when this happens, which will make it much easier to identify why the IDE was unable to fully start up.
