### ISSUE TITLE
Windows 32bit version - please!

### ISSUE THREAD

**Issue by heinerolli** [arduino/arduino-ide#302]
Arduinos are small and cheap (and great) often used in projects outside the house. 
I (and probably many others) use an old (32bit) Windows Tablet - which is not convertable to Linux.... to test, modify & upload my code for outside projects. I don't have access to my main Laptop (64 bit) there.
-> So please make this build also for 32 bit Windows 10 available.

**Comment by kittaakos** [comment]
Duplicate of #109.
