### ISSUE TITLE
Spurious Language Server result for `SparkFun:apollo3` platform

### ISSUE THREAD

**Issue by jerabaul29** [arduino/arduino-ide#307]
I am using the latest IDE2.0 on Ubuntu 20.04.

I am compiling a sketch for the Sparkfun Artemis board (third party boards). I installed the Sparkfun Artemis core v1.2.1 (installed by hand). The sketch compiles fine (see message in the command line interface pane).

However, I get some faulty error messages, in particular, see the one here:

![Screenshot from 2021-04-09 19-28-28](https://user-images.githubusercontent.com/8382834/114219340-cd025f80-996a-11eb-9a02-66f8d400a9a5.png)

Any idea:

- what is causing it?
- how to fix it?

**Comment by mrbbp** [comment]
hello, i've got the same pb with added libraries

i use SD_FAT lib and have `unknown_type`, as it doesn't read the lib for var, knowned functions and authorized name


<img width="475" alt="Capture d’écran 2021-04-12 à 11 26 08" src="https://user-images.githubusercontent.com/1716290/114372587-052fbb00-9b82-11eb-8b0d-718d5637664e.png">
<img width="426" alt="Capture d’écran 2021-04-12 à 11 26 19" src="https://user-images.githubusercontent.com/1716290/114372610-09f46f00-9b82-11eb-8450-775872d163dc.png">
<img width="792" alt="Capture d’écran 2021-04-12 à 11 26 34" src="https://user-images.githubusercontent.com/1716290/114372631-0fea5000-9b82-11eb-8486-a7ff0b048519.png">

**Comment by kgrabe** [comment]
to recreate on win 10, ide beta 7:
![image](https://user-images.githubusercontent.com/12760714/119256577-45d71700-bbb9-11eb-95ee-c508f28695a7.png)
now comment out not-existent library, comile to get error:
![image](https://user-images.githubusercontent.com/12760714/119256622-77e87900-bbb9-11eb-952c-56f47ac3ae23.png)
now uncomment the libary..
![image](https://user-images.githubusercontent.com/12760714/119256650-a1090980-bbb9-11eb-98d5-045f66ff96b4.png)
and previousely ok code shows errors even though the code compiles ok:
![image](https://user-images.githubusercontent.com/12760714/119256671-bed66e80-bbb9-11eb-87b7-2e378daed3a5.png)

**Comment by per1234** [comment]
Closing as resolved by https://github.com/arduino/arduino-language-server/pull/92
