### ISSUE TITLE
Arduino IDE 2.0 conflicts with software package Multipass on Windows

### ISSUE THREAD

**Issue by ferrybig** [arduino/arduino-ide#311]
**Describe the bug**
Having Multipass installed breaks the new Arduino IDE, as Multipass listeners on the same ports (127.0.0.1:50051) that the Arduino IDE 2.0 uses

**To Reproduce**
1. Install the software package https://multipass.run/ by the people who also made Ubuntu
2. Install the Arduino IDE 2.0 editor
3. Run the Arduino IDE 2.0 editor

See the following error reported by the command line output (note that any non-techincal users would never seen these error messages, _they just see a frozen Arduino 2.0 editor_)

```
...
daemon INFO Starting daemon from C:\Users\fernando\AppData\Local\Programs\Arduino IDE\resources\app\node_modules\arduino-ide-extension\build\arduino-cli.exe...
daemon INFO Using config file: c:\Users\fernando\.arduinoIDE\arduino-cli.yaml
daemon INFO arduino-cli.exe version 0.17.0
daemon INFO Failed to listen on TCP port: 50051. Unexpected error: listen tcp 127.0.0.1:50051: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.
daemon INFO Failed to start the daemon.
daemon ERROR Error: Failed to listen on TCP port. Address already in use.
    at new DaemonError (C:\Users\fernando\AppData\Local\Programs\Arduino IDE\resources\app\node_modules\arduino-ide-extension\lib\node\arduino-daemon-impl.js:370:28)
    at Function.parse (C:\Users\fernando\AppData\Local\Programs\Arduino IDE\resources\app\node_modules\arduino-ide-extension\lib\node\arduino-daemon-impl.js:388:24)
    at Socket.<anonymous> (C:\Users\fernando\AppData\Local\Programs\Arduino IDE\resources\app\node_modules\arduino-ide-extension\lib\node\arduino-daemon-impl.js:306:53)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
daemon INFO Restarting daemon in 5 seconds...
...
```

**Expected behavior**
I expected the Arduino IDE 2.0 to automatically select a different free port if the one it decided to use is in use. Loading forever or giving an error message is not an acceptable behaviour.

**Screenshots**
![image](https://user-images.githubusercontent.com/1576684/114462607-92572c00-9be3-11eb-93ba-357f7832e4d7.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 64-bit
 - Version: 2.0.0-beta.4 (according to the download link, the program does not start properly, so I'm unable to open the about dialog screen)

**Additional context**
I did not test it on other operation systems, it might or might not also conflict on other operation systems

**Comment by per1234** [comment]
Hi @ferrybig. Thanks for taking the time to submit an issue.

I see we already have a prior issue report about this at https://github.com/arduino/arduino-ide/issues/201.

It's best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
