### ISSUE TITLE
Preferences Quick Suggestions tick box problem.

### ISSUE THREAD

**Issue by Willem43T** [arduino/arduino-ide#313]
**Describe the bug**
The Preferences Quick Suggestions tick box does not reflect the current status.  When opening Preferences it is always cleared.  If ticked, it actually toggles the current status and will be cleared again when next time Preferences is opened.

**To Reproduce**
1. Open File/Preferences.  The Editor Quick Suggestions tick box is cleared.
2. Click on the tick box.  The blue arrow arears.  Close Preferences.
3. Type text and check if Quick Suggestions are shown.
4. Open Preferences - the tick box is cleared.
5. Click it again and check if Quick Suggestions has changed.
6. The tick box will again be cleared when opening Preferences.

**Expected behavior**
Tick box should reflect the current status of Quick Suggestions.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro

**Comment by per1234** [comment]
Closing as fixed by https://github.com/arduino/arduino-ide/pull/494

If you want to test it out, the fix is now available in the nightly build of Arduino IDE 2.x
https://github.com/arduino/arduino-ide#nightly-builds
