### ISSUE TITLE
No network ports are shown

### ISSUE THREAD

**Issue by gq97a6** [arduino/arduino-ide#316]
No network ports are shown. Is OTA implemented yet? My old ide v1.8.12 works fine.

**Comment by per1234** [comment]
Hi @gq97a6. No, network ports support has not been added to Arduino IDE 2.x yet. You can learn about that here:
https://github.com/arduino/arduino-ide/issues/123

It's best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
