### ISSUE TITLE
In Dark mode top of the window is white

### ISSUE THREAD

**Issue by ednieuw** [arduino/arduino-ide#321]
### Describe the problem

In dark mode the top of the windows is white

![image](https://user-images.githubusercontent.com/12166816/115108566-7d76f180-9f71-11eb-868c-bb4732e2f41b.png)

### Expected behavior

This should also be black

### Arduino IDE version

2.0.0 beta.4

### Operating system

Windows

### Operating system version

10

**Comment by ClaudioCas** [comment]
Probably is not really a bug, but a dark header like VS Code will be really great!
![immagine](https://user-images.githubusercontent.com/4325427/115110014-705e0080-9f79-11eb-8c86-9a25d4a44638.png)

**Comment by kittaakos** [comment]
> but a dark header like VS Code will be really great!

The dark window title bar in VS Code on Windows is not native but custom. It's handled by the `window.titleBarStyle` setting, currently disabled on Windows and not supported by Theia IDE on macOS: https://github.com/arduino/arduino-ide/pull/1870
