### ISSUE TITLE
Problems with port detection of Raspberry Pico

### ISSUE THREAD

**Issue by sstaub** [arduino/arduino-ide#322]
Using Raspberry Pico with official Arduino Mbed Core

When plugging in my Pico the Port is automatic detected and selected, but the port is twice in the list
<img width="579" alt="Port 1" src="https://user-images.githubusercontent.com/6450325/115115149-fdfa1a00-9f92-11eb-97e3-a18c3a3219f3.png">
After uploading, the port is not automatic detected and I have to select the port manually.
<img width="579" alt="Port 2" src="https://user-images.githubusercontent.com/6450325/115115169-1bc77f00-9f93-11eb-833c-c5de71e302be.png">

This behavior is different to classic IDE where the automatic port detection after upload works as expected.

**Desktop (please complete the following information):**
 - OS: macOS 11.2.3
 - Version: 2.0.0 beta 5

**Comment by g2721** [comment]
Is this problem still there?

**Comment by sstaub** [comment]
The problem seems solved with Build 9.
