### ISSUE TITLE
Application start up is paused when window is minimised

### ISSUE THREAD

**Issue by Logicer16** [arduino/arduino-ide#327]
**Describe the bug**
If the loading project Windows is minimised while the application is starting the starting process will not continue and the splash screen will stay visible indefinitely (or at least for an abnormally longer amount of time).

**To Reproduce**
1. Start application
2. Minimise the loading project window
3. Loading will not continue and splash screen stays visible 

**Expected behavior**
Starting will continue or the splash screen will be minimised along with the window

**Screenshots**
![Long](https://user-images.githubusercontent.com/81077770/115137013-c2c91b00-a066-11eb-93dc-b2096e70b7e6.gif)
(Stalls at splash screen for some time)

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.2.3
 - Version: 2.0.0-beta.5-nightly.20210418

**Comment by Silver-Fang** [comment]
OK, so this issue is not fixed for more than a year …

**Comment by Logicer16** [comment]
Even though it won't solve the issue, #717 may make this issue far less noticeable

**Comment by Silver-Fang** [comment]
> Even though it won't solve the issue, #717 may make this issue far less noticeable

So this is an extremely hard-to-fix iceberg bug that involves the design of the underlying architecture?

**Comment by Logicer16** [comment]
> So this is an extremely hard-to-fix iceberg bug that involves the design of the underlying architecture?

I wouldn't say that. I'm not sure what it's causing this, I was just pointing out that the pr I mentioned would make it less noticeable as it allows other windows to be placed on top of the splashscreen
