### ISSUE TITLE
Icon not showing in Linux

### ISSUE THREAD

**Issue by LumitoLuma** [arduino/arduino-ide#329]
**Describe the bug**
Arduino IDE 2.0.0 logo does not show in Linux menu bar/top bar/dock.

**To Reproduce**
1. Open Arduino IDE 2.0.0 for Linux
2. Look the menu bar/top bar/dock

**Expected behavior**
The Arduino IDE 2.0.0 logo should show.

**Screenshots**

![ide_2_logo_not_showing](https://user-images.githubusercontent.com/50250351/115148869-bc847000-a061-11eb-995f-c1a5d7d489a4.png)

**Desktop (please complete the following information):**
 - OS: Debian
 - Version: Testing

**Comment by per1234** [comment]
Hi @LumitoLuma. Thanks for taking the time to submit an issue.

I see we already have a prior issue report about this at https://github.com/arduino/arduino-ide/issues/131.

It's best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
