### ISSUE TITLE
Usability

### ISSUE THREAD

**Issue by mink99** [arduino/arduino-ide#332]
**Is your feature request related to a problem? Please describe.**
The ide is based on a VSCode clone. Therefore it has the same deficiencies in usability as VSCode. To be an IDE that is suitable for beginners and pros, some major improvements should be available.

**Describe the solution you'd like**

1. The VI Style Interface (F1 or some-hard-to-remember-hotkey) and a command line input is not sufficient for beginners. this is because a beginner does not know which commands exist. 
Every action should be available either the top-menu, on a dialog launched from the top-menu, additionally on a context-menu or toolbar.
The menu would have much more entries, eg a view for enabling/disabling the different panes (eg toggle xxx commands etc).
2. Hotkeys should be configurable, eg the debugger should be able to switch the hotkeys from the classic CodeView Hotkeys to the more modern set, that is used in many debuggers, btw F1 is help, not command line.....
3. There are tasks that should be in dialogs, not in the navigation pane on the left, eg the device manager or the library manager.
4. A window switching menu for multiple opened projects would increase productivity if the IDE is in fullscreen
5. Project and per-file settings should be clearly distinguishable, One menu for file related tasks, one for project related.
6. It should be possible to open files which are not part of the project, but eg from a used header, eg as a result from a goto definition or goto implementation.

**Describe alternatives you've considered**
there are many alternative IDE available, so the Arduino IDE should at least be on par with those. The MS Visual Studio UI concept shows how a modern IDE should behave, but also Geany is a good example :
![Image5](https://user-images.githubusercontent.com/11485843/115298204-74e30e80-a15d-11eb-9a5a-fdd94f43c70e.png)

**Additional context**

**Comment by per1234** [comment]
Hi @mink99. Thanks for taking the time to provide some feedback! In the future, please create a separate issue for each distinct feature request or bug report. Having a bunch of unrelated things jumbled together in a single issue makes it very difficult to maintain the repository

>(F1 or some-hard-to-remember-hotkey) and a command line input is not sufficient for beginners. this is because a beginner does not know which commands exist.

All the functionality needed by a beginner is accessible via the menus. The functionality that is exclusively available via the command palette is only for advanced users.

>Hotkeys should be configurable,

Done: https://github.com/arduino/arduino-ide/pull/231

>There are tasks that should be in dialogs, not in the navigation pane on the left, eg the device manager or the library manager.

"Should not" is insufficient justification for making this change.

>It should be possible to open files which are not part of the project, but eg from a used header, eg as a result from a goto definition or goto implementation.

This is already supported. The language server doesn't support all architectures at the moment (example: https://github.com/arduino/arduino-ide/issues/31), so if you have one of those boards selected, or no board at all, then you will find that this functionality doesn't work.

>The MS Visual Studio UI concept shows how a modern IDE should behave,

The Arduino IDE has a very different mission than Visual Studio. This focus has made it something valuable and unique. If Arduino IDE was just a clone of Visual Studio, then there would be no point for its existence. We already have a Visual Studio. If you prefer that IDE, you are welcome to use it.

**Comment by mink99** [comment]
Hi per1234, thank you for taking the time to read my request. Basically it is one topic, that was why i created only one request. There are well established standards on UI Design and Usability, almost all applications follow those. The request was to **follow these standards** too. While not following these well-established standards may make an application unique, this may not render the application valuable, because of the learning curve not only for beginners.
I placed this request to open a discussion on usability.
Unfortunately you did not quite get my points : 

>  If you prefer that IDE, you are welcome to use it.

I was talking about UI and navigation, not about features. The examples from geany, VS, i may add almost _every_ other IDE or Editor should show the expected menu-setup, navigation pane etc. 

>This is already supported. The language server doesn't support all architectures at the moment (example: #31), so if you have one of those boards selected, or no board at all, then you will find that this functionality doesn't work.

nope, this is not even intended to be implemented (opening a header from a referenced library), what you said has nothing to do with what i asked, sorry

> "Should not" is insufficient justification for making this change.

The left pane is used in almost all applications for navigation. "should not" is just a polite wording for just "follow the standards" :) 

> All the functionality needed by a beginner is accessible via the menus. The functionality that is exclusively available via the command palette is only for advanced users.

nope... 
but this makes a great idea : provide two menu sets, one for beginners, one for advanced users, or make the menus configurable.

**Comment by mink99** [comment]
btw 
 > Hotkeys should be configurable, Done: #231

i did not find this feature on the places where expected:
no menu item 
no button on preferences
