### ISSUE TITLE
Add setting to disable "Problems" visibility in editor

### ISSUE THREAD

**Issue by wachidsusilo** [arduino/arduino-ide#335]
### Describe the request

Please add a setting that allows the user to control whether the editor displays "squiggles" for "Problems" diagnostics.

### Describe the current behavior

I'm starting to write my ESP32 project and 'curly red underline' is everywhere although it's compiled fine. It makes my code hard to read.

#### Related

- https://forum.arduino.cc/t/esp32-cam-on-mac-ide-2-3-2-gives-xcode-error/1289981/45

**Comment by per1234** [comment]
Thanks for your suggestion @wachidsusilo. The requested setting was added in https://github.com/arduino/arduino-ide/pull/1811. It disables the display of squiggles for "Problems" in the editor view by default.

For the reference of anyone who does want to enable the display of these squiggles, I'll provide instructions you can follow to do this by adjusting [Arduino IDE's advanced settings](https://github.com/arduino/arduino-ide/blob/main/docs/advanced-usage.md#advanced-settings):

1. Press the <kbd>**Ctrl**</kbd>+<kbd>**Shift**</kbd>+<kbd>**P**</kbd> keyboard shortcut (<kbd>**Command**</kbd>+<kbd>**Shift**</kbd>+<kbd>**P**</kbd> for macOS users) to open the "Command Palette".
   A menu will appear on the editor toolbar:
   ![Command Palette](https://github.com/arduino/arduino-ide/assets/8572152/a117c17d-82f8-417d-addd-221d524b04ea)
1. Select the "**Preferences: Open Settings (UI)**" command from the menu.
   **ⓘ** You can scroll down through the list of commands to find it or type the name in the field.
   A "**Preferences**" tab will open in the Arduino IDE main panel.
1. Type `arduino.language.realTimeDiagnostics` in the "**Search Settings**" field of the "**Preferences**" tab.
1. Check the box under the "**Arduino › Language: Real Time Diagnostics**" setting.
1. Close the **Preferences** tab by clicking its **X** icon.
