### ISSUE TITLE
Format Document not works for me 

### ISSUE THREAD

**Issue by JAICHANGPARK** [arduino/arduino-ide#337]
**Describe the bug**
- I'd like to auto format my code 
- so I tried to format document 
- but It's not working for me

**Screenshots**

![image](https://user-images.githubusercontent.com/19484515/115664238-8b1ae580-a37c-11eb-9c4e-b6c7d5b6ad53.png)

![image](https://user-images.githubusercontent.com/19484515/115664372-b30a4900-a37c-11eb-8ac0-24cad19b6a63.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10 ]
 - Version: [e.g. 2.0.0-beta5]

**Comment by Theagainmen** [comment]
Same here, came to make an issue but see it's already an open one :). 

![image](https://user-images.githubusercontent.com/24569139/116289384-bc3b5180-a792-11eb-981c-070b614cbe1b.png)

**Comment by JAICHANGPARK** [comment]
Any have update this issue?
