### ISSUE TITLE
[not a bug] Thank you for all your work!

### ISSUE THREAD

**Issue by gabrielcsapo** [arduino/arduino-ide#340]
I just wanted to say thank you for everyone who has been working on this project. I am not a daily developer for Arduino but lately after jumping back in after long hiatus this IDE has given me a ton of energy to keep pushing.

The UI is great (the sidebar with all the quick links on the side are nice and compact, the notifications and output and serial monitor all integrated is super compact and way less window management hell), it works and is really fast. The new features and constant improvement is so much appreciated. 

So again, thank you all!

**Comment by per1234** [comment]
Thanks so much for your feedback and kind words @gabrielcsapo!
