### ISSUE TITLE
Show in the Tools dropdown menu the chosen options

### ISSUE THREAD

**Issue by Theagainmen** [arduino/arduino-ide#343]
### Describe the request

Show the value of each custom board option after the menu item in the **Tools** menu, as it is in Arduino IDE 1.x.

### Describe the current behavior

Arduino boards platform authors may define any number of arbitrary ["custom board options"](https://arduino.github.io/arduino-cli/dev/platform-specification/#custom-board-options) for each of the platform's board definitions. These allow the user to adjust the configuration of the board. Some 3rd party platforms have many custom board options.

Custom board options are shown in the Arduino IDE UI as additional menus under the **Tools** menu.

Unlike Arduino IDE 1.x, the value of the custom board options are not shown in the **Tools** menu. The user is unable to see all the settings at a glance simply by opening the **Tools** menu as before. Now the user has to manually holds it mouse over each option to see what's selected.

### Arduino IDE version

2.0.2

### Operating system

All

### Operating system version

Any

### Additional context

In Arduino IDE 1.x, the **Tools** menu shows the selection of the custom board options submenus:

![image](https://user-images.githubusercontent.com/24569139/116289802-176d4400-a793-11eb-810b-c81726769650.png)

Arduino IDE 2.x does not:

![image](https://user-images.githubusercontent.com/24569139/116289847-2522c980-a793-11eb-8668-d88652c84fa4.png)

(note that the board, port, and programmer selections are shown)

All the possible options looks hidden this way, and you have to manually check all of them. My upload speed was wrong for example, and usually you notice that in one go when you open the **Tools** menu. But now you specifically need to hover over each of the custom board option menus to double check these settings.

---

Other reports:

- https://forum.arduino.cc/t/how-to-show-all-tools-settings-in-the-menu/1057883
- https://github.com/arduino/arduino-ide/issues/1434

**Comment by Lorandil** [comment]
That bothers me, too :)

**Comment by DaleMitchell** [comment]
Are there any plans to add this back? @per1234  ?

**Comment by DaleMitchell** [comment]
Are there any plans to add this back? @per1234   ? @AlbyIanna  ?

I very much miss this feature and share the frustration of others that this was removed in Arduino IDE 2.0 for unknown reasons.

This feature allows for easy documentation of options selected for the board, a single screenshot can be taken. Also, it allows for double checking each option at a quick glance without having to tediously hover over each option.
