### ISSUE TITLE
Compilation error: Error: 13 INTERNAL: grpc: error while marshaling: string field contains invalid UTF-8

### ISSUE THREAD

**Issue by EliasA97** [arduino/arduino-ide#345]
When I was using the Pro IDE I could compile without problems. When it became IDE 2.0 it gets me that error.

**Comment by per1234** [comment]
Hi @EliasA97. Thanks for taking the time to submit an issue.

I see we already have a prior issue report about this at https://github.com/arduino/arduino-ide/issues/135.

It's best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
