### ISSUE TITLE
4K monitor support

### ISSUE THREAD

**Issue by WA5X** [arduino/arduino-ide#346]
I am running Windows10 on a 4K monitor. most applications will scale but the arduino ide 1.8.13 that I am using does not scale properly.  The initial splash screen is microscopic. If I set the editor font size to 12 the text is too small for me to read.  If I try to print a code listing it will print at the editor font size so if I either increase font size or scale the interface in the settings menu when I try to print it prints out H U G E !!!  This is unacceptable.   I have to use a different application to print my listings.  This is cumbersome and totally unnecessary. Please fix this.

I suggest that a new setting for print output be added independent of screen font or interface scaling.  I would like to be able to scale up the font or interface for more comfortable coding but still be able to print properly

**Comment by per1234** [comment]
>the arduino ide 1.8.13 that I am using

Hi @WA5X. Thanks for taking the time to submit an issue. This is the repository used for Arduino IDE 2.x beta and onward. Reports related to Arduino IDE versions older than 2.0.0-beta are off topic here so I'll go ahead and close this.

Please give the beta preview of the Arduino IDE 2.0.0 a try. You can download it here:
https://www.arduino.cc/en/software#experimental-software
If you discover any problems with the new IDE version that have not previously been reported, please report them here.
