### ISSUE TITLE
Sketchbook subfolders not supported

### ISSUE THREAD

**Issue by ubidefeo** [arduino/arduino-ide#35]
**Describe the bug**
The Java IDE's **File > Sketchbook** menu is structured according to the folder structure of the sketchbook folder. Sketches in subfolders of the sketchbook are shown in submenus of the File > Sketchbook menu. This is very useful for organization once you accumulate a lot of sketches.

So given this sketchbook structure:
```
{sketchbook folder}
|_ Bar
|    |_ Bar.ino
|_ Foo
|    |_ Foo.ino
|_ sketchbook-subfolder
    |_ Baz
         |_ Baz.ino
```
The Java IDE's *File > Sketchbook* menu looks like this
![ide](https://user-images.githubusercontent.com/1894487/109177941-a0163680-7788-11eb-8dd5-7ca60040583b.png)

IDE 2 currently only recognizes sketches in the root of the sketchbook folder, so given the above sketchbook folder structure, the menu looks like this:
![ide2](https://user-images.githubusercontent.com/1894487/109178582-49f5c300-7789-11eb-8263-1d18598b890d.png)

**Desktop (please complete the following information):**
- OS: Windows 10
- Version: 2.0.0-beta.2-snapshot.298cc11
- CLI Version: 0.16.0 alpha [c977a238

**Additional context**
Sketches in the libraries and hardware subfolders of the sketchbook folder are not affected.

[ originally reported by @per1234 ]

**Comment by kittaakos** [comment]
Closed via https://github.com/arduino/arduino-ide/pull/198.
