### ISSUE TITLE
preferences.txt seems not be applied // error color in console not helpful

### ISSUE THREAD

**Issue by alve89** [arduino/arduino-ide#353]
**Describe the bug**
The color for errors in the console is the same as the "normal" font color. Errors are not obviously displayed.

Also the editor font size is not applied from the preferences.txt.

**To Reproduce**
Generate a compilation error and check the console output

**Expected behavior**
I expected that the errors are displayed in an obvious way.

**Screenshots**
About the error color:
![image](https://user-images.githubusercontent.com/11487054/117115270-2fddef80-ad8d-11eb-9cd4-0bce6c615a49.png)
![image](https://user-images.githubusercontent.com/11487054/117113546-e68ca080-ad8a-11eb-8481-39d8ed252275.png)

About the preferences.txt settings:
![image](https://user-images.githubusercontent.com/11487054/117114406-1be5be00-ad8c-11eb-8f56-5e2bbfb9c061.png)
Screenshot from IDE preferences dialog
![image](https://user-images.githubusercontent.com/11487054/117114457-2e5ff780-ad8c-11eb-9e15-6ef3945a092d.png)

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10 Enterprise
 - Version: 2.0.0-beta.5

**Additional context**
I also added the following line in `C:\Users\sherzog\AppData\Local\Arduino15` (is this the the correct path at all?):
    console.error.color=#ff8c00

**Comment by per1234** [comment]
>The color for errors in the console is the same as the "normal" font color. Errors are not obviously displayed.

Thanks for taking the time to submit an issue @alve89 .

I see we already have a prior issue report about this at https://github.com/arduino/arduino-ide/issues/229.

It's best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.

>Also the editor font size is not applied from the preferences.txt.

This is expected. Arduino IDE 2.x is a complete rewrite of the Arduino IDE. It does not use preferences.txt. You can set the font size in **File > Preferences > Editor font size**.
