### ISSUE TITLE
Installation issue - can't find python

### ISSUE THREAD

**Issue by bobbryce** [arduino/arduino-ide#355]
Fresh install of Arduino IDE 2.0 (Beta 5) on Linux Mint 20.1
Loaded the espressif ESP32 boards and selected ESP32 Dev Board, plugged in actual board and it seems to be detected OK.
Loaded a basic 'Blink' script from the Examples.
Compile fails with the following error
Error: Request compile failed with message: 2 UNKNOWN: exec: "python": executable file not found in $PATH

From the Terminal, typing 'python' gets 'Command not found' but typing 'python3' successfully loads python 3.8.5.

Is there a fix that will not mess with my other apps?

Regards
Bob

**Comment by per1234** [comment]
Thanks for your interest in this open source project. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there:

https://forum.arduino.cc/
