### ISSUE TITLE
New sketch tab tooltip does not have "Unsaved - " prefix on Windows

### ISSUE THREAD

**Issue by ubidefeo** [arduino/arduino-ide#36]
**Describe the bug**
After creating a new sketch (which is stored in a temporary folder), the tooltip shown when hovering over the sketch file tab should have a format like "Unsaved - sketch_feb18b". Once the "Save as..." process has been completed, the "Unsaved - " prefix is no longer shown in the tooltip.
I have verified this behavior on Linux and @ubidefeo has verified it on macOS, but the prefix is never shown on Windows.

**To Reproduce**
1. Start Arduino IDE 2.0.0 on a Windows machine
1. File > New
1. Hover the mouse over the sketch file tab. The tooltip only shows the file name (e.g., "sketch_feb18b").
![tooltip](https://user-images.githubusercontent.com/1894487/109179446-30a14680-778a-11eb-8c2a-f085a00bc0bd.png)

On non-Windows machines it looks like this:
<img width="505" alt="Screenshot 2021-02-18 at 10 51 04" src="https://user-images.githubusercontent.com/1894487/109179464-35fe9100-778a-11eb-9173-e34fa683e8cf.png">

**Expected behavior**
The unsaved status to be displayed

**Desktop (please complete the following information):**
- OS: Windows 10
- Version: 2.0.0-beta.2-snapshot.298cc11
- CLI Version: 0.16.0 alpha [c977a238]

[ originally reported by @per1234 ]

**Comment by kittaakos** [comment]
This is just a guess, but a good one: the issue depends on the length of the Windows username. An [8.3 filename](https://en.wikipedia.org/wiki/8.3_filename) issue has been fixed via https://github.com/arduino/arduino-ide/commit/27a2a6ca033f0a3cd6ae37945940a669fd4dda18. IDE2 compares URI strings, and there was a chance the string match did not work on Windows. Before the change, IDE2 failed to provide a correct result for the [`isTemp`](https://github.com/arduino/arduino-ide/blob/76f9f635d8558f399423f64c0c709e3a53bdcd03/arduino-ide-extension/src/common/protocol/sketches-service.ts#L62-L66) check.

+1 for closing this issue as resolved.
