### ISSUE TITLE
Serial monitor baudrate values: make higher values available

### ISSUE THREAD

**Issue by jerabaul29** [arduino/arduino-ide#362]
It looks like the highest baudrate available in the serial monitor of the IDE 2.0 is 115200 (at least in the version I have). The "traditional" arduino IDE provides higher values, which I enjoy very much on some of my boards (for example, the Sparkfun Artemis boards work fine at baudrate 1000000).

Can we get the higher baudrates available in the IDE 2.x? :) .

**Comment by per1234** [comment]
Hi @jerabaul29. Thanks for taking the time to submit an issue.

I see we already have a prior issue report about this at https://github.com/arduino/arduino-ide/issues/111.

It's best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
