### ISSUE TITLE
Custom boards in hardware dot displaying menu items

### ISSUE THREAD

**Issue by CreativeRobotics** [arduino/arduino-ide#364]
**Describe the bug**
Custom board definitions in the hardware folder (in sketchbook) don't display customised menu options in the IDE.

**To Reproduce**
1 Copy a working set of board files installed with the boards manager (e.g Adafruit SAMD) and place them in the hardware folder in sketchbook
2 open Arduino, the custom boards will be listed, but if you pick a board the menu items will only include serial port, nothing else.

**Expected behavior**
The IDE should display menu items just as it does with board files installed using the boards manager.

**Screenshots**

**Desktop (please complete the following information):**
WIndows 10
IDE 2.0.0

**Comment by per1234** [comment]
Hi @CreativeRobotics. Thanks for taking the time to submit an issue.

I see we already have a prior issue report about this at https://github.com/arduino/arduino-ide/issues/126.

It's best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
