### ISSUE TITLE
Please add the cursor column to the status line

### ISSUE THREAD

**Issue by RudolfAtHome** [arduino/arduino-ide#367]
All IDEs I use show the current line in the status line as well as the current cursor column. But the Arduino IDE only shows the line number. I am very grateful for addition of the column! It's more then enough room.
See examples:

![Examples](https://user-images.githubusercontent.com/8531410/118016083-4370f380-b355-11eb-9f55-1956533b018a.png)
I use German language tools: Zeile -> line, Spalte -> column

**Comment by Lorandil** [comment]
I'm missing that functionality too!
It would even save space in the code window because it would allow to disable the line numbers.

**Comment by Daedelos** [comment]
And Textpad:
![image](https://user-images.githubusercontent.com/25985496/118153914-54317000-b40e-11eb-8aa1-2d76ba26a4b7.png)

**Comment by RudolfAtHome** [comment]
It is based on the Theia IDE framework... And the Theia IDE shows in its status line (right corner):
![Theia](https://user-images.githubusercontent.com/8531410/118408997-9b2a9a00-b688-11eb-9fa3-04c01c01f4de.JPG)

**Comment by per1234** [comment]
For the sake of creating a cross-reference, I'll add a link here to the equivalent Arduino IDE 1.x issue: https://github.com/arduino/Arduino/issues/4403

**Comment by kittaakos** [comment]
2.1.0 shows the line and column numbers.


https://github.com/arduino/arduino-ide/assets/1405703/75c44861-f0cb-495a-99c3-ed7c704ba7c7
