### ISSUE TITLE
Verbose output preferences are not applied correctly

### ISSUE THREAD

**Issue by per1234** [arduino/arduino-ide#374]
## Describe the bug

The **File > Preferences > Show verbose output during** preferences are meant to control the display of verbose output from the compilation or upload processes.

🐛Instead, they are controlling the display of all verbose output during the **Verify** or **Upload** actions.

| Verbose compilation pref | Verbose upload pref | Action | Compile output     | Upload output | Correct   |
| ------------------------ | ------------------- | ------ | ------------------ | ------------- | --------- |
| Unchecked                | Unchecked           | Verify | non-verbose        | NA            | Yes       |
| Unchecked                | Unchecked           | Upload | non-verbose        | non-verbose   | Yes       |
| Checked                  | Unchecked           | Verify | verbose            | NA            | Yes       |
| Checked                  | Unchecked           | Upload | **🐛 non-verbose** | non-verbose   | **🐛 NO** |
| Unchecked                | Checked             | Verify | non-verbose        | NA            | Yes       |
| Unchecked                | Checked             | Upload | **🐛 verbose**     | verbose       | **🐛 NO** |
| Checked                  | Checked             | Verify | verbose            | NA            | Yes       |
| Checked                  | Checked             | Upload | verbose            | verbose       | Yes       |

## To Reproduce

1. Select **File > Preferences** from the Arduino IDE's menus.
2. Check the box next to **Show verbose output during: [ ] compile**
3. Uncheck the box next to **Show verbose output during: [ ] upload**
3. Click the <kbd>OK</kbd> button.
4. Select **Sketch > Upload** from the Arduino IDE's menus.
   **Expected behavior:** verbose output from the compilation process is displayed. verbose output from the upload process is not displayed.
   **Actual behavior:** 🐛 no verbose output is displayed.
1. Select **File > Preferences** from the Arduino IDE's menus.
2. Uncheck the box next to **Show verbose output during: [ ] compile**
3. Check the box next to **Show verbose output during: [ ] upload**
3. Click the <kbd>OK</kbd> button.
4. Select **Sketch > Verify/Compile** from the Arduino IDE's menus.
   **Expected behavior:** verbose output from the compilation process is not displayed. verbose output from the upload process is displayed.
   **Actual behavior:** 🐛 verbose output from both processes is displayed.

## Expected behavior

Verbose output behavior to be aligned with the classic Arduino IDE.

## Desktop

- OS: Windows 10
- Version: Version: 2.0.0-beta.6
Date: 2021-05-12T10:22:48.736Z
CLI Version: 0.18.2 alpha [7b5a22a4]

## Additional context

Originally reported at: https://forum.arduino.cc/t/preferences-setting-mixup/862092

**Comment by JonnyPhenomenon** [comment]
Yeah, wow. this one is all messed up. 
I too identified this issue.
