### ISSUE TITLE
Autocomplete not working for object Serial

### ISSUE THREAD

**Issue by alexarnoldi** [arduino/arduino-ide#378]
The code completation doesn't work for Serial object , The IDE give me this error
 when i type Serial.begin(9600) : 

Use of undeclared identifier 'Serial'clang(undeclared_var_use)

OS: Windows 10
Version: 2.0 beta 6

**Comment by per1234** [comment]
Thanks for taking the time to submit an issue @alexarnoldi .

I see we already have a prior issue report about this at https://github.com/arduino/arduino-ide/issues/159.

It's best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
