### ISSUE TITLE
Method tooltips show for a fraction of a second

### ISSUE THREAD

**Issue by Markz878** [arduino/arduino-ide#386]
Several method tooltips, like String.substring, String.ToInt and String.length are visible for about 0.1 seconds when hovered, making it impossible to read the signatures/hints.

**Comment by kittaakos** [comment]
> are visible for about 0.1

This could be a language server issue. @Markz878, which board did you select?
Possibly related: https://github.com/arduino/arduino-language-server/issues/68.

**Comment by per1234** [comment]
I'm going to go ahead and close this as resolved. If anyone is still having this problem, please comment here and I'll investigate.
