### ISSUE TITLE
Posibility to open .ino files via explorer

### ISSUE THREAD

**Issue by fm-sys** [arduino/arduino-ide#389]
Currently, if you select the Arduino IDE 2.x as target app in the Windows explorer, nothing happens. Arduino IDE 2.x just starts without loading the file. Would be pretty cool if files can be opened via explorer instead of only inside the software.

**Comment by kittaakos** [comment]
Same as: https://github.com/arduino/arduino-ide/issues/72
Related: https://github.com/arduino/arduino-ide/issues/370

**Comment by per1234** [comment]
Thanks Akos!

Since @fm-sys was kind enough to add a note to https://github.com/arduino/arduino-ide/issues/72 about it not being macOS-specific, I'll go ahead and close this as a duplicate. It's best to have only a single issue per subject so we can consolidate all relevant discussion to one place.
