### ISSUE TITLE
Compilation error: Error: 2 UNKNOWN: no FQBN provided

### ISSUE THREAD

**Issue by LieKeWu** [arduino/arduino-ide#393]
What is the meaning of the term FQBN?

How should this report error be resolved?

**Comment by per1234** [comment]
Hi @LieKeWu. Thanks for taking the time to submit an issue.

I see we already have a prior issue report about this error message being unclear at https://github.com/arduino/arduino-ide/issues/62, and also a proposal for an improvement to the first use experience here https://github.com/arduino/arduino-ide/issues/56.

It's best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you would like assistance with using the Arduino IDE 2.x, please make a topic in the Arduino Forum's dedicated category here:
https://forum.arduino.cc/c/software/arduino-ide-2-0-beta/93
I'll be happy to help you out over there.
