### ISSUE TITLE
Bug - inconsistent syntax in beta IDE

### ISSUE THREAD

**Issue by utherbone** [arduino/arduino-ide#395]
**Some syntax UNDECLARED INDENTIFIER**
Similar to: https://github.com/arduino/arduino-ide/issues/291 and archived repo: https://github.com/arduino/arduino-pro-ide/issues/244

**Reproduce this bug**

1. chage board to STM32
2. IDE show insues UNDECLARED INDENTIFIER

**Expected**
Even with this syntax bug it compiles and uploads correctly, I tested in ide 1.x this does not occur.

**Screenshots**
![image](https://user-images.githubusercontent.com/13210391/120591316-53d73400-c412-11eb-9eef-4f356830c8d9.png)

**Distribution:**
 - OS: Ubuntu
 - Version: 20.04.2 LTS
**Kernel:**
 - kernel: Linux
 - Version: 5.4.0-73-generic 

**Additional context**
I searched here did not find much about the new updates I hope have helped. sharing what happened

If change to board AVR nano shows this:
![image](https://user-images.githubusercontent.com/13210391/120592041-8c2b4200-c413-11eb-908f-c08fcc1c3b09.png)

**Comment by per1234** [comment]
Thanks for taking the time to submit an issue @utherbone .

I see we already have a prior issue report about this at https://github.com/arduino/arduino-ide/issues/220.

It's best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
