### ISSUE TITLE
Add Comment / Uncomment to context menu

### ISSUE THREAD

**Issue by tistructor** [arduino/arduino-ide#398]
The Comment / Uncomment item is absent from the quick menu associated with the right mouse button (MLB).

Put the command in that menu as it is inconvenient to use the main menu to use the command.

<img width="248" alt="Cattura" src="https://user-images.githubusercontent.com/24445373/120782436-48772c00-c52a-11eb-8ee1-086531bdaca8.PNG">
<img width="397" alt="Cattura1" src="https://user-images.githubusercontent.com/24445373/120782445-4a40ef80-c52a-11eb-810b-9ce996eefc40.PNG">

SO: Windows10
Version: 2.0.0-beta.7
Date: 2021-05-17T10:10:22.608Z
CLI Version: 0.18.3 alpha [d710b642]

**Comment by per1234** [comment]
Hi @tistructor. Thanks for taking the time to submit this issue.

I see we already have a prior request about this at https://github.com/arduino/arduino-ide/issues/223.

It's best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
