### ISSUE TITLE
Allow Serial Monitor to be Viewed After Disconnecting 

### ISSUE THREAD

**Issue by Logicer16** [arduino/arduino-ide#400]
**Is your feature request related to a problem? Please describe.**
When removing a board that had its output displayed on the serial monitor, the serial monitor will clear and begin trying to repeatedly reconnect. For example, a user may want to analyse the output of an board without being bombarded with now messages, or where a board is a shared resource and serial output is used to get debug information that can be worked on while someone else uses the board.

**Describe the solution you'd like**
The serial monitor should not clear after the board is disconnected and instead. Also there should be an option to enable auto-reconnect to stop messages potentially blocking the serial monitor (similar to arduino/arduino-ide#314), and instead show a single message giving the user the option to begin the auto-reconnect process.

**Describe alternatives you've considered**
- Turning off auto-scroll allows the messages to be viewed but not highlighted or copied (#247, arduino/arduino-ide#167). 
- Also, as this could be done in the original Arduino IDE, a user could have both installed and use 2.x for development and 1.x for the serial monitor though that would be extremely inconvenient.

**Comment by per1234** [comment]
This was fixed somewhere between the 2.0.0-rc1 and 2.0.0-rc2 releases. I guess it must have been one of the changes in https://github.com/arduino/arduino-ide/pull/661
