### ISSUE TITLE
Uninstalling a platform or library does not update the version SELECT drop-down

### ISSUE THREAD

**Issue by ubidefeo** [arduino/arduino-ide#417]
**Describe the bug**
Installing a platform or a library refreshes the boards/libraries manager tab, displaying the version older than the one just installed in the drop-down menu as a pre-selected option (for downgrade).
Uninstalling leaves the select menu in its last state, with the previous version selected, not the latest available

**To Reproduce**
1. Install a platform or a library at its latest version
2. verify that the drop-down changes to the older version
3. uninstall the platform
4. verify that the drop-down has not changed

**Expected behavior**
uninstalling should reset the position of the drop-down

**Screenshots**
before uninstalling
<img width="473" alt="Screenshot 2021-06-16 at 15 24 27" src="https://user-images.githubusercontent.com/1894487/122227905-9fc8b500-ceb7-11eb-8cc0-9dcf2df67d8f.png">

after uninstalling
<img width="386" alt="Screenshot 2021-06-16 at 15 24 47" src="https://user-images.githubusercontent.com/1894487/122227955-aeaf6780-ceb7-11eb-8268-1c64fd0ada32.png">

**Desktop (please complete the following information):**
 - OS: Mac OS Big Sur
 - Version: 11.2.3

**Comment by ubidefeo** [comment]
this issue is not present in RC9

**Comment by per1234** [comment]
I can still reproduce the issue with the latest build (2.0.0-rc9-snapshot-55927ac). However, I think it is fine to consider it a "wontfix", since the behavior is unlikely to cause problems in real world usage.
