### ISSUE TITLE
Adding support for Pololu Orangutan board loses "Programmer" item in Tools menu

### ISSUE THREAD

**Issue by ChrisBalmforth** [arduino/arduino-ide#420]
The Pololu Orangutan is an AVR 328 based robot controller board. Adding support in the Arduino v1 IDE is documented here https://www.pololu.com/docs/0J17  This works fine with the linux version of v1.8.13  When I follow the same procedure with ide v2.0.0-beta7 the board is available in Board Manager, but the Orangutan examples are greyed out in the Examples menu and the Programmer item disappears completely from the Tools menu. Sketches compile OK, but attempting to upload a sketch gives the error message "Upload error: Error: 2 UNKNOWN: a programmer is required to upload for this board"

1. Add a "hardware" sub-folder to the Sketches folder if not already present.
2. Download the zip file https://www.pololu.com/file/0J1229/libpololu-arduino-161018.zip and unzip the folder libpololu-arduino to the hardware sub-folder.
3. Re-start the IDE and select one of the Orangutan boards from the Tools menu.
4. Open the Tools menu again and the Programmer entry has disappeared.

I am running Linux Mint 20.1 on a HP Envy laptop.

[libpololu-arduino-161018.zip](https://github.com/arduino/arduino-ide/files/6676385/libpololu-arduino-161018.zip)
[orangutan_arduino.pdf](https://github.com/arduino/arduino-ide/files/6676394/orangutan_arduino.pdf)

**Comment by per1234** [comment]
Hi @ChrisBalmforth. Thanks for taking the time to report this bug.

I see we already have a prior issue report about this at https://github.com/arduino/arduino-ide/issues/126.

It's best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.

For now, only Boards Manager installation of Arduino boards platforms is supported by Arduino IDE 2.x. If the developers of the boards platform you are using did not make the effort to provide that installation method, you'll need to continue to use the classic Arduino IDE until support has been added for manually installed platforms.
