### ISSUE TITLE
library management on a per-project basis, with a "requirements" file and / or a "lib" folder

### ISSUE THREAD

**Issue by jerabaul29** [arduino/arduino-ide#424]
At present, working with several projects requiring similar libraries in different versions is, as far as I know, quite painful.

I wonder if it would be nice on the Arduino IDE to get some slightly better library management system? :) 

What about something like:

- have a ```lib``` folder by default in each sketchbook, where one can drop either arduino compatible libraries, or other kinds of libraries? Of course the user can set it up himself now, but would be great to "establish a standard".

- have a "requirements" file or similar at the root of each sketchbook, where one can list libraries and their versions, in combination with the possibility to install several versions of each library on a given machine.

Agree that then this starts to look more like platformio than the "old" arduino ide, but I guess that this is anyways the direction things are going to slowly but steadily when wanting to turn the arduino ide into a more full-featured tool :) .

**Comment by per1234** [comment]
Hi @jerabaul29. Thank for your suggestions.

>have a lib folder by default in each sketchbook, where one can drop either arduino compatible libraries, or other kinds of libraries?

I see we already have a prior issue report about this at https://github.com/arduino/arduino-cli/issues/1255.

>have a "requirements" file or similar at the root of each sketchbook, where one can list libraries and their versions, in combination with the possibility to install several versions of each library on a given machine.

I see we already have multiple issues about this, including: https://github.com/arduino/arduino-cli/issues/1321, https://github.com/arduino/arduino-cli/issues/1011, https://github.com/arduino/arduino-cli/issues/108

It's best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the others.

If you end up with additional information to share, feel free to comment in the other threads.
