### ISSUE TITLE
protecting the existing code from flashing without verification. creating authorized embedding technique  

### ISSUE THREAD

**Issue by Mubarikneja** [arduino/arduino-ide#425]
** feature-request **: user authentication for updating/flashing the existing code

**the problem? ** anyone who installs the IDE can update/flash the device.

** the solution **: there should be some portion from EEPROM to store user credentials to verify before updating/flash the existing program.

how? is my question.

**Comment by per1234** [comment]
Hi @Mubarikneja. Thanks for your interest in this open source project. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to have a productive discussion and proposals regarding this topic over there:

https://forum.arduino.cc/
