### ISSUE TITLE
Serial Port is attached to one open instance of Arduino IDE

### ISSUE THREAD

**Issue by embhobbb** [arduino/arduino-ide#426]
I am using older Arduino from long and i am really liked it. And i am very impressed with new GUI of the ARDUINO IDE 2.0. 
But one improvement can be done on Serial Connection.  Serial connection is attached to one open instance of the Arduino IDE.
(I understand that each instance has different Serial Terminal).

There can be option given for disconnecting Serial connection. This will help us a lot.

**Comment by per1234** [comment]
Hi @embhobbb. Thanks for taking the time to submit an issue.

I see we already have a prior issue report about this at https://github.com/arduino/arduino-ide/issues/271.

It's best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
