### ISSUE TITLE
Hover popups cover items you are trying to select or right click on

### ISSUE THREAD

**Issue by toogooda** [arduino/arduino-ide#428]
**Describe the bug**
One of the nice new features about the IDE is the helpful hover popups for errors and definitions. Unfortunately the definition popups are not placed well. More often than not the cover the item you are hovering, and with the hoover duration so short you cannot select or right click on items due to a popup covering it entirely. This happens more often at the top of a sketch. 
Other times it flashes the disappears before it can be read, this tends to happen when there is no room below it at the bottom of a sketch 
The placement of ones showing undeclared errors are always in the same place and work `well.

**To Reproduce**
1. Go to any large sketch
2. Hover over function calls or macros at top and bottom of the sketch
3. popup will cover content or disappear

**Expected behavior**
Popup with either show directly above or directly below depending on where it will fit

**Screenshots**
![visible](https://user-images.githubusercontent.com/9059644/123702578-6cbef200-d8b7-11eb-8b50-6982f732cbc7.png)
![Covered](https://user-images.githubusercontent.com/9059644/123702656-82ccb280-d8b7-11eb-8ff5-74e59d02797d.png)

**Desktop (please complete the following information):**
 - Windows10
 - Screen Resolution 1920x1080

**Additional context**

**Comment by per1234** [comment]
Hi @toogooda. Thanks for taking the time to submit an issue.

I see we already have a prior issue report about this at https://github.com/arduino/arduino-language-server/issues/68 (once the language server is fixed the hover hover behavior in the IDE should be automatically fixed without any need to modify the code base here).

It's best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
