### ISSUE TITLE
Port selection of Portenta H7 (M4 Core) is lost on every upload

### ISSUE THREAD

**Issue by ubidefeo** [arduino/arduino-ide#43]
### Describe the problem

When uploading to the M4 core of the **Arduino Portenta H7** board, the port selection is lost.

🐛 It is inconvenient for the user to have to reselect the port after every upload, and may cause confusion if they didn't notice this happened.

#### Equipment

- [Arduino Portenta H7](https://store.arduino.cc/products/portenta-h7)

#### Steps

1. Use **Boards Manager** to install version **3.5.4** of the "**Arduino Mbed OS Portenta Boards**" platform.
   **ⓘ** Versions 4.0.2 and newer do not provide the required conditions to reproduce the fault due to https://github.com/arduino/ArduinoCore-mbed/commit/29184e93ae0ef4d03b3e0bcca74caaa52b4182eb
1. Select **File > New** from the Arduino IDE menus.
1. Connect a "**Portenta H7**" board to your computer.
1. Select **Tools > Board > Arduino Portenta H7 (M4 Core)** from the Arduino IDE menus.
   ![image](https://user-images.githubusercontent.com/8572152/186387961-7148ba5f-58f7-4473-8d8b-21a153b09d9a.png)
1. Select the port of the board from the **Tools > Port** menu.
1. Select **Sketch > Upload** from the Arduino IDE menus.
1. Wait for the upload to finish.
1. Open the **Tools > Port** menu.

🐛 The port is no longer selected. You must select the port from the menu again after every single upload to this board.

![image](https://user-images.githubusercontent.com/8572152/186388278-6454620d-8304-4234-a8bb-9f05791767c2.png)

### Expected behavior

The port selected by the user remains selected after uploading.

#### Original report

2.0.0-beta.2-snapshot.f9730ab

#### Last verified with

2.0.0-rc9.2.snapshot-ca47e8a

### Operating system

Windows

### Operating system version

10

### Additional context

I suspect this is related to the behavior of the port of the native USB boards, where the USB CDC serial port disappears and reappears during the switch from the bootloader to the sketch application.

The **Portenta H7** is unique in that it has two different board definitions, but only one of these ("**Arduino Portenta H7 (M7 Core)**") is [associated with the USB VID/PID of the port](https://arduino.github.io/arduino-cli/dev/platform-specification/#:~:text=If%20the%20platform%20supports%20pluggable%20discovery%20it%20may%20also%20declare%20a%20set%20of%20upload_port.*%20properties):

https://github.com/arduino/ArduinoCore-mbed/blob/3.2.0/boards.txt#L104-L111

```text
envie_m7.upload_port.0.vid=0x2341
envie_m7.upload_port.0.pid=0x025b
envie_m7.upload_port.1.vid=0x2341
envie_m7.upload_port.1.pid=0x035b
envie_m7.upload_port.2.vid=0x2341
envie_m7.upload_port.2.pid=0x045b
envie_m7.upload_port.3.vid=0x2341
envie_m7.upload_port.3.pid=0x055b
```

This causes the Arduino IDE's automatic board selection to lose the port selection when the selected board doesn't match the VID/PID of the port that appears at the end of the upload process.

---

Originally reported at: https://forum.arduino.cc/t/0-1-0-portenta-wonders-ide-released/671634/7

> I am able to build these and get them both onto the board and run, but it seems in this arrangement, the IDE windows commonly wind up reporting "not connected" in the lower right status bar.
> I'm completely new to this IDE so I am curious if I should have the expectation that the connection status should be live whether the target sketch is running or not..
> I also noticed that the second session I opened for the M4 sketch, I had to tell it over and over which board and port to target.  I got the impression that having both sketches open might be causing a fight for the link.

---

Another variant of this bug was reported at https://github.com/arduino/arduino-ide/issues/82

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

**Comment by salasidis** [comment]
I realize this is an old thread, but did you ever fix the issue.

I have a new Portenta H7, that does exactly what yours was doing.

I can uplad a sketch when putting the Portenta into Bootloader mode (two pushes on reset button).

Once the sketch is uploaded, the serial port disappears, and I cannot connect with the serial monitor as a result. The program runs though.

I have to push the reset twice again to make the port reappear to reload the sketch.

**Comment by per1234** [comment]
@salasidis that is a different problem than what is tracked here. This issue is about the port selection in the IDE being lost, not the loss of the port itself on the board.

The former is a bug in the Arduino IDE. The latter is a bug in the firmware running on your Portenta H7, and so off topic for this repository dedicated to the Arduino IDE code base. I see you have already posted to the appropriate place on the Arduino forum and are receiving assistance there:

https://forum.arduino.cc/t/serial-com-port-issues-with-portenta-h7/982875
