### ISSUE TITLE
Hope Can Install Extension Improve User Experience, Just Like VSCode!!!

### ISSUE THREAD

**Issue by minexo79** [arduino/arduino-ide#440]
Like Topic!!

**Comment by per1234** [comment]
Hi @minexo79. Thanks for taking the time to submit a feature request.

I see we already have a prior issue report about this at https://github.com/arduino/arduino-ide/issues/207.

It's best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
