### ISSUE TITLE
Make "minimap" feature accessible via the primary UI

### ISSUE THREAD

**Issue by CptHolzschnauz** [arduino/arduino-ide#448]
### Describe the request

Like they do in Visual Studio Code. A code miniature view at the right scrollbar:

<img width="323" alt="Bildschirmfoto 2021-07-11 um 07 39 08" src="https://user-images.githubusercontent.com/68701579/125190786-2b2b3100-e23f-11eb-8de5-af9dc31262ce.png">

### Describe the current behavior

In long sketches you often need the scroller at the right and the thumbnail view  is used for orientation.

### Arduino IDE version

76f9f635d8558f399423f64c0c709e3a53bdcd03

### Operating system

All

### Operating system version

Any

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My request contains all necessary details

**Comment by CptHolzschnauz** [comment]
For other minibar lovers who found this thread: just change to
`"editor.minimap.enabled": true`
in bundle.js and index.js.
Too little for a pull request.

**Comment by kittaakos** [comment]
> just change to
> `"editor.minimap.enabled": true`
> in bundle.js and index.js.

The minimap is disabled by default. One can use more convenient ways to enable the minimap:

1. _Command Palette_:
  - <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>,
  - type `View: Toggle Mininap`, and
  - press <kbd>Enter</kbd>.

<img width="540" alt="Screen Shot 2023-05-11 at 09 45 39" src="https://github.com/arduino/arduino-ide/assets/1405703/18df8f8b-5a61-41ec-b983-5903fa6a2a41">

2. Use [Advanced settings](https://github.com/arduino/arduino-ide/blob/main/docs/advanced-usage.md#advanced-settings) UI:
 - <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>,
 - type `Preferences: Open Settings (UI)`,
 - type `minimap` in the search field, and
 - click the checkbox to have the minimap in IDE2.

![Screen Shot 2023-05-11 at 09 47 24](https://github.com/arduino/arduino-ide/assets/1405703/dd115343-06c5-424c-b2f4-4363a765a1b6)

3. Configure the advanced settings in the `settings.json`:
 - <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>,
 - type `Preferences: Open Settings (JSON)`, and
 - add the `"editor.minimap.enabled": true`.

![Screen Shot 2023-05-11 at 09 50 49](https://github.com/arduino/arduino-ide/assets/1405703/af397b4b-ca92-40e9-8d86-4fbc89e139da)

```jsonc
{
  // other settings
  "editor.minimap.enabled": true`
  // maybe more settings
}
```

The minimap can be enabled from the primary UI without modifying any files inside the application. I am closing it as _won't do_.

If you disagree, please ping me, and we can discuss it.
If you maintainer, reopen the ticket.

Thanks!
