### ISSUE TITLE
UFT-8 multibyte characters are broken when using the "Pull" function on your Remote Sketchbook

### ISSUE THREAD

**Issue by BlackBrix** [arduino/arduino-ide#449]
### Describe the problem

When you do a "Pull" on a file in your Remote Sketchbook that contains UTF-8 multibyte characters, these characters are not displayed correct in Arduino IDE.

### To reproduce

1. Create a sketch in Arduino Web Editor that contains UFT-8 multibyte characters.
   Here's my shared one as an example:   https://create.arduino.cc/editor/Dirk67/d86881f0-faf3-48cd-8097-ce9915bb1ca0/preview .  
2. Sync Remote Sketchbook in Arduino IDE.
3. Pull the sketch you created in step 1.  
4. Open this sketch in Arduino IDE
5. Compare the display of the UFT-8 multibyte characters within Arduino IDE to the characters as they are displayed in "Arduino Web Editor".

![image](https://user-images.githubusercontent.com/8572152/138600747-b7e5091b-2bfa-419e-9dff-825113b6013c.png)

### Expected behavior

UFT-8 multibyte characters, should always display correctly.

### Arduino IDE version

2.0.0-beta.9

### Operating system

Windows

### Operating system version

10

### Additional context

Additional reports:

- https://github.com/arduino/arduino-ide/issues/1874
- https://github.com/arduino/arduino-ide/issues/1509

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
>What's your opinion on this, @per1234?

I think it is a very useful feature. It is common to see forum posts from people asking for help with cryptic compilation errors like:

```text
C:\Users\per\Documents\Arduino\sketch_feb21a\sketch_feb21a.ino:3:16: error: stray '\342' in program
   Serial.print(“don’t use smart quotes in code”);
                ^
C:\Users\per\Documents\Arduino\sketch_feb21a\sketch_feb21a.ino:3:17: error: stray '\200' in program
   Serial.print(“don’t use smart quotes in code”);
                 ^
C:\Users\per\Documents\Arduino\sketch_feb21a\sketch_feb21a.ino:3:18: error: stray '\234' in program
   Serial.print(“don’t use smart quotes in code”);
                  ^
C:\Users\per\Documents\Arduino\sketch_feb21a\sketch_feb21a.ino:3:22: error: stray '\342' in program
   Serial.print(“don’t use smart quotes in code”);
                      ^
C:\Users\per\Documents\Arduino\sketch_feb21a\sketch_feb21a.ino:3:23: error: stray '\200' in program
   Serial.print(“don’t use smart quotes in code”);
                       ^
C:\Users\per\Documents\Arduino\sketch_feb21a\sketch_feb21a.ino:3:24: error: stray '\231' in program
   Serial.print(“don’t use smart quotes in code”);
                        ^
C:\Users\per\Documents\Arduino\sketch_feb21a\sketch_feb21a.ino:3:51: error: stray '\342' in program
   Serial.print(“don’t use smart quotes in code”);
                                                   ^
C:\Users\per\Documents\Arduino\sketch_feb21a\sketch_feb21a.ino:3:52: error: stray '\200' in program
   Serial.print(“don’t use smart quotes in code”);
                                                    ^
C:\Users\per\Documents\Arduino\sketch_feb21a\sketch_feb21a.ino:3:53: error: stray '\235' in program
   Serial.print(“don’t use smart quotes in code”);
                                                     ^
C:\Users\per\Documents\Arduino\sketch_feb21a\sketch_feb21a.ino:4:18: error: stray '\342' in program
   Serial.println(‘!’);
                  ^
C:\Users\per\Documents\Arduino\sketch_feb21a\sketch_feb21a.ino:4:19: error: stray '\200' in program
   Serial.println(‘!’);
                   ^
C:\Users\per\Documents\Arduino\sketch_feb21a\sketch_feb21a.ino:4:20: error: stray '\230' in program
   Serial.println(‘!’);
                    ^
C:\Users\per\Documents\Arduino\sketch_feb21a\sketch_feb21a.ino:4:22: error: stray '\342' in program
   Serial.println(‘!’);
                      ^
C:\Users\per\Documents\Arduino\sketch_feb21a\sketch_feb21a.ino:4:23: error: stray '\200' in program
   Serial.println(‘!’);
                       ^
C:\Users\per\Documents\Arduino\sketch_feb21a\sketch_feb21a.ino:4:24: error: stray '\231' in program
   Serial.println(‘!’);
                        ^
C:\Users\per\Documents\Arduino\sketch_feb21a\sketch_feb21a.ino: In function 'void setup()':
C:\Users\per\Documents\Arduino\sketch_feb21a\sketch_feb21a.ino:3:19: error: 'don' was not declared in this scope
   Serial.print(“don’t use smart quotes in code”);
                   ^~~
C:\Users\per\Documents\Arduino\sketch_feb21a\sketch_feb21a.ino:3:19: note: suggested alternative: 'tone'
   Serial.print(“don’t use smart quotes in code”);
                   ^~~
                   tone
C:\Users\per\Documents\Arduino\sketch_feb21a\sketch_feb21a.ino:4:25: error: expected primary-expression before ')' token
   Serial.println(‘!’);
                         ^
```

This is caused by website software or word processors prettying up code text by doing things like replacing correct straight quotes with "[smart quotes](https://en.wikipedia.org/wiki/Quotation_mark#Curved_quotes_within_and_across_applications)".

So I would leave the feature enabled, but we can consider refining the default "Unicode Highlight" settings if we see indications that specific aspects of the current settings are producing a poor UX. Unfortunately I see that the most common culprit: the curved double quote is not even highlighted with the current defaults.
