### ISSUE TITLE
Autoformat might remove characters from method declarations

### ISSUE THREAD

**Issue by rsora** [arduino/arduino-ide#45]
**Describe the bug**
declaring a function like this in the `.ino` files

```c
void     foo(int i, float x, void* ptr) {}
```

(please note the extra spaces)

and calling the autoformat might cause the autoformat to remove some characters:

```c
void foo(int i, float x,  vid *ptr) {}
```

(please note the missing `o` in `void`)

**To Reproduce**
1. Open new sketch
2. Write the following function: `void     foo(int i, float x, void* ptr) {}`
3. **Tools > Autoformat**
4. See error on `vid` type in function declaration

**Expected behavior**
Function correctly formatted like:
```c
void foo(int i, float x, void *ptr) {}
```

**Screenshots**
![image](https://user-images.githubusercontent.com/35916119/109286743-f2a43100-7822-11eb-8856-8f12b3296810.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.4 LTS 64bit
- Version: 2.0.0-beta.3-snapshot.9fb8c4b
- Date: 2021-02-25T15:29:51.087Z
- CLI Version: 0.16.1 alpha [76f55490]

**Comment by per1234** [comment]
I was not able to reproduce this, even using 2.0.0-beta.3. However, any of these content loss issues should be solved by https://github.com/arduino/arduino-ide/pull/1019

If anyone is still able to reproduce this issue using [the latest nightly build](https://github.com/arduino/arduino-ide#nightly-builds), please comment here and I will investigate.
