### ISSUE TITLE
Creating files for a project

### ISSUE THREAD

**Issue by VladimirVecera** [arduino/arduino-ide#456]
Does the new Arduino IDE allow you to create files within a project that will be visible to the project and easy to insert via #include?
If this feature already works, how do I get it? There is only a sketchbook.

**Comment by per1234** [comment]
Hi @VladimirVecera. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. We have a dedicated forum category just for Arduino IDE 2.x. I'm sure we'll be able to help you with your problem over there:

https://forum.arduino.cc/c/software/arduino-ide-2-0-beta/93
