### ISSUE TITLE
How do I upload my code to my Ardino Uno???

### ISSUE THREAD

**Issue by leo7878** [arduino/arduino-ide#458]
When I have my finished written code and have selected my board and port it always comes up with: Error: Request upload failed with message: 2 UNKNOWN: exit status 1. How do I fix this issue someone please tell me!(I am on Mac)

**Comment by per1234** [comment]
Hi @leo7878. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum, where we have a dedicated forum category just for Arduino IDE 2.x. I'm sure we'll be able to help you with your problem over there:

https://forum.arduino.cc/c/software/arduino-ide-2-0-beta/93
