### ISSUE TITLE
Arduino IDE 2.0 check for update

### ISSUE THREAD

**Issue by versamodule** [arduino/arduino-ide#468]
I have to say, I am shocked at how long it took you guys to see the light and get to IDE 2.0.  
Whats even more nuts is that there is no " Check For Update" feature.

**Comment by per1234** [comment]
Hi @versamodule. Thanks for taking the time to submit an issue.

I see we already have a prior issue report about this at https://github.com/arduino/arduino-ide/issues/361.

It's best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
