### ISSUE TITLE
Better contrast for icons in Dark (Theia) theme

### ISSUE THREAD

**Issue by nandanvasudevan** [arduino/arduino-ide#478]
### Describe the problem

In "**Dark (Theia)**" theme, the top toolbar icons could use better contrast.

### Expected behavior

Consider a lighter fill colour like the gray used for the other icons or maybe even white.

### Arduino IDE version

2.0.0-beta.10

### Additional context

![image](https://user-images.githubusercontent.com/28172619/129448116-a0d4af36-8ebc-45ae-9d73-efc4c5459fcb.png)

The icons are really hard to view when I have my blue light filter ON. Even otherwise they can surely use more contrast.

**Comment by nandanvasudevan** [comment]
Just found developer tools and set it to white. I find this to be much better. Goes better with the theme too.
![image](https://user-images.githubusercontent.com/28172619/129448329-53075639-75e9-48dd-9573-c4356b15d7d8.png)

**Comment by ubidefeo** [comment]
with our own themes being implemented and styled this issue seems irrelevant.
Please confirm @91volt

**Comment by 91volt** [comment]
Yes, I confirm that Arduino Dark theme provide an accessible contrast in toolbar actions. 
This issue can be considered solved for me
<img width="179" alt="Schermata 2022-07-29 alle 15 26 40" src="https://user-images.githubusercontent.com/92443068/181770270-64604af7-12e7-42f1-a045-4bd2089da8bd.png">
.
