### ISSUE TITLE
Unable to start server

### ISSUE THREAD

**Issue by bansalshashank** [arduino/arduino-ide#488]
**Describe the bug**
when starting the server using yarn start getting this error:

```
daemon INFO Starting daemon from /home/s1stard/public_html/arduino-ide/arduino-ide-extension/build/arduino-cli...
root ERROR Could not start contribution Error: Unknown or unsupported transport “disabled” for address “disabled:”
root ERROR Uncaught Exception:  Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
root ERROR Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at process.target.send (internal/child_process.js:678:16)
    at /home/s1stard/public_html/arduino-ide/electron-app/src-gen/backend/main.js:12:17
```

**Comment by fstasi** [comment]
@bansalshashank how did you compile the IDE2?

did you built both the browser and the electron part following the readme?

If so, can you please provide the full log in order to help us providing you support?

Thanks

**Comment by per1234** [comment]
Hi @bansalshashank. We are still waiting for you to provide the information requested in the previous reply so that we can proceed with the investigation or evaluation of this.

**Comment by per1234** [comment]
Closing due to lack of response.

@bansalshashank if you will provide the requested information by commenting here, I'll be happy to re-open this issue.
