### ISSUE TITLE
Change the default port: `/dev/ttyS0->/dev/ttyUSB0`

### ISSUE THREAD

**Issue by nagayev** [arduino/arduino-ide#490]
Hello. I have tried to upload my sketch to UNO board and I coudn't.
So I had to run dmesg and then I see that arduino recognised as ttyUSB0 device, not as default ttyS0.
So I suppose to change the default port to USB. It's actual espessialy for boards whose connected using USB like my UNO.

**Comment by ckuethe** [comment]
So much this. Either `ttyUSB0` or `ttyACM0`are likelier to be arduino devices than `ttyS0`

**Comment by per1234** [comment]
Possibly related: https://github.com/arduino/serial-discovery/issues/37

**Comment by per1234** [comment]
Arduino IDE 2.x does not have default ports. By default, no port is selected. If you select a board and port, then that selection is associated with the sketch. This might give the impression that a default port is coded into the IDE, but it is actually only the port you selected, which can be changed by selecting a different port.

The possibly related issue I mentioned above https://github.com/arduino/serial-discovery/issues/37 has been resolved.
