### ISSUE TITLE
Startup Background Colour (dependent on Theme selection)

### ISSUE THREAD

**Issue by specs32** [arduino/arduino-ide#498]
Please have the Startup Background colour set Dark if the Dark Theme is configured in the IDE, otherwise i have that glaring white screen in my face for 10 seconds until the app with the dark theme is loaded. 

I am using a very large monitor with high contrast which is consistently dark themed, so if Arduino startup goes full screen white I am blind for a minute... 

Thanks for all your good work !!!!!!
greetings.

#### Last verified with

2.0.0-rc8-snapshot-f4a68e7
Windows 10

**Comment by kittaakos** [comment]
It should be like that. See the upstream changes: https://github.com/eclipse-theia/theia/pull/11570. I am closing it as resolved.

If anybody disagrees, please ping me, and we can discuss this issue.
