### ISSUE TITLE
Warning triangle next to board and com port

### ISSUE THREAD

**Issue by moth4017** [arduino/arduino-ide#500]
V2 beta 11, windows Pro v10

Why is there a Warning triangle next to board and com port

It seems to have no warning anywhere in the notification window, nor does it stop you up loadiing to the Arduino PCB , and the serial monitor is working.

**Screenshots**
![image](https://user-images.githubusercontent.com/22909429/132450249-32d24302-0bc6-4e7c-b852-34ba4db1d935.png)

**Comment by per1234** [comment]
Hi @moth4017. Thanks for taking the time to submit an issue.

I see we already have a prior issue report about this at https://github.com/arduino/arduino-ide/issues/200. You can refer to that thread to get an answer to your question.

It's best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
