### ISSUE TITLE
Arduino IDE 2.0Beta error

### ISSUE THREAD

**Issue by rohigithub** [arduino/arduino-ide#502]
![Screenshot (1124)](https://user-images.githubusercontent.com/86924269/132540796-2f25fd23-2c43-4d0b-b36e-a7924e30f05f.png)

I am getting this error while compiling for Servo library

**Comment by per1234** [comment]
Hi @rohigithub. If you have used the classic Arduino IDE, you might be accustomed to always having some of the most popular fundamental libraries such as Servo pre-installed. Arduino IDE 2.x does not currently come with any libraries pre-installed so you must always install all the libraries used by your sketch.

Fortunately, it is very easy to do this using the Arduino Library Manager. Please try this:
1. Select **Sketch > Include Libraries > Manage Libraries...** from the Arduino IDE menus.
2. In the "Filter your search..." field, type `servo arduino`.
3. Scroll way way down through the list of search results until you see **Servo by Michael Margolis, Arduino**. Click on it.
4. Click the <kbd>INSTALL</kbd> button.
5. Wait for the installation to finish.

Now you can try compiling your sketch again.

If you need further assistance, feel free to ask on the Arduino Forum. We will be happy to help you out over there:
https://forum.arduino.cc/
