### ISSUE TITLE
Undeclared Identifier OUTPUT for STM32 Boards

### ISSUE THREAD

**Issue by imk2021** [arduino/arduino-ide#508]
**Describe the bug**
Function call Parameter eg OUTPUT are underscored in Red in Ver 2 IDE beta 11 when using STM32 library 

**To Reproduce**
1. Install STM32 generic library's
2. Import Blink Example
3. Select board black pill STM32 F411CE

**Expected behavior**
I would expect the OUTPUT parameter not to be highlighted (Red underscored)  as Undeclared Identifier 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 64 Bit

**Additional context**
Version Two IDE behaves as expected (Not Highlighted Red) when board type is Arduino NANO

I have Arduino IDE 1.8.16 Installed and installed all my libraries via it.
Same libraries are visible in Version 2 Beta 11 so i assume are included.
The Blink program compiles uploads and works as expected 
For both the NANO and Black Pill STM32 F411CE boards. ( Pin C13 and predefined LED_BUILTIN )

STM32 Upload is via STM CubeProgrammer SWD Genuine ST Link Programmer

Hope that helps, code below;

void setup() 
{  // initialize digital pin LED_BUILTIN as an output.
pinMode(LED_BUILTIN, OUTPUT);
}

// the loop function runs over and over again forever
void loop()
{
digitalWrite(LED_BUILTIN, HIGH);   // turn the LED on (HIGH is the voltage level)
delay(20);                       // wait for a second
digitalWrite(LED_BUILTIN, LOW);    // turn the LED off by making the voltage LOW
delay(20);                       // wait for a second
}

**Comment by per1234** [comment]
Hi @imk2021. Thanks for taking the time to submit an issue.

I see we already have a prior issue report about this at https://github.com/arduino/arduino-ide/issues/220.

It's best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
