### ISSUE TITLE
Descriptive pop up on `textDocument/hover`

### ISSUE THREAD

**Issue by Hutkikz** [arduino/arduino-ide#51]
**Describe the bug**
The little pop up when you hover over a variable/function name only seems to work in the global area before any function definition. After that it only appears for a split second then disappears After awhile it stops popping up at all.
Also when it does work it almost always covers what I'm working on making it hard to edit etc.

**To Reproduce**
1. It is always like that.

**Expected behavior**

1. Pop up should remain up while hovered over subject variable/function name.
2. It should not cover subject variable/function name. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Version: 0.1.4
Date: 2021-02-10T12:24:17.658Z
CLI Version: 0.15.2 alpha [0d4cb150]

Copyright © 2021 Arduino SA

**Additional context**

**Comment by kittaakos** [comment]
This is tracked here: https://github.com/arduino/arduino-language-server/issues/68

Closing.
