### ISSUE TITLE
Add a "Reload" option in the File menu to refresh a file that was modified by an external editor.

### ISSUE THREAD

**Issue by gitmeister** [arduino/arduino-ide#510]
**Is your feature request related to a problem? Please describe.**
I often use Notepad++ to better visualize code and because the IDE is often fairly slow to load (even on my high-end W10 system with a SSD) I often leave it running with the project loaded. 

**Describe the solution you'd like**
The addition of a "Reload" option in the File menu.

**Describe alternatives you've considered**
The only solution I know of is to File->New, Close the Project, and File->Open Recent....etc

**Additional context**

**Comment by per1234** [comment]
Not necessary. Arduino IDE 2.x already has a better functionality. It simply loads all external changes immediately.
