### ISSUE TITLE
ide 2.0

### ISSUE THREAD

**Issue by bubbyatkins** [arduino/arduino-ide#511]
When I try to install the new 2.0 it will not copy the javascript files. It says the file names are too long.

**Comment by per1234** [comment]
Hello @bubbyatkins. Thanks for taking the time to submit an issue.

I see we already have a prior issue report about this at https://github.com/arduino/arduino-ide/issues/106.

It's best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
