### ISSUE TITLE
Opening example with `.pde` file extension fails silently

### ISSUE THREAD

**Issue by lmtanco** [arduino/arduino-ide#518]
### Describe the problem

If the example for a library has `.pde` file extension, Arduino IDE will silently fail to open it.

### To reproduce

1. Use Library Manager to install version "**1.1**" of the "**TimerOne**" library from Library Manager
1. Select **Examples > TimerOne > Interrupt**

🐛 The example doesn't open. There is no communication of a problem.

### Expected behavior

Arduino IDE opens all valid example sketches, regardless of whether they use a deprecated file extension.

### Arduino IDE version

2.0.0-beta.11

### Operating system

- macOS
- Windows

### Operating system version

- Windows 10
- macOS (not stated)

### Additional context

On the [Arduino forum](https://forum.arduino.cc/t/arduino-ide-2-0-beta-silently-fails-if-library-example-has-pde-extension/909565), user [in0](https://forum.arduino.cc/u/in0/summary) has reproduced the error on Windows and provides additional info: 

> I can reproduce it. You can see the problem when run from the command line:
>
> ```
> root ERROR Request cloneExample failed with error: ENOENT: no such file or directory, rename 'c:\Users\<user name>\AppData\Local\Temp\.arduinoIDE-unsaved2021827-16716-11heo0w.vdua\Interrupt\Interrupt.pde' -> 'c:\Users\<user name>\AppData\Local\Temp\.arduinoIDE-unsaved2021827-16716-11heo0w.vdua\Interrupt\Interrupt.ino'
> ```
>
> It's trying to rename the sketch in the temporary folder rather than in its true path under the library installation.
>
> I don't have this problem with a standalone sketch using the .pde file extension.

#### Additional Reports

- https://forum.arduino.cc/t/why-some-library-examples-do-not-load-in-arduino-ide-2-0/1104079/1
- https://forum.arduino.cc/t/exmaple-not-loading/1069511
- https://forum.arduino.cc/t/in-version-2-0-0-i-cant-open-accelstepper-examples/1041358
- https://forum.arduino.cc/t/newping-librarys-example-code-wont-open/1036177
- https://forum.arduino.cc/t/ds3231-of-example-frome-custom-libraries-is-not-open/934173
- https://forum.arduino.cc/t/ide-wont-load-sketches/1112447

<a name="workaround"></a>

#### Workaround

Rename the example sketch to use the `.ino` file extension.

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by ubidefeo** [comment]
hi @lmtanco 
Thank you for the kind words :)

This issue is in our backlog, but since more and more 3rd party developers are updating their libraries and examples to comply with specifications, we gave it very low priority.
The `.pde` extension for Arduino has been long deprecated, and we feel that if we leave it as is nobody will care to bring their Sketch code into 2021 and beyond :)

I have created a PR to Paul with the extensions updated.
https://github.com/PaulStoffregen/TimerOne/pull/54

Thank you

**Comment by mrkylegp** [comment]
I have this issue in 2.0.2. Can't open a .pde example for the PCM library. Very frustrating.

**Comment by KurtE** [comment]
Just checked again, with yesterday's daily build (after 2.0.2) and still has issue.  

This time with the Radiohead library.

**Comment by mrkylegp** [comment]
@KurtE Yep, it's very frustrating. Not exactly an upgrade IMO since several of the libraries I use have .pde files that wont open and the developers aren't going to be updating these libraries again. I'm back to using the older IDE for now.

**Comment by nbourre** [comment]
My suggestion would be to detect if the library's examples are using the obsolete format, if so ask the user if he would like to upgrade them.

**Comment by wh201906** [comment]
I think this has been fixed in commit 0ab28266dfe1859eb4e1c88502452f419b667099.
In the code before this, the `copy()` will rename the `.pde` into `.ino`, but it will try to access the new file with the old `.pde` extension, so it fails.
I have tested this bug on v2.1.0 and it was fixed.

**Comment by lmtanco** [comment]
Apologies for not closing this before. 

This works perfectly now (v2.2.1). Even if the example has .pde extension, it will open it, then it will ask the user if they want to change its extension. 

Tested on macOS Apple Silicon (screenshot) and Windows 11.  

![image](https://github.com/arduino/arduino-ide/assets/1093084/cee8e1d8-a3b7-4b5b-8bf5-6c94e4c1fc06)

**Comment by drf5n** [comment]
This is broken in IDE 2.3.2.

For example, try opening the:

File/Examples/AccelStepper/Bounce example that refers to this file on my Mac:

    /Users/drf/Documents/Arduino/libraries/AccelStepper/examples/Bounce/Bounce.pde

Using the workaround for a differential test, rename your Random.pde to Random.ino within its library directory and the Arduino IDE will open it as usual.

For example:

    /Users/drf/Documents/Arduino/libraries/AccelStepper/examples/Random/Random.ino


...functions as expected.

Tested on MacOS Sonoma 14.2.1 on Apple Silicon M2 

<img width="828" alt="image" src="https://github.com/arduino/arduino-ide/assets/2236516/d40fba7c-519b-4bad-84da-aeb81021e5cc">

No screen shot of the silent failure.

**Comment by drf5n** [comment]
See https://github.com/arduino/arduino-ide/issues/2377 for 2.3.2 issue

**Comment by drf5n** [comment]
See https://github.com/arduino/arduino-ide/issues/2377 for 2.3.2 issue
