### ISSUE TITLE
Serial Monitor lags behind and uses a lot of CPU

### ISSUE THREAD

**Issue by ubidefeo** [arduino/arduino-ide#519]
When printing data to Serial at high speed (115200) the Serial Monitor cannot keep up with the board output and CPU performances jump through the roof.

OS: Mac OS 11.3

**Comment by kittaakos** [comment]
Some work has been done on [`serial-monitor-rate-limiter`](https://github.com/arduino/arduino-ide/tree/serial-monitor-rate-limiter) branch. This [`comment`](https://github.com/arduino/arduino-ide/issues/391#issuecomment-850622814) could be related. Note, every single character comes with a request to the frontend, as no rate-limiter is configured on the CLI side. This means if you have a `println("foo")` sketch, you will get `f`, then `o`, finally `o` on the IDE side.  Maybe the communication is too chatty between the CLI and the IDE.

**Comment by ConnahGriffin** [comment]
I have the same problem. So I just limit it to somewhere around 200ms delay on the main loop() funtion.

OS: Linux(Ubuntu 20.04.3 x86_64)
