### ISSUE TITLE
nightly-20211005_Linux_64bit does not start

### ISSUE THREAD

**Issue by s0170071** [arduino/arduino-ide#523]
**Describe the bug**
IDE does not start

**To Reproduce**
1. download the  zip file
2. extract folder
3. click on "arduino-ide"
 

**Expected behavior**
The ide should open

**Screenshots**

**Desktop (please complete the following information):**
Linux Mint 20.1

**Additional context**
Installing instructions are here: 
https://www.arduino.cc/en/Tutorial/getting-started-with-ide-v2/ide-v2-downloading-and-installing#linux
I also tried chmod +x arduino-ide but with no success. If I try to run it as a command, it says command not found.

**Comment by per1234** [comment]
>click on "arduino-ide"

Unfortunately, it is not currently possible to start Arduino IDE 2.x in this way on Linux. I see the documentation implies this is possible, but that is not so. You must follow the second method described in the documentation and run it from the terminal.

Open a terminal at the folder where you have extracted the IDE download and run this command:
```
./arduino-ide
```
