### ISSUE TITLE
Debugging ist not supported by ESM32-CAM

### ISSUE THREAD

**Issue by s0170071** [arduino/arduino-ide#526]
The 2.0.0 beta11-nightly 20211005 says that Debugging is not supported by ESM32-CAM.
In fact, it is. It has Jtag pins.

**Comment by per1234** [comment]
The IDE is correct. Two things are required for debugging support:

- The microcontroller must have a debug interface that is compatible with the IDE's integrated debugger. 
  [The debugger](https://github.com/Marus/cortex-debug) is developed for use with microcontrollers that have an ARM Cortex-M core, whereas the ESP32 uses a Tensilica Xtensa core, so it's uncertain whether this compatibility is possible or not (but certainly worth a try!)
- The Arduino boards platform must be configured to work with the debugger.
  The ESP32 boards platform has not been configured for working with the debugger.

The only boards platform I know of that has support for the Arduino IDE 2.x debugger is the Arduino SAMD Boards. The easiest board to use is the [Arduino Zero](https://store.arduino.cc/arduino-zero), which has an on-board debugger, meaning you only need to plug the Zero in to your computer and you're read to debug! Another good option is the [MKR1000](https://store.arduino.cc/arduino-mkr1000-wifi). This board does not have an on-board debugger, so you will need to also get a CMSIS-DAP compatible debug probe, but the MKR 1000 does have a standard SWD header, meaning you will be able to connect your debug probe to the board easily. All the [MKR Boards](https://store.arduino.cc/catalogsearch/result/?tab=store&q=mkr) and the [Nano 33 IoT](https://store.arduino.cc/arduino-nano-33-iot) can also be used with the Arduino IDE 2.x debugger but the connection to the debug probe must be done via the pads on the bottom of the board.
