### ISSUE TITLE
Serial Monitor swallowing leading and repeated spaces

### ISSUE THREAD

**Issue by paulwas** [arduino/arduino-ide#535]
**Describe the bug**
Today I copied the nightly build files (arduino-ide_nightly-20211008_Windows_64bit) and launched the Arduino IDE to continue work on my current project. I'm outputting a lot of formatted data via the Serial Port to the Serial Monitor (115200 baud) and have been using this IDE (2.0 Beta) for a number of weeks. The Serial Monitor has been working fine until last nights build. Now all the leading spaces have disappeared. So for example:
This output:

```text
Events:
  List 'E'
  Add  'EA mm/dd/yyyy rr Annual|Once Description..'
  Edit 'EE nn [mm/dd/yyyy] | [rr] | [Annual|Once] | [Description..]'
  Del  'ED nn'
Time/Date:
  Get  'T'
  Set  'T [mm/dd/yyyy][hh:mm[:ss][am/pm]]'
```

Now looks like this:

```text
Events:
List 'E'
Add  'EA mm/dd/yyyy rr Annual|Once Description..'
Edit 'EE nn [mm/dd/yyyy] | [rr] | [Annual|Once] | [Description..]'
Del  'ED nn'
Time/Date:
Get  'T'
Set  'T [mm/dd/yyyy][hh:mm[:ss][am/pm]]'
```

**To Reproduce**
1. `Serial.print("   xyz");`
2. Output looks like this "`xyz`"

**Expected behavior**
The serial output should now swallow any characters that are output.
Output should look like this "`   xyz`"

**Desktop (please complete the following information):**
 - OS: 
Edition	Windows 10 Pro
Version	21H1
Installed on	‎1/‎16/‎2021
OS build	19043.1237
Serial number	011754392857
Experience	Windows Feature Experience Pack 120.2212.3530.0
- Version: arduino-ide_nightly-20211008_Windows_64bit

**Comment by tomjennings** [comment]
Same here. 1.8.19, vs 2.0, all multiple spaces suppressed.

Here's a snapshot of a "datascope" in 1.8.19:
<img width="1420" alt="Screen Shot 2022-01-05 at 11 01 33" src="https://user-images.githubusercontent.com/10536133/148277512-18dc0287-b4e2-468b-bbb5-065fe946c19d.png">


And the same sketch running in 2.0:
<img width="1420" alt="Screen Shot 2022-01-05 at 11 03 18" src="https://user-images.githubusercontent.com/10536133/148277557-1d5ed70a-f2cc-45ea-9ef2-aa1cb7fc69bf.png">

Also jamming serial monitor into the tiny compiler-output area is a related fail as well, but a separate issue.
