### ISSUE TITLE
Notification is missing the close icon (dark theme) 

### ISSUE THREAD

**Issue by VladimirVecera** [arduino/arduino-ide#536]
For the newer beta 12 version, clicking on the bell below will open a notification that is missing the close icon (dark theme). 
![err](https://user-images.githubusercontent.com/64955913/136649666-5e729844-3a5e-4a74-96fa-0ace3949eeeb.jpg)

**Comment by per1234** [comment]
Hi @VladimirVecera. Thanks for taking the time to submit an issue.

I see we already have a prior issue report about this at https://github.com/arduino/arduino-ide/issues/531.

It's best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
