### ISSUE TITLE
The first time you run it, the other files in the project will not load (tabs)

### ISSUE THREAD

**Issue by VladimirVecera** [arduino/arduino-ide#541]
The first time you open the Arduino IDE, the project I had last opened is loaded. However, it uses other files that do not open in tabs. I have to open a new project and then reopen my project in which all the files will be loaded into the tabs. 
![1](https://user-images.githubusercontent.com/64955913/136773275-fa8dd209-90f8-44bc-8c89-5e80046a1937.jpg)
![2](https://user-images.githubusercontent.com/64955913/136773278-a3741f30-1547-4c85-865e-e245df132869.jpg)

Windows 10
Arduino 12 beta
Project ESP32 2.0

**Comment by fstasi** [comment]
https://github.com/arduino/arduino-ide/pull/612

**Comment by ubidefeo** [comment]
@fstasi I have approved the PR
