### ISSUE TITLE
Auto Format Not Working(Most of the Time)

### ISSUE THREAD

**Issue by ISSac25E** [arduino/arduino-ide#548]
Auto Format does not work and when it does work, it does so under some weird conditions. I tried both with the shortcut and menu tool and both don't work or at least not properly. Anytime when I am coding 99% of the time I could never get it to work. The only time I got it to work "somewhat" reliably was when I opened a blank sketch and even then under very specific circumstances. (btw, I tested this with 2.0.0-beta.12 using .exe .msi and .zip on both Win 10 and Win 7, Exact same effect on all, I have yet to try on Mac)

The only way I got Auto format to work is if you have a blank sketch with only the void setup and loop. If you put a space in front of void loop() like this:
![image](https://user-images.githubusercontent.com/92411691/137048739-a9d9c072-c721-4fe0-bb36-8d057439ea2c.png)
If you hit CTRL + t or click the button from the menu (after it finishes building the sketch of course) you will see it will format and shift the void loop back where it belongs and it will do so quite reliably every single time I found:
![image](https://user-images.githubusercontent.com/92411691/137048886-833e47ca-767f-488c-ad19-8d5934fcb79c.png)
However, if you try to do this with the setup() like this:
![image](https://user-images.githubusercontent.com/92411691/137048928-a34d7563-37d8-482c-a80c-c588787ede54.png)
It will not work no matter how much you try, even if you try to do this to both(loop and setup) It just simply stops working at this point:
![image](https://user-images.githubusercontent.com/92411691/137048984-f447e187-3c67-46e0-b892-0d3090083814.png)
This is by far the weirdest behavior I found with the Auto Format tool. All the other times Auto Format would simply not work at all.
Anyway, I just wanted to bring this to attention and thought this might be some useful clue that might help out in figuring out what is really going on

I actually got the auto format to somehow randomly delete some line of code while doing the test but so far I did not find a way to replicate this.

**Desktop (please complete the following information):**
 - OS: Windows 7, Windows 10
 - Version: Arduino IDE 2.0.0-beta.12

**Comment by per1234** [comment]
Hi @ISSac25E. Thanks for taking the time to submit an issue.

I see we already have a prior issue report about this at https://github.com/arduino/arduino-ide/issues/396.

It's best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.

>I actually got the auto format to somehow randomly delete some line of code while doing the test but so far I did not find a way to replicate this.

I submitted a bug report for that here: https://github.com/arduino/arduino-ide/issues/543
It does occur intermittently, but I am able to reproduce it frequently via the instructions in that issue.

**Comment by ISSac25E** [comment]
@per1234 So sorry about that, First time using GitHub. I go right over and post this in the comments if it will help

**Comment by per1234** [comment]
No worries. This issue has been linked to the other one now, will will make the information you shared here accessible to interested parties, including the IDE developers  during the course of their investigation. But you are welcome to comment there with any additional information you feel will be useful. Thanks!
