### ISSUE TITLE
 IntelliSense doesn't work without #include <Arduino.h>

### ISSUE THREAD

**Issue by zeroamps** [arduino/arduino-ide#55]
IntelliSense doesn't work correctly. 
After adding #include <Arduino.h> it starts working fine.

**Screenshots**
![image](https://user-images.githubusercontent.com/22910341/108511525-562cdc80-72c0-11eb-996e-c39cc3a022ab.png)

**Desktop**
 - OS: Windows 10
 - Arduino PRO IDE : 0.1.4.

**Comment by mink99** [comment]
This seems to be a conceptual/design error in the clang integration. 
The compilation path is well known in the ide, but the clang tool is fed with another source of information, which is obviously faulty. Providing two different sources of information, the compile path generated correctly, and the clang include path not will or has resulted already in many similar bugs.

You may see that the IDE had not even tried to parse the libraries, regardless of whether it is a system library (referring to Arduino.h) or a user library (referring to nmidi.h)
[inols-clangd.log](https://github.com/arduino/arduino-ide/files/6328928/inols-clangd.log)
[inols-clangd-err.log](https://github.com/arduino/arduino-ide/files/6328929/inols-clangd-err.log)

**Comment by mink99** [comment]
Simple partial Fix:
create a clangd configuration file in your home directory (see : https://clangd.llvm.org/config.html) like this
`CompileFlags:
    Add:    -I K:\Develop\Libraries`
now clangd will parse the #includes, even by magic the <arduino.h>

please note: K:\Develop is my sketch folder, therefore K:\Develop\Libraries is my libraries folder

of course the correct solution would be to create a project configuration file (.clandgd) in the current source tree and put the well known library path , system and user in there.

**Comment by mink99** [comment]
no <arduino.h> included :
![Image3](https://user-images.githubusercontent.com/11485843/115141998-a49bf480-a03f-11eb-97e7-d3198dbd1b29.png)

**Comment by per1234** [comment]
Thanks for your reports @zeroamps and @mink99 . There have been some recent improvements to the [Arduino Language Server](https://github.com/arduino/arduino-language-server) that provides this capability in the IDE. These improvements are available from the latest release of the Arduino IDE.

Please try again with [the latest build](https://github.com/arduino/arduino-ide#nightly-builds) of the Arduino IDE and let us know whether or not the bug is fixed for you.

**Comment by per1234** [comment]
Closing due to lack of response.

@zeroamps and @mink99 if you will provide the requested information by commenting here, I'll be happy to re-open this issue.

**Comment by mink99** [comment]
Tried, and did not work....
Did you try the recommended fix (.clangd as mentioned above ) ?

**Comment by mink99** [comment]
The bug is not about Arduino.h. it is about all external libraries that are not in the project directory, but are used in an include <blablabla.h> statement, or as described above, the compilation path is not provided to the language parser.

**Comment by mink99** [comment]
It seems you even broke the simple fix with .clangd with the latest update :)
