### ISSUE TITLE
Let a project contain compilation/upload settings

### ISSUE THREAD

**Issue by AndKe** [arduino/arduino-ide#554]
**Is your feature request related to a problem? Please describe.**
Different projects often require very different compilation target/programmer and other settings.
Switching between project requires to find and apply all those setttings, 
for example, one of my projects require this config:
  Board: Generic STMF1
  Board Part : Bluepill F103C8
  U(S)ART support: Enabled(generic Serial)
  USB Support: CDC(generic "serial" supersede U(S)ART"
  USB Speed: Low/Full Speed
  Optimize: Smallest (-Os default)
  C Runtime Library : newlib Nano(default)
  Upload Method: STM23CubeProgrammer(SWD)  (ST_LINKV2)

- then I open another and need to reset it accordingly.

**Describe the solution you'd like**
parse first file for some text, can be commented text, that sets config as described in the file.
for example
in comments look for:
BOARD="Generic STMF1"
BOARD_PART="Bluepill F103C8"
UART_SUPPORT="Enabled(generic Serial)"
....

OR
Just look for, and apply selections to menus based on text only: 
set check for, and set each menu item based on text.... no prior knowledge of options needed.
----SETTINGS---
  "Board Part"="Bluepill F103C8"
  "U(S)ART support"="Enabled(generic Serial)"
  "USB Support"="CDC(generic "serial" supersede U(S)ART)"
....
----END-SETTINGS---

and simply apply, or offer to apply those settings automatically on load.

**Describe alternatives you've considered**
N/A

**Additional context**
I also tried to suggest it for Arduino 1.x  -back then, with fewer hardware choices, it was not implemented.

**Comment by per1234** [comment]
Thanks for taking the time to submit this suggestion @AndKe .

I see we already have a prior request for this at https://github.com/arduino/arduino-ide/issues/125.

It's best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
