### ISSUE TITLE
Missing tab width adjustment

### ISSUE THREAD

**Issue by KXCheng** [arduino/arduino-ide#555]
**Is your feature request related to a problem? Please describe.**
The tab width cannot be adjusted like in previous versions.

**Describe the solution you'd like**
Bring back the option to adjust tab width.

Please, and thank you :)

**Comment by per1234** [comment]
Thank you for the clarification!

It is already possible to configure this. If you like the classic Arduino IDE approach of editing a configuration file directly, you can open `C:\Users<username>\AppData\.arduinoIDE\settings.json` (`~/.arduinoIDE/settings.json` for any Linux users who are reading this) and then change the value of the `editor.tabSize` key.

It is also possible to adjust these advanced settings via Arduino IDE 2.x through **Settings: Open Preferences** in the Command Palette (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>).

Even though you only mentioned the whitespace resulting from pressing <kbd>Tab</kbd>, most who want to customize that will also want to customize the IDE's auto format configuration to match. Arduino IDE 2.x uses the industry standard open source ClangFormat tool as a code formatter. You can add a custom `.clang-format` configuration file to the root of each sketch folder to customize the behavior of the auto formatter. Information about that file here:
https://releases.llvm.org/11.0.1/tools/clang/docs/ClangFormatStyleOptions.html
You will be interested in the `IndentWidth` setting. The remaining piece of the puzzle for some would be a global custom auto formatter configuration file. Some of the work has already been done to support this and the remaining work is tracked at https://github.com/arduino/arduino-ide/issues/566. Other than that, I think we can consider this resolved.

Regards, Per

**Comment by per1234** [comment]
The second screenshot shows you are opening the basic preferences via **File > Preferences** menu. The tab width is set in the advanced preferences. As I mentioned above, those are accessed by opening the Command Palette (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>) and then selecting **Settings: Open Preferences**.

**Comment by ProxyPlayerHD** [comment]
how exactly are you supposed to know of the existance of the "Command Palette" as a newer user (i didn't know that was a thing until i found this page...)
and why have 2 seperate preferences menus with the less useful one being much simpler to access? why not just combine them into one and have it easily accessible from toolbar under File -> Preferences?
