### ISSUE TITLE
Text colour clash.

### ISSUE THREAD

**Issue by BanksySan** [arduino/arduino-ide#557]
**Describe the bug**
The _Dark (Theia)_ theme renders the intelli-sense info unreadable.

**To Reproduce**
1. Set theme to _Dark (Theia)_.
2. Try to read the intellisense/quick-info.

**Expected behavior**
The contrast between text and background is high enough to be readable.

**Screenshots**
![image](https://user-images.githubusercontent.com/996280/137603188-ea3dd825-4ea5-4b01-9f0b-512fd2573877.png)

Desktop (please complete the following information):

- Edition Windows 10 Home
- Version 21H1
- OS build 19043.1288
- Experience Windows Feature Experience Pack 120.2212.3920.0

Additional context

IDE:

- Version 2.0.0-beta.12
- Date 2021-10-07T07:55:54.325Z
- CLI Version 0.19.1 alpha [718bbbf2]

**Comment by per1234** [comment]
This was resolved in Arduino IDE 2.0.0-rc1, but the developers forgot to close the issue at that time. I didn't bisect it to the exact commit, but I'm sure it was https://github.com/arduino/arduino-ide/pull/610
