### ISSUE TITLE
No output information during operation

### ISSUE THREAD

**Issue by SebCanet** [arduino/arduino-ide#562]
**Describe the bug**
The console does not output information during compilation or upload process.

**To Reproduce**
1. Click on 'Verify' or 'Upload'
2. Look at 'Output console'
3. See error

**Expected behavior**
In v1.x.x of IDE, we have information, we know that a process is on. Now when we click on operation we don't even know it works or it's started, on ly have output at the end, so debug is difficult. With kids it's a problem because they're not sure of what they do.

**Desktop (please complete the following information):**
 - OS: Windows 7, 10...
 - Version: 2.0.0 b10, b11, b12...

Thanks!

**Comment by ubidefeo** [comment]
@per1234 
I think we can keep this one related to the better ways of displaying minimal feedback/output (when verbose is off)
