### ISSUE TITLE
Missing board option and Programmer menus for manually installed platforms

### ISSUE THREAD

**Issue by per1234** [arduino/arduino-ide#565]
**Describe the bug**

Menus are not added to the Arduino IDE **Tools** menu for boards of platforms installed to the sketchbook folder which have [custom board options](https://arduino.github.io/arduino-cli/dev/platform-specification/#custom-board-options).

A **Programmer** menu is not added to the Arduino IDE **Tools** menu when a board of a platform installed to the sketchbook folder is selected.

**To Reproduce**
1. Do a manual installation of the `attiny:avr` boards platform to the sketchbook. For example:
   ```
   git clone https://github.com/damellis/attiny ~/Arduino/hardware/attiny/avr
   ```
   Note: The issue is not specific to the `attiny:avr` platform. It should occur with any platform that has custom board menus.
1. Start the Arduino IDE.
1. Select **Tools > Board > ATtiny Microcontrollers (in Sketchbook) > ATtiny24/44/45** from the Arduino IDE menus.
1. Open the **Tools** menu. Note that there is no **Processor**, **Clock**, or **Programmer** menu, even though [the `attiny:avr:ATtinyX4` board has custom menus.](https://github.com/damellis/attiny/blob/6bba7d452af59d5190025bc870ec9e53d170e4d9/boards.txt#L1-L2) and inherits [programmers](https://github.com/arduino/ArduinoCore-avr/blob/master/programmers.txt) from the [referenced `arduino:avr` core](https://arduino.github.io/arduino-cli/dev/platform-specification/#core-reference).

![image](https://user-images.githubusercontent.com/8572152/138220285-afd9cec6-4f24-4fac-bc9e-ad3805dc9111.png)

They are handled correctly by the classic IDE:
![image](https://user-images.githubusercontent.com/8572152/138222874-82c00e03-914e-4e20-9603-4d885440f590.png)
and by Arduino CLI:
```
per@HAL MINGW64 /c/ide 2/arduino-ide_nightly-20211021_Windows_64bit/resources/app/node_modules/arduino-ide-extension/build
$ ./arduino-cli board details attiny:avr:ATtinyX4
Board name:            ATtiny24/44/84
FQBN:                  attiny:avr:ATtinyX4

Package name:          attiny

Platform name:         ATtiny Microcontrollers
Platform architecture: avr

Option:                Processor                       cpu
                       ATtiny24                   ✔    cpu=attiny24
                       ATtiny44                        cpu=attiny44
                       ATtiny84                        cpu=attiny84
Option:                Clock                           clock
                       Internal 1 MHz             ✔    clock=internal1
                       Internal 8 MHz                  clock=internal8
                       External 8 MHz                  clock=external8
                       External 16 MHz                 clock=external16
                       External 20 MHz                 clock=external20
Programmers:           Id                         Name
```
(`arduino-cli` doesn't show the board's referenced programmers, but the output is the same even with the working Boards Manager installation, so I'm not sure it's related)

If you install the same platform via Boards Manager, the menus are shown as expected:

![image](https://user-images.githubusercontent.com/8572152/138222778-e12edb66-8c96-4e80-bff3-13761fac64b8.png)

**Expected behavior**
Menus should be added to the **Tools** menu for programmers and custom options of the selected board regardless of how the board's platform was installed.

**Desktop (please complete the following information):**
 - OS: Windows 10, Ubuntu 20.04
 - Version: 2.0.0-beta.12-nightly.20211021
Date: 2021-10-21T03:03:16.691Z
CLI Version: 0.19.1 alpha [718bbbf2]

**Additional context**

Originally reported at:
- https://forum.arduino.cc/t/arduino-ide-2-0-bets-processor-drop-down-not-present/916551
- https://github.com/arduino/arduino-ide/issues/364
- https://github.com/arduino/arduino-ide/issues/420

Related: https://github.com/arduino/arduino-ide/issues/126

**Comment by ubidefeo** [comment]
@silvanocerza , I've assigned this one to you after some reviews and tests.
This is an important thing to work out since it impacts development of cores which is carried out using the Sketchbook's Hardware folder

**Comment by silvanocerza** [comment]
The problem seems to be in the IDE, I just verified the CLI is correctly returning the necessary information via gRPC. I'll get to it.
