### ISSUE TITLE
Preferences: when changing Sketchbook location the IDE won't reload resources

### ISSUE THREAD

**Issue by ubidefeo** [arduino/arduino-ide#570]
**Describe the bug**
A default installation of IDE 2.0 points to the user's documents > Arduino folder.
A user might want to point this to a preexisting folder using the Preferences Panel.
When this happens, the IDE keeps seeing the same resources in matter of Sketchbook content and Libraries until a Sketch is saved or the IDE is restarted.
Until this "reload" happens, also a list of libraries remains unavailable, hence their examples

**To Reproduce**
1. Launch the IDE and open **Preferences**
2. Point the **Sketchbook** location to a new, empty folder
3. Quit the IDE
4. Relaunch the IDE
5. Select "Sketchbook" from the File menu
5a. Observe arduino/arduino-ide#569
6. Create a new Sketch
7. **File > Save as...** and give it a name
8. The **File** menu will now have a **Sketchbook** entry listing the newly saved Sketch
9. Repeat step 1 and point the Sketchbook location back to the previous one (it is assumed Sketches and Libraries are present)
10. The **File > Sketchbook** menu will still only list the recently saved Sketch
11. **File > Save As...** and give it a name
12. The window for the Sketch currently saving will reload
13.  The **File > Sketchbook** menu will now correctly list all the Sketches you previously had plus the new one
14. This indicates that saving has reloaded the data structures

**Expected behavior**
Changing the Sketchbook location should reload/rebuild the essential environment settings

**Screenshots**
Default Sketchbook location (empty, new install)
<img width="791" alt="Screenshot 2021-10-22 at 10 51 40" src="https://user-images.githubusercontent.com/1894487/138429202-6c0db441-8650-43bf-b703-81c33d052dfe.png">

After saving a Sketch
<img width="692" alt="Screenshot 2021-10-22 at 10 51 32" src="https://user-images.githubusercontent.com/1894487/138429255-a87abdfe-faa8-48c1-a0f3-b67cba37f8e5.png">

Changing location to folder full of Sketch/Libraries
<img width="796" alt="Screenshot 2021-10-22 at 10 52 02" src="https://user-images.githubusercontent.com/1894487/138429315-2c1c9f6a-a825-4900-b76c-ba4194fd3eff.png">

No change in content of Sketchbook (also examples for libraries will not be shown - next image)
<img width="584" alt="Screenshot 2021-10-22 at 10 52 12" src="https://user-images.githubusercontent.com/1894487/138429528-9a83ceaf-65d3-476c-af99-f04caca9604f.png">

Libraries are not yet shown
<img width="403" alt="Screenshot 2021-10-22 at 11 25 14" src="https://user-images.githubusercontent.com/1894487/138430034-9962c420-e4d9-4c58-89fd-f2dedf12f674.png">

Sketchbook after relaunching
<img width="206" alt="Screenshot 2021-10-22 at 11 27 06" src="https://user-images.githubusercontent.com/1894487/138430299-18cbb0f0-cbaa-41e3-a25e-501904616485.png">

Examples after relaunching
<img width="429" alt="Screenshot 2021-10-22 at 11 27 17" src="https://user-images.githubusercontent.com/1894487/138430344-8881fd0d-6433-41b0-83d4-fef86c0bc0b9.png">

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Version: [e.g. 2.0.0]

**Additional context**
arduino/arduino-ide#569

**Comment by per1234** [comment]
I see there is another report of this at https://github.com/arduino/arduino-ide/issues/796. Even though this one came first, the other has more information so I'll close this in favor of https://github.com/arduino/arduino-ide/issues/796
