### ISSUE TITLE
Leading zeros are stripped from Serial Monitor timestamps

### ISSUE THREAD

**Issue by per1234** [arduino/arduino-ide#580]
### Describe the problem

🐛 The timestamps produced by the Serial Monitor have a non-standard format resulting from stripping the leading zeros from the hours and minutes.

🐛 This is not even done consistently as the leading zeros are preserved for seconds.

### To Reproduce

1. Upload a sketch to an Arduino board that periodically prints to the serial port. For example:
   ```cpp
   void setup() {
     Serial.begin(9600);
   }
   void loop() {
     Serial.println("hello");
     delay(1000);
   }
   ```
1. Select **Tools > Serial Monitor** from the Arduino IDE menus.
1. Click the :clock10: icon ("Toggle Timestamp") that is near the top right corner of the output panel
1. Wait for a time that contains a second less than 10.
1. Look at the Serial Monitor output pane.
   🙂 Note that the leading zero on the second component of the time has _not_ been removed.
1. Wait for a time that contains a minute less than 10.
1. Look at the Serial Monitor output pane.
   🐛 Note that the leading zero on the minute component of the time has been removed.
1. Wait for a time that contains an hour less than 10.
1. Look at the Serial Monitor output pane.
   🐛 Note that the leading zero on the hour component of the time has been removed.

```
23:59:58.610 -> hello
23:59:59.609 -> hello
0:0:00.620 -> hello
0:0:01.618 -> hello
0:0:02.630 -> hello
```

### Expected behavior

Serial Monitor timestamps to be formatted the same as they were in the classic Arduino IDE:
hh:mm:ss.sss

```
00:05:02.590 -> hello
```

#### Original report

2.0.0-beta.12-nightly.20211028

#### Last verified with

2.0.0-rc9-snapshot-5087ff0

### Operating system

Windows 10

### Additional context

Originally reported at:
- https://forum.arduino.cc/t/serial-monitor-changes-time-stamp-format/870115
- https://github.com/arduino/arduino-ide/issues/391#issuecomment-877585479

**Comment by mklemarczyk** [comment]
It is still exists in 2.0.0-rc4.

![image](https://user-images.githubusercontent.com/2727261/156933816-bf1a352c-73c8-42c1-b0cd-b052697dccd6.png)

**Comment by ubidefeo** [comment]
@per1234 
do we still have this issue?

**Comment by per1234** [comment]
@ubidefeo yes:

![image](https://user-images.githubusercontent.com/8572152/180804060-2d5c9ed2-3394-469c-9db2-89616592d002.png)

**Comment by nmzaheer** [comment]
I think the relevant code affecting this is given here
https://github.com/arduino/arduino-ide/blob/df8658eff9d1758239923c740357ed6b33b7397e/arduino-ide-extension/src/browser/serial/monitor/serial-monitor-send-output.tsx#L110-L113

Can I go ahead and submit a PR changing it to
```ts
  const timestamp =
    (data.timestamp &&
      `${dateFormat(data.lines[index].timestamp, 'HH:MM:ss.l')} -> `) ||
    '';
```

**Comment by per1234** [comment]
>Can I go ahead and submit a PR

Hi @nmzaheer. Please do. I'll be happy to review it.

**Comment by nmzaheer** [comment]
@per1234 I've tested it on Ubuntu through WSL with my Uno board and it works.
