### ISSUE TITLE
Port auto-reconnect should only happen on upload or opening serial-monitor.

### ISSUE THREAD

**Issue by StephenJD** [arduino/arduino-ide#584]
**Is your feature request related to a problem? Please describe.**
Constant attempts to reconnect a port when a previous connection is lost is very annoying.
1. It creates a lot of IDE "noise".
2. If a second IDE is open on another port, the one that looses the connection reconnects to the second IDE's port.
3. When the first IDE is reconnected, the original port has to manually reselected.

**Describe the solution you'd like**
1. Port-searching and connection ONLY happens when you try to upload or open the Serial Monitor.
2. If a previous port connection is lost, it remembers that port, and on attempting a reconnect, it first tries the previously connected port.

**Describe alternatives you've considered**
Using IDE 1.8 which does not suffer from this behaviour.

**Additional context**

**Comment by per1234** [comment]
Thanks for taking the time to submit an issue @StephenJD.

I see we already have a prior issue report about this at https://github.com/arduino/arduino-ide/issues/314.

It's best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
