### ISSUE TITLE
Portenta Driver not listed in Device Manager

### ISSUE THREAD

**Issue by kg117** [arduino/arduino-ide#59]
## Describe the bug

Windows 10 Pro Portenta Driver is not listed in Device Manager as shown in the tutorial:

https://docs.arduino.cc/tutorials/portenta-h7/por-ard-gs#3-verify-the-usb-connection-windows-only

![Drivers1](https://user-images.githubusercontent.com/5963151/107707137-5114cf80-6cb9-11eb-895d-34e1ed441572.png)
Universal Serial Bus devices not listed but have "Universal Serial Device (COM9) under PORTS

## To Reproduce

1. I uninstalled arduino-1.8.13-windows using Windows Apps
1. I cleared `D:\Arduino\arduino-pro-ide_0.1.4_Windows_64bit`
1. I cleared all the following folders:
   ```text
   C:\Users\kevin.arduinocdt
   C:\Users\kevin.arduinoProIDE
   C:\Users\kevin\AppData\Local\Arduino15
   C:\Users\kevin\AppData\Roaming\Arduino Pro IDE logs
   C:\Users\kevin.theia
   C:\Users\kevin\AppData\Roaming\arduino-pro-ide
   C:\Users\kevin\AppData\Roaming.theia
   ```
1. I installed: https://downloads.arduino.cc/arduino-pro-ide/nightly/arduino-pro-ide_nightly-latest_Windows_64bit.zip
1. I plugged in my Portenta H7 board.
1. In Pro IDE "**Boards Manager**", I searched for "Portenta Boards": None were listed
1. IDE did not find port: Menu **Tools->Port** selected "**COM3**"
1. A dialogue appeared:
   > Install mbed enabled boards? Yes/No
1. I clicked <kbd>Yes</kbd>
1. I completed the installation process.
1. A dialogue appeared:
   > Run dpinst-amd64
1. A Windows App dialogue appeared:
   > Do you wish to install?
1. I clicked <kbd>Yes</kbd>, but dpinst-am64 dialogue disappeared! No installation of Portenta Driver
1. "USB Serial Device (COM3)" appears in Device Manager
   Properties: Microsoft 21/06/2006 10.0.19041.1
1. I clicked the drop-down list in the IDE and selected "Arduino Portenta H7 (M7 core) at COM3"

Still no Arduino Driver available?

folder location.txt
[folder location.txt](https://github.com/arduino/arduino-pro-ide/files/5987223/folder.location.txt)

2021-02-16_log.log
[2021-02-16_log.log](https://github.com/arduino/arduino-pro-ide/files/5987224/2021-02-16_log.log)

![IDE1](https://user-images.githubusercontent.com/5963151/108038688-0d142880-7033-11eb-8d59-8a880a062f99.png)

## Expected behavior

As shown in the tutorial screenshot: "Verify the USB connection (Windows only)":

https://docs.arduino.cc/tutorials/portenta-h7/por-ard-gs#3-verify-the-usb-connection-windows-only

## Desktop (please complete the following information):**

- OS: Windows 10 Pro, version: 19042.804
- IDE version: 0.1.4-nightly.20210215

## Additional context

[portenta upload.txt](https://github.com/arduino/arduino-pro-ide/files/5968804/portenta.upload.txt)

[2021-02-14_log.log](https://github.com/arduino/arduino-pro-ide/files/5985407/2021-02-14_log.log)

Totally cleared PC of Arduino Classic and Pro IDEs: unable to get `dpinst-amd64` to install Portenta Driver.

**Comment by marqdevx** [comment]
PR at https://github.com/arduino/docs-content/pull/144

Please close this issue :)

**Comment by per1234** [comment]
Closing as resolved by https://github.com/arduino/docs-content/pull/144
Thanks @marqdevx!
