### ISSUE TITLE
Debugger doesn't see my configurations

### ISSUE THREAD

**Issue by 0nliner** [arduino/arduino-ide#594]
my configurations:

![image](https://user-images.githubusercontent.com/78047335/140381641-2e2a1d40-914d-428a-b3ca-6dc185a433dc.png)

**Comment by per1234** [comment]
Thanks for taking the time to submit an issue @0nliner .

I see we already have a prior issue report about this at https://github.com/arduino/arduino-ide/issues/315.

It's best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.

If you would like to learn how to use the J-Link with the Arduino IDE 2.x integrated debugger, see this tutorial:
https://docs.arduino.cc/software/ide-v2/tutorials/ide-v2-debugger#j-link
