### ISSUE TITLE
Blame width not adjustable.

### ISSUE THREAD

**Issue by BanksySan** [arduino/arduino-ide#599]
**Describe the bug**
When I view the blame annotations the width of the blame window is about 50% of the code window which makes it very difficult to work with.

**To Reproduce**
1. Create a Git repo and some commits.
2. Open file with a history.
3. Right-click and show blame annotations
4. Try to change size of window.

**Expected behavior**
Reduce size of window so that I can clearly see the code.

**Screenshots**
![Blame annotations window](https://user-images.githubusercontent.com/996280/140610049-04fff6e7-0223-4264-812b-7ec1b7fb294d.png)

**Desktop (please complete the following information):**
_Processor_	Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz   2.30 GHz
_Installed RAM_	32.0 GB (31.9 GB usable)
_System type_	64-bit operating system, x64-based processor
Pen and touch	Pen and touch support with 10 touch points

_Edition_	Windows 11 Home
_Version_	21H2
_OS build_	22000.282
_Experience_	Windows Feature Experience Pack 1000.22000.282.0

**Comment by per1234** [comment]
Obsoleted by the removal of the Git extension in https://github.com/arduino/arduino-ide/pull/1018
