### ISSUE TITLE
One needs to do hacking to access file explorer. WHY?

### ISSUE THREAD

**Issue by wojciechsura** [arduino/arduino-ide#601]
**Describe the bug**
The file explorer known from Visual Studio Code is not available in easy way. One have to hack to get access to files in the sketch.

**To Reproduce**
1. Start the application
2. Explorer window is not available

**Expected behavior**
Explorer window should be available from start. Also, user should be able to close tabs with simple [x] on the tab. 

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 2.0.0-beta12

**Additional context**
The behavior in old Arduino IDE is very confusing and I hoped, that in the 2.x versions it will be easier to navigate files in the sketch (since Arduino IDE uses the same core as the fantastic VS Code). But it looks like even though Arduino IDE is built on the same engine, one might still need VS Code for file editing and then Arduino IDE to upload them. 

I also believe, that beginners might get very confused by this behavior (namely, inability to browse through files in the sketch, inability to close a tab containing the file, forced opening of all files in the sketch). It doesn't resemble behavior seen in any other IDE or, for that matter, also in any other MDI software. Forcing user to work with files in only one way also makes the learning curve more steep and since Arduino is meant for beginner engineers, this "feature" is simply against the core spirit of Arduino.

Also, forced opening all files in the project may clutter the view if project contains mode header/source files. This, in effect will cause beginners to keep everything in one giant file instead of elegantly dividing it to smaller modules. In the end, users will be encouraged to use bad development practices, because of the IDE imperfections.

What's the point in using very advanced core for Arduino IDE, when the useful features are being hidden or removed? It just makes completely no sense.

**Comment by per1234** [comment]
Thanks for taking the time to submit an issue @wojciechsura .

I see we already have a prior issue report about this at https://github.com/arduino/arduino-ide/issues/377.

It's best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
