### ISSUE TITLE
Examples aren't available for contributed libraries installed manually

### ISSUE THREAD

**Issue by kengregson** [arduino/arduino-ide#602]
Examples included with libraries installed manually (copied into the sketchbook libraries directory) aren't available in the File->Examples dropdown menu.

Examples from Custom libraries installed via the library manager are available. The examples are displayed and accessible when using version 1.8.16 of rhe IDE.

The Contributed libraries themselves are visible and available to include in the sketch from the menu Sketch->Include Library.

**To Reproduce**
1. Download a third-party library
- I'm using the Arduino I2Cdev and MPU6050 libraries from https://github.com/jrowberg/i2cdev)
- mkdir -p ~/Downloads/github.com/jrowberg; cd ~/Downloads/github.com/jrowberg; git clone https://github.com/jrowberg/i2cdevlib
2. Copy the libraries to ~/Arduino/libraries 
- cp -r ~/Downloads/github.com/jrowberg/i2cdevlib/Arduino/I2Cdev ~/Arduino/libraries
- cp -r ~/Downloads/github.com/jrowberg/i2cdevlib/Arduino/MPU6050 ~/Arduino/libraries
3. Start a new project in the arduino2 IDE
- select a board (I'm using a UNO)
4. Observe contributed libraries are available and can be included in sketch as shown in screenshot via:
- Sketch->Include LIbrary->I2Cdev
- Sketch->Include Library->MPU6050
5. The error: however library examples are not available in File->Examples as shown in second screenshot
- Examples from libraries installed via the library manager are available (eg. the Adafruit Motor Shield library seen on the screenshot)

Screenshots attached

**Desktop (please complete the following information):**
 - OS: linux
 - Version: ubuntu 20.04
 - Arduino IDE: 2.0.0-beta.12, Date: 2021-10-07T07:55:21.158Z
 - CLI Version: 0.19.1 alpha [718bbbf2]
 
![MPU6050_test | Arduino IDE 2 0 0-beta 12_001](https://user-images.githubusercontent.com/1144342/141520427-aa57ee9d-ef32-4157-a354-a938b2514c78.png)
![MPU6050_test | Arduino IDE 2 0 0-beta 12_003](https://user-images.githubusercontent.com/1144342/141520454-68eb27de-bcf8-43d8-b114-f1aadd561676.png)

**Comment by per1234** [comment]
Thanks for taking the time to submit an issue.

I see we already have a prior issue report about this at https://github.com/arduino/arduino-ide/issues/40

It's best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.

---
As mentioned in https://github.com/arduino/arduino-ide/issues/40, you'll find the examples all in this untitled menu item:

![image](https://user-images.githubusercontent.com/8572152/141534115-e5e246d3-2f48-410b-ab55-da3390327b81.png)
