### ISSUE TITLE
Open a project in Windows File Explorer

### ISSUE THREAD

**Issue by Silver-Fang** [arduino/arduino-ide#607]
**Is your feature request related to a problem? Please describe.**
Currently, a project will not be opened by double-clicking the .ino file in Windows File Explorer. IDE will always open the last project opened in the last session before close.

**Describe the solution you'd like**
IDE should recognize that I'm opening a specific .ino file and load the project.

**Comment by per1234** [comment]
Thanks for taking the time to submit an issue @Silver-Fang .

I see we already have a prior issue report about this at https://github.com/arduino/arduino-ide/issues/370.

It's best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
