### ISSUE TITLE
Make error message from compiling w/o board selected more user friendly

### ISSUE THREAD

**Issue by per1234** [arduino/arduino-ide#62]
## Describe the current behavior

On the first use, no board is selected. A new user may not realize it is necessary to select one. If they attempt to compile a sketch without selecting one, they will receive only this cryptic error message:

```
Compilation error: Missing FQBN (Fully Qualified Board Name)
```

and this notification:

```
Error: Request compile failed with message: Compilation error: Missing FQBN (Fully Qualified Board Name)
```

This doesn't mean anything to even very advanced IDE users, and the user will have difficulty understanding what they need to do to resolve it.

## To reproduce

1. Quit the IDE if it is running.
1. Simulate a fresh install by deleting the configuration folder:
   - Windows:
     ```
     C:\Users\<user name>\AppData\Roaming\arduino-ide\
     ```
   - Linux:
     ```
     ~/.config/arduino-ide/
     ```
   - macOS:
     ```
     ~/Library/Application Support/arduino-ide/
     ```
   This step is done because the IDE currently makes it otherwise difficult for those with internal serial ports to achieve the required state of having no port selected, due to the odd fallback port selection behavior (e.g., https://github.com/arduino/arduino-ide/issues/180).
1. Start the Arduino IDE.
   The board/port selector menu should show "**:x: No board selected**".
1. Select **Sketch > Verify/Compile** from the Arduino IDE menus.

## Describe the request

Show a user friendly error message. Something like:

> No board selected. Please select your Arduino board from the **Tools > Board** menu.

## Desktop

- OS: Windows 10
- Version: 2.0.0-rc3-snapshot.1d88263
Date: 2022-01-24T16:22:30.529Z
CLI Version: 0.20.2 [13783819]

## Additional context

Even among Arduino CLI users, I have found that the concept of "FQBN" is not widely known. IDE users are even less likely to be familiar with this acronym, and even less anxious to spend their time learning what it means, since the it is not otherwise a part of the IDE user experience.

---

Note that the error message produced by the reproduction instructions above is currently different than described due to a recent regression in Arduino CLI: https://github.com/arduino/arduino-cli/issues/1812

### Related

- https://github.com/arduino/docs-content/issues/300

**Comment by ubidefeo** [comment]
with an upcoming minor UX facelift the Verify/Upload buttons won't be enabled unless they can yield results.
* no board is selected > no compilation is possible
* no board is discovered (platform/board/discovery constraints apply) > no upload is possible

Those changes are not exactly around the corner, so maybe it's worth to just map this error to a more meaningful string for now.
I'll give it a criticality label and move it to one of our upcoming sprints

**Comment by kittaakos** [comment]
> they will receive only this cryptic error message:
> 
> ```
> Compilation error: Missing FQBN (Fully Qualified Board Name)
> ```

Currently blocked by this: https://github.com/arduino/arduino-cli/issues/1812.

The CLI is used to log `Missing FQBN`, now it's `Marshal called with nil` if the FQBN is not set. The IDE2 has no chance to figure out the cause of the issue and translate it into a human-readable error message.

**Comment by kittaakos** [comment]
Related: https://github.com/arduino/arduino-ide/issues/845
