### ISSUE TITLE
Change command line flags used to the start language server

### ISSUE THREAD

**Issue by cmaglie** [arduino/arduino-ide#622]
we should remove the flags:
* `-cli /path/to/atduino-cli`
* `-cli-config /path/to/cli-config.yml`

and replace them with:
* `-cli-daemon-addr localhost:50051`
* `-cli-daemon-instance 1`  (where 1 is the "Instance" value of the gRPC instance you're using in the IDE)

I need this change for the next release of the language server.

**Comment by per1234** [comment]
Resolved by https://github.com/arduino/arduino-ide/pull/610
