### ISSUE TITLE
Provide Chinese support

### ISSUE THREAD

**Issue by cike-567** [arduino/arduino-ide#627]
**Is your feature request related to a problem? Please describe.**

**Add support for Chinese**

**Describe the solution you'd like**

**I can help within my ability.For example, translate text.**

**Describe alternatives you've considered**

**Machine translated text.**

**Comment by per1234** [comment]
>I can help within my ability.For example, translate text.

Thanks so much for your generous offer @cike-567! We are now putting out a call for assistance from the community in the translation of the Arduino IDE. This is being done via the Transifex platform:

https://www.transifex.com/arduino-1/ide2/
