### ISSUE TITLE
Port selection disappeared from the tools menu

### ISSUE THREAD

**Issue by strickce** [arduino/arduino-ide#628]
**Describe the bug**
I have been using Beta 12 for several days and have successfully uploaded to my esp8266 several times.  But this morning, the port selection is gone from the tools menu.  When I try to load my sketch, I get an error saying that I must select a port, but of course I cannot, since the menu item is missing.

**To Reproduce**
I have no idea what caused the menu to disappear, so I don't know how you could reproduce it.

**Expected behavior**
The menu item should always be present

**Screenshots**

<img width="756" alt="Screen Shot 2021-11-20 at 7 50 31 AM" src="https://user-images.githubusercontent.com/45801945/142727294-16e492a6-51bf-4149-9a82-21329a31a6bc.png">

**Desktop (please complete the following information):**
 - OS: [MACOS]
 - Version: [12.0.1]

**Additional context**

**Comment by strickce** [comment]
I just tried to select another board and port, and got an error that there were no ports found.  I unplugged the usb cable and reinserted it and the port showed up there and the menu item returned.  So I'm not sure what the problem really is.  First, I think the IDE should have known that the port was there.  But if not, I think the menu item should be there and it should report that there are no ports found.

**Comment by ubidefeo** [comment]
hi @strickce 
on which version of the IDE are you?
Beta 12 or Nightly?
We have done some refactoring this past week on that specific item, so if it's the Nightly it's something we need to address as a regression

**Comment by per1234** [comment]
Thanks for taking the time to submit an issue.

I see we already have a prior issue report about this at https://github.com/arduino/arduino-ide/issues/573.

It's best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.

**Comment by strickce** [comment]
I am using beta 12
