### ISSUE TITLE
Deleting primary tab has no effect

### ISSUE THREAD

**Issue by per1234** [arduino/arduino-ide#649]
### Describe the problem

Sketch files can be deleted by selecting "**Delete**" from editor toolbar context menu.

🐛 The "**Delete**" menu option is enabled when the primary tab is selected, and a confirmation dialog indicates it will delete the sketch, but nothing happens.

### To reproduce

1. Select **File > New** from the Arduino IDE menus.
1. Save the sketch to somewhere convenient.
1. Select the leftmost tab of the sketch.
1. Click the **●●●** icon on the right side of the editor toolbar.
1. Select "**Delete**" from the menu.
   A "**Do you want to delete the current sketch?**" dialog will appear.
1. Click the <kbd>OK</kbd> button.

🐛 The sketch remains open in Arduino IDE.

🐛 If you check the location of the sketch on your drive, you will see that it is still present.

### Expected behavior

If sketch deletion is offered, it should work.

#### Original report

2.0.0-rc1-snapshot.f0d9894

#### Last verified with

692f29f

### Operating system

- Windows
- macOS

### Operating system version

- Windows 10
- Windows 11
- macOS 12.5.1

### Additional context

Arduino IDE 1.x has the same behavior of deleting the sketch when the primary tab is deleted via the tab management menu, except it works in Arduino IDE 1.x.

#### Additional reports

- https://github.com/arduino/arduino-ide/issues/1843

**Comment by mklemarczyk** [comment]
I can not delete additional files / tabs in 2.0.0-rc3. It is regression.
