### ISSUE TITLE
Arduino splash screen is too intrusive

### ISSUE THREAD

**Issue by ckuethe** [arduino/arduino-ide#653]
**Describe the bug**
Arduino splash screen pops up right in the middle of the screen, on all workspaces, and can't be dismissed or resized. This is super annoying while startup is experiencing other issues.

**To Reproduce**
1. start arduino ide in one workspace
2. switch to another workspace
3. observe that the splash screen follows you areound

**Expected behavior**
Make the splash screen movable, dismissable, minimizable, etc.

**Screenshots**
![Screenshot_2021-12-01_14-31-41](https://user-images.githubusercontent.com/1131751/144324893-85be8491-4957-458e-956d-572f6b2486d6.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu x86_64
 - Version: 21.04LTS
 - Desktop: XFCE4
 - Arduino: 2.0.0-rc1

**Additional context**

**Comment by per1234** [comment]
Hi @ckuethe. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/324 and https://github.com/arduino/arduino-ide/issues/325.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
