### ISSUE TITLE
Show "Tools > Port" menu even when empty

### ISSUE THREAD

**Issue by per1234** [arduino/arduino-ide#655]
### Describe the request

Show A **Port** menu item under the Arduino IDE **Tools** menu even when there are no ports to populate that **Tools > Port** menu.

🙂 The lack of ports will be communicated to the user in an intuitive manner.

### Describe the current behavior

The Arduino IDE's **Tools > Port** menu is populated by the discovered ports.

An unexpected lack of a port is a common problem for Arduino users. This might happen when the user has a bad USB cable, didn't install the drivers for their board, burned up the board, etc.

Currently, when no ports were discovered the **Tools > Port** menu item is missing entirely. I feel this is not a great user experience. An empty menu better communicates the lack of a port to the user than the menu itself being absent. The missing menu gives the user the impression there is a fault in the Arduino IDE application rather than a lack of an external resource listed by the menu.

![image](https://user-images.githubusercontent.com/8572152/144349144-2a026cad-e146-4e06-81a0-b5a99c2d92b7.png)

Compare to the behavior of Arduino IDE 1.x under these conditions:

![image](https://user-images.githubusercontent.com/8572152/144348961-b914ebbc-97b5-4201-bd95-4a91b00f6520.png)

### Arduino IDE version

2.0.0-rc1-snapshot.f0d9894

### Operating system

Windows

### Operating system version

10

### Additional context

There are some other menus that are dependent on external resources:

- **File > Sketchbook** - Equivalent request tracked at https://github.com/arduino/arduino-ide/issues/569
- **File > Examples** - this will never be empty under normal conditions due to the built-in examples included with the Arduino IDE installation
- **Tools > Board** - this is unlikely to be empty due to the IDE installing Arduino AVR Boards on first run (https://github.com/arduino/arduino-ide/pull/497)

---

Originally reported at https://forum.arduino.cc/t/compilation-fails-due-to-no-upload-port-specified/926836/5

---

Additional reports:

- https://forum.arduino.cc/t/why-is-there-no-port-menu-item-under-tools/942983

**Comment by seaxwi** [comment]
I think this issue should be prioritized. I am getting feedback from several Help Center readers that are confused about why the menu option is missing. I'm addressing this on my end by updating content, but the fact remains that there are tons of content out there assuming that the **Tools > Port** menu will always be available. I agree with @per1234 about an empty menu being fundamentally better for user experience.

I suggest displaying the text "No ports discovered" (or whatever the Board Selector shows). This way there is a shared "phrase" that lends itself to searching and writing troubleshooting content.
