### ISSUE TITLE
Parts of the UI disappear when window is to small

### ISSUE THREAD

**Issue by dronecz** [arduino/arduino-ide#662]
**Describe the bug**
Footbar of the IDE disappear when window height is < 545 px. Search icon (top right corner) disappear when width of the window < 560px 

**To Reproduce**
see screenshot

**Expected behavior**
Footbar should be always visible or windows should have some minimal size, after which you could not make it smaller.  

**Screenshots**
![arduino_2_rc1_resize_issue](https://user-images.githubusercontent.com/16454728/144589424-1b23c294-703d-41d3-8052-55745f1db41b.gif)

**Desktop (please complete the following information):**
- OS: Windows 10 19043.1348
- Version: 2.0.0-rc1
- Date: 2021-11-30T13:13:52.071Z
- CLI Version: 0.20.1 [abb21449]

**Comment by kittaakos** [comment]
> Search icon (top right corner) disappear

Related issue: https://github.com/arduino/arduino-ide/issues/129

**Comment by dronecz** [comment]
Thx @kit, I did not find this issue.

**Comment by per1234** [comment]
Closing as resolved by https://github.com/arduino/arduino-ide/pull/1151
