### ISSUE TITLE
Copy code for discord

### ISSUE THREAD

**Issue by DarwinWasWrong** [arduino/arduino-ide#672]
In the edit menu, there is an option to **copy code for forum**. _Control shift C_
this places [CODE]  and [/CODE] around the copied code.  
This is very handy for posting code to the forum.

Is it possible to add either a **copy code for discord**  or have the code block specification adjustable  in setup

On discord, the code surrounds are three back ticks, the word arduino  then three back ticks closing off the block
`\`` arduino        ```

The use of the arduino keyword colors the code

![image](https://user-images.githubusercontent.com/6262140/145321195-691d96d9-3d6c-4e8d-96e2-f3ddc0dd4716.png)

**Comment by per1234** [comment]
Hi @DarwinWasWrong. Fortunately, the switch to using Discourse for the Arduino Forum software last spring introduced support for the same Markdown markup language used by Discord, GitHub, Stack Exchange, etc. This means that a single menu item can serve for all these communication channels used by the Arduino community.

It was only necessary to change from using BBCode (which is still supported as an alternative markdown language on the forum) to Markdown in the copied text. That work has already been done in [Arduino IDE 2.x](https://github.com/arduino/arduino-ide).
