### ISSUE TITLE
'\t' sent to Serial Monitor are converted to single space

### ISSUE THREAD

**Issue by ermtl** [arduino/arduino-ide#675]
In previous versions (up to Arduino 1.8x), sending a /t tab character to the serial monitor resulted in an aligned output (8 character tab spacing)

Exemple
 ```
 int value1=11;
 int value2=22;
 int value3=33;
 Serial.print("\tParameter 1\tParameter 2\tParameter 3\n");
 Serial.print("\t");
 Serial.print(value1);
 Serial.print("\t\t");
 Serial.print(value2);
 Serial.print("\t\t");
 Serial.println(value3);

```
in previous versions, the output would look like this
```
        Parameter 1     Parameter 2     Parameter 3
        11              22              33
```
In Arduino 2, it looks like this :

```
Parameter 1 Parameter 2 Parameter 3
11 22 33
```
The \t character is replaced by a space (except as the first character of a line where it produces no output).

This makes tables and aligned data difficult to read as proper formatting is lost.

I tested this on Linux Mint 20.2

**Comment by per1234** [comment]
Thanks for your report @ermtl
 
I am not able to reproduce the issue with Arduino IDE 2.0.0-beta.11, but I am able to reproduce it with 2.0.0-beta.12 and onward. 

So I'm certain it was introduced by https://github.com/arduino/arduino-ide/pull/524, as with the similar https://github.com/arduino/arduino-ide/issues/535
