### ISSUE TITLE
Unintuitive dialogue on close with unsaved changes

### ISSUE THREAD

**Issue by UKHeliBob** [arduino/arduino-ide#677]
The standard Windows dialogue when closing an unsaved document is used by the classic IDE and offers 3 options, ie save changes Yes, No and Cancel and the default is Yes

![image](https://user-images.githubusercontent.com/4510180/145712063-ab95aed9-68c6-4db3-8002-3d859519e4e7.png)

The 3 options are very clear and the default is to save the changes

However, with IDE 2.0 the dialogue offers only 2 options, Yes and No   
![image](https://user-images.githubusercontent.com/4510180/145712089-b04ec438-a016-45d8-b10b-92a75323994c.png)

The default is still Yes, however, the logic is inverted compared to the standard dialogue and the default is for changes not to be saved, which I feel is wrong

Was there a reason for departing from the standard and inverting the logic ?

See https://forum.arduino.cc/t/ide-closing-dialogue/934992

**Comment by per1234** [comment]
This was resolved by https://github.com/arduino/arduino-ide/pull/1351 but we didn't close this issue at that time.

The dialog whenever closing an IDE window would result in loss of sketch content now looks like this:

![image](https://user-images.githubusercontent.com/8572152/207848879-64f51d5f-c410-4099-8144-1de90cd94c0d.png)

The default selection is the safe option of saving the sketch.
