### ISSUE TITLE
Verbose upload output rate is very slow

### ISSUE THREAD

**Issue by per1234** [arduino/arduino-ide#68]
## Describe the bug

🐛 The rate of the output from the upload tool shown when verbose upload output is enabled in the preferences is very slow. 

There seems to be some significant bottleneck in the communication stream between the tool and the Pro IDE's output pane.

## To Reproduce

1. Select **File > Preferences** from the Arduino IDE menus.
1. Check the box next to "**Show verbose output during: upload**"
1. Click the <kbd>OK</kbd> button.
1. Upload a sketch to an AVR board, megaAVR board (upload tool is AVRDUDE), or the "Programming Port" of a Zero (upload tool is OpenOCD).
   For some reason, I don't have the problem when uploading to a board that uses bossac as the upload tool (e.g., the "Native Serial" port of the Zero).

🐛 The output from the upload tool slowly streams in to the output pane for seconds after the actual upload has finished.

## Expected behavior

The upload tool output to be displayed in the output pane at approximately the same speed as when using it from the command line.

### Original report

- OS: Windows 10
- Version: 0.1.4-snapshot.3042c1a
Date: 2021-02-08T10:04:20.854Z
CLI Version: 0.15.1 alpha [c7403ed2]

### Last verified with

- OS: Windows 10, Ubuntu 20.04
- Version: 2.0.0-rc7

## Additional context

I don't have any problems with the rate of the compilation output.

**Comment by ben-qnimble** [comment]
I believe I see the same issue when uploading a sketch from the IDE via the bossa command line program. Bossa has output progress bar that gives an update after every page is written. When I run this from the command line, the the write and verify is almost instant (I can't see it, bossa reports less than 100ms to write 70 pages). When I run from the IDE, bossa reports the same time, it takes ~3 seconds for the progress bar to go from 0% to 100%. It fees like to can only do ~20 screen updates per second. For 70 pages, each with a display update, that takes ~4 seconds. 

Having the serial monitor open or not makes no difference.

**Comment by ubidefeo** [comment]
@ben-qnimble @per1234 

There's some kind of throttling we had to add to overcome a responsiveness issue and it is probably at the root of this.
We need to rework that on the CLI side so it might take a bit :)

**Comment by Lorandil** [comment]
I'm experiencing the same behaviour... Upload lags behind by some dozen seconds.

**Comment by FredM67** [comment]
Problem still present with:
Version: 2.0.0-rc3
Date: 2021-12-22T15:46:56.004Z
CLI Version: 0.20.2 [13783819]

Copyright © 2022 Arduino SA

**Comment by GClairet** [comment]
I'm experiencing the same behaviour... Upload lags behind by some tens seconds and I have to repress the reset button on my Arduino Micro to have a programming success.
Version: 2.0.0-rc5
Date: 2022-03-10T11:09:10.332Z
CLI Version: 0.21.0 [10107d24]

Copyright © 2022 Arduino SA
