### ISSUE TITLE
Ports list not populated in "Select Other Board & Port" dialog of subsequent windows

### ISSUE THREAD

**Issue by per1234** [arduino/arduino-ide#681]
## Describe the bug

The "**Select Other Board & Port**" dialog allows any available board and port to be selected.

When the IDE is started, the dialog contains the list of ports as expected. However, after opening any additional 

## To Reproduce

1. Ensure that your computer presents at least one virtual serial port, such as it will if an Arduino board is connected.
1. Select **File > New** from the Arduino IDE menus.
   ℹ️ It occurs on opening any new IDE window; not only on a new sketch.
1. Open the board selector dropdown menu:
   ![image](https://user-images.githubusercontent.com/8572152/145824240-feab6e08-c4a3-4a74-859e-e43ee8971390.png)
1. Select "**Select Other Board & Port**" from the dropdown menu.

:bug: Note that the "**PORTS**" section of the dialog says "**NO PORTS DISCOVERED**":

![image](https://user-images.githubusercontent.com/8572152/145824384-bab8f797-a5fa-4612-ae6b-102c45cd189a.png)

## Expected behavior

The "**Select Other Board & Port**" dialog to always show the list of available ports.

### Original report

- OS: Windows 10
- Version: 2.0.0-rc2
Date: 2021-12-13T10:09:39.122Z
CLI Version: 0.20.2 [13783819]

### Last verified with

- OS: Windows 10
- Version: 2.0.0-rc5-snapshot-c9b498f
Date: 2022-03-29T15:54:18.646Z
CLI Version: 0.21.0 [10107d24]

## Additional context

---

The "**PORTS**" section of the dialog is populated as expected if a port is added or removed, which can be produced by connecting or disconnecting an Arduino board to your computer.

---

The issue occurs even in the first window if a reload occurs, such as what happens when certain preferences are changed.

---

The issue also occurs with the build from https://github.com/arduino/arduino-ide/commit/49d12d99ff2843bf62a81932eae06cdec9c4a5f2, so it was not introduced by https://github.com/arduino/arduino-ide/commit/a8ae0bb4e035d655c61fa68836795430ae9e080f

---

It seems very similar to https://github.com/arduino/arduino-ide/issues/605, except for the following significant difference:

> 4. Pull out my USB connected board and plug it in again
> 5. Still found no ports connected

---

Originally reported by @UKHeliBob at https://forum.arduino.cc/t/upload-does-nothing/930864/42

**Comment by bugrasan** [comment]
experiencing the same issue with `arduino-ide_nightly-20220316_Linux_64bit`. however disconnecting & reconnecting the board from USB doesn't populate the dialog at all.
however the port `ttyUSB0` is available over the menu.
![2022-03-19-arduino1](https://user-images.githubusercontent.com/8294295/159097694-b097bc19-aa7b-4ed4-a489-c712fb45edd2.png)
![2022-03-19-arduino2](https://user-images.githubusercontent.com/8294295/159097695-2d2fc5fc-7ef1-4234-821e-6056dfc65a69.png)
![2022-03-19-arduino3](https://user-images.githubusercontent.com/8294295/159097700-da96043e-d34a-4189-abef-90e40f5696a0.png)
