### ISSUE TITLE
Firmware update fails if Serial Monitor is open

### ISSUE THREAD

**Issue by per1234** [arduino/arduino-ide#684]
## Describe the bug

The Arduino IDE includes a "**WiFi101 / WiFiNINA Firmware Updater**"" tool that can be used to update the firmware on the WiFi radio module of Arduino boards such as the [MKR WiFi 1010](https://store.arduino.cc/arduino-mkr-wifi-1010) and [Nano 33 IoT](https://store.arduino.cc/arduino-nano-33-iot).

If the Serial Monitor is open when a firmware update is attempted, it fails.

## To Reproduce

1. Connect an Arduino board that has a u-blox NINA-W102 module to your computer via the USB cable.
1. Select the board and port in the IDE.
1. Open the Arduino IDE Serial Monitor (**Tools > Serial Monitor**).
1. Select **Tools > WiFi101 / WiFiNINA Firmware Updater** from the Arduino IDE menus.
1. Select the board in the **Firmware Updater** dialog.
1. Click the <kbd>Check Updates</kbd> button.
1. Click the <kbd>Install</kbd> button
   (it doesn’t matter which firmware version you flash).
1. Wait for the update process to finish.

The process fails without any indication of the cause

> ⚠️ Installation failed. Please try again.

## Expected behavior

Ideally, the IDE's Firmware Updater tool would automatically close the serial port as needed, reopening it in Serial Monitor once done, similar to how it is handled during the Upload process.

If that is not feasible, it should check for open Serial Monitor at the start of the firmware update process and clearly communicate to the user that they must close it. This is the approach taken by the classic IDE's firmware updater tool:

![Clipboard01](https://user-images.githubusercontent.com/8572152/145947181-8d571c5d-4be6-4071-aca1-d9c59c3de516.png)

## Desktop

- OS: Windows 10
- Version: 2.0.0-rc2
Date: 2021-12-13T10:09:39.122Z
CLI Version: 0.20.2 [13783819]

## Additional context

I think it could be a common occurrence because most often people are motivated to update their firmware after seeing the outdated firmware message that is printed to Serial Monitor by the "CheckFirmwareVersion" example of the WiFiNINA library or by the ArduinoIoTCloud library.

**Comment by ubidefeo** [comment]
When this kind of prioritised workflows are intiated (we might have something else in the future) we should force close the Serial Monitor and Serial Plotter views/apps and close the connection.
Firmware update is a blocking operation anyway, and messing with serial ports in the process will sure lead to failure
