### ISSUE TITLE
startup splash screen shows on all virtual desktop screens

### ISSUE THREAD

**Issue by sebasdt** [arduino/arduino-ide#69]
**Describe the bug**
This is more an enhancement thingy not really a bug. 
anyway, this "bug" happens when you switch virtual desktop screens and And the Arduino pro ide splash screen shows up.

**To Reproduce**
this only will happen when using a desktop or laptop with windows 10. (I only have windows)
1. startup Arduino pro ide
2. wait until the splash screen shows.
3. switch to another virtual desktop screen.

**Expected behaviour**
what I think needs to happen is:
show the splash screen on the virtual desktop screen where the Arduino pro ide was started.

**Screenshots**

https://user-images.githubusercontent.com/67417070/107115238-7fcf1800-686b-11eb-962c-6fe0562c0310.mp4
![image](https://user-images.githubusercontent.com/67417070/107114982-cc195880-6869-11eb-80bb-419cec44bca9.png)

**Desktop**
 - OS: windows 10 pro
 - Version: 20H2

**Additional context**
for me this isn't a problem, I can deal with it.

**Comment by Lanove** [comment]
Also can you please make the startup splash screen not overlaying every program?, it's pretty annoying because i can't do anything else while waiting the splash screen to disappear.

**Comment by kittaakos** [comment]
There is no splash screen anymore. See https://github.com/arduino/arduino-ide/pull/1287. Please let us know if the issue persists on your side, and I will reopen this task. I am closing as resolved.
