### ISSUE TITLE
portenta machinge control not working

### ISSUE THREAD

**Issue by VibinNoodles** [arduino/arduino-ide#718]
it connected at first and I downloaded all the nessacary things then after that it stopped connecting and I can't get it to connect

**Comment by per1234** [comment]
Hi @VibinNoodles. Thanks for your interest in this open source project. This topic appears to be more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/

I'll keep an eye on that discussion over on the forum and if, after getting more information about the problem, we determine that it indicates a bug or missing feature in the Arduino IDE 2.x, I'll be sure to re-open this issue report.
