### ISSUE TITLE
macOS, cannot open a file directly from Finder

### ISSUE THREAD

**Issue by sstaub** [arduino/arduino-ide#72]
**Describe the bug**
On macOS it is not possible to open a file directly from the Finder.
This possible with the classic Arduino IDE.
On double click or right click / open with... starts the Pro IDE but not with right file

**To Reproduce**
1. Go to Finder
2. Open a folder with an .ino file inside
3. Double click for opening
4. IDE opens but not with the file you clicked

**Expected behavior**
It should possible to open an .ino file directly from the Finder, like on Classic IDE.
Also with a message when there is no right folder -> auto create a folder

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7
 - Version: Alpha 0.1.3

**Comment by fm-sys** [comment]
Same applies to Windows

**Comment by per1234** [comment]
Issue for the equivalent deficiency on Windows here:
https://github.com/arduino/arduino-ide/issues/370

**Comment by fstasi** [comment]
Assigned to Mark
