### ISSUE TITLE
Support for other languages such as Portuguese-BR

### ISSUE THREAD

**Issue by MicSG-dev** [arduino/arduino-ide#725]
**Is your feature request related to a problem? Please describe.**
Arduino IDE 1.8.19 and earlier supports my language language (PT-BR). I would like the arduino Arduino IDE 2.0 to also have support for other languages.

**Describe the solution you'd like**
Implement language from other languages, such as Portuguese-BR.

**Additional context**
![image](https://user-images.githubusercontent.com/71986598/147584582-8a6a4553-eee5-488a-b460-65721261ffb3.png)

**Arduino IDE 2.0 RC (2.0.0-rc3)**
Windows ZIP file (64bit)
Version: 2.0.0-rc3
Date: 2021-12-22T15:46:56.004Z
CLI Version: 0.20.2 [13783819]

**Comment by per1234** [comment]
Hi @MicSG-dev. There is an existing high level issue about this here: https://github.com/arduino/arduino-ide/issues/28
I believe the final step is tracked here: https://github.com/arduino/arduino-ide/issues/712

You'll be glad to learn that, thanks to the amazing work from the Arduino community, we have already reached 100% translation coverage to Portuguese as well as several other languages:
https://www.transifex.com/arduino-1/ide2/
