### ISSUE TITLE
[Feature-Request] Open the Arduino IDE with a different skeleton using arduino-cli

### ISSUE THREAD

**Issue by F-Schmidt99** [arduino/arduino-ide#733]
When opening the Arduino IDE, this skeleton code will be loaded:

`void setup() {

}

void loop() {

}`

It would be awesome, if a sketch could be created from a file copied.
The command could look like this:

`arduino-cli sketch new my_new_program_name --from my_skeleton_file.ino`

This feature would be useful for universities, because then you could just create a simple desktop icon which calls this command and then they can start directly without loading an example code and saving a copy from that.

Even better would be an optional flag which would first execute the command and create a new sketch and after that starts the Arduino IDE.

**Comment by per1234** [comment]
Thanks for taking the time to submit an issue @F-Schmidt99 .

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/373.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
