### ISSUE TITLE
What release Chinese version

### ISSUE THREAD

**Issue by PH8719** [arduino/arduino-ide#741]
What release Chinese version

**Comment by per1234** [comment]
Hi @PH8719. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/627.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
