### ISSUE TITLE
Warnings and errors in the output window aren't highlighted anymore

### ISSUE THREAD

**Issue by Lorandil** [arduino/arduino-ide#742]
Before IDE 2.0 warnings and errors in the compiler output were easy to spot because they were highlighted in red.

It would be really helpful to get this feature back, I think it was really helpful, especially for beginners.

**Comment by per1234** [comment]
Hi @Lorandil. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/229.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
