### ISSUE TITLE
Newly plugged in serial ports not detected until program restart

### ISSUE THREAD

**Issue by tavdog** [arduino/arduino-ide#744]
**Describe the bug**
If I plug in a device to be programmed (eg /dev/cu.usbserial-02473F29) the IDE will not detect this serial port until the IDE is restarted.

**Expected behavior**
In the old IDE new ports would be detected without a restart.

**Desktop (please complete the following information):**
 - OS: OSX M1 Macbook
 - Version: Version: 2.0.0-rc3

**Comment by ubidefeo** [comment]
@tavdog
can you check with the latest Nightly build?
https://github.com/arduino/arduino-ide#nightly-builds

**Comment by tavdog** [comment]
Yes, the nightly build has fixed this issue.
