### ISSUE TITLE
Cannot undock Serial Monitor

### ISSUE THREAD

**Issue by TS200010** [arduino/arduino-ide#755]
**Describe the bug**
The Serial Monitor Window is locked in a Tab. In previous versions, the monitor appeared in a separate window. This is my preferred behaviour.

**To Reproduce**
Open Serial Monitor and try to move the tab to a window...

**Expected behavior**
The Serial Monitor should open in a separate window just as earlier versions did or it should be possible to undock it.

**Screenshots**
None

**Desktop (please complete the following information):**
OSX Catalina

**Additional context**
None

**Comment by per1234** [comment]
Hi @TS200010. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/289.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
