### ISSUE TITLE
Add preference to disable splash screen

### ISSUE THREAD

**Issue by rozrabiak** [arduino/arduino-ide#763]
Hi, add to preferences "disable splash screen" OR change splash screen to not to show ALWAYS ON TOP. When Arduino IDE 2.0 starting splash screen is always ON TOP over all running applications.

**Comment by per1234** [comment]
Hi @rozrabiak. Thanks for taking the time to submit a request.

>OR change splash screen to not to show ALWAYS ON TOP

We are already tracking this issue at https://github.com/arduino/arduino-ide/issues/324 and even have a proposed fix here: https://github.com/arduino/arduino-ide/pull/717

So this issue will be dedicated solely to your request:

>add to preferences "disable splash screen"

**Comment by per1234** [comment]
Obviated by the removal of the splash screen entirely in https://github.com/arduino/arduino-ide/pull/1287
