### ISSUE TITLE
IDE 2.0 Serial monitor Side by Side not working as example shown

### ISSUE THREAD

**Issue by RonKsr** [arduino/arduino-ide#764]
Running Windows 11
Sketch1 Ardunio MEGA port 9   Hello world!
Sketch2 Arduino UNO port 3     Hello Mars!

Followed the example 'https://docs.arduino.cc/software/ide-v2/tutorials/ide-v2-serial-monitor'.
 Does not work as the example explains. The monitors for Sketch1 and Sketch2 do not run independently of each other. 
Both Sketchs output the same text on their Serial monitors as:
Hello world!
Hello Mars!
Hello world!
Hello Mars!
Hello world!
Hello Mars!

**Comment by per1234** [comment]
Hi @RonKsr. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/613.
While looking at https://github.com/arduino/arduino-ide/issues/613, I realized that it was not as clear as it could be regarding this output merging behavior, even though we had discussed on a related thread. So I added a note to it about that behavior.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
