### ISSUE TITLE
Can only open sketch files

### ISSUE THREAD

**Issue by iplayfast** [arduino/arduino-ide#767]
**Describe the bug**
File/Open will only open a file with the extension of .ino
Often you need to see include files to know how classes are to be used.

You at minimum should have a wildcard (*.*) open, but should also allow *.cpp and *.h as well.

**Comment by per1234** [comment]
Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/88.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

>Often you need to see include files to know how classes are to be used.

Then you'll be very happy to learn that Arduino IDE 2.x already provides this functionality in a vastly more convenient manner than hunting down the correct (you have multiple copies of some libraries, and which one is used depends on the conditions of the specific compilation you are doing) path to use in the **File > Open** dialog.

Simply right click on the file name in the `#include` directive and then select "**Go to Definition**" from the context menu. The header file will now open as a tab in the Arduino IDE. You can also do this with specific code you are interested in to be taken to its definition.
