### ISSUE TITLE
Use the latest "pluggable monitor" gRPC APIs

### ISSUE THREAD

**Issue by fstasi** [arduino/arduino-ide#769]
The IDE2 needs to use the latest pluggable monitor gRPC APIs, rather than the legacy ones, which are deprecated

**Comment by PaulStoffregen** [comment]
@AlbyIanna - Any chance for pluggable monitor to be implemented by RC7?

**Comment by AlbyIanna** [comment]
Hi @PaulStoffregen! Sadly, this was delayed for multiple reasons, the main ones being the complexity of the change (a pretty big refactor was necessary). BUT we're working on it! I can't make promises, but I believe it will be working soon.

If you're curious, this is the branch we're working on: https://github.com/arduino/arduino-ide/tree/pluggable-monitor

**Comment by PaulStoffregen** [comment]
@AlbyIanna - Glad it's happening.  Do you have a Teensy board?  If not and you want one for testing, just say the word and I can send you one.  As far as I know, Teensy is the only 3rd party board (so far) using the new pluggable monitor API.

**Comment by AlbyIanna** [comment]
Thank you so much @PaulStoffregen 😄  but I believe @ubidefeo can lend me one of his Teensy boards for testing!
