### ISSUE TITLE
Can't select language packet in Preferences

### ISSUE THREAD

**Issue by ChrSchultz** [arduino/arduino-ide#771]
**Describe the bug**
I am not able to select other language packs for ui.

**To Reproduce**
1. Go to prefernces
2. Click on '.language 'en'
3. try to select cn or de or each other...
4. remark, you are not able to select any other language , but en.
5. than I have a look into the installation Directory in laguage and all other languages are installed.

**Expected behavior**
I expect, selecting many other languages

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Window 10 21H2 -64bit
 - Version: 2.0.0 rc3

**Additional context**
I tried in localuser and system installations mode and both is the behaviour the same

**Comment by per1234** [comment]
Hi @ChrSchultz it is possible to install the stock "language pack" extensions by following the instructions [here](https://github.com/arduino/arduino-ide/pull/625).

However, that only provides the base UI translations. None of the Arduino IDE-specific translations are in those extensions.
My understanding is that the integration of the Arduino translations depends on https://github.com/arduino/arduino-ide/issues/712

**Comment by qizaizi** [comment]
The plugin directory is in the installation location arduino2.0\Arduino IDE\resources\app\plugins
