### ISSUE TITLE
Auto Format doesn't do anything

### ISSUE THREAD

**Issue by NoSmoke999** [arduino/arduino-ide#78]
**Describe the bug**
Auto Format (ctrl-T) doesn't seem to do anything (unlike the non-pro IDE).

**To Reproduce**
2. Click on 'Tools/Auto Format'

**Expected behavior**
Code to be formatted.

**Desktop (please complete the following information):**
 - OS: [Win 10 Home 64 bit]
 - Version: [Version	10.0.19041 Build 19041; Arduino Pro 0.1.3  20201215]

**Additional context**

**Comment by JimDrewGH** [comment]
Does this problem really still exist nearly a year later?  I don't see the problem with beta 11, but I do with beta 12.
