### ISSUE TITLE
Output gets very slow during uploading on at least Arduino Uno

### ISSUE THREAD

**Issue by FredM67** [arduino/arduino-ide#785]
When clicking on "Upload", the output gets very slow just after displaying "Compilation complete.".
It's so slow, that I get the popup that Upload is done several seconds before all messages are displayed in the output.

**Comment by per1234** [comment]
OK, thanks for the clarification. For future reference, development of Arduino IDE 2.x is being done in this repository:
https://github.com/arduino/arduino-ide
so issues specific to Arduino IDE 2.x should be submitted here:
https://github.com/arduino/arduino-ide/issues
(I already transferred your issue)

The other repository:
https://github.com/arduino/Arduino
Is the home of the Arduino IDE 1.x code base, as well as a "catch all" issue tracker for reports related to things that don't have a dedicated issue tracker.

---

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/68.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
