### ISSUE TITLE
Serial Monitor update rate issue. 

### ISSUE THREAD

**Issue by cl330b** [arduino/arduino-ide#79]
The Serial Monitor built in to the IDE has a significantly delayed update rate.

I am using the Arduino Zero. I am using the following to print serial information to the internal Serial Monitor and an external bit of software (GTKTerm v1.1) to monitor the serial information being written to the native USB port. 

` Serial.begin(115200);
  SerialUSB.begin(115200);`

1. Open built in Serial Monitor.
2. Open external Serial Monitor.
3. Open scope to view which output is currently active.
4. View lag in the built in Serial Monitor.
5. Compare the lag with an external Serial Monitor.

I would expect to see the update rate of the built in Serial Monitor match the modulated outputs of the microcontroller. I am using a scope to view the outputs of the Zero. I can see in real time which outputs are on compared to the built in Serial Monitor and the external Serial Monitoring software.

(Please see attached screenshots for context.)
![no_cyan_pulses](https://user-images.githubusercontent.com/75517556/101975711-5a1eed00-3bf3-11eb-8d64-3c157eaac915.png)
![no_yellow_pulses](https://user-images.githubusercontent.com/75517556/101975713-5ee3a100-3bf3-11eb-9f4f-1ce17339875e.png)
![no_pink_pulses](https://user-images.githubusercontent.com/75517556/101975715-630fbe80-3bf3-11eb-9068-c2c0a8f409e5.png)

**Version Information:**
`Linux 5.8.0-31-generic arduino/arduino-pro-ide#33-Ubuntu SMP Mon Nov 23 18:44:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux` 
`arduino-pro-ide_nightly-20201211_Linux_64bit`

**Additional Information Regarding Issue**
When I hold the board in reset, the built in Serial Monitor continues to update as if still reading incoming serial data.

-cl330b

**Comment by toogooda** [comment]
Hi, can I please add that while the Serial monitor is struggling to keep up if effects the performance of the editor, with things like  Auto complete; auto indent and even Ctl+T not working.
I have to slow Serial down to 4800 board before the ide could keep up and allow debugging using Serial near real time.
In my example where I simple displayed an incrementing unsigned long then hit reset at 3000 shown onn the screen it continues to count up to over 6000.

```
unsigned long a=0;

void setup() {
  Serial.begin(4800);
}

void loop() {
  Serial.println(a);
  a++;
}
```

**Comment by pavel-b-kr12** [comment]
very bad performance at speed more than 57600
void loop() {
  Serial.println(1);
}
cause UI slowdown and progressive increasing lag before show new data in terminal

**Comment by ubidefeo** [comment]
@pavel-b-kr12 
can you try Beta 4 and if you still have the issue test the Nightly Build?
I know we have implemented a couple fixes for this but not sure they made it into release yet

**Comment by toogooda** [comment]
Beta 4 no improvement that I can see. will try nightly build.

**Comment by toogooda** [comment]
Tested nightly build seems to be a bit quicker but still unusable above 9600 :(
Some low speed serial output now OK
baud-----Serial Keep up
300-------Yes
1200------Yes
2400------Yes
4800------Yes
9600------No - but close
19200-----No
38400-----No
57600-----No
115200----No
 
```
unsigned long a=0;
void setup() {
  Serial.begin(4800);
}

void loop() {
  Serial.println(a);
  a++;
}
```
@ 115200 If I let it run for one second then hold reset it keeps scrolling for another 9-10 seconds

**Comment by ubidefeo** [comment]
@toogooda 
I'll investigate with the team tomorrow if that fix is on track :)

**Comment by goktug7913** [comment]
![image](https://user-images.githubusercontent.com/74943971/133625818-990103b8-a516-4ea1-a86b-4f3199b60520.png)
Still having this exact issue, i'm working on RF transceiving so this is becoming a big problem for me

**Comment by mcenderdragon** [comment]
I am running ide 2-rc3 and still have this issue. CPU is at 100% and the serial monitor is EMPTY. this makes button presses & the IDE in genrall very slow to respond. every other IDE (inlcuding the old one) does not have any similar issues.
