### ISSUE TITLE
Add `user-agent` property to gRPC client

### ISSUE THREAD

**Issue by cmaglie** [arduino/arduino-ide#790]
**Is your feature request related to a problem? Please describe.**
This feature request is related to this new feature of the `arduno-cli`: https://github.com/arduino/arduino-cli/pull/1640
`arduino-cli` now passes a new `ARDUINO_USER_AGENT` env variable to all the tools used to compile and upload. In particular, while running as a daemon `arduino-cli` will pass also the name of the client using the daemon instance (in our case it will be `ArduinoIDE`), for example:

```
ARDUINO_USER_AGENT=arduino-cli/0.21.0 ArduinoIDE/2.0.0-rc3
```

**Describe the solution you'd like**
Since gRPC already supports passing the user-agent, I'd like this option to be set to `ArduinoIDE/<version>`, like `ArudinoIDE/2.0.0-rc3`

**Comment by PaulStoffregen** [comment]
@silvanocerza - Any chance to have the IDE send this info soon, now that CLI 0.21 is integrated?  I need this info to begin testing on Teensy's upload tool to adapt between GUI vs CLI usage.

**Comment by silvanocerza** [comment]
@PaulStoffregen I've opened a PR, you should be able to test it as soon as the workflows generate the build artifacts if you don't want to wait for it to be merged in `main`. 

It's a small change so I would expect it will be merged in a short time.
