### ISSUE TITLE
Uploading to raspberry pi pico with no port selected

### ISSUE THREAD

**Issue by dommilosz** [arduino/arduino-ide#794]
**Describe the bug**
Upload button doesn't respond when raspberry pi pico without serial port is selected. In old version of the IDE the compilation works even if port is not selected. Old IDE simply uploads elf file to "USB drive" of the pico. Helpful when pico gets stuck and serial port doesn't work. Only possible option is to click bootsel button, after resetting into bootsel mode there is no serial port visible either only the usb drive so IDE 2.0 cannot upload. I have to upload program via old IDE in order to unstuck the pico.

The pico core resets the pico and then tries to upload to usb drive. When it cannot reset the drive (because of serial port not connected) it tries to upload to usb drive and may succed if the pico was in bootsel mode

The most interesting thing is that if I connect the serial port before it kinda remembers that and even if I restart the pico to bootsel mode (removing the serial connection) it stil lets me upload the sketch but fails after compiling because of need of serial connection. At that point it should be able to continue uploading and would most likely succed. When I reselect the pico device it starts preventing me clicking upload button again.

**To Reproduce**
1. Select raspberry pi pico device
2. Click on the upload button

**Expected behavior**
It uploads to visible usb drive with no port selected.

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Version: nightly 20220202

**Comment by per1234** [comment]
Thanks for taking the time to report this bug @dommilosz.

I see we have a previous report about this at https://github.com/arduino/arduino-ide/issues/770.
(the reporter was using a DigiSpark, but this bug affects any upload where it is not possible to select a port in the IDE)

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.

---

I have described a workaround here: https://github.com/arduino/arduino-ide/issues/770#issuecomment-1021087650
