### ISSUE TITLE
Custom board options menu items not in order specified by boards.txt

### ISSUE THREAD

**Issue by mjs513** [arduino/arduino-ide#801]
**Describe the bug**
In the boards.txt file for the Teensy we have specified a list of menu items for USB Type, e.g.,  
```
teensyMM.menu.usb.serial=Serial
teensyMM.menu.usb.serial.build.usbtype=USB_SERIAL
teensyMM.menu.usb.serial2=Dual Serial
teensyMM.menu.usb.serial2.build.usbtype=USB_DUAL_SERIAL
teensyMM.menu.usb.serial3=Triple Serial
teensyMM.menu.usb.serial3.build.usbtype=USB_TRIPLE_SERIAL
teensyMM.menu.usb.keyboard=Keyboard
teensyMM.menu.usb.keyboard.build.usbtype=USB_KEYBOARDONLY
teensyMM.menu.usb.keyboard.fake_serial=teensy_gateway
teensyMM.menu.usb.touch=Keyboard + Touch Screen
teensyMM.menu.usb.touch.build.usbtype=USB_TOUCHSCREEN
teensyMM.menu.usb.touch.fake_serial=teensy_gateway
teensyMM.menu.usb.hidtouch=Keyboard + Mouse + Touch Screen
teensyMM.menu.usb.hidtouch.build.usbtype=USB_HID_TOUCHSCREEN
teensyMM.menu.usb.hidtouch.fake_serial=teensy_gateway
teensyMM.menu.usb.hid=Keyboard + Mouse + Joystick
teensyMM.menu.usb.hid.build.usbtype=USB_HID
teensyMM.menu.usb.hid.fake_serial=teensy_gateway
teensyMM.menu.usb.serialhid=Serial + Keyboard + Mouse + Joystick
teensyMM.menu.usb.serialhid.build.usbtype=USB_SERIAL_HID
teensyMM.menu.usb.midi=MIDI
teensyMM.menu.usb.midi.build.usbtype=USB_MIDI
teensyMM.menu.usb.midi.fake_serial=teensy_gateway
teensyMM.menu.usb.midi4=MIDIx4
teensyMM.menu.usb.midi4.build.usbtype=USB_MIDI4
teensyMM.menu.usb.midi4.fake_serial=teensy_gateway
teensyMM.menu.usb.midi16=MIDIx16
teensyMM.menu.usb.midi16.build.usbtype=USB_MIDI16
teensyMM.menu.usb.midi16.fake_serial=teensy_gateway
teensyMM.menu.usb.serialmidi=Serial + MIDI
teensyMM.menu.usb.serialmidi.build.usbtype=USB_MIDI_SERIAL
teensyMM.menu.usb.serialmidi4=Serial + MIDIx4
teensyMM.menu.usb.serialmidi4.build.usbtype=USB_MIDI4_SERIAL
teensyMM.menu.usb.serialmidi16=Serial + MIDIx16
teensyMM.menu.usb.serialmidi16.build.usbtype=USB_MIDI16_SERIAL
teensyMM.menu.usb.audio=Audio
teensyMM.menu.usb.audio.build.usbtype=USB_AUDIO
teensyMM.menu.usb.audio.fake_serial=teensy_gateway
teensyMM.menu.usb.serialmidiaudio=Serial + MIDI + Audio
teensyMM.menu.usb.serialmidiaudio.build.usbtype=USB_MIDI_AUDIO_SERIAL
teensyMM.menu.usb.serialmidi16audio=Serial + MIDIx16 + Audio
teensyMM.menu.usb.serialmidi16audio.build.usbtype=USB_MIDI16_AUDIO_SERIAL
teensyMM.menu.usb.mtp=MTP Disk (Experimental)
teensyMM.menu.usb.mtp.build.usbtype=USB_MTPDISK
teensyMM.menu.usb.mtp.fake_serial=teensy_gateway
teensyMM.menu.usb.rawhid=Raw HID
teensyMM.menu.usb.rawhid.build.usbtype=USB_RAWHID
teensyMM.menu.usb.rawhid.fake_serial=teensy_gateway
teensyMM.menu.usb.flightsim=Flight Sim Controls
teensyMM.menu.usb.flightsim.build.usbtype=USB_FLIGHTSIM
teensyMM.menu.usb.flightsim.fake_serial=teensy_gateway
teensyMM.menu.usb.flightsimjoystick=Flight Sim Controls + Joystick
teensyMM.menu.usb.flightsimjoystick.build.usbtype=USB_FLIGHTSIM_JOYSTICK
teensyMM.menu.usb.flightsimjoystick.fake_serial=teensy_gateway
#teensyMM.menu.usb.disable=No USB
#teensyMM.menu.usb..disable.build.usbtype=USB_DISABLED
```
However, when we go in the IDE 2.0 when we select USB Type from the Tools dropdown (after selecting the board the order of USB Types appears to be in random order:
![Capture](https://user-images.githubusercontent.com/5366213/152181117-0cf93300-ddce-401b-b999-28437d5e7721.PNG)

This behavior not constrained to just this menu.  The list of boards is also not in the order specified.

**To Reproduce**
1. Install Teensy Boards using package: https://www.pjrc.com/teensy/td_156/package_teensy_index.json
2. Install Teensy from Boards Manager
3. Open boards.txt file in arduino15 for Teensy
4. Go to tools, select Teensy MircoMod
5. Select USB Type and compare to boards.txt for TMM.menu.usb....

**Expected behavior**
Order specified in the boards.txt file should be the order shown in the menu item in the Tools drop downs for the board specified.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10x64
 - Version: Version: 2.0.0-rc3-nightly.20220201
Date: 2022-02-01T03:08:59.105Z
CLI Version: 0.20.2 [13783819]

**Additional context**

**Comment by KurtE** [comment]
I thought I would mention, this is not specific to just this specific menu, it appears to be true with most if not all of the menus that are specified in boards.txt

For example CPU Speed: Arduino 1.8.19 follows the order in boards.txt:
![image](https://user-images.githubusercontent.com/1558080/152191876-ffc17d9f-46a5-4348-9561-ad8f09352c41.png)
But the daily build of IDE 2 does not:
![image](https://user-images.githubusercontent.com/1558080/152192150-541906ea-fbe4-4c87-84d7-d003aef357d6.png)

Likewise the order of the boards listed under Teensy does not match the order they are defined:
![image](https://user-images.githubusercontent.com/1558080/152192478-24b26ebd-a91e-48d4-b417-471bd405e2c7.png)

My guess not specific to teensy.

**Comment by per1234** [comment]
Thanks @KurtE. You make a valuable observation that this bug is universal to the sorting of all [custom board option](https://arduino.github.io/arduino-cli/dev/platform-specification/#custom-board-options) menus (except when the arbitrary sorting order of the IDE happens to match coincidentally).

I had modified the issue title to make sure the scope of this issue is clear to interested parties.

>Likewise the order of the boards listed under Teensy does not match the order they are defined

Even though they are very similar, I think I will use a dedicated issue to track the **Boards** menu sorting since I think this might facilitate the tracking, planning, and development work: https://github.com/arduino/arduino-ide/issues/802

**Comment by berrak** [comment]
I want to confirm the behavior after using the tips in reports #591 and #1030 and removing **all** the Arduino user data in the folder:
```
~/.config/arduino-ide
```
With this Arduino, IDE 2.0-rc9 updates the *Tools->Board part number* after restarting the IDE. The pictures confirm what this issue describes but emphasize that wiping the user data does not change anything. 
![IDE-1 8 19-SortOrderOK](https://user-images.githubusercontent.com/1911497/181181412-79d5774f-839d-48d5-a1cd-e723a40d8d16.png)
![IDE-2 0-SortOrder-boards-txt-Confusing](https://user-images.githubusercontent.com/1911497/181181463-e128f02e-b2e6-4be8-b47e-38dc906a7bf6.png)

**Comment by per1234** [comment]
I am no longer able to reproduce this. I bisected the fix to https://github.com/arduino/arduino-ide/commit/960a2d0634d22d5db53b69ecbc1d97d91a1dcf20. I can still reproduce the fault using the build for the previous commit (https://github.com/arduino/arduino-ide/commit/e577de4e8e8a3682ea4422fdb38658eb30628375).

Note that it is only the order of the option values (e.g., **Tools > USB Type > MIDIx16**) that was fixed. There is still a bug in the ordering of the parent menu items (e.g., **Tools > USB Type**). That bug is being tracked in a dedicated issue https://github.com/arduino/arduino-ide/issues/2036
