### ISSUE TITLE
Automatic board selection

### ISSUE THREAD

**Issue by AndriuxaNoMercy** [arduino/arduino-ide#81]
Would be great to have last used board stored and loaded on IDE start-up.
What could be even more awesome is an option to #define board prefered for current sketch.

Picking up first available COM port automatically would probably suit at least half of users, as there is rarely several boards bphisically attached to PC...

**Comment by per1234** [comment]
>Would be great to have last used board stored and loaded on IDE start-up.

Fixed by https://github.com/arduino/arduino-ide/commit/c86d82d2737d466e95dfa0f6347f107411b43888

>What could be even more awesome is an option to #define board prefered for current sketch.

There is a dedicated issue for this subject: https://github.com/arduino/arduino-ide/issues/55
