### ISSUE TITLE
Serial Monitor panel issue with multiple sketches open for same board

### ISSUE THREAD

**Issue by KurtE** [arduino/arduino-ide#813]
**Describe the bug**
There are times I am still getting the Not connected line  even though it is...
Note this is daily build 20220205 after #713 was integrated.
Note: I am doing this using Teensy Micromod (T4.x)... 

**To Reproduce**
1)I had two different sketches I was working on which had Serial monitor window active ..., closed them down
2) restarted the IDE with Teensy still connected, one of the windows came back, and it started the Serial monitor with the message about CTRL+enter... 
3) Open the other file back up (Open Recent) and it opens up new window also with Serial monitor, and Serial output goes to both windows, and now I see the Yellow/Orange like color banner over the ctrl+enter line showing Not connected, although output is going out, but not taking any input... 
4) I manually select the same teensy/port  still nothing...  Still message there
5) click to close both serial monitors and click to open it again in one.   And it still shows not connected, but CTRL+enter and data does
now go through...
**Expected behavior**

I expect that I can enter the data... Unclear how you should handle two sketch windows with both are pointing to the same Serial port. 

**Screenshots**

I start up the IDE, and it shows one program and it must have remembered that I had serial monitor active:
![image](https://user-images.githubusercontent.com/1558080/152685731-36162cec-f43a-4bf7-b59c-07aecddaa22d.png)

Wrong sketch (I closed two, but want to try the other one) So I open it up again from recent:
And I now see the choose... Plus both windows showing serial output...
![image](https://user-images.githubusercontent.com/1558080/152685812-ade8a7b4-1942-4dc7-9200-a8d51bafb47e.png)
I stop the Serial monitor in both windows,  I then click to start it again in one of the window, and it still shows the
Not connected: select a board... but ctrl+enter does send data through

Note: I then closed one window, rebuilt reselected com port and now it is back to normal:
![image](https://user-images.githubusercontent.com/1558080/152687030-ae20e778-cc36-408c-bb93-42bd5929a4e5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: nightly build 20220205

**Additional context**

**Comment by per1234** [comment]
>There are times I am still getting the Not connected line even though it is...

Tracked at https://github.com/arduino/arduino-ide/issues/753

>output is going out, but not taking any input...

Tracked at https://github.com/arduino/arduino-ide/issues/752

---

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the others.

If you end up with additional information to share, feel free to comment in the other thread.
