### ISSUE TITLE
File Close and File Close Editor is the same, File Close should just close the sketchbook

### ISSUE THREAD

**Issue by bnneupart** [arduino/arduino-ide#825]
The File menu contains "Close" and "Close Editor", both with the same sort-cut key and both will quit the application. 

**To Reproduce**
1. Open the File menu
2. Select "Close" and the application Quits

1. Open the File menu
2. Select "Close Editor" and the application Quits

**Expected behavior**
I was expecting that "Close" would close the current SketchBook (as it is in the SketchBook section of the menu) and not the application

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: 12.2 Monterey

**Comment by per1234** [comment]
Thanks for taking the time to submit an issue @bnneupart.

I see we have previous reports about this at https://github.com/arduino/arduino-ide/issues/660 and https://github.com/arduino/arduino-ide/issues/758.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the thread of the relevant issue.
