### ISSUE TITLE
Communicate to user when upload is impossible due to no board selection

### ISSUE THREAD

**Issue by per1234** [arduino/arduino-ide#845]
## Describe the current behavior

On the first run of a fresh installation, no board is selected in the IDE. A "no board selected" condition might be produced in other ways (e.g., https://github.com/arduino/arduino-ide/issues/657) after that time as well.

Compilation and upload commands are configured for each board. For this reason, compilation or upload is impossible if a board has not been selected.

🙁 The Arduino IDE does not provide any indication of what went wrong when an upload is attempted without a board selected.

## To reproduce

1. Quit the IDE if it is running.
1. Rename or delete (:warning: cautiously) the following folder to simulate a first run:
   - Windows:
     ```
     C:\Users\<user name>\AppData\Roaming\arduino-ide
     ```
   - Linux:
     ```
     ~/.config/arduino-ide
     ```
   - macOS:
     ```
     ~/Library/Application Support/arduino-ide
     ```
1. Start the Arduino IDE.
1. Select a port from the **Tools > Port** menu in the Arduino IDE.
   🛈 This step is not required. It is only done to show that the issue is not dependent on a missing port selection (https://github.com/arduino/arduino-ide/issues/770)
1. Select **Sketch > Upload** from the Arduino IDE menus.

🙁 Nothing at all happens. There is no notification, error message, etc.

## Describe the request

Clearly communicate to the user when uploading is not possible due to no board selection.

Even though it is not great (https://github.com/arduino/arduino-ide/issues/62), there is at least some communication when compilation is attempted without a board selection.

## Desktop

- OS: Windows 10
- Version: 2.0.0-rc4-snapshot.9b1f15d-snapshot-9b1f15d
Date: 2022-02-17T10:40:50.003Z
CLI Version: 0.21.0 [10107d24]

## Additional context

This is likely only another symptom of the same issue that causes https://github.com/arduino/arduino-ide/issues/770

I decided to create a separate issue report since there is a significantly different expected outcome between the two user paths (in https://github.com/arduino/arduino-ide/issues/770 the upload should be successful, while here the issue is only that the failure is not communicated).

---

### Related

- https://github.com/arduino/arduino-ide/issues/973

**Comment by ubidefeo** [comment]
@91volt 
isn't this case handled by your latest UX explorations?
