### ISSUE TITLE
Boards Manager not updating with additional URL

### ISSUE THREAD

**Issue by davmacario** [arduino/arduino-ide#861]
When trying to import additional boards via URL (namely CircuitMess' Ringo module - https://raw.githubusercontent.com/CircuitMess/CircuitMess-Ringo-Arduino-packages/master/package_CircuitMess_Ringo_index.json) boards were not available for selection in the Boards Manager section. Closing and reopening the application solved this problem. 

1. Go to "Preferences" (ctrl + comma)
2. Enter URL (https://raw.githubusercontent.com/CircuitMess/CircuitMess-Ringo-Arduino-packages/master/package_CircuitMess_Ringo_index.json) in "Additional boards manager URLs"
3. Press "OK"
4. Go to the side menu "Boards Manager"
5. Trying to find any of the newly installed boards (e.g., 'Ringo by CircuitMess') results in a null search.

Restarting the application should solve the problem.

System info:
 - OS: Windows 11 Pro
 - Version: 21H2
 - OS build: 22000.493

**Comment by per1234** [comment]
Hi @davmacario. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/637.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
