### ISSUE TITLE
Serial monitor speed

### ISSUE THREAD

**Issue by Speedjf37** [arduino/arduino-ide#867]
Hi,

Serial Monitor limits:
Speed limit is 115200 bds

Marlin Serial speed is 250000 bds

Can you restore as IDE 1.xx

Thank JF

**Comment by per1234** [comment]
Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/111.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
