### ISSUE TITLE
Unable to upload program when more than one instance of IDE is open.

### ISSUE THREAD

**Issue by mklemarczyk** [arduino/arduino-ide#888]
**Describe the bug**
Unable to upload the program to Arduino Nano 33 IoT or monitor serial port.
When two or more instances of Arduino IDE are open and assigned to the same serial port.

**To Reproduce**
1. Open project and upload it to Arduino (program A)
2. Open serial monitor to see messages from the Arduino
3. Open another instance of Arduino IDE with different project (program B)
4. Try to upload the program from second instance of Arduino IDE

**Expected behavior**
It should be marked that other Arduino IDE uses the serial connection for that device.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 64 bits
 - Version: 2.0.0-rc3

**Additional context**
I want to be able to work on multiple programs with the same device.
I upload program A to the device and debug it, while I write program B in another IDE.
Than I upload program B to the device and improve code of program A.
It happened to me to work up to 3 different projects at the same time.

It is necessary if you are testing long running programs with complex logic.
I find it better that I can open multiple instances of IDE, but serial port management is very bad at the moment.
From time to time, I have to close all instances, because IDE is not able to use COM port anymore.

I use Arduinos with on-board ISP. (Arduino Nano 33 IoT, Arduino Nano 33 BLE, Arduino RP2040 Connect)

**Comment by per1234** [comment]
Thanks for taking the time to submit an issue @mklemarczyk .

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/726.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
