### ISSUE TITLE
Byte type is not blue

### ISSUE THREAD

**Issue by mklemarczyk** [arduino/arduino-ide#890]
**Describe the bug**
Syntax coloring is wrong for type byte.

**To Reproduce**
1. Create a project and declare a byte variable.

**Expected behavior**
Byte word is blue as int or char.

**Screenshots**
![image](https://user-images.githubusercontent.com/2727261/156932701-ab5d6cc7-391b-4c6a-8222-4797b47c36b5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 (64 bit)
 - Version: 2.0.0-rc4

**Additional context**
I want to see all my variables declared easily. It is hard to spot the byte variables.

**Comment by per1234** [comment]
Hi @mklemarczyk. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/380.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.

## Related

- https://github.com/arduino/arduino-ide/issues/291
- https://github.com/arduino/arduino-ide/issues/171
- https://github.com/arduino/arduino-ide/issues/108
- https://github.com/arduino/arduino-pro-ide/issues/150
