### ISSUE TITLE
Very slow output in terminal window on upload

### ISSUE THREAD

**Issue by willie68** [arduino/arduino-ide#892]
**Describe the bug**
Very slow output in terminal window (300Baud :-) ) with avrdude.exe on uploading program.
I have 3 versions rc3 rc4 and the "old" 1.8. Rc3 and 1.8 are fast on upload, but the terminal output on rc4 is very slow.
The upload itself is fast, only the output to the terminal window is very slow...

**To Reproduce**
Press upload button

**Expected behavior**
The output should be as fast as in the compile window. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 2.0 rc4

**Comment by per1234** [comment]
Hi @willie68. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/68.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
