### ISSUE TITLE
Close Editor(Ctrl + F4) not working

### ISSUE THREAD

**Issue by youkidearitai** [arduino/arduino-ide#895]
**Describe the bug**
Close Editor(also shortcut Ctrl + F4) is not working

**To Reproduce**
1. Click on 'File'
2. Click on 'Close Editor (Ctrl + F4)'
3. Don't work anything

**Expected behavior**
Close current editor

**Screenshots**
![2022-03-09-arduino-ide-20-rc4-close-editor-not-working](https://user-images.githubusercontent.com/305368/157425250-a171ca1d-97b5-4dcb-b7fc-82ce3a05fd49.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 2.0.0-rc4

**Comment by per1234** [comment]
Hi @youkidearitai. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/660.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
