### ISSUE TITLE
Select all fails in Serial Monitor

### ISSUE THREAD

**Issue by sellensr** [arduino/arduino-ide#899]
Select text in Serial monitor pane and you can cut/paste with Ctrl-C/Ctrl-V, but Ctrl-A jumps to the code pane and selects all code.

**To Reproduce**
Open Serial Monitor 
Select some output to be sure that pane has focus
Ctrl-A (Cmd-A on Mac) and all code will highlight yellow and focus will shift to code pane.
Ctrl-C (Cmd-C on Mac) then copies the code, not the Serial Monitor content.

**Expected behavior**
Expected all content in Serial Monitor to be selected and highlighted for copying

**Desktop (please complete the following information):**
IDE 2.0.0-sc5 and sc4
Mac OS 12.2.1 (Mac Mini M1)
also verified same behaviour on Windows 10 with IDE sc5

**Additional context**
Ctrl-A is a valuable feature for students grabbing large collections of output measurement data in my engineering courses.

**Comment by per1234** [comment]
Hi @sellensr. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/812.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
