### ISSUE TITLE
Teensy board support

### ISSUE THREAD

**Issue by Fluxanode** [arduino/arduino-ide#90]
When will there be support for the Teensy boards?

**Comment by lukehutch** [comment]
Once Teensy is supported under Arduino IDE 2.0, what work will be needed to get the debugger working with Teensy?

https://blog.arduino.cc/2020/02/28/preview-the-debugger-feature-for-the-arduino-pro-ide/

**Comment by ubidefeo** [comment]
@lukehutch 
I'm not sure how many (and which) Teensy boards actually expose any form of debugging interfaces.
If an interface is exposed via pins or test-points I'm fairly sure a configuration JSON file can be put together to debug these boards

**Comment by lukehutch** [comment]
Thanks, I found out that @ftrias built a pretty functional gdb stub for Teensy boards:

https://github.com/ftrias/TeensyDebug

It looks like since this supports the gdb serial protocol, wiring this into Arduino IDE 2.0 would be pretty straightforward, via a configuration JSON alone?

**Comment by per1234** [comment]
Closing as resolved by https://github.com/arduino/arduino-ide/pull/982
