### ISSUE TITLE
rc4 and rc5 - File > Preferences > Additional Boards Manager URLS entry field too small to use

### ISSUE THREAD

**Issue by wittend** [arduino/arduino-ide#903]
On  the entry field for Additional Boards Manager URLs is to small to use in rc4 and rc5.  rc3 was OK.
**To Reproduce**
1. Go to 'File'
2. Click on 'Preferences'
3. Click on 'Additional boards manager URLs' edit Icon.

**Screenshots**
![Arduino 2 0 rc5 bug 2022-03-10 22-22-51](https://user-images.githubusercontent.com/337442/157802983-f4b3ce91-9170-4e3f-8b10-e0b968cc5950.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint (Ubuntu)
 - Version: Linux Mint 20.3 Cinnamon

**Comment by per1234** [comment]
Hi @wittend. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/881.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
