### ISSUE TITLE
CTR + R reloads the IDE instead of compile

### ISSUE THREAD

**Issue by Travelbacon** [arduino/arduino-ide#907]
**Describe the bug**
CTR+R reloads the IDE instead of compiling the code.

**To Reproduce**
Press CTR+R to compile the code.

**Expected behavior**
The compilers should compile the code.

**Desktop (please complete the following information):**
 - Debian Bullseye - Gnome 3.85.5
 - Version: 2.0.0-RC5 (ZIP file version)

**Additional context**
On the same system, RC 3 has no issue with CTR+R

**Comment by per1234** [comment]
Hi @Travelbacon. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/852.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
