### ISSUE TITLE
Additional Boards Manager URLs Dialog box does not expand. Does not load any new boards

### ISSUE THREAD

**Issue by Azzkikin** [arduino/arduino-ide#910]
When trying to add additional boards, selecting the Additional Boards Manager URLs button, the dialog box does not expand. Not able to add other boards.

**To Reproduce**
1. Go to Preferences
2. Click on Additional Boards Manager URLs dialog box
3. See screenshot

**Expected behavior**

**Screenshots**
![Screenshot 2022-03-14 183948](https://user-images.githubusercontent.com/101610771/158289053-66312564-20a2-4825-b696-cb3a6b66041b.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10 64
 - IDE 2.0.0-rc5

**Comment by per1234** [comment]
Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/881.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
