### ISSUE TITLE
Cannot install a new board after adding URL to preferences

### ISSUE THREAD

**Issue by Azzkikin** [arduino/arduino-ide#911]
**Describe the bug**
After adding a URL to the boards manager URL, the board never shows up in the list. 

**To Reproduce**
1. Go to Preferences
2. Click on Additional boards dialog box. 
3. Delete existing URL (cannot add multiple URLs as the "enter additional URL box does not allow to be expanded.)
4. Paste new URL in box. 
5. Click the OK button
6. Check boards manager for new board
7. Restart IDE so trigger loading of new boards.

**Expected behavior**
Package index is downloaded after adding a new URL to File > Preferences > Additional Boards Manager URLs.

**Screenshots**
![blank URL](https://user-images.githubusercontent.com/101610771/158296947-d211bac3-7b11-4930-a000-aa4bcdcd5163.jpg)
![added URL](https://user-images.githubusercontent.com/101610771/158296950-7c32574a-ba27-4b32-91eb-30e78f4e5c31.jpg)
![Screenshot 2022-03-14 183948](https://user-images.githubusercontent.com/101610771/158296956-401a1f6b-de61-46af-9171-34e0181d7f7f.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10 64
 - Version: IDE 2.0.0-rc5

**Additional context**
I have tried to copy many different boards, no difference. I have shut my antivirus down to prevent it from interrupting.

**Comment by per1234** [comment]
Now being supported at @Azzkikin's forum topic:
https://forum.arduino.cc/t/cannot-install-a-new-board-after-adding-url-to-preferences/969365
