### ISSUE TITLE
Add option to list functions used in a sketch.

### ISSUE THREAD

**Issue by ahuikeshoven** [arduino/arduino-ide#924]
### Describe the request

I would like to see a menu option implemented that displays a list of all functions / methods used in a sketch like Notepad++ does. This is very useful when working with large sketches and saves hours of unnecessary scrolling.

### Describe the current behavior

Currently no Arduino IDE version is capable of showing a seperate (clickable) list of sketch used functions/methods.
For comparison see Notepad ++ that does have this option.

### Arduino IDE version

any version

### Operating system

Windows

### Operating system version

Windows 10

### Additional context

While I prefer this option to be added to the lastest Adruino IDE 2.0 it would be nice if it could be added to the older versions too.

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My request contains all necessary details

**Comment by per1234** [comment]
Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/237.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
