### ISSUE TITLE
xtensa-lx106-elf-g++: error: unrecognized command line option '-std=gnu++17'

### ISSUE THREAD

**Issue by hajos118** [arduino/arduino-ide#937]
### Describe the problem

"Verify" works, "upload" brings the error message:

```text
xtensa-lx106-elf-g++: error: unrecognized command line option '-std=gnu++17'
```

### To reproduce

Sketch:
```cpp
unsigned long previousMillis;

void setup() {
  Serial.begin(9600);
}

void loop() {
  if (Serial.available() > 0) {
    while (Serial.available() > 0) {
      Serial.write(Serial.read());
    }
    Serial.println();
  } else if (millis() - previousMillis >= 1000) {
    previousMillis = millis();
    Serial.println(random(100));
  }
}
```

CPU: LOLIN(WEMOS) D1 R2 & mini

### Expected behavior

Works fine with old IDE

### Arduino IDE version

IDE 2.0.0-rc5

### Operating system

Windows

### Operating system version

10

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @hajos118. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/1182.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place. Even though this one came first, I started an investigation on the newer one, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread. I would be interested to hear over there whether you are still experiencing this problem when using Arduino IDE 2.x, and if not, what the solution was you found.
