### ISSUE TITLE
Missing Option to configure python executable path

### ISSUE THREAD

**Issue by ebogdum** [arduino/arduino-ide#949]
### Describe the request

Right now, Arduino IDE 2 doesn't have an option where you can tell it where the python executable is. By default it looks for python, but on newer OSX versions python doesn't exist and/or isn't supported anymore (for example you can't install it with homebrew).

It would be very nice if the IDE would have the option to set the python executable path, and also support python3.

### Describe the current behavior

When you try to compile a sketch you get an error that the python executable is missing. 
If you do a softlink at OS level, from python3 to python it will ask for command line developer tools and even if that's installed it will still not work.

### Arduino IDE version

2.0.0-rc5

### Operating system

macOS

### Operating system version

OSX Monterey 12.3.1

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My request contains all necessary details

**Comment by per1234** [comment]
Hi @ebogdum. Thanks for your interest in this open source project.

The Arduino IDE does not use Python for anything. The Arduino IDE does allow the boards platforms to define arbitrary compilation and upload recipes. Some of the 3rd party boards platforms do use Python in those recipes. The IDE also allows the authors of those platforms to automatically install all the required tools, and this is how all the official platforms and most 3rd party platforms work. A few of the 3rd party platform (e.g., ESP32) creators have chosen to not provide the necessary tool dependencies in some cases, making it the responsibility of the user to set up their environment to provide the tools.

The Arduino IDE is intended to be a general purpose tool for the development of Arduino sketches, so it would not make sense to add UI elements for a single specific use case. Instead, it is up to the boards platform developers to choose how they want to use the framework provided by Arduino and how to instruct the users of their platform in its usage.
