### ISSUE TITLE
The selected board + port should used for new sketches

### ISSUE THREAD

**Issue by kittaakos** [arduino/arduino-ide#95]
When I open a sketch and configure my board and port settings and I create a new sketch again, my previous board settings are not used for the new sketch; the app shows `no board selected`.

The sketches (browser windows) do not know anything about each other. We should put the selected board + port into the URL as a query, and when opening a new window, we should try to retrieve this info.

**Comment by tigoe** [comment]
One of the problems with auto-associating the old board and port with the new sketch is that it weakens one of the nicer new features of the new IDE, namely the ability to keep track of multiple boards and ports. This is related to #271 Auto-associating would make 2.0 seem more like 1.0, though, so it might be a useful option that the user can enable if they prefer it.
