### ISSUE TITLE
[UX] The board select dialog is broken when the window size is small

### ISSUE THREAD

**Issue by kittaakos** [arduino/arduino-ide#96]
As a user, I can reduce the window size to 200X120 pixes but the board config dialog does not like it. It's a bug. See the screencast.

![screencast 2020-09-04 09-25-13](https://user-images.githubusercontent.com/1405703/92211524-e1402480-ee90-11ea-867e-e3e997f17899.gif)

**Comment by Ho-Ro** [comment]
> the tool has now become unnecessarily effectively unusable for those using machines with smaller display dimensions typical of many laptops for example

Q'n'D solution for KDE Plasma (Debian stable) for my ThinkPad T400 (1280x800):
* Click titlebar menu (leftmost button)
![image](https://user-images.githubusercontent.com/12542359/109951537-19a8aa00-7cde-11eb-8840-7d761f3443ec.png)

* More Actions > Special Window Settings
* Tab Window matching:
![image](https://user-images.githubusercontent.com/12542359/109949841-24fad600-7cdc-11eb-8445-19d5f8e30844.png)
* Tab Size & Position
![image](https://user-images.githubusercontent.com/12542359/109949905-3c39c380-7cdc-11eb-8f39-a35e64f5a967.png)
* Click OK and Apply

The change is permanent and can be found later in:
* System Settings > Workspace / Window Management > Window Rules

HTH, Martin

**Comment by ubidefeo** [comment]
nice hack, @Ho-Ro

**Comment by Ho-Ro** [comment]
> From now on, the minimum window size is 900 x 800

On my system 800x700 is more than sufficient to show the complete "Select Board" window. 
@kittaakos , @ubidefeo : Would it be possible to decrease the minimum size to this value that makes the new IDE much more usable for a lot of "HD ready 720p" laptops?

**Comment by sebromero** [comment]
@Ho-Ro Yes we should probably do that. The actual fix is to use a different layout, a responsive one ideally. We'll look into it.

**Comment by kittaakos** [comment]
Reported by @abnair1982 [here](https://github.com/arduino/arduino-ide/issues/232#issue-833591162):

> **Describe the bug**
> 
> When I open Select Board Dialog, the OK button to confirm selection is hidden. I am unable to resize the IDE or move the Select Board Dialog. As a result I am unable to select board easily. I have a mac style dash. So I have to drag the ide to the right to make the button visible. I tried to move and resize Select Board Dialog. But I was not able to move the dialog. Please check the screenshot
> 
> **To Reproduce**
> 
> 1. Open IDE
> 2. Click On 'Select Other Board & Port'
> 3. 'Select Board' Dialog will open. 'OK' button to confirm selection is hidden.
> 4. Try to drag or resize 'Select Board' dialog. It will not allow you to move the dialog
> 5. Try to resize the IDE. It will not allow to resize IDE.
> 
> **Expected behavior**
> 
> 1. Ability to resize the IDE.
> 2. Ability to move or resize the "Select Board"  Dialog opened in IDE
> 3. Have 'OK' button at place that will be always easily accessible.
> 
> **Screenshots**
> On opening the select board dialog:
> ![image](https://user-images.githubusercontent.com/59200388/111447568-92265680-8733-11eb-992a-a596d09ddc3b.png)
> 
> On moving the ide to right:
> ![image](https://user-images.githubusercontent.com/59200388/111447620-9e121880-8733-11eb-9b2a-b329a8ba812d.png)
> 
> **Desktop (please complete the following information):**
> 
> * OS: Ubuntu
> * Version: 18.04
> * Arduino Ide Version: arduino-ide_2.0.0-beta.3_Linux_64bit
> 
> **Additional context**
> I have to move the IDE to the right for the buttons to became visible.

**Comment by Patronon** [comment]
Thanks for working on this nice IDE and for keeping it running. i was looking for something like it for a while.
But
for me it feels the explained issue is still there on Linux Mint for your version 1.14!
see pic!?
i can not extent the windows and neither can I see the whole window of the IDE (i have a lenovo thinkpad x220 with (i guess 12.5")
Cheers
![Bildschirmfoto vom 2021-05-18 23-32-45](https://user-images.githubusercontent.com/84419208/118726503-b389e880-b831-11eb-96f7-451c2cc41883.png)

**Comment by per1234** [comment]
@Patronon you are using an outdated version of the IDE from before the fix. Please install the latest version 2.0.0-beta.7 from this page:
https://www.arduino.cc/en/software#experimental-software
