### ISSUE TITLE
Output area is severely delayed.

### ISSUE THREAD

**Issue by AndKe** [arduino/arduino-ide#963]
### Describe the problem

When compiling, the "output" area spawns text well after the popup notification says "compilation complete"
Worse:
if compiler output is enabled, this is very delayed..

### To reproduce

compile something..  - or please see attached video

### Expected behavior

about realtime text output.

### Arduino IDE version

RC6 appimage

### Operating system

Linux

### Operating system version

Ubuntu 22.04

### Additional context

[Screencast from 22. april 2022 kl. 10.29 +0200.zip](https://github.com/arduino/arduino-ide/files/8538662/Screencast.from.22.april.2022.kl.10.29.%2B0200.zip)

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @AndKe. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/68 and https://github.com/arduino/arduino-ide/issues/405.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
