### ISSUE TITLE
Menu item "Edit > Select All" only select 10 lines of code

### ISSUE THREAD

**Issue by ubidefeo** [arduino/arduino-ide#969]
### Describe the problem

When wanting to select all the code in the current tab, if using the CMD+A shortcut it is correctly selected,
while using the menu item will only select 10 lines and it's not really clear where the starting point is, because the selection begin/end are offset from the last cursor position

### To reproduce

* open a Sketch
* place your cursor in the code window
* from the application menu __Edit > Select All__
* unselect by clicking in an unselected part of the text
* only 10 lines will be selected
* use the shortcut CMD+A (CTRL+A on Windows)
* the entire code will be selected

<img width="1251" alt="CleanShot 2022-04-25 at 15 36 05@2x" src="https://user-images.githubusercontent.com/1894487/165101195-c40cb041-19a0-4f32-ba10-3c2c7bc39b2f.png">

<img width="1245" alt="CleanShot 2022-04-25 at 15 36 50@2x" src="https://user-images.githubusercontent.com/1894487/165101207-d2e598f5-5960-4ca6-8154-319da6cd0868.png">

### Expected behavior

The entire code in the current tab should be selected and ready to be acted upon

### Arduino IDE version

2.0.0-rc6

### Operating system

macOS

### Operating system version

12.3

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

**Comment by kittaakos** [comment]
PR: https://github.com/arduino/arduino-ide/pull/1022. Please review. Thank you!

**Comment by kittaakos** [comment]
The PR is not merged. I have reopened this issue.

**Comment by ubidefeo** [comment]
Tested PR and approved
