### ISSUE TITLE
CPU usage too high

### ISSUE THREAD

**Issue by JachinY** [arduino/arduino-ide#981]
### Describe the problem

CPU usage too high
![image](https://user-images.githubusercontent.com/42339509/167246844-399c69cc-aced-4bc3-a1f6-e1cc5b88de41.png)

### To reproduce

![image](https://user-images.githubusercontent.com/42339509/167246794-551b0d2e-f756-4b5d-85c3-ec063cc2cdeb.png)

### Expected behavior

![image](https://user-images.githubusercontent.com/42339509/167246798-6c97ad06-62c5-430c-bc89-29fdd1588ae6.png)

### Arduino IDE version

2.0.0-rc6

### Operating system

Windows

### Operating system version

win11

### Additional context

![image](https://user-images.githubusercontent.com/42339509/167246837-65229b39-9cac-469c-8d50-496f876ce104.png)

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

**Comment by ubidefeo** [comment]
@JachinY 
This is a very unfriendly way of reporting an issue and your should either compile a proper one or retract it.
I do not tolerate such behaviour.

Thank you

**Comment by JachinY** [comment]
Ok sorry thank you I dont know english
