### ISSUE TITLE
Debugger does not disconnect after stopping it

### ISSUE THREAD

**Issue by asereq** [arduino/arduino-ide#995]
### Describe the problem

After a debug session, the debugger not responds because it cannot disconnect.

### To reproduce

1) Start de IDE.
2) Open an example (blink for example).
3) Compile (verify) the code.
4) Start the debugger (debugger runs correctly)
5) Stop the debugger.
6) De debugger does not run anymore.

### Expected behavior

Debugger runs again without problems.

### Arduino IDE version

Arduino IDE AppImage 2.0.0-rc6

### Operating system

Linux

### Operating system version

Arch Linux

### Additional context

The IDE, running from command line, after step 5, says this:
```
root INFO [hosted-plugin: 102967] stopping debug adapter session: '7348c2ee-07f5-435f-9e11-1542d80fadc4'
root INFO [hosted-plugin: 102967] error in debug adapter session: '7348c2ee-07f5-435f-9e11-1542d80fadc4': {"code":"ERR_STREAM_WRITE_AFTER_END"}
root ERROR Error on disconnect
```

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Thanks so much for your report @asereq. This bug was resolved by https://github.com/arduino/arduino-ide/pull/1662 (I can reproduce it using the build from the previous commit 3ad660927f2dea3eaff3e4738179ecb7c92da255 but not with the build for ac9cce16f749f7b43abc145ed8d1ee79159dd5e9 or newer).
