### ISSUE TITLE
Time format of Serial Monitor causes shift of output

### ISSUE THREAD

**Issue by Akinollo** [arduino/arduino-ide#997]
### Describe the problem

The time of the serial monitor should be formated with leading "0" if hour or minute has only one digit. Its already done for the seconds and milliseconds. Here the text is shifted left/right when the minute changes from 9 to 10:
21:9:59.812 -> URef 894.177551  kCal 0.004580746 | BuckDnC_In 19.935
21:9:59.937 -> URef 894.177368  kCal 0.004580747 | BuckDnC_In 19.935
21:10:00.062 -> URef 894.177185  kCal 0.004580748 | BuckDnC_In 19.935
21:10:00.187 -> URef 894.177002  kCal 0.004580748 | BuckDnC_In 19.935

### To reproduce

Toggle timestamp to see the time in the serial monitor and wait... 

### Expected behavior

21:09:59.812 -> URef 894.177551  kCal 0.004580746 | BuckDnC_In 19.935
21:09:59.937 -> URef 894.177368  kCal 0.004580747 | BuckDnC_In 19.935
21:10:00.062 -> URef 894.177185  kCal 0.004580748 | BuckDnC_In 19.935
21:10:00.187 -> URef 894.177002  kCal 0.004580748 | BuckDnC_In 19.935

### Arduino IDE version

arduino-ide_2.0.0-rc6-nightly-20220519

### Operating system

Windows

### Operating system version

10

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @Akinollo. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-ide/issues/580.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
