### ISSUE TITLE
Window title changes to "index.html" during reload

### ISSUE THREAD

**Issue by per1234** [arduino/arduino-ide#999]
### Describe the problem

The Arduino IDE window may reload during some operations such as after a change to the "**Language**" preference.

🐛 The window title changes to "**index.html**" during the reload operation. This is not an optimal user experience.

### To reproduce

1. Open the "**Command Palette**" (<kbd>**Ctrl**</kbd>+<kbd>**Shift**</kbd>+<kbd>**P**</kbd>)
1. Run the "**Reload Window**" command.

🐛 The window title changes to "**index.html**" during the reload operation.

![image](https://user-images.githubusercontent.com/8572152/169552602-c2a48e37-05be-49fe-aa5f-6cd5aa06e9b9.png)

### Expected behavior

Standard window title is preserved through the reload:

![image](https://user-images.githubusercontent.com/8572152/169552631-50d648e8-c61b-423d-83bb-67a332b65d3b.png)

### Arduino IDE version

2.0.0-rc6-snapshot-b407d0a

### Operating system

Windows, Ubuntu

### Operating system version

Windows 10, Ubuntu 20.04

### Additional context

The issue was introduced at https://github.com/arduino/arduino-ide/commit/112153fb965f63d952d126c8244cd3f84f0a1a1b (does not occur in the build for the previous commit https://github.com/arduino/arduino-ide/commit/69ac1f4779589d0d21ce3d37c180b3393ad6156c).

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

**Comment by kittaakos** [comment]
See: https://github.com/eclipse-theia/theia/pull/11575
